### PR TITLE
[Fix #13614] Fix false positives for `Style/RaiseArgs` with anonymous splat and triple dot forwarding

### LINKED ISSUE #13614: Style/RaiseArgs suggests incorrect changes
## Expected behavior

Changes which break the code should not be suggested.

## Actual behavior

Given this code:

```ruby
  def self.parse_float(str, klass, *)
    Float(str)
  rescue StandardError
    raise klass.new(*)
  end
```

the `Style/RaiseArgs` cop will make this suggestion:

```
Offenses:

lib/osm.rb:512:5: C: [Correctable] Style/RaiseArgs: Provide an exception class and message as arguments to raise.
    raise klass.new(*)
    ^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense autocorrectable
Finished in 0.40765087300678715 seconds
```

so it wants to replace the raise with `raise klass, *` but that is only correct if the `*` only expands to a single argument, which is unknowable.

## RuboCop version

```
1.69.2 (using Parser 3.3.6.0, rubocop-ast 1.37.0, analyzing as Ruby 3.2, running on ruby 3.3.6) [x86_64-linux]
  - rubocop-capybara 2.21.0
  - rubocop-factory_bot 2.26.1
  - rubocop-minitest 0.36.0
  - rubocop-performance 1.23.0
  - rubocop-rails 2.27.0
  - rubocop-rake 0.6.0
```

### PR DESCRIPTION
**Pull request by Earlopain**
Fixes #13614

I also found out that `...` results in the same error, so ignore it as well. `**` was already correctly ignored, I just added a test.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/raise_args_spec.rb [hunk 1]
```diff
@@ -322,6 +322,22 @@ def do_something
       expect_no_offenses('raise MyCustomError.new(*args)')
     end
 
+    context 'when Ruby >= 3.2', :ruby32 do
+      it 'accepts a raise with anon splatted arguments' do
```
Comment (koic) [inline spec/rubocop/cop/style/raise_args_spec.rb:326]: That's just my two cents:

```suggestion
      it 'accepts a raise with anonymous splatted arguments' do
```

File: spec/rubocop/cop/style/raise_args_spec.rb [hunk 2]
```diff
@@ -322,6 +322,22 @@ def do_something
...
+        expect_no_offenses('def foo(*) raise MyCustomError.new(*) end')
+      end
+
+      it 'accepts a raise with anon keyword splatted arguments' do
```
Comment (koic) [inline spec/rubocop/cop/style/raise_args_spec.rb:330]:
```suggestion
      it 'accepts a raise with anonymous keyword splatted arguments' do
```

**Comment by koic** [comment]
Thanks!

**Comment by aniruddhaadak80** [comment]
Perfect catch on `Style/RaiseArgs`! Triple dot forwarding (`...`) and anonymous splats often confuse the AST parser into thinking standard args are missing. This heavily suppresses annoying noise for modern Ruby developers.
