### PR TITLE
[Fix #12731] Treat csend the same way as send for setter methods

### LINKED ISSUE #12731: `AssignmentInCondition` didn't find the style problem
## Expected behavior

RuboCop should find the style problem in the `if` statement

## Actual behavior

RuboCop didn't find the style problem

## Steps to reproduce the problem

test.rb

```rb
a = 1

if a&.to_i = 1
  puts '111'
end
```

Run:

```bash
rubocop --only Lint/AssignmentInCondition -a test.rb
```

Result:

```
Inspecting 1 file
.

1 file inspected, no offenses detected
```

## RuboCop version

```bash
root@localhost:~$ rubocop -v
1.61.0
```

### PR DESCRIPTION
**Pull request by jonas054**
In order to detect code like `if test&.method = 10` we need to find not only `send` nodes but also `csend` nodes.

### CODE REVIEW

File: lib/rubocop/cop/mixin/safe_assignment.rb [hunk 1]
```diff
@@ -14,7 +14,7 @@ module SafeAssignment
       def_node_matcher :empty_condition?, '(begin)'
 
       # @!method setter_method?(node)
-      def_node_matcher :setter_method?, '[(send ...) setter_method?]'
+      def_node_matcher :setter_method?, '[({send csend} ...) setter_method?]'
```
Comment (koic) [inline lib/rubocop/cop/mixin/safe_assignment.rb:17]: Can you use `call` instead?

```suggestion
      def_node_matcher :setter_method?, '[(call ...) setter_method?]'
```

**Comment by bbatsov** [comment]
Thanks!
