### PR TITLE
[Fix #13766] Fix false positives for `Style/InverseMethods`

### LINKED ISSUE #13766: Incorrect auto-correct on Style/InverseMethods and safe navigation.
`Style/InverseMethods` auto-corrects  `!my_list&.any?` to `my_list&.none?`. That's not correct, because `!nil&.any?` is `true` but `nil&.none?` is `nil`.

This is similar to https://github.com/rubocop/rubocop/issues/12649 and was partially fixed in https://github.com/rubocop/rubocop/pull/12650

--------

## Expected behavior

Either: 
1. Rubocop should not flag this code as a violation.
2. Rubocop should flag this, but should autocorrect it to a changed implementation.

## Actual behavior

Rubocop autocorrected my code such that its output was different.

## Steps to reproduce the problem

```
!list&.any?(&:odd)
```

## RuboCop version

```
$ bundle exec rubocop -V
1.71.0 (using Parser 3.3.7.0, rubocop-ast 1.38.0, analyzing as Ruby 3.3, running on ruby 3.3.6) [arm64-darwin22]
  - rubocop-performance 1.23.1
  - rubocop-sorbet 0.8.7
```

### PR DESCRIPTION
**Pull request by koic**
This PR fixes false positives for `Style/InverseMethods` when using `any?` or `none?` with safe navigation operator.
Additionally, some specs for the existing incorrect behavior has been updated.

Fixes #13766.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/inverse_methods.rb [hunk 1]
```diff
@@ -166,6 +168,12 @@ def end_parentheses(node, method_call)
           method_call.source_range.end.join(node.source_range.end)
         end
 
+        def incompatible_method?(node)
+          return false if node.send_type?
+
+          INCOMPATIBLE_INVERSE_METHODS.include?(node.method_name)
+        end
```
Comment (dvandersluis) [inline lib/rubocop/cop/style/inverse_methods.rb:175]: These are only incompatible with safe navigation, correct? I think it'd make sense to make the method name more descriptive.

File: spec/rubocop/cop/style/inverse_methods_spec.rb [hunk 2]
```diff
@@ -160,25 +145,26 @@ def test_method
   it_behaves_like 'all variable types', 'foo["bar"]'
   it_behaves_like 'all variable types', 'foo.bar'
 
-  { any?: :none?,
+  {
```
Comment (dvandersluis) [inline spec/rubocop/cop/style/inverse_methods_spec.rb:148]: Since this test doesn't use safe navigation, why is `any?: :none?` removed?

File: spec/rubocop/cop/style/inverse_methods_spec.rb [hunk 3]
```diff
@@ -209,6 +195,32 @@ def test_method
     end
   end
 
+  it 'registers an offense for using `any?` method' do
+    expect_offense(<<~RUBY)
+      !nullable.any?(&:odd)
+      ^^^^^^^^^^^^^^^^^^^^^ Use `none?` instead of inverting `any?`.
+    RUBY
+  end
```
Comment (dvandersluis) [inline spec/rubocop/cop/style/inverse_methods_spec.rb:203]: `expect_correction` should be included for this test as well as the one on line 211.

File: lib/rubocop/cop/style/inverse_methods.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/cop/style/inverse_methods.rb]: Finding a better name is difficult 😅  but `incompatible_context?` has been chosen.

File: spec/rubocop/cop/style/inverse_methods_spec.rb (hunk 2 above)
Comment (koic) [reply spec/rubocop/cop/style/inverse_methods_spec.rb]: Oops. I mistakenly remove it. Thanks for pointing it out.

File: spec/rubocop/cop/style/inverse_methods_spec.rb (hunk 3 above)
Comment (koic) [reply spec/rubocop/cop/style/inverse_methods_spec.rb]: It was a redundant test, so it has been removed.

File: lib/rubocop/cop/style/inverse_methods.rb [hunk 4]
```diff
@@ -46,6 +46,7 @@ class InverseMethods < Base
 
         MSG = 'Use `%<inverse>s` instead of inverting `%<method>s`.'
         CLASS_COMPARISON_METHODS = %i[<= >= < >].freeze
+        INCOMPATIBLE_INVERSE_METHODS = %i[any? none?].freeze
```
Comment (bbatsov) [inline lib/rubocop/cop/style/inverse_methods.rb:49]: I'd probably add a comment here mentioning they are incompatible only in the context of safe navigation.

**Comment by koic** [comment]
I adjusted the naming and logic based on the background of safe navigation instead of adding comments. I hope the naming appropriately reflects the background, considering the amount of code changes. If there is still any lack of clarity, I will add comments, so please let me know.

**Comment by bbatsov** [comment]
I think that's enough for now.
