### PR TITLE
[Fix #11104] Fix an error for `Style/CollectionCompact`

### LINKED ISSUE #11104: Error in Style/CollectionCompact
```
1 error occurred:
An error occurred while Style/CollectionCompact cop was inspecting /Users/jcoyne85/workspace/projectblacklight/blacklight/lib/blacklight/parameters.rb:10:6.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.37.0 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 3.1.2) [x86_64-darwin21]
```

The debug log says
```
An error occurred while Style/CollectionCompact cop was inspecting /Users/jcoyne85/workspace/projectblacklight/blacklight/lib/blacklight/parameters.rb:10:6.
undefined method `method_name' for s(:lvar, :params):RuboCop::AST::Node

          TO_ENUM_METHODS.include?(node.children.first.method_name)
                                                      ^^^^^^^^^^^^
Did you mean?  method
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #11104.

This PR fixes an error for `Style/CollectionCompact` when using `reject` method and receiver is a variable.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/collection_compact_spec.rb [hunk 1]
```diff
@@ -114,6 +114,24 @@
         array.lazy.compact!
       RUBY
     end
+
+    it 'registers an offense and corrects when using `to_enum.reject` on array to reject nils and receiver is a variable' do
+      expect_offense(<<~RUBY)
+        def foo(params)
+          array.to_enum.reject { |e| e.nil? }
```
Comment (bbatsov) [inline spec/rubocop/cop/style/collection_compact_spec.rb:121]: In this example the direct receiver is `to_enum`, not a variable, so I find the description to be a bit misleading.

Comment (koic) [reply spec/rubocop/cop/style/collection_compact_spec.rb]: Oops... actually the repro code is also wrong. I've updated this PR.

**Comment by bbatsov** [comment]
Thanks!
