### PR TITLE
[Fix #13341] Fix false positives for `Lint/SafeNavigationChain`

### LINKED ISSUE #13341: Infinite loop for `Lint/SafeNavigationChain` and `Lint/SafeNavigationConsistency`
```ruby
foo&.bar&.baz && foo&.bar&.zoo
```

```
Offenses:

example.rb:3:26: W: [Corrected] Lint/SafeNavigationChain: Do not chain ordinary method call after safe navigation operator.
foo&.bar&.baz && foo&.bar.zoo
                         ^^^^
example.rb:3:26: W: [Corrected] Lint/SafeNavigationConsistency: Use . instead of unnecessary &..
foo&.bar&.baz && foo&.bar&.zoo
                         ^^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in example.rb and caused by Lint/SafeNavigationConsistency -> Lint/SafeNavigationChain
Hint: Please update to the latest RuboCop version if not already in use, and report a bug if the issue still occurs on this version.
Please check the latest version at https://rubygems.org/gems/rubocop.
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #13341.

This PR fixes false positives for `Lint/SafeNavigationChain` when a safe navigation operator is used with a method call as the RHS operand of `&&` for the same receiver.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/safe_navigation_chain.rb [hunk 1]
```diff
@@ -52,6 +54,13 @@ def on_send(node)
 
         private
 
+        def require_safe_navigation?(node)
+          parent = node.parent
+          return true unless parent&.and_type?
+
+          parent.rhs != node || parent.lhs.receiver != parent.rhs.receiver
```
Comment (fatkodima) [inline lib/rubocop/cop/lint/safe_navigation_chain.rb:61]: Shouldn't we also check if `parent.lhs` is a `send` node before calling `.receiver`?

Comment (koic) [reply lib/rubocop/cop/lint/safe_navigation_chain.rb:61]: As far as I have verified, it seems there are no cases where this does not respond to `RuboCop::AST::Node#receiver`.

Comment (fatkodima) [reply lib/rubocop/cop/lint/safe_navigation_chain.rb:61]: Ah, nice, was thinking `receiver` is only for send nodes.
