### PR TITLE
[Fix #12558] Fix an incorrect autocorrect for `Style/MapToHash`

### LINKED ISSUE #12558: Error with Style/MapToHash that's locally disabled
## Expected behavior

Not to get an error.

## Actual behavior

An error occurred, and also an additional offense is register for an unnecessary disabling.

## Steps to reproduce the problem

`.rubocop.yml`:
```yaml
AllCops:
  NewCops: enable
```

`test.rb`:
```ruby
# frozen_string_literal: true

module Java::JavaUtil::Map # rubocop:disable Style/ClassAndModuleChildren
  def transform_values
    map do |k, v| # rubocop:disable Style/MapToHash, Style/HashTransformValues
      [k, (yield v)]
    end.to_h
  end
end
```

```
$ rubocop -d test.rb

For /Users/cody/src: configuration from /Users/cody/src/.rubocop.yml
Default configuration from /Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/config/default.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /Users/cody/src/test.rb
An error occurred while Style/MapToHash cop was inspecting /Users/cody/src/test.rb:5:4.
undefined method `source' for nil:NilClass

          message = format(MSG, method: map_node.loc.selector.source, dot: map_node.loc.dot.source)
                                                                                           ^^^^^^^
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/style/map_to_hash.rb:55:in `on_send'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/commissioner.rb:143:in `public_send'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/commissioner.rb:143:in `block (2 levels) in trigger_restricted_cops'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/commissioner.rb:142:in `block in trigger_restricted_cops'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/commissioner.rb:141:in `each'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/commissioner.rb:141:in `trigger_restricted_cops'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/commissioner.rb:70:in `on_send'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-ast-1.30.0/lib/rubocop/ast/traversal.rb:154:in `on_def'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/commissioner.rb:71:in `on_def'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-ast-1.30.0/lib/rubocop/ast/traversal.rb:138:in `on_while'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-ast-1.30.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/commissioner.rb:87:in `investigate'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/team.rb:156:in `investigate_partial'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cop/team.rb:98:in `investigate'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:345:in `block in inspect_file'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:344:in `each'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:344:in `flat_map'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:344:in `inspect_file'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:287:in `block in do_inspection_loop'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:321:in `block in iterate_until_no_changes'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:314:in `loop'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:314:in `iterate_until_no_changes'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:283:in `do_inspection_loop'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:164:in `block in file_offenses'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:189:in `file_offense_cache'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:163:in `file_offenses'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:154:in `process_file'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:134:in `each'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:134:in `reduce'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:134:in `each_inspected_file'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:120:in `inspect_files'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/runner.rb:73:in `run'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli.rb:118:in `run_command'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli.rb:125:in `execute_runners'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli.rb:51:in `block in run'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/lib/rubocop/cli.rb:43:in `run'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/exe/rubocop:19:in `block in <top (required)>'
/Users/cody/.rubies/ruby-3.1.3/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/Users/cody/.gem/ruby/3.1.3/gems/rubocop-1.59.0/exe/rubocop:19:in `<top (required)>'
/Users/cody/.gem/ruby/3.1.3/bin/rubocop:25:in `load'
/Users/cody/.gem/ruby/3.1.3/bin/rubocop:25:in `<main>'
W

Offenses:

test.rb:3:1: C: Style/Documentation: Missing top-level documentation comment for module Java::JavaUtil::Map.
module Java::JavaUtil::Map # rubocop:disable Style/ClassAndModuleChildren
^^^^^^^^^^^^^^^^^^^^^^^^^^
test.rb:5:37: W: [Correctable] Lint/RedundantCopDisableDirective: Unnecessary disabling of Style/MapToHash.
    map do |k, v| # rubocop:disable Style/MapToHash, Style/HashTransformValues
                                    ^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected, 1 offense autocorrectable

1 error occurred:
An error occurred while Style/MapToHash cop was inspecting /Users/cody/src/test.rb:5:4.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.1.3) [arm64-darwin21]
Finished in 0.11219099990557879 seconds
```

## RuboCop version

```
$ rubocop -V
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.1.3) [arm64-darwin21]
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12558.

This PR fixes an incorrect autocorrect for `Style/MapToHash` when using `map.to_h` without receiver.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/map_to_hash_spec.rb [hunk 1]
```diff
@@ -46,11 +59,11 @@
         it 'registers an offense and corrects' do
           expect_offense(<<~RUBY, method: method)
             foo&.#{method} { |x| [x, x * 2] }.to_h
-                 ^{method} Pass a block to `to_h` instead of calling `#{method}&.to_h`.
+                 ^{method} Pass a block to `to_h` instead of calling `#{method}.to_h`.
           RUBY
 
           expect_correction(<<~RUBY)
-            foo.to_h { |x| [x, x * 2] }
+            foo&.to_h { |x| [x, x * 2] }
```
Comment (koic) [inline spec/rubocop/cop/style/map_to_hash_spec.rb:66]: This corrects typos in the original test case.

**Comment by bbatsov** [comment]
Thanks!

File: spec/rubocop/cop/style/map_to_hash_spec.rb (hunk 1 above)
Comment (ydakuka) [reply spec/rubocop/cop/style/map_to_hash_spec.rb:66]: @koic 

Now there is an error.

```ruby
2.7.6 :001 > foo = [1, 2, 3]
 => [1, 2, 3] 
2.7.6 :002 > foo&.map { |x| [x, x * 2] }.to_h
 => {1=>2, 2=>4, 3=>6} 
2.7.6 :003 > foo&.to_h { |x| [x, x * 2] }
 => {1=>2, 2=>4, 3=>6} 
```

```ruby
2.7.6 :005 > foo = nil
 => nil 
2.7.6 :006 > foo&.map { |x| [x, x * 2] }.to_h
 => {} 
2.7.6 :007 > foo&.to_h { |x| [x, x * 2] }
 => nil 
```
