### PR TITLE
[Fix #14973] Fix `Style/ReduceToHash` false positive when accumulator is read in key/value

### LINKED ISSUE #14973: Style/ReduceToHash breaks code when accumulator is used for comparisons
Recent introduction of Style/ReduceToHash introduces breaking autofix.

--------

## Steps to reproduce the problem

Original Code:

```ruby
data = submissions.each_with_object({}) do |submission, hash|
  hash[submission.user_id] =
    if hash[submission.user_id].blank?
      { submission.form_id => submission.created_at }
    else
      hash[submission.user_id].merge({
        submission.form_id => submission.created_at,
      })
    end
end
```

## Expected behavior

Should remain untouched because accumulator (hash) is being used as a reader, not just setter

## Actual behavior

Mutates to the following, which breaks:

```ruby
data = submissions.to_h do |submission|
  [submission.user_id, if hash[submission.user_id].blank?
                          { submission.form_id => submission.created_at }
                        else
                          hash[submission.user_id].merge({
                            submission.form_id => submission.created_at,
                          })
                        end,]
end
```

(still refers to `hash` which no longer exists)

Extracting the attrs into variable before using hash stops autofix (this is left untouched):

```ruby
data = submissions.each_with_object({}) do |submission, hash|
  attrs = { submission.form_id => submission.created_at }
  hash[submission.user_id] =
    if hash[submission.user_id].blank?
      attrs
    else
      hash[submission.user_id].merge(attrs)
    end
end
```

## RuboCop version

```
› bundle exec rubocop -V
1.85.0 (using Parser 3.3.10.2, Prism 1.9.0, parser_prism, rubocop-ast 1.49.0, analyzing as Ruby 3.4, running on ruby 3.4.7) [arm64-darwin25]
  - rubocop-rails 2.34.3
  - rubocop-performance 1.26.1
  - rubocop-rspec 3.9.0
  - rubocop-rspec_rails 2.32.0
  - rubocop-factory_bot 2.28.0
```

### PR DESCRIPTION
**Pull request by sferik**
When the accumulator variable (e.g. `hash`) is referenced inside the key or value expression of `hash[key] = value`, converting to `to_h` is invalid because the variable no longer exists in the new block.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/reduce_to_hash.rb [hunk 1]
```diff
@@ -98,10 +98,32 @@ def check_offense(node, block_node)
...
+        end
+
+        def accumulator_name(block_node)
+          if block_node.numblock_type?
+            block_node.method?(:each_with_object) ? :_2 : :_1
+          elsif block_node.method?(:each_with_object)
+            block_node.arguments[1].source.to_sym
+          else
+            block_node.first_argument.source.to_sym
+          end
```
Comment (koic) [inline lib/rubocop/cop/style/reduce_to_hash.rb]:
```suggestion
          index = block_node.method?(:each_with_object) ? 1 : 0
          block_node.argument_list[index].name
```

File: lib/rubocop/cop/style/reduce_to_hash.rb [hunk 2]
```diff
@@ -98,10 +98,32 @@ def check_offense(node, block_node)
...
+        end
+
+        def references_variable?(node, name)
+          return true if node.lvar_type? && node.children.first == name
+
+          node.each_child_node.any? { |child| references_variable?(child, name) }
```
Comment (koic) [inline lib/rubocop/cop/style/reduce_to_hash.rb]:
```suggestion
          node.each_node(:lvar).any? { |lvar| lvar.children.first == name }
```

File: lib/rubocop/cop/style/reduce_to_hash.rb [hunk 3]
```diff
@@ -98,10 +98,31 @@ def check_offense(node, block_node)
...
+        def accumulator_name(block_node)
+          if block_node.numblock_type?
+            block_node.method?(:each_with_object) ? :_2 : :_1
+          elsif block_node.method?(:each_with_object)
+            block_node.arguments[1].source.to_sym
+          else
+            block_node.first_argument.source.to_sym
+          index = block_node.method?(:each_with_object) ? 1 : 0
+          block_node.argument_list[index].name
+        end
```
Comment (koic) [inline lib/rubocop/cop/style/reduce_to_hash.rb:114]: It seems the diff was not applied correctly. The intended changes are as follows.

```suggestion
        def accumulator_name(block_node)
          index = block_node.method?(:each_with_object) ? 1 : 0
          block_node.argument_list[index].name
        end
```

**Comment by sferik** [comment]
Sorry, I was reviewing and merging your suggestions from my phone. Back at my laptop now. I will rebase and squash those changes into a single commit.

**Comment by sferik** [comment]
@koic How does it look now?
