### PR TITLE
Call .value to get gemspec required_ruby_version only if str_type?

### LINKED ISSUE #12744: rubocop-1.61.0 crashes when the project's gemspec dynamically sets `spec.required_ruby_version`
If a ruby project's `.gemspec` file dynamically sets the `required_ruby_version` value, this causes rubocop to crash while attempting to parse the right-hand side of the `spec.required_ruby_version` assignment.

## Expected behavior

`rubocop` does not raise an exception.

## Actual behavior

Exception during parsing of the `.gemspec` file.

```
For /home/postmodern/test/ruby/rubocop: Default configuration from /home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/config/default.yml
Use parallel by default.
Running parallel inspection
Loading cache from /home/postmodern/.cache/rubocop_cache/63946c0a4b45db596847d31eeb2af70462172a01/6d7a3b621ca1730e04accd938619e4bdab66cfb1/8a1678080d7059e7ca65c4e59b9279c0c996b758
Loading cache from /home/postmodern/.cache/rubocop_cache/63946c0a4b45db596847d31eeb2af70462172a01/6d7a3b621ca1730e04accd938619e4bdab66cfb1/3ad87dc6dd6f42e6ea5cba216e50c80c2fc1b1e3
undefined method `value' for s(:send,
  s(:send, nil, :data), :[],
  s(:str, "ruby_version")):RuboCop::AST::SendNode
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:111:in `version_from_right_hand_side'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:120:in `find_default_minimal_known_ruby'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:83:in `find_version'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:29:in `initialize'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:257:in `new'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:257:in `block in source'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:257:in `each'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:257:in `each'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:257:in `each'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:257:in `each'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:257:in `each'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:257:in `detect'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:257:in `source'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/target_ruby.rb:261:in `version'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/config_validator.rb:63:in `target_ruby_version'
/usr/share/ruby/forwardable.rb:240:in `target_ruby_version'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/runner.rb:472:in `get_processed_source'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/runner.rb:273:in `do_inspection_loop'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/runner.rb:164:in `block in file_offenses'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/runner.rb:189:in `file_offense_cache'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/runner.rb:163:in `file_offenses'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/runner.rb:99:in `block in warm_cache'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:627:in `call_with_index'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:597:in `process_incoming_jobs'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:577:in `block in worker'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:568:in `fork'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:568:in `worker'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:559:in `block in create_workers'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:558:in `each'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:558:in `each_with_index'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:558:in `create_workers'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:497:in `work_in_processes'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:291:in `map'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/parallel-1.24.0/lib/parallel.rb:235:in `each'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/runner.rb:99:in `warm_cache'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/runner.rb:72:in `run'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli/command.rb:11:in `run'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli.rb:118:in `run_command'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli.rb:125:in `execute_runners'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli.rb:51:in `block in run'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/lib/rubocop/cli.rb:43:in `run'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/exe/rubocop:19:in `block in <top (required)>'
/usr/share/ruby/benchmark.rb:311:in `realtime'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/gems/rubocop-1.61.0/exe/rubocop:19:in `<top (required)>'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/bin/rubocop:25:in `load'
/home/postmodern/test/ruby/rubocop/vendor/bundle/ruby/3.2.0/bin/rubocop:25:in `<top (required)>'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/cli.rb:492:in `exec'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/cli.rb:28:in `start'
/usr/local/share/gems/gems/bundler-2.4.20/exe/bundle:37:in `block in <top (required)>'
/usr/local/share/gems/gems/bundler-2.4.20/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/share/gems/gems/bundler-2.4.20/exe/bundle:29:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Finished in 0.3068897270022717 seconds
```

## Steps to reproduce the problem

1. `bundle gem test`
2. `cd test/`
3. Edit `test.gemspec` and add the line `  spec.required_ruby_version = ENV['required_ruby_version']` to the `Gem::Specification.new` block.
4. Edit the `Gemfile`:

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rubocop'
```
5. `bundle install`
6. `bundle exec rubocop`

## RuboCop version

```
$ bundle exec rubocop -V
1.61.0 (using Parser 3.3.0.5, rubocop-ast 1.31.1, running on ruby 3.2.2) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by davidrunger**
fixes #12744

This change avoids an exception (NoMethodError: undefined method \`value' for an instance of RuboCop::AST::SendNode) that currently occurs in `rubocop` version 1.61.0 when the project has a gemspec file and that gemspec specifies a `required_ruby_version` by reading from another file (such as `.ruby-version`).

**Example of an affected gemspec file:**

```rb
Gem::Specification.new do |spec|
  # ...
  spec.required_ruby_version = Gem::Requirement.new(">= #{File.read('.ruby-version').rstrip}")
  # ...
end
```

This bug began occurring in several of my projects as a result of #12645 (d1746bedd) ("Check gemspec `required_ruby_version` before `.ruby-version` and other sources"). My projects have both a `.ruby-version` file and also a gemspec that (as in the example above) sets the `required_ruby_version` by reading from that `.ruby-version` file. Prior to #12645, the latent bug that this change fixes was not occurring for me, because the GemspecFile TargetRuby finder was never running, because the RubyVersionFile TargetRuby finder had higher precedence (and a target Ruby version was found using this finder), and so the GemspecFile TargetRubyVersion finder was never invoked.

With #12645, because the GemspecFile finder now runs before the RubyVersionFile finder, this exception has started occurring in these projects, when I try to run rubocop 1.61.0.

This change fixes/avoids this exception by checking that the `right_hand_side` is a `str_type?` before attempting to call `right_hand_side.value`. In a setup like mentioned in my projects above, `right_hand_side` will be a `RuboCop::AST::SendNode` and `str_type?` will be `false`, so we avoid the NoMethodError exception that otherwise will occur if we attempt to call `.value` on that node.

With this change, for projects with such a gemspec file that reads from a `.ruby-version` file, the GemspecFile finder will now return `nil` for the target Ruby version (rather than raising an unhandled exception), and so we will continue through the other TargetRuby finder classes, until the RubyVersionFile finder returns a Ruby version based on the one specified in the `.ruby-version` file.

I also updated several of the specs in the `target_ruby_spec.rb` file. The motivation for these spec changes is that several of the specs were at risk of "falsely passing", because they had spec setups that intended for `2.7` to be returned as the target Ruby version, but Ruby 2.7 is also currently the `RuboCop::TargetRuby::DEFAULT_VERSION`. So, in working on the bug that is the focus of this change, although one of my initial attempts to fix the bug actually broke some relevant functionality, all of the specs nevertheless still passed, because they expected a target Ruby version of 2.7 to be returned, and it _was_ still being returned, even after I had broken some of the functionality, simply because Ruby 2.7 is also the default. By setting up the specs to expect a target Ruby version other than the default (Ruby 2.7), the specs will now fail, if/when the relevant functionality under test is broken.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/target_ruby_spec.rb [hunk 1]
```diff
@@ -42,39 +42,39 @@
           content = <<~HEREDOC
             Gem::Specification.new do |s|
               s.name = 'test'
-              s.required_ruby_version = '>= 2.7.2'
+              s.required_ruby_version = '>= 3.2.2'
```
Comment (davidrunger) [inline spec/rubocop/target_ruby_spec.rb:45]: As alluded to in the PR description, most of these changes to Ruby version numbers in this PR are not necessary. The specs continue to pass without these changes. The reason that I am making these changes is because these specs were at risk of passing, even when the relevant functionality has been broken, because the specs previously expected `2.7` to be returned, which also happens to be the current default Ruby version. By changing the specs to expect a non-default Ruby version, they will now fail, if/when the relevant functionality is broken (as, indeed, I did break it, in one of my initial attempts at fixing this bug).

File: spec/rubocop/target_ruby_spec.rb [hunk 2]
```diff
@@ -163,26 +163,41 @@
...
+            end
+          HEREDOC
+
+          create_file(gemspec_file_path, content)
+          expect(target_ruby.version).to eq 3.2
+        end
+      end
+
+      context 'when file reads the required_ruby_version from another file' do
+        it 'uses the default target ruby version' do
```
Comment (davidrunger) [inline spec/rubocop/target_ruby_spec.rb:190]: This is the only new spec actually being added in this PR. All of the other changes in this file are just changing the Ruby version for existing specs.

**Comment by bbatsov** [comment]
The tests are currently failing.

**Comment by bbatsov** [comment]
Done.

**Comment by davidrunger** [comment]
@bbatsov : Tests passed, with the exception of "CircleCI Pipeline" (which I am guessing you need to separately approve?) and a number of pending checks (which I am guessing will be run after you approve the "CircleCI Pipeline" check?).

Thank you again for working with me on this!

**Comment by bbatsov** [comment]
Something seems broken with CircleCI in general right now, but I'll look into this separately. Thanks for working on this!
