### PR TITLE
[Fix #12146] Fix a false positive for `Lint/FloatComparison`

### LINKED ISSUE #12146: `Lint/FloatComparison`, `Style/NumericPredicate` and comparing by 0
I have the following rubocop config:

```yaml
Style/NumericPredicate:
  EnforcedStyle: comparison
```

`Lint/FloatComparison` discourages comparing by absolute values. I know why but zero seems like something that should be made an exception for.

```rb
if value.to_f != 0.0 # Lint/FloatComparison: Avoid (in)equality comparisons of floats as they are unreliable
  10 / value.to_f
end
```

If I switch to `EnforcedStyle: predicate` for `Style/NumericPredicate` I can write the following without offence:

```rb
unless value.to_f.zero? # All good!
  10 / value.to_f
end
```
`value` is user-provided and I want to prevent `NaN` from being returned, falling back to some other logic in that case. Alternatively, how would I write this without triggering an offense?

## Expected behavior

Rubocop should either allow `value.to_f != 0.0` or disallow `value.to_f.zero?`

## RuboCop version

```
$ [bundle exec] rubocop -V
1.55.1 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [x86_64-linux-musl]
  - rubocop-erb 0.3.0
  - rubocop-rails 2.20.2
```

### PR DESCRIPTION
**Pull request by Earlopain**
Allow comparing against 0. See https://github.com/rubocop/rubocop/pull/12387#issuecomment-1818508562

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by koic** [comment]
This cop is categorized under `Lint`, not `Style`. `0.zero?`, `0.0.zero?`, and `0 == 0.0` all return true. Therefore, it doesn't seem like bad code that should be marked as bad in `Lint`.

It appears that this issue should rather be addressed under `Style/NumericPredicate` to ensure consistency, I think.

**Comment by Earlopain** [comment]
`0.0 == 0.0` returns true as well but is still flagged by `Lint/FloatComparison`. That is kind of the point that I made in my initial issue. 0 has special meaning and sometimes it is wanted to check for it. Basically https://github.com/rubocop/rubocop/pull/8432#issuecomment-682931742

My understanding is that `Style/NumericPredicate` enforces uniform usage of `x == 0` and `x.zero?` while `Lint/FloatComparison` makes you aware that you are dealing with floating point numbers and should be careful. This change seems appropriate, at least for how it currently works.

However, if you want to change `Lint/FloatComparison` to not flag comparision by zero, especially with  `x == 0.0` which is currently an offense, I can give that a shot as well.

**Comment by koic** [comment]
> `0.0 == 0.0` returns true as well but is still flagged by `Lint/FloatComparison`.

This looks like a false positive. In any case, registering an offense for `zero?` by `Lint` cop seems strict for the users.

> However, if you want to change `Lint/FloatComparison` to not flag comparision by zero, especially with  `x.to_f == 0.0` which is currently an offense, I can give that a shot as well.

Yeah, that seems reasonable to me. I think zero is special.

**Comment by Earlopain** [comment]
Changed as requested. I'm not entirely sure if I only need to check in `on_send` but I couldn't think of an example that doesn't work with this

File: lib/rubocop/cop/lint/float_comparison.rb [hunk 1]
```diff
@@ -15,6 +15,10 @@ module Lint
       #   x == 0.1
       #   x != 0.1
       #
+      #  # good - comparing against zero
+      #   x == 0.0
+      #   x != 0.0
```
Comment (koic) [inline lib/rubocop/cop/lint/float_comparison.rb:20]: Nits: Can you swap the positions of the `# good - using BigDecimal` example? It's to contrast it with the bad case, as `# good - using BigDecimal` is more illustrative when placed opposite.

**Comment by koic** [comment]
Thanks!
