### PR TITLE
[Fix #12024] Fix a false positive for `Lint/RedundantRegexpQuantifiers`

### LINKED ISSUE #12024: RedundantRegexpQuantifiers is incorrect with interpolated values
The new Lint/RedundantRegexpQuantifiers rule (#11565) thinks that this regexp:

```ruby
FOO = /foo/
BAR = /a*#{FOO}?/x
```

ought to be corrected to:

```ruby
FOO = /foo/
BAR = /a*#{FOO}/x
```

which unless I'm missing something is not the same thing.

--------

## Expected behavior


No warnings for the above regexp


## Actual behavior

```
bundle exec rubocop --debug foo.rb                                                                                                                                                                                                                                                                                                   Mon  3 Jul 17:42:40 2023
For /Users/jon/Developer/web: configuration from /Users/jon/Developer/web/.rubocop.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-capybara-2.18.0/config/default.yml
Default configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-1.54.0/config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-capybara-2.18.0/lib/../config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-factory_bot-2.22.0/config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-factory_bot-2.22.0/lib/../config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-performance-1.18.0/config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-performance-1.18.0/config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-rails-2.20.2/config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-rails-2.20.2/config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-rspec-2.22.0/config/default.yml
configuration from /Users/jon/Developer/web/vendor/bundle/nix-bundle/ruby/3.2.0/gems/rubocop-rspec-2.22.0/config/default.yml
Inheriting configuration from /Users/jon/Developer/web/.rubocop_todo.yml
Inspecting 1 file
Scanning /Users/jon/Developer/web/foo.rb
Loading cache from /Users/jon/.cache/rubocop_cache/48171ced22e8e3296ed3e6f7fd0eceeed315852b/54104447a3375cf77f8576dbe02772b138da069d/5807de7a226f560f395da1b40085f52f19a101a7
W

Offenses:

foo.rb:4:9: W: [Correctable] Lint/RedundantRegexpQuantifiers: Replace redundant quantifiers * and ? with a single *.
BAR = /a*#{FOO}?/x
        ^^^^^^^^

1 file inspected, 1 offense detected, 1 offense autocorrectable
Finished in 0.324270000011893 seconds
```

## Steps to reproduce the problem

Create a file containing:

```ruby
# frozen_string_literal: true

FOO = /foo/
BAR = /a*#{FOO}?/x
```

and run rubocop on it.

## RuboCop version

```
$ bundle exec rubocop -V
1.54.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [arm64-darwin21]
  - rubocop-capybara 2.18.0
  - rubocop-factory_bot 2.22.0
  - rubocop-performance 1.18.0
  - rubocop-rails 2.20.2
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.22.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12024.

This PR fixes a false positive for `Lint/RedundantRegexpQuantifiers` when interpolation is used in a regexp literal.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/redundant_regexp_quantifiers.rb [hunk 1]
```diff
@@ -5,6 +5,9 @@ module Cop
     module Lint
       # Checks for redundant quantifiers inside Regexp literals.
       #
+      # It is always allowed when interpolation is used in a regexp literal,
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/redundant_regexp_quantifiers.rb:8]: I'd also add an example illustrating the use of interpolation.

Comment (koic) [reply lib/rubocop/cop/lint/redundant_regexp_quantifiers.rb:8]: Sure! I added an example for it.

**Comment by bbatsov** [comment]
Thanks!
