### PR TITLE
[Fix #14605] Fix false positive for `Lint/EmptyInterpolation` when interpolation is inside a `%W` literal

### LINKED ISSUE #14605: `Lint/EmptyInterpolation` false positive
`Lint/EmptyInterpolation` does not understand that being inside `%W` affects behavior; Auto-correct changes program semantics:

```
3.4.6 :001 > %W[#{''} test]
 => ["", "test"]
3.4.6 :002 > %W[ test]
 => ["test"]
```

--------

## Steps to reproduce the problem

```ruby
# in example.rb

def foo
  parts = %W[#{""} one two]
  raise StandardError if parts.length < 3
  puts "done"
end

foo
```

Running `ruby example.rb` prints "done" to the console.

## Expected behavior

Running `rubocop --only Lint/EmptyInterpolation --autocorrect example.rb` should not change the file.

## Actual behavior

```
Inspecting 1 file
W

Offenses:

example.rb:2:14: W: [Corrected] Lint/EmptyInterpolation: Empty interpolation detected.
  parts = %W[#{""} one two]
             ^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

The file is incorrectly changed to:

```ruby
def foo
  parts = %W[ one two]
  raise StandardError if parts.length < 3
  puts "done"
end

foo
```

Running `ruby example.rb` now errors:

```
example.rb:3:in 'Object#foo': StandardError (StandardError)
	from example.rb:7:in '<main>'
```

## RuboCop version

```
rubocop -V
1.80.2 (using Parser 3.3.9.0, rubocop-ast 1.47.1, analyzing as Ruby 2.7, running on ruby 3.4.6) [arm64-darwin24]
```

### PR DESCRIPTION
**Pull request by dvandersluis**
Interpolating an empty string inside a `%W` literal is a common way to include an empty string in the resulting array.

Fixes #14605.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/empty_interpolation_spec.rb [hunk 1]
```diff
@@ -82,4 +82,21 @@
...
+  it 'registers an offense for an empty string interpolation inside an array' do
+    expect_offense(<<~'RUBY')
+      ["#{''}", one, two]
+        ^^^^^ Empty interpolation detected.
+    RUBY
+
+    expect_correction(<<~RUBY)
+      ["", one, two]
+    RUBY
+  end
```
Comment (koic) [inline spec/rubocop/cop/lint/empty_interpolation_spec.rb:107]: It looks like the same handling is needed not only for `%W` but also for `%I`.

File: lib/rubocop/cop/lint/empty_interpolation.rb [hunk 2]
```diff
@@ -19,12 +19,23 @@ class EmptyInterpolation < Base
...
           add_offense(begin_node) { |corrector| corrector.remove(begin_node) }
         end
+
+        private
+
+        def in_percent_w_upper_literal?(begin_node)
+          array_node = begin_node.each_ancestor(:array).first
+          return false unless array_node
+
+          array_node.source.start_with?('%W')
```
Comment (koic) [inline lib/rubocop/cop/lint/empty_interpolation.rb]: Considering `%I` as well, wouldn’t `percent_literal?` be more appropriate?

```suggestion
          array_node.percent_literal?
```

Comment (dvandersluis) [reply lib/rubocop/cop/lint/empty_interpolation.rb]: `percent_literal?` allows for `%w` and `%i` too but since those cannot contain dstr/dsym, it should be okay.

File: spec/rubocop/cop/lint/empty_interpolation_spec.rb (hunk 1 above)
Comment (dvandersluis) [reply spec/rubocop/cop/lint/empty_interpolation_spec.rb:107]: Good point, thank you. Updated.

**Comment by koic** [comment]
Thanks!
