### PR TITLE
[Fix #13415] Fix false positives for `Naming/MemoizedInstanceVariableName`

### LINKED ISSUE #13415: `Naming/MemoizedInstanceVariableName` should disable if method name is `initialize_copy`, `initialize_clone`, `initialize_dup`
https://github.com/rubocop/rubocop/blob/b1113a2593f9921d0d11059ab464e4bd2f891ced/lib/rubocop/cop/naming/memoized_instance_variable_name.rb#L254

### PR DESCRIPTION
**Pull request by koic**
Fixes #13415.

This PR fixes false positives for `Naming/MemoizedInstanceVariableName` when using `initialize_clone`, `initialize_copy`, or `initialize_dup`.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/naming/memoized_instance_variable_name.rb [hunk 1]
```diff
@@ -155,6 +155,7 @@ class MemoizedInstanceVariableName < Base
         UNDERSCORE_REQUIRED = 'Memoized variable `%<var>s` does not start ' \
                               'with `_`. Use `@%<suggested_var>s` instead.'
         DYNAMIC_DEFINE_METHODS = %i[define_method define_singleton_method].to_set.freeze
+        INITIALIZE_METHODS = %i[initialize initialize_clone initialize_copy initialize_dup].freeze
```
Comment (lolychee) [inline lib/rubocop/cop/naming/memoized_instance_variable_name.rb:158]: you forget to add `to_set`
