### PR TITLE
[Fix #13969] Fix a false positive for `Lint/SharedMutableDefault`

### LINKED ISSUE #13969: Cop `Lint/SharedMutableDefault` reports on ruby 3.4 Hash.new(capacity: 1) form
Ruby 3.4 introduces optional keyword argument `capacity`
https://docs.ruby-lang.org/en/3.4/Hash.html#method-c-new

Cop `Lint/SharedMutableDefault` is reporting that valid usage as invalid

Image

--------

## Expected behavior
`Lint/SharedMutableDefault` does not report code like `Hash.new(capacity: 1)` to be invalid

## Actual behavior
```
(spacious-rails-sxxp) ~/projects/spacious/spacious-rails (master ✗) rubocop --debug rubocop_test.rb
For /Users/pikachuexe/projects/spacious/spacious-rails: configuration from /Users/pikachuexe/projects/spacious/spacious-rails/.rubocop.yml
Inheriting configuration from /Users/pikachuexe/projects/spacious/spacious-rails/.rubocop.base.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-performance-1.24.0/config/default.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-rails-2.30.3/config/default.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-rake-0.7.1/config/default.yml
Inheriting configuration from /Users/pikachuexe/projects/spacious/spacious-rails/.rubocop.performance.yml
Inheriting configuration from /Users/pikachuexe/projects/spacious/spacious-rails/.rubocop.base.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-performance-1.24.0/config/default.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-rails-2.30.3/config/default.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-rake-0.7.1/config/default.yml
Inheriting configuration from /Users/pikachuexe/projects/spacious/spacious-rails/.rubocop.lint.yml
Inheriting configuration from /Users/pikachuexe/projects/spacious/spacious-rails/.rubocop.base.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-performance-1.24.0/config/default.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-rails-2.30.3/config/default.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-rake-0.7.1/config/default.yml
Inheriting configuration from /Users/pikachuexe/projects/spacious/spacious-rails/.rubocop.security.yml
Inheriting configuration from /Users/pikachuexe/projects/spacious/spacious-rails/.rubocop.base.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-performance-1.24.0/config/default.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-rails-2.30.3/config/default.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-rake-0.7.1/config/default.yml
Inheriting configuration from /Users/pikachuexe/projects/spacious/spacious-rails/.rubocop.rake.yml
Inheriting configuration from /Users/pikachuexe/projects/spacious/spacious-rails/.rubocop.base.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-performance-1.24.0/config/default.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-rails-2.30.3/config/default.yml
Plugin configuration from /Users/pikachuexe/.local/share/mise/installs/ruby/3.4.2/lib/ruby/gems/3.4.0/gems/rubocop-rake-0.7.1/config/default.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /Users/pikachuexe/projects/spacious/spacious-rails/rubocop_test.rb
W

Offenses:

rubocop_test.rb:3:1: W: Lint/SharedMutableDefault: Do not create a Hash with a mutable default value as the default value can accidentally be changed.
Hash.new(capacity: 1)
^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## Steps to reproduce the problem
Set rubocop config to enable the cop like:
```yaml
Lint/SharedMutableDefault:
  Enabled: true
  Severity: warning
```

Create `rubocop_test.rb`
```ruby
Hash.new(capacity: 1)
```

Run `rubocop --debug rubocop_test.rb`

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ [bundle exec] rubocop -V
1.73.2 (using Parser 3.3.7.1, rubocop-ast 1.38.1, analyzing as Ruby 3.4, running on ruby 3.4.2) +server [arm64-darwin22]
  - rubocop-performance 1.24.0
  - rubocop-rails 2.30.3
  - rubocop-rake 0.7.1
  - rubocop-performance 1.24.0
  - rubocop-rails 2.30.3
  - rubocop-rake 0.7.1
...
```
(It keeps printing same 3 lines so many times)

### PR DESCRIPTION
**Pull request by koic**
This PR fixes a false positive for `Lint/SharedMutableDefault` when `capacity` keyword argument is used.

NOTE: The `minimum_target_ruby_version: 3.4` is intentionally not specified. A false negative may occur in Ruby 3.3 or earlier, but the intent behind upgrading to Ruby 3.4 is prioritized.

Fixes #13969.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/shared_mutable_default_spec.rb [hunk 1]
```diff
@@ -38,6 +38,14 @@
     end
   end
 
+  context 'when `capacity` keyword argument is used' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/shared_mutable_default_spec.rb:41]: Might be a good idea to also have a test for a combination of a default value and `capacity:`.

Comment (koic) [reply spec/rubocop/cop/lint/shared_mutable_default_spec.rb:41]: I have added a test case for `Hash.new(capacity:)`. However, this represents hash value omission introduced in Ruby 3.1 rather than a default value. Please let me know if this differs from the intended meaning of the comment.

Comment (bbatsov) [reply spec/rubocop/cop/lint/shared_mutable_default_spec.rb:41]: That's a good test, but I was thinking of something like:

`Hash.new({}, capacity: 42)` that would flag an offense. Basically a test for a combination of a default value and keyword params. (looking at the API those can be combined)

**Comment by bbatsov** [comment]
Thanks!
