### PR TITLE
[Fix #14665] Cache plugin integration in CopHelper to avoid repeated loading

### LINKED ISSUE #14665: Performance issue with rubocop rspec support
I was profiling a fairly large rspec test suite (with sampling) which is using `require rubocop/rspec/support` in order to enable testing of internal custom cops. I found that the `cop_helper` which is included there defines a global `before(:all)` hook that causes the rubocop config to be loaded, parsed, and validated for every example in the whole suite, which ends up having a significant performance impact over the whole runtime, especially considering there are only a few small examples that are testing custom cops.

I think this overhead is more or less acceptable in the context of testing cops, especially if it is difficult to fix, but IMO this overhead shouldn't leak out to the rest of the suite. It would be better if the hook could be conditionally included for a specific spec file or example group without leaking, or globally if the caller wants to use it that way.

Image

--------

## Steps to reproduce the problem
`require rubocop/rspec/support` in `rails_helper.rb`

## Expected behavior
`cop_helper`'s `before(:all)` hook performance impact does not leak to all examples unrelated to testing cops

## Actual behavior
`cop_helper`'s `before(:all)` hook performance impact does leak to all examples unrelated to testing cops

## RuboCop version
```
bundle exec rubocop -V
1.81.1 (using Parser 3.3.9.0, Prism 1.5.2, rubocop-ast 1.47.1, analyzing as Ruby 3.4, running on ruby 3.4.7) [arm64-darwin24]
  - rubocop-rails 2.33.4
  - rubocop-rspec 3.7.0
  - rubocop-performance 1.26.0
```

### PR DESCRIPTION
**Pull request by 55728**
## Description

Cache plugin integration in `CopHelper#before(:all)` to run `Plugin.integrate_plugins` only once per process instead of once per example group.

Fixes #14665

## Root Cause

`rubocop/rspec/support` globally includes `CopHelper` via `config.include CopHelper`, which means the `before(:all)` hook fires for every `describe` block in the test suite. Each invocation calls `Plugin.integrate_plugins`, which loads and integrates all plugins from scratch — scanning `Gem.loaded_specs`, requiring gems, and merging configuration.

In large test suites with hundreds of `describe` blocks, this repeated integration adds significant overhead to examples that don't test cops at all.

## Changes

Add a module-level `plugins_integrated` flag to `CopHelper` that ensures `Plugin.integrate_plugins` runs only once per process. Subsequent `before(:all)` invocations hit `next if CopHelper.plugins_integrated` and return immediately.

This is safe because plugin integration is idempotent:
- Gem `require` is a no-op if already loaded
- Cop registry entries are not duplicated
- Configuration merging produces the same result

## Design Note

The root cause is that `CopHelper` is globally included rather than scoped to cop-testing examples (e.g., via `config.include CopHelper, :cop_test`). A metadata-based approach would be a more fundamental fix but would be a breaking change for existing users of `rubocop/rspec/support`. This caching approach resolves the performance issue without breaking the public API.

## Test Results

```
bundle exec rake spec
31,246 examples, 0 failures

bundle exec rubocop
1,704 files inspected, no offenses detected
```

### CODE REVIEW

File: lib/rubocop/rspec/cop_helper.rb [hunk 1]
```diff
@@ -6,6 +6,12 @@
 module CopHelper
   extend RSpec::SharedContext
 
+  @plugins_integrated = false
+
+  class << self
+    attr_accessor :plugins_integrated
```
Comment (bbatsov) [inline lib/rubocop/rspec/cop_helper.rb]: Why not `integrated_plugins`? The proposed name reads somewhat odd.

Comment (55728) [reply lib/rubocop/rspec/cop_helper.rb]: Good point, renamed to integrated_plugins. Force-pushed.
