### PR TITLE
[Fix #11482] Avoid comment deletion by `Style/IfUnlessModifier` when the modifier form expression has long comment

### LINKED ISSUE #11482: Comment deletion in if/unless modifier lines
When examining long lines with `if` or `unless` modifiers and subsequent comments,
RuboCop with the `-A` flag deletes the comment, leaving the surrounding code as is.

This problem can easily go unnoticed and is (to me at least) unexpected.

--------

## Steps to reproduce the problem

Using the default configuration (i.e. no custom 'rubocop.yml'),
create a file with the following line:

```ruby
some_statement if some_quite_long_condition # The condition might have been long, but this comment is longer. In fact, it is too long for Rubocop
```

Then run `rubocop -A` on the file.

## Expected behavior

Detect that the comment is causing the line to be too long, and place it somewhere sensible.

For example:

```ruby
# The condition might have been long, but this comment is longer. In fact, it is too long for Rubocop
some_statement if some_quite_long_condition
```

## Actual behavior

RoboCop seems to blame the `if` modifier to cause the long line.

```
test.rb:3:16: C: [Corrected] Style/IfUnlessModifier: Modifier form of if makes the line too long.
some_statement if some_quite_long_condition # The condition might have been long, but this comment is longer. In fact, it is too long for Rubocop
```

It proceeds to transform it into the following:

```ruby
if some_quite_long_condition
  some_statement
end # The condition might have been long, but this comment is longer. In fact, it is too long for Rubocop
```

Next, it dislikes the comment after `end`, so it presumably removes it (I have not yet confirmed that the comment is removed in this step).

```
test.rb:5:5: C: [Corrected] Style/CommentedKeyword: Do not place comments on the same line as the end keyword.
end # The condition might have been long, but this comment is longer. In fact, it is too long for Rubocop
```

With the comment out of the way, RuboCop prefers the modifier form of `if`:

```
test.rb:3:1: C: [Corrected] Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
if some_quite_long_condition
```

The final result is the initial line with the comment missing. No other lines have been touched.

```ruby
some_statement if some_quite_long_condition
```

## RuboCop version

```
1.43.0 (using Parser 3.2.0.0, rubocop-ast 1.24.1, running on ruby 3.0.5) [x86_64-linux]
```

For debugging purposes, here is the (anonymized) `--debug` header from my tests:

```
For $PWD: Default configuration from /usr/lib/ruby/gems/3.0.0/gems/rubocop-1.43.0/config/default.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning $PWD/test.rb
Loading cache from $HOME/.cache/rubocop_cache/3fb3810be52a0588e38fe598cd2408c05c5458f4/6d7a3b621ca1730e03accd938619e4bdab66cfb1/69258fadcfb00690acd86d208048f4cb9810aca7
```

I am using Arch Linux. If helpful, [here](https://github.com/archlinux/svntogit-community/blob/packages/rubocop/trunk/PKGBUILD) is the script to build and package rubocop.

### PR DESCRIPTION
**Pull request by nobuyo**
This PR fixes #11482.

Now the cop corrects code from:
```rb
# frozen_string_literal: true

some_statement if some_quite_long_condition # The condition might have been long, but this comment is longer. In fact, it is too long for Rubocop
```
to:

```rb
# frozen_string_literal: true

# The condition might have been long, but this comment is longer. In fact, it is too long for Rubocop
some_statement if some_quite_long_condition
```

I think the correction is ok. But the message for the offense is still indicate `if` is bad, not comment.
Any ideas for this?

```console
test.rb:3:16: C: [Corrected] Style/IfUnlessModifier: Modifier form of if makes the line too long.
some_statement if some_quite_long_condition # The condition might have been long, but this comment is longer. In fact, it is too long for Rubocop
               ^^
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/if_unless_modifier.rb [hunk 1]
```diff
@@ -101,26 +102,43 @@ def defined_argument_is_undefined?(if_node, defined_node)
...
+
         def too_long_due_to_modifier?(node)
           node.modifier_form? && too_long_single_line?(node) &&
             !another_statement_on_same_line?(node)
         end
 
+        def too_long_due_to_comment_after_modifier?(node, comment)
+          source_length = processed_source.lines[node.first_line - 1].length
+          source_length >= max_line_length \
+            && source_length - comment.source_range.length <= max_line_length
```
Comment (koic) [inline lib/rubocop/cop/style/if_unless_modifier.rb:139]:
```suggestion
          source_length >= max_line_length &&
            source_length - comment.source_range.length <= max_line_length
```

**Comment by koic** [comment]
> I think it's unrelated to the change in this PR. Should I report this as a bug?

Hm, I'm not sure if a non-reproducible issue on CI should be opened.

**Comment by nobuyo** [comment]
> > I think it's unrelated to the change in this PR. Should I report this as a bug?
> 
> Hm, I'm not sure if a non-reproducible issue on CI should be opened.

OK, I misread comment and opened the issue, never mind.

**Comment by bbatsov** [comment]
The changes look good to me. Thanks!
