### PR TITLE
[Fix #10949] Fix documentation error for `Layout/BlockAlignment`

### LINKED ISSUE #10949: Documentation bug: bad code and good code are completely different
Apologies if this is the wrong place for documentation bugs, but this looks wrong:
```
# bad

foo.bar
   .each do
     baz
       end

# good

variable = lambda do |i|
  i
end
```
(from https://docs.rubocop.org/rubocop/cops_layout.html#enforcedstylealignwith-either-default ) because the _good_ version of the code and the _bad_ version of the code bear no relation to each other.

### PR DESCRIPTION
**Pull request by ydah**
Resolve: #10949

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [-] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [-] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/block_alignment.rb [hunk 1]
```diff
@@ -51,16 +52,17 @@ module Layout
...
-      #          end
+      #     .each do
+      #       baz
+      #         end
       #
       #   # good
       #
       #   foo.bar
       #     .each do
-      #        baz
```
Comment (ydah) [inline lib/rubocop/cop/layout/block_alignment.rb:62]: [memo] This indentation also changes at `.each do` with bad/good, which seemed confusing, so we are fixing that.

File: lib/rubocop/cop/layout/block_alignment.rb [hunk 2]
```diff
@@ -22,23 +22,24 @@ module Layout
...
+      #       baz
       #   end
       #
       # @example EnforcedStyleAlignWith: start_of_block
       #   # bad
       #
       #   foo.bar
-      #      .each do
-      #        baz
-      #          end
```
Comment (ydah) [inline lib/rubocop/cop/layout/block_alignment.rb:41]: [memo] This indentation also changes at .each do with bad/good, which seemed confusing, so we are fixing that.
