### PR TITLE
[Fix #13364] Fix incorrect autocorrect with `Lint/UselessAssignment` a multiple assignment or `for` contains an inner assignment

### LINKED ISSUE #13364: `Lint/UselessAssignment` autofix completely trashes an expression
## Expected behavior

Describe here how you expected RuboCop to behave in this particular situation.

```ruby
def func(a, b, c = 0)
  [a, b, c]
end

a, = func(
  1,
  2,
  3,
)

a
```

## Actual behavior

Describe here what actually happened.
Please use `rubocop --debug` when pasting rubocop output as it contains additional information.

```console
$ ./rubocop --except Naming/MethodParameterName -a t.rb 
/home/stdedos/Documents/RelexOy/planning-cloud/backend/bin/bundle:7: warning: unused literal ignored
t.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
def func(a, b, c = 0)
^
t.rb:8:3: W: [Corrected] Lint/UselessAssignment: Useless assignment to variable - c. Use _ or _c as a variable name to indicate that it won't be used.
  c = 3,
  ^
 1/1 file |======================= 100 =======================>| Time: 00:00:01 

1 file inspected, 2 offenses detected, 1 offense corrected, 1 more offense can be corrected with `rubocop -A`


You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false
$ cat t.rb 
def func(a, b, c = 0)
  [a, b, c]
end

a, = func(
  1,
  2,
  _,
)

a
```

## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ [bundle exec] rubocop -V
1.67.0 (using Parser 3.3.5.0, rubocop-ast 1.32.3, analyzing as Ruby 3.3, running on ruby 3.3.5) [x86_64-linux]
  - rubocop-performance 1.22.1
  - rubocop-rspec 3.1.0
```

### PR DESCRIPTION
**Pull request by dvandersluis**
With code such as:

```ruby
a, b = func(c = 3)
[a, b]
```

`Lint/UselessAssignment` was previously considering the inner assignment (`c = 3`) to be part of the multiple assignment for autocorrection. This changes it to not consider assignment inside a method argument to be part of the containing `meta_assignment_node` for `masgn` and `for` nodes. 

Fixes #13364.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/variable_force/assignment.rb [hunk 1]
```diff
@@ -119,7 +120,15 @@ def rest_assignment_node
...
-          node.ancestors.find(&:for_type?)
+          parent_node = node.parent
+          return unless parent_node
+
+          grandparent_node = parent_node.parent
+
+          return parent_node if parent_node.for_type?
+          return grandparent_node if parent_node.mlhs_type? && grandparent_node&.for_type?
+
+          nil
```
Comment (koic) [inline lib/rubocop/cop/variable_force/assignment.rb:131]: Can you tweak to the following? There is a possibility for an early return before searching for `grandparent_node`.

```suggestion
          return unless (parent_node = node.parent)
          return parent_node if parent_node.for_type?

          grandparent_node = parent_node.parent
          return grandparent_node if parent_node.mlhs_type? && grandparent_node&.for_type?

          nil
```

File: spec/rubocop/cop/variable_force/assignment_spec.rb [hunk 2]
```diff
@@ -144,6 +144,110 @@ def some_method
         expect(assignment.meta_assignment_node.type).to eq(:for)
       end
     end
+
+    context 'when it is an argument of a send node' do
+      # The `lvasgn` in question in this `context` is the one inside a call to `my_method`
+      let(:lvasgn_node) { ast.each_node.select(&:lvasgn_type?).last } # rubocop:disable Performance/Detect
```
Comment (koic) [inline spec/rubocop/cop/variable_force/assignment_spec.rb:150]:
```suggestion
      # The `lvasgn` in question in this `context` is the one inside a call to `my_method`.
      let(:lvasgn_node) { ast.each_node.to_a.reverse.find(&:lvasgn_type?) }
```

File: lib/rubocop/cop/variable_force/assignment.rb (hunk 1 above)
Comment (dvandersluis) [reply lib/rubocop/cop/variable_force/assignment.rb]: Updated.

File: spec/rubocop/cop/variable_force/assignment_spec.rb (hunk 2 above)
Comment (dvandersluis) [reply spec/rubocop/cop/variable_force/assignment_spec.rb]: Updated.

**Comment by koic** [comment]
Thanks!
