### PR TITLE
[Fix #10573] Fix a false positive for `Layout/SpaceBeforeBrackets`

### LINKED ISSUE #10573: `Layout/SpaceBeforeBrackets`: false positive for arguments forwarding to `Hash#[]`
## Expected behavior

It does not detect offense of `Layout/SpaceBeforeBrackets`.

## Actual behavior

```
$ rubocop --debug --cache false --only Layout/SpaceBeforeBrackets foo.rb
For /Users/yuji_developer/foo: configuration from /Users/yuji_developer/foo/.rubocop.yml
Default configuration from /Users/yuji_developer/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rubocop-1.28.1/config/default.yml
Inspecting 1 file
Scanning /Users/yuji_developer/foo/foo.rb
C

Offenses:

foo.rb:7:10: C: [Correctable] Layout/SpaceBeforeBrackets: Remove the space before the opening brackets.
    @hash.[](...)
         ^

1 file inspected, 1 offense detected, 1 offense auto-correctable
Finished in 0.06047500018030405 seconds
```

## Steps to reproduce the problem

Run `rubocop --only Layout/SpaceBeforeBrackets foo.rb` on the following config and code.

```yaml
# .rubocop.yml
AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
```
```ruby
# foo.rb
class Foo
  def initialize
    @hash = {}
  end

  def [](...)
    @hash.[](...)
  end
end
```

## RuboCop version

```
$ rubocop -V
1.28.1 (using Parser 3.1.2.0, rubocop-ast 1.17.0, running on ruby 2.7.6 arm64-darwin21)
```

### PR DESCRIPTION
**Pull request by nobuyo**
…when using desugared `Hash#[]` method.

Fixes #10573.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/space_before_brackets.rb [hunk 1]
```diff
@@ -37,13 +37,20 @@ def offense_range(node, begin_pos)
...
             return if receiver_end_pos >= selector_begin_pos
+            return if brackets_without_syntax_sugar?(node, receiver_end_pos, selector_begin_pos)
 
             range_between(receiver_end_pos, selector_begin_pos)
           elsif node.method?(:[]=)
             offense_range_for_assignment(node, begin_pos)
           end
         end
 
+        def brackets_without_syntax_sugar?(node, receiver_end_pos, selector_begin_pos)
```
Comment (koic) [inline lib/rubocop/cop/layout/space_before_brackets.rb:48]: Does this mean something like this?

```suggestion
        def dot_before_brackets?(node, receiver_end_pos, selector_begin_pos)
```

Comment (nobuyo) [reply lib/rubocop/cop/layout/space_before_brackets.rb:48]: Exactly, that was a littie weired naming :)

File: lib/rubocop/cop/layout/space_before_brackets.rb [hunk 2]
```diff
@@ -37,13 +37,20 @@ def offense_range(node, begin_pos)
...
             range_between(receiver_end_pos, selector_begin_pos)
           elsif node.method?(:[]=)
             offense_range_for_assignment(node, begin_pos)
           end
         end
 
+        def dot_before_brackets?(node, receiver_end_pos, selector_begin_pos)
+          return false unless node.loc.respond_to?(:dot)
+
+          node.loc.dot&.begin_pos == receiver_end_pos && node.loc.dot&.end_pos == selector_begin_pos
```
Comment (koic) [inline lib/rubocop/cop/layout/space_before_brackets.rb:51]: I'm not sure about the best, but the following can reduce method calls and eliminate safe navigation.

```suggestion
          return false unless node.loc.respond_to?(:dot) && (dot = node.loc.dot)

          dot.begin_pos == receiver_end_pos && dot.end_pos == selector_begin_pos
```

Comment (nobuyo) [reply lib/rubocop/cop/layout/space_before_brackets.rb]: Thank you, I've committed your suggestion.

**Comment by koic** [comment]
Thanks!
