### PR TITLE
[Fix #7900] Fix `Style/FormatStringToken` false positive with formatted input and `template` style enforced, and add autocorrection

### LINKED ISSUE #7900: Style/FormatStringToken false positive with formatted input and template style enforced
## Expected behavior

When enforcing the template style: 
```
Style/FormatStringToken:
  EnforcedStyle: template
```

and with the following code:
```
format('%<number>0.02f', value) }
```

Formatting input doesn't work with template style - [source](https://ruby-doc.org/core-2.7.0/Kernel.html#method-i-format)

> %<name>s style uses format style, but %{name} style doesn’t.

The cop should not report offenses or accept an new configuration option for formatted input.

I guess this is a similar issue reported in [this comment](https://github.com/rubocop-hq/rubocop/issues/5630#issuecomment-546450054)
 

## Actual behavior

It returns the offense :

```
Style/FormatStringToken: Prefer template tokens (like %{foo}) over annotated tokens (like %<foo>s).
  format('%<number>0.02f', value)
```

## Steps to reproduce the problem

See examples above

## RuboCop version

```
$ [bundle exec] rubocop -V
0.79.0
```

### PR DESCRIPTION
**Pull request by FnControlOption**
Fixes #7900.

Types of format strings:
- `annotated`: `'%<name>s'` (where `s` is the format type)
- `template`: `'%{name}'`
- `unannotated`: `'%s'`

The format string `'%{name}'` is only equivalent to `'%<name>s'`, so when enforcing the `template` style, no offenses should be reported if the format type is not `s` (for example, `'%<name>f'`).

The autocorrection from `template` style `%[flags][width][.precision]{name}` to `annotated` style is `%<name>[flags][width][.precision]s`, and vice versa.

Because `unannotated` has no names, it can't be autocorrected to `annotated` or `template`.

Autocorrecting from either `annotated` or `template` to `unannotated` is possible, but I haven't attempted adding this yet. The method arguments must be updated too, so `def on_send` would need to be added (maybe as a new cop). For example:

```rb
format('%<greeting>s', greeting: 'Hello')
format('%{foo} %{bar} %{foo}', foo: 'foo', bar: 'bar')
# becomes
format('%s', 'Hello')
format('%1$s %2$s %1$s', 'foo', 'bar')
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/format_string_token.rb [hunk 1]
```diff
@@ -105,6 +101,38 @@ def use_ignored_method?(node)
...
+        def autocorrect_sequence(corrector, detected_sequence, token_range)
+          return if style == :unannotated
+
+          name = detected_sequence.name
+          return if name.nil?
+
+          flags = detected_sequence.flags
+          width = detected_sequence.width
+          precision = detected_sequence.precision
+          type = detected_sequence.style == :template ? 's' : detected_sequence.type
```
Comment (FnControlOption) [inline lib/rubocop/cop/style/format_string_token.rb:128]: I realized that these lines can be simplified to:

```rb
return if style == :unannotated || detected_sequence.style == :unannotated

name = detected_sequence.name
flags = detected_sequence.flags
width = detected_sequence.width
precision = detected_sequence.precision
type = case detected_sequence.style
       when :annotated then detected_sequence.type
       when :template then 's'
       end
```

**Review by marcandre — APPROVED** [review]
Looks good to me 👍
