### PR TITLE
[Fix #11977] Add new global `StringLiteralsFrozenByDefault` option

### LINKED ISSUE #11977: Style/EmptyLiteral with --enable=frozen-string-literal flag
## Expected behavior

`String.new` should not be auto-corrected with `''` when have `Style/EmptyLiteral` enabled and run with the `--enable=frozen-string-literal` flag.

## Actual behavior

`String.new` will be replaced with `''`

## Steps to reproduce the problem

1. add a ruby file with a line `String.new`.
2. run `export RUBYOPT="--enable-frozen-string-literal"` in command line.
3. run auto-correct on the ruby file.
4. `String.new` will be replaced with `''`

## RuboCop version

```
$ [bundle exec] rubocop -V
1.53.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.0.0) [x86_64-linux]
  - rubocop-performance 1.15.0
  - rubocop-rails 2.16.1
```

## Possible fixes:

We can check `RUBYOPT` in `frozen_string_literals_enabled?` method.
Ex:
```rb
return true if ENV['RUBYOPT'].include?('--enable-frozen-string-literal')
```
https://github.com/rubocop/rubocop/blob/a7b7c5f95ac32612b0f9c0a9661281b5633ae07b/lib/rubocop/cop/mixin/frozen_string_literal.rb#L21-L41

### PR DESCRIPTION
**Pull request by Earlopain**
While Ruby continues to not have this the default, user can opt into it using the `RUBYOPT` environment variable. To make RuboCop behave correctly when doing that, offer a config value to say how literals behave by default.

The most egregious cop `Style/FrozenStringLiteralComment` can already be configured appropriately by setting `EnforcedStyle` to `never`. This makes if possible to also change behaviour about cops that concern themselves with string literals (primarily `MutableConstant`).

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
> While Ruby continues to not have this the default, user can opt into it using the RUBYOPT environment variable. To make RuboCop behave correctly when doing that, offer a config value to say how literals behave by default.

Alternatively we can check the env variable and remove the need for some manual configuration. But in general I'm OK with your proposal.

**Comment by Earlopain** [comment]
Draft for now, found an issue with `Style/EmptyLiteral` that needs to be addressed first.

File: lib/rubocop/cop/style/empty_literal.rb [hunk 1]
```diff
@@ -129,8 +129,10 @@ def correction(node)
         def frozen_strings?
           return true if frozen_string_literals_enabled?
 
-          frozen_string_cop_enabled = config.for_cop('Style/FrozenStringLiteral')['Enabled']
```
Comment (Earlopain) [inline lib/rubocop/cop/style/empty_literal.rb:132]: Typo since introduction, was always true for most users since `Enabled` came from the department.

File: lib/rubocop/cop/style/empty_literal.rb [hunk 2]
```diff
@@ -129,8 +129,10 @@ def correction(node)
         def frozen_strings?
```
Comment (Earlopain) [inline lib/rubocop/cop/style/empty_literal.rb:129]: This function says strings are frozen in preparation of `Style/FrozenStringLiteralComment` doing its autocorrect. Introduced in #9773. I don't love this since it now gets complicated when the default changes. The change to the function works but I feel pretty meh about it.

Why no `autocorrect_incompatible_with`? `EmptyLiteral` comes before `FrozenStringLiteralComment` alphabetically. I played around with letting cops say their autocorrect is more important than others but didn't like how that turned out.

I would rather get rid of this workaround entirely. The user runs unsafe autocorrect and should not be surprised when things break.

**Comment by Earlopain** [comment]
Is this good or do I need to change anything?

File: lib/rubocop/cop/style/empty_literal.rb (hunk 2 above)
Comment (bbatsov) [reply lib/rubocop/cop/style/empty_literal.rb:129]: No argument from me.

**Comment by bbatsov** [comment]
Looks good to me. Thanks!

**Comment by Earlopain** [comment]
Can't wait to yeet these magic comments in a few of my projects (:

Really nice that this is possible, most libraries seem well-prepared already.
