### PR TITLE
[Fix #12823] Fix uninitialized constant error

### LINKED ISSUE #12823: `bundle exec` required for running rubocop 1.63.0 and rubocop-rails
## Expected behavior

Rubocop should run successfully without `bundle exec` within a rails project. It appears this is happening since the cut of `1.63.0`, `bundle exec rubocop` is expected. If this is now expected behavior (`bundle exec` required), the docs should probably be updated.

## Actual behavior

Running `rubocop` results in a `uninitialized constant RuboCop::Lockfile::Bundler` error, while running `bundle exec rubocop` completes successfully.

<details>

<summary>Error without bundle exec</summary>

```
$ rubocop --only Rails --require rubocop-rails                             
uninitialized constant RuboCop::Lockfile::Bundler
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/lockfile.rb:66:in `rescue in parser'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/lockfile.rb:60:in `parser'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/lockfile.rb:38:in `gem_versions'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/config.rb:332:in `read_gem_versions_from_target_lockfile'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/config.rb:293:in `gem_versions_in_target'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/config.rb:309:in `read_rails_version_from_bundler_lock_file'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/config.rb:304:in `target_rails_version_from_bundler_lock_file'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/config.rb:255:in `target_rails_version'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cop/base.rb:264:in `target_rails_version'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cop/team.rb:182:in `support_target_rails_version?'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cop/team.rb:166:in `block in roundup_relevant_cops'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cop/team.rb:161:in `select'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cop/team.rb:161:in `roundup_relevant_cops'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cop/team.rb:88:in `investigate'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:348:in `block in inspect_file'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:347:in `each'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:347:in `flat_map'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:347:in `inspect_file'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:290:in `block in do_inspection_loop'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:324:in `block in iterate_until_no_changes'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:317:in `loop'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:317:in `iterate_until_no_changes'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:286:in `do_inspection_loop'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:167:in `block in file_offenses'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:192:in `file_offense_cache'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:166:in `file_offenses'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:102:in `block in warm_cache'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:627:in `call_with_index'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:597:in `process_incoming_jobs'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:577:in `block in worker'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:568:in `fork'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:568:in `worker'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:559:in `block in create_workers'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:558:in `each'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:558:in `each_with_index'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:558:in `create_workers'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:497:in `work_in_processes'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:291:in `map'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/parallel-1.24.0/lib/parallel.rb:235:in `each'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:102:in `warm_cache'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/runner.rb:75:in `run'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli.rb:118:in `run_command'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli.rb:125:in `execute_runners'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli.rb:51:in `block in run'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/lib/rubocop/cli.rb:43:in `run'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/exe/rubocop:19:in `block in <top (required)>'
/Users/taylorryan/.rvm/rubies/ruby-3.0.6/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/gems/rubocop-1.63.0/exe/rubocop:19:in `<top (required)>'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/bin/rubocop:25:in `load'
/Users/taylorryan/.rvm/gems/ruby-3.0.6/bin/rubocop:25:in `<main>'
``` 

</details>

<details>

<summary>Success with bundle exec</summary>

```
$ bundle exec rubocop --only Rails --require rubocop-rails                   
Inspecting 176 files
.....C..C.CC...C...CC..........C.CC.CCC...CCCCCC...............C..CC..............C.....C.................CC.C.....C..C.C...CC........C.........................C...C..C....C.C.

Offenses:

# TRIMMED 

176 files inspected, 68 offenses detected, 39 offenses autocorrectable
```

</details>

It seems to be related to these changes: https://github.com/rubocop/rubocop/commit/caac0022b352cefdd3101de4a4d8223f672bb1c2, where we wouldnt hit the `rescue` since we already checked for `defined?(Bundler)` on [line 37](https://github.com/rubocop/rubocop/commit/caac0022b352cefdd3101de4a4d8223f672bb1c2#diff-ea315f91121985f09990cfdec25432799284584bcf6778086f4dae8f2a0176eaL37)

## Steps to reproduce the problem

1. Create new rails project, add rubocop 1.63.0 and latest rubocop-rails to Gemfile
2. `rubocop --only Rails --require rubocop-rails` will fail to run
3. `bundle exec rubocop --only Rails --require rubocop-rails` will succeed

## RuboCop version

```
$ rubocop -V 
1.63.0 (using Parser 3.3.0.5, rubocop-ast 1.31.2, running on ruby 3.0.6) [arm64-darwin22]
```

### PR DESCRIPTION
**Pull request by amomchilov**
Fixes #12823

The bug originates from #12186, which changed the `defined?` check in a way that didn't cover this broken reference to `Bundler` on line 66:

https://github.com/rubocop/rubocop/blob/a4447ea10744d65b8ea781ec5fbe591c1b514e92/lib/rubocop/lockfile.rb#L59-L68

This wasn't caught in CI, because none of the cops used by Rubocop (to check its own source code in CI) use Rails cops, so `RuboCop::Config#target_rails_version_from_bundler_lock_file` was never called in CI.

# Validation

An easy way to reproduce this is to just modify a gem used by Rubocop itself (e.g. `RuboCop::Cop::Layout::IndentationStyle`), adding `requires_gem 'rubocop'` to its body. This triggers the `target_rails_version_from_bundler_lock_file` code path when you run `exe/rubycop .` to run rubocop on its own codebase.

<details><summary><code>code_to_reproduce.patch</code></summary>

```diff
diff --git a/lib/rubocop/cop/layout/indentation_style.rb b/lib/rubocop/cop/layout/indentation_style.rb
index e2b936f73..5e4a152b7 100644
--- a/lib/rubocop/cop/layout/indentation_style.rb
+++ b/lib/rubocop/cop/layout/indentation_style.rb
@@ -37,6 +37,8 @@ module RuboCop
         include RangeHelp
         extend AutoCorrector

+        requires_gem 'rubocop'
+
         MSG = '%<type>s detected in indentation.'

         def on_new_investigation
```

</details>

It fails on `1.63.0`, and passes with this PR's changes.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] ~Added tests.~
     * I don't think we have an easy way to test this, since CI will always have `Bundler` defined, given that it returns tests in the bundle, that's the whole point).
     
         There's probably some way to test it by spawning a fresh process, but I'm not smart enough to figure that out quickly enough to get this bugfix out :)
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/lockfile.rb [hunk 1]
```diff
@@ -1,5 +1,11 @@
 # frozen_string_literal: true
 
+begin
+  require 'bundler'
+rescue LoadError
+  nil
+end
+
```
Comment (amomchilov) [inline lib/rubocop/lockfile.rb:8]: This should have been here all along, but feel free to pull it out of this PR, if you want to keep it super-focused on just fixing the exact bug that's reported by #12823

I put this as a second commit, so feel free to `drop` it if you'd like.

**Review by amomchilov — COMMENTED** [review]
Apologies for the bug, but here's the fix :)

@koic @bbatsov

**Comment by bbatsov** [comment]
The proposed fix looks good to me. Thanks!

File: lib/rubocop/lockfile.rb (hunk 1 above)
Comment (graaff) [reply lib/rubocop/lockfile.rb:8]: This does not look right. The question with your checks in the other commit in this PR is not "is bundler available on the system at all" which this require does, but "is this project using bundler". By forcefully loading bundler here, you are also introducing it in cases where bundler is not used (e.g. in a simple ruby script file). Consequently, rubocop now fails because it cannot find a Gemfile.

Comment (bbatsov) [reply lib/rubocop/lockfile.rb:8]: > Consequently, rubocop now fails because it cannot find a Gemfile.

Can you elaborate on that? I don't think that using bundler as a library imposes the requirement for a `Gemfile` to be present.

Comment (graaff) [reply lib/rubocop/lockfile.rb:8]: I saw failures related to it and effectively the `defined?(Bundler)` check later is now always true given that normally it should always be possible to require bundler. I'll try to create a proper test case to verify and will open a separate issue for it if I can reproduce it properly.

Comment (koic) [reply lib/rubocop/lockfile.rb:8]: This issue is expected to be resolved in #12847, which aims to solve #12846.

**Comment by bbatsov** [comment]
https://github.com/rubocop/rubocop/releases/tag/v1.63.2 is out
