### PR TITLE
[Fix #13257] Don't consider cops to be opted in for department enables

### LINKED ISSUE #13257: Department disable comments enables a cop for the rest a file even if it is excluded with `Include`/`Exclude`
## Description

When disabling an entire department for some lines, a cop that would normally not run on that file because of `Include` restrictions. See https://github.com/rubocop/rubocop-rails/issues/1365 for the original report. cc @pdobb

## Steps to reproduce the problem
```yaml
# .rubocop.yml
AllCops:
  DisabledByDefault: true

Style/HashSyntax:
  Enabled: true
  Include:
    - foo.rb
# Alternatively:
#  Exclude:
#    - bar.rb
```

```rb
# bar.rb
{ :a => :b }

# rubocop:disable Style
{ :a => :b }
# rubocop:enable Style
```

I expect no offenses here since that cop is not supposed to run on this file:

```
$ bundle exec rubocop
Inspecting 2 files
.C

Offenses:

bar.rb:1:3: C: [Correctable] Style/HashSyntax: Use the new Ruby 1.9 hash syntax.
{ :a => :b }
  ^^^^^

2 files inspected, 1 offense detected, 1 offense autocorrectable
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, running on ruby 3.4.0) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by Earlopain**
Fix #13257

When a whole department is enabled, then that cop would also run for code outside of that block, even if it is explicitly excluded via cop config.
This comes from https://github.com/rubocop/rubocop/pull/11603 were cops didn't run when explicitly enabled via `Department/Cop` but that logic should only apply when the cop is fully qualified.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/directive_comment.rb [hunk 1]
```diff
@@ -88,10 +88,15 @@ def cop_names
       @cop_names ||= all_cops? ? all_cop_names : parsed_cop_names
     end
 
+    # Returns an array of cops for this directive comment, without resolving departments
+    def raw_cop_names
```
Comment (bbatsov) [inline lib/rubocop/directive_comment.rb:92]: I guessing this should stay private.

Comment (Earlopain) [reply lib/rubocop/directive_comment.rb:92]: No, it needs to be accessed by the comment config. I've added a test, but it would also be fine to mark it `@api private` if you prefer.

Comment (bbatsov) [reply lib/rubocop/directive_comment.rb:92]: Ah, yeah - just notice that usage in the file above. I'm not sure about the name, but it's not a big deal. We can consider it public API.
