### PR TITLE
[Fix #10280] Add `AllowComments` option to `Style/SymbolProc`

### LINKED ISSUE #10280: Style/SymbolProc ignores comments
Style/SymbolProc ignores comments when linting, and destroys them when it auto-corrects.

--------

## Expected behavior

In the following code, I expect:
* no reported offense from Style/SymbolProc, because the block doesn't only call `x`, it also contains a comment.
* no auto-correction from Style/SymbolProc, because the block doesn't only call `x`, it also contains a comment.
```
hello do |r|
  # IMPORTANT MESSAGE
  r.x
end
```

## Actual behavior

It shows reports an offense, and auto-correct destroys the comment!

```
hello(&:x)
```

I mean, I know the cop is unsafe, but that may be a bit too unsafe? 😆 

## Steps to reproduce the problem

Paste the first snipped in a file, and run `rubocop -A` on it.

## RuboCop version

Happens in 
0.79.0 (using Parser 3.0.2.0, running on ruby 2.6.6 x86_64-linux)
and 
1.23.0 (using Parser 3.0.2.0, rubocop-ast 1.13.0, running on ruby 2.6.6 x86_64-linux)

### PR DESCRIPTION
**Pull request by ydah**
Resolve: https://github.com/rubocop/rubocop/issues/10280

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/symbol_proc.rb [hunk 1]
```diff
@@ -42,6 +42,13 @@ module Style
       #   # good
       #   something.map(&:upcase)
       #
+      #   # good  - if there are comment in either position
```
Comment (koic) [inline lib/rubocop/cop/style/symbol_proc.rb:45]: Maybe this is a corner case and it would be better to provide `AllowComments: false (default)` option. if `AllowComments: false`, it will not be auto-corrected. And it would be user-friendly to mention it in the document.

Comment (ydah) [reply lib/rubocop/cop/style/symbol_proc.rb]: @koic It's certainly better that way. Thank you so much.
I've made the correction, could you please review again?

File: lib/rubocop/cop/style/symbol_proc.rb [hunk 2]
```diff
@@ -100,6 +119,11 @@ def destructuring_block_argument?(argument_node)
 
         private
 
+        def contains_comment?(node)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/symbol_proc.rb:122]: Why don't you use the `CommentsHelp` module instead? I think it provides exactly the same method there.

**Comment by bbatsov** [comment]
The proposed changes look good to me, apart from the note about reusing `CommentsHelp` to remove some code duplication.

File: lib/rubocop/cop/style/symbol_proc.rb (hunk 2 above)
Comment (ydah) [reply lib/rubocop/cop/style/symbol_proc.rb]: I'd missed it. Thank you so much.

**Comment by ydah** [comment]
@bbatsov Thank you so much. I updated this PR.

**Comment by bbatsov** [comment]
Thanks!
