### PR TITLE
[Fix #12068] Fix a false positive for `Style/ReturnNilInPredicateMethodDefinition`

### LINKED ISSUE #12068: Style/ReturnNilInPredicateMethodDefinition is firing incorrectly
## Expected behavior

`Style/ReturnNilInPredicateMethodDefinition` should only fire when a predicate method returns `nil`.

## Actual behavior

Offences are reported for code that uses `nil` but does not return it:

```
Offenses:

app/models/oauth_token.rb:51:23: C: [Correctable] Style/ReturnNilInPredicateMethodDefinition: Return false instead of nil in predicate methods.
    invalidated_at != nil
                      ^^^
lib/bounding_box.rb:92:19: C: [Correctable] Style/ReturnNilInPredicateMethodDefinition: Return false instead of nil in predicate methods.
    to_a.exclude?(nil)
                  ^^^

2 files inspected, 2 offenses detected, 2 offenses autocorrectable
Finished in 0.807309715077281 seconds
```

## Steps to reproduce the problem

Run rubocop on these methods:

```ruby
def invalidated?
  invalidated_at != nil
end

def complete?
  to_a.exclude?(nil)
end
```

## RuboCop version

```
1.55.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [x86_64-linux]
  - rubocop-capybara 2.18.0
  - rubocop-factory_bot 2.23.1
  - rubocop-minitest 0.31.0
  - rubocop-performance 1.18.0
  - rubocop-rails 2.20.2
  - rubocop-rake 0.6.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12068.

This PR fixes a false positive for `Style/ReturnNilInPredicateMethodDefinition` when the last method argument in method definition is `nil`.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by mobilutz** [comment]
@koic Do you know, when this will be merged?

**Comment by bbatsov** [comment]
@mobilutz All in good time. 😉

File: spec/rubocop/cop/style/return_nil_in_predicate_method_definition_spec.rb [hunk 1]
```diff
@@ -59,12 +59,17 @@ def foo?
       RUBY
     end
 
-    it 'does not register an offense when using `return false`' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/return_nil_in_predicate_method_definition_spec.rb:62]: Why did you remove this test case?

File: spec/rubocop/cop/style/return_nil_in_predicate_method_definition_spec.rb [hunk 2]
```diff
@@ -101,6 +106,40 @@ def foo?
...
+
+    it 'does not register an offense when assigning `nil` to a variable in predicate method definition' do
+      expect_no_offenses(<<~RUBY)
+        def foo?
+          bar = nil
+        end
+      RUBY
+    end
+
+    it 'does not register an offense when using `return false`' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/return_nil_in_predicate_method_definition_spec.rb:133]: Ah, seems it was moved.

File: lib/rubocop/cop/style/return_nil_in_predicate_method_definition.rb [hunk 3]
```diff
@@ -77,6 +77,8 @@ def on_def(node)
         private
 
         def nil_node_at_the_end_of_method_body(body)
+          return if !body.begin_type? && !body.nil_type?
```
Comment (bbatsov) [inline lib/rubocop/cop/style/return_nil_in_predicate_method_definition.rb:80]: It seems to me the logic in this method became a bit too convoluted. I wonder if there isn't a simpler way to get the final node of method that doesn't use `body.children.last` and would not require to the additional checks. I'm guessing you can also just check that the parent of the last `nil` is either `begin` or `def`.

Comment (koic) [reply lib/rubocop/cop/style/return_nil_in_predicate_method_definition.rb]: I haven't come up with a good logic yet 💦, but for now, I've simplified the conditions a bit.

Comment (bbatsov) [reply lib/rubocop/cop/style/return_nil_in_predicate_method_definition.rb]: Yeah, it reads better this way. I guess it will do for now.
