### PR TITLE
[Fix #10962] Fix a false positive for `Lint/ShadowingOuterLocalVariable` when conditional with if/elsif/else branches

### LINKED ISSUE #10962: Lint/ShadowingOuterLocalVariable: a false positive case with if/eslif/else statement and block variable
## Expected behavior

No offense with Lint/ShadowingOuterLocalVariable cop 

## Actual behavior

```
 W: Lint/ShadowingOuterLocalVariable: Shadowing outer local variable - item.
    items.each { |item| frobnicate(item) }
                  ^^^^
```

## Steps to reproduce the problem

```
def do_something(items, what)
  if what == :first
    item = items[0]
    frobnicate(item)
  elsif what == :second
    item = items[1]
    frobnicate(item)
  else
    items.each { |item| frobnicate(item) }
  end
end

rubocop --only Lint/ShadowingOuterLocalVariable
```

Removing the `elsif` does not cause the warning to be emitted (see #10479)

## RuboCop version

```
%% rubocop -V
1.35.1 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.1.2 x86_64-darwin21)
```

### PR DESCRIPTION
**Pull request by ydah**
Fix: #10962

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/shadowing_outer_local_variable.rb [hunk 1]
```diff
@@ -64,14 +64,24 @@ def before_declaring_variable(variable, variable_table)
...
+            (variable_node == outer_local_variable_node ||
+              variable_node == outer_local_variable_node.else_branch)
+        end
+
+        def variable_node(variable)
+          if variable.scope.node.parent.when_type?
+            variable.scope.node.parent.parent
+          else
+            variable.scope.node.parent
+          end
```
Comment (koic) [inline lib/rubocop/cop/lint/shadowing_outer_local_variable.rb:84]:
```suggestion
          parent_node = variable.scope.node.parent
          
          if parent_node.when_type?
            parent_node.parent
          else
            parent_node
          end
```

**Comment by ydah** [comment]
I updated this PR. Thank you so much!
