### PR TITLE
[Fix #10657] Fix `AutoGenerateConfig` command ignores specified config file by option

### LINKED ISSUE #10657: Supplied config file not used when .rubocop.yml exists when regenerating TODO
I'm not sure if this is a known issue or not, but I didn't see anything in the docs about it.

We're working to add RuboCop to a mature codebase, and have developed a strategy that'll allow us to slowly introduce new cops. We essentially maintain two configs:
- `.rubocop.yml` — Disables all cops by default, and just enables ones we've explicitly allowed after evaluating them, configuring as necessary, and fixing offenses. 
- `.rubocop_wip.yml` — The "typical" `.rubocop.yml` setup. Enables all default cops, and layers on our own configuration. Includes `.rubocop_todo.yml`. 

The idea here is that we can run `rubocop` with `.rubocop.yml` and it'll run against cops we've evaluated/configured. That allows us to correct offenses for those cops on an ongoing basis.

For new code, after fixing those offenses, we'd like to run `rubocop --config .rubocop_wip.yml --regenerate-todo` to refresh the TODO file with all new offenses for cops we _haven't_ evaluated yet (since the offenses for those which we have evaluated would have been fixed above). 

However, that doesn't seem to work. It looks like `rubocop` ignores the `--config` flag and generates the `.rubocop_todo.yml` based off `.rubocop.yml`, so long as that file exists. 

Demo with reproduction steps: https://github.com/jimryan/rubocop-custom-config-regenerate-todo-demo

--------

## Expected behavior

Supplied config file is used to generate the TODO.

## Actual behavior

rubocop uses `.rubocop.yml` despite being explicitly passed a config file via `--config`

## Steps to reproduce the problem

https://github.com/jimryan/rubocop-custom-config-regenerate-todo-demo

## RuboCop version

```
$ [bundle exec] rubocop -V
1.29.1 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 2.7.6 arm64-darwin21)
```

### PR DESCRIPTION
**Pull request by nobuyo**
Fixes #10657.

This PR fixes a bug that caused config files specified by `--config` options to be unintentionally ignored in `AutoGenerateConfig` command.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cli/auto_gen_config_spec.rb [hunk 1]
```diff
@@ -430,6 +430,50 @@ def f
...
+        create_file('example1.rb', ['def foo', '  # bar', '  end'])
+        create_file('.rubocop.yml', <<~YAML)
+          AllCops:
+            DisabledByDefault: true
+
+          Layout/DefEndAlignment:
+            Enabled: true
+        YAML
+        create_file('cop_config.yml', <<~YAML)
+        YAML
```
Comment (koic) [inline spec/rubocop/cli/auto_gen_config_spec.rb:444]: Can you use `create_empty_file` instead?

```suggestion
        create_empty_file('cop_config.yml')
```

Comment (nobuyo) [reply spec/rubocop/cli/auto_gen_config_spec.rb]: Thank you, I've committed and squashed it.

File: changelog/fix_autogenerateconfig_command_ignores_config.md [hunk 2]
```diff
@@ -0,0 +1 @@
+* [#10657](https://github.com/rubocop/rubocop/issues/10657): Fix `AutoGenerateConfig` command ignores specified config file by option. ([@nobuyo][])
```
Comment (koic) [inline changelog/fix_autogenerateconfig_command_ignores_config.md:1]: Perhaps user knows command line option name, not internal class name, right?

```suggestion
* [#10657](https://github.com/rubocop/rubocop/issues/10657): Fix `--auto-gen-config` command option ignores specified config file by option. ([@nobuyo][])
```

Comment (nobuyo) [reply changelog/fix_autogenerateconfig_command_ignores_config.md]: Yeah, you're right. I've updated branch.

**Comment by koic** [comment]
Thanks!
