### PR TITLE
[Fix #12271] Fix a false positive for `Lint/RedundantSafeNavigation`

### LINKED ISSUE #12271: RedundantSafeNavigation does not consider constants may be nil.
## Expected behavior

```
FOO = nil

self::FOO&.dig(...)
      ^^^^^
[Correctable] Lint/RedundantSafeNavigation: Redundant safe navigation detected.
```

## Actual behavior

I don't believe we should flag constants as not needing safe navigation.

## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

## RuboCop version

```
1.57.0 (using Parser 3.2.2.4, rubocop-ast 1.29.0, running on ruby 3.2.2) [x86_64-linux]
  - rubocop-rspec 2.24.1

```

## Potential Fix

Consider deleting this line? https://github.com/rubocop/rubocop/blob/128618c7a8e3336bbe9ff8f800a73ff04dfc7a81/lib/rubocop/cop/lint/redundant_safe_navigation.rb#L76

### PR DESCRIPTION
**Pull request by koic**
Fixes #12271.

This PR fixes a false positive for `Lint/RedundantSafeNavigation` when using snake case constant receiver.

Camel case is used for naming classes and modules, while snake case is used for all other constants. This naming conforms with `Naming/ConstantName` cop.

Since constants that turn into classes or modules are normally not `nil`, they will continue to be detected.
However, this PR will update to allow safe navigation for constants in snake case.

This change resolves both issue https://github.com/rubocop/rubocop-rails/issues/1104 and #12271.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/redundant_safe_navigation.rb [hunk 1]
```diff
@@ -4,8 +4,8 @@ module RuboCop
   module Cop
     module Lint
       # Checks for redundant safe navigation calls.
-      # Use cases where a constant is `nil` are rare and an offense is detected
-      # when the receiver is a constant.
+      # Use cases where a constant, named in camel case for classes and modules is `nil` are rare,
+      # and an offense is detected when the receiver is a snake case constant.
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/redundant_safe_navigation.rb:8]: I think you meant to write "is not detected" here.

Comment (bbatsov) [reply lib/rubocop/cop/lint/redundant_safe_navigation.rb:8]: Ah, you mean to target just `SCREAMING_SNAKE_CASE`. I see.

**Comment by bbatsov** [comment]
Frankly, I'm not sure what's the best course of action here, as I don't understand why anyone would have a `nil` constant regardless of whether it's a class/module reference or not.

**Comment by bbatsov** [comment]
P.S. Probably we need some cop about assigning `nil` to constants, as it makes very little sense to me.

File: lib/rubocop/cop/lint/redundant_safe_navigation.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/cop/lint/redundant_safe_navigation.rb]: Oops! I've updated the text.

**Comment by koic** [comment]
> P.S. Probably we need some cop about assigning `nil` to constants, as it makes very little sense to me. 

Hm, naming for magic literal, like magic number? 🤔 While I also don't have the use case for assigning `nil` to a constant, So I agree that it's worth considering.

File: spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb [hunk 2]
```diff
@@ -14,6 +14,12 @@
     RUBY
   end
 
+  it 'does not register an offense and corrects when `&.` is used for snake case const receiver' do
+    expect_no_offenses(<<~RUBY)
+      FOO&.do_something
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb:19]: Btw, I guess there's a small change that a class name will be one word, all caps - e.g. `URL`, `URI`, etc. I guess we can leave it as is, but are test cases for `CONST_NAME` and `Const_name`, so it's clearer what we are testing for exactly.

Comment (koic) [reply spec/rubocop/cop/lint/redundant_safe_navigation_spec.rb]: Sure! I've updated the test cases.

**Comment by bbatsov** [comment]
Thanks!
