### PR TITLE
[Fix #9762] Update `VariableForce` to be able to handle `case-match` nodes

### LINKED ISSUE #9762: Lint/UselessAssignment: bad behavior with pattern matching
## Expected behavior

In the following example, `res` is obviously needed:

```ruby
def f
  case '0'
  in String
    res = 1
  else
    res = 2
  end
  res
end

puts f
```

so Lint/UselessAssignment should not claim it is useless.

## Actual behavior

```
Offenses:

patmatch.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
def f
^
patmatch.rb:4:5: W: Lint/UselessAssignment: Useless assignment to variable - res.
    res = 1
    ^^^

1 file inspected, 2 offenses detected, 1 offense auto-correctable
```

Please use `rubocop --debug` when pasting rubocop output as it contains additional information.

```
For /private/tmp/foo: configuration from /private/tmp/foo/.rubocop.yml
Inheriting configuration from /private/tmp/foo/.rubocop_todo.yml
Default configuration from /opt/local/lib/ruby3.0/gems/3.0.0/gems/rubocop-1.13.0/config/default.yml
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.

Please also note that can also opt-in to new cops by default by adding this to your config:
  AllCops:
    NewCops: enable

Gemspec/DateAssignment: # (new in 1.10)
  Enabled: true
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/SymbolConversion: # (new in 1.9)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/TripleQuotes: # (new in 1.9)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashConversion: # (new in 1.10)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/StringChars: # (new in 1.12)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
For more information: https://docs.rubocop.org/rubocop/versioning.html
Inspecting 1 file
Scanning /private/tmp/foo/patmatch.rb
W

Offenses:

patmatch.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
def f
^
patmatch.rb:4:5: W: Lint/UselessAssignment: Useless assignment to variable - res.
    res = 1
    ^^^

1 file inspected, 2 offenses detected, 1 offense auto-correctable
Finished in 0.1654020000132732 seconds
```

## Steps to reproduce the problem

See above.

## RuboCop version

```
$ rubocop -V
1.13.0 (using Parser 3.0.1.0, rubocop-ast 1.4.1, running on ruby 3.0.1 x86_64-darwin18)
```

## Greetings

Thanks for rubocop!

### PR DESCRIPTION
**Pull request by dvandersluis**
`VariableForce::Branch` was not aware of `case-match` nodes and thus did not properly mark all assignments in the following code as used, which caused rubocop to register a false positive `Lint/UselessAssignment`.

 ```ruby
def f
  case '0'
  in String
    res = 1 # would not be registered, causing an offense
  else
    res = 2 # would be registered
  end
  res
end
```

Fixes #9762.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/variable_force/branch.rb [hunk 1]
```diff
@@ -226,6 +226,21 @@ def always_run?
           end
         end
 
+        # case target
+        # in clause # in_clause
```
Comment (koic) [inline lib/rubocop/cop/variable_force/branch.rb:230]: How about the name `in_pattern`?

```suggestion
        # in patter # in_pattern
```

c.f.:

```ruby
% ruby-parse -e 'case foo; in bar; end'
(case-match
  (send nil :foo)
  (in-pattern
    (match-var :bar) nil nil) nil)
```

File: lib/rubocop/cop/variable_force/branch.rb [hunk 2]
```diff
@@ -226,6 +226,21 @@ def always_run?
...
+        # else
+        #   else_body
+        # end
+        class CaseMatch < Base
+          define_predicate :target?,      child_index: 0
+          define_predicate :in_clause?,   child_index: 1..-2
+          define_predicate :else_body?,   child_index: -1
```
Comment (koic) [inline lib/rubocop/cop/variable_force/branch.rb:237]: The alignment space seems to be redundant.

```suggestion
          define_predicate :target?,     child_index: 0
          define_predicate :in_pattern?, child_index: 1..-2
          define_predicate :else_body?,  child_index: -1
```

File: spec/rubocop/cop/lint/useless_assignment_spec.rb [hunk 3]
```diff
@@ -1416,4 +1416,19 @@ def some_method(environment)
       end
     end
   end
+
+  context 'inside a `case-match` node', :ruby30 do
+    it 'does not register an offense when the variable is used' do
```
Comment (koic) [inline spec/rubocop/cop/lint/useless_assignment_spec.rb:1421]: It would be better to add a phrase about pattern matching syntax.

File: spec/rubocop/cop/lint/useless_assignment_spec.rb [hunk 4]
```diff
@@ -1416,4 +1416,19 @@ def some_method(environment)
       end
     end
   end
+
+  context 'inside a `case-match` node', :ruby30 do
```
Comment (koic) [inline spec/rubocop/cop/lint/useless_assignment_spec.rb:1420]:
```suggestion
  context 'inside a `case-match` node', :ruby27 do
```

File: spec/rubocop/cop/lint/useless_assignment_spec.rb (hunk 3 above)
Comment (koic) [reply spec/rubocop/cop/lint/useless_assignment_spec.rb:1421]: Ah, it is enough because it is explained in context 💦

File: lib/rubocop/cop/variable_force/branch.rb (hunk 1 above)
Comment (dvandersluis) [reply lib/rubocop/cop/variable_force/branch.rb:230]: Sounds good!

**Comment by dvandersluis** [comment]
Applied your suggestions, thanks @koic!

**Comment by koic** [comment]
Great! Thank you @dvandersluis!
