### PR TITLE
[Fix #10465] Fix false positive for `Naming/BlockForwarding` when the block argument is redefined

### LINKED ISSUE #10465: False positives for `Naming/BlockForwarding` where the block has a fallback
The `Naming/BlockForwarding` cop is returning offenses for methods where the named block variable has a fallback defined via `||=`. Autofixing this changes the methods behavior. 

```ruby
def example(&block)
  block ||= -> { 'something' }
  [].map(&block)
end
```

--------

## Expected behavior

No offenses detected.

## Actual behavior

```
$ rubocop --debug 
For /Users/benedikt/Workspace/Ruby/rubocop-example: configuration from /Users/benedikt/Workspace/Ruby/rubocop-example/.rubocop.yml
Default configuration from /Users/benedikt/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.26.1/config/default.yml
Use parallel by default.
Running parallel inspection
Loading cache from /Users/benedikt/.cache/rubocop_cache/c214916517681acc71076fdbd8cd5e24c8caa2a6/6d7a3b621ca1730e04accd938619e4bdab66cfb1/8b686c07dc716bd5a417d5214ae1fd0143f01685
Inspecting 1 file
Scanning /Users/benedikt/Workspace/Ruby/rubocop-example/example.rb
Loading cache from /Users/benedikt/.cache/rubocop_cache/c214916517681acc71076fdbd8cd5e24c8caa2a6/6d7a3b621ca1730e04accd938619e4bdab66cfb1/8b686c07dc716bd5a417d5214ae1fd0143f01685
C

Offenses:

example.rb:3:13: C: [Correctable] Naming/BlockForwarding: Use anonymous block forwarding.
def example(&block)
            ^^^^^^
example.rb:5:10: C: [Correctable] Naming/BlockForwarding: Use anonymous block forwarding.
  [].map(&block)
         ^^^^^^

1 file inspected, 2 offenses detected, 2 offenses auto-correctable
Finished in 0.15310699999099597 seconds
```

## Steps to reproduce the problem

This only happens on Ruby 3.1, and I'm using this basic `.rubocop.yml`: 

```yaml
AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
```

Here's a minimal `example.rb` file that shows the problem:

```ruby
# frozen_string_literal: true

def example(&block)
  block ||= -> { 'something' }
  [].map(&block)
end
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ rubocop -V
1.26.1 (using Parser 3.1.1.0, rubocop-ast 1.16.0, running on ruby 3.1.1 x86_64-darwin21)
```

### PR DESCRIPTION
**Pull request by dvandersluis**
If the block argument is used in an assignment, it has to be explicitly named.

Fixes #10465.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/naming/block_forwarding.rb [hunk 1]
```diff
@@ -47,11 +47,17 @@ class BlockForwarding < Base
 
         MSG = 'Use %<style>s block forwarding.'
 
+        # @!method block_assignment?(node, var_name)
+        def_node_search :block_assignment?, <<~PATTERN
+          (lvasgn %1)
+        PATTERN
```
Comment (koic) [inline lib/rubocop/cop/naming/block_forwarding.rb:53]: Perhaps the following change to the production code on L110 instead of this matcher will cover the issue. 
How about this suggestion?

```diff
- node.body.each_descendant(:lvar).any? do |lvar|
+ node.body.each_descendant(:lvar, :lvasgn).any? do |lvar|
```

File: spec/rubocop/cop/naming/block_forwarding_spec.rb [hunk 2]
```diff
@@ -189,6 +189,15 @@ def foo
           end
         RUBY
       end
+
+      it 'does not register an offense when redefining the block arg' do
```
Comment (koic) [inline spec/rubocop/cop/naming/block_forwarding_spec.rb:193]: Perhaps `assigning` looks reasonable :-)

```suggestion
      it 'does not register an offense when assigning the block arg' do
```

**Comment by dvandersluis** [comment]
Thanks @koic, I made the changes you requested.

File: changelog/fix_fix_false_positive_for.md [hunk 3]
```diff
@@ -0,0 +1 @@
+* [#10465](https://github.com/rubocop/rubocop/issues/10465): Fix false positive for `Naming/BlockForwarding` when the block argument is redefined. ([@dvandersluis][])
```
Comment (koic) [inline changelog/fix_fix_false_positive_for.md:1]: How about updating the changelog entry?

```suggestion
* [#10465](https://github.com/rubocop/rubocop/issues/10465): Fix false positive for `Naming/BlockForwarding` when the block argument is assigned. ([@dvandersluis][])
```

Comment (dvandersluis) [reply changelog/fix_fix_false_positive_for.md]: Sure, updated.

**Comment by koic** [comment]
Thanks!

**Comment by benedikt** [comment]
Thanks for the quick fix! :)
