### PR TITLE
[Fix #12614] Fix false positiveis for `Style/RedundantParentheses`

### LINKED ISSUE #12614: Incorrect autocorrection for `Style/RedundantParentheses`
## Expected behavior

```ruby
x do
  next foo && bar
end
```

## Actual behavior

```ruby
x do
  next
    foo && bar # <--- W: Lint/UnreachableCode: Unreachable code detected.
end
```

## Steps to reproduce the problem

```ruby
x do
  next (
    foo && bar
  )
end
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.60.0 (using Parser 3.3.0.3, rubocop-ast 1.30.0, running on ruby 3.1.2) [x86_64-darwin21]
  - rubocop-performance 1.20.2
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.26.1
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12614.

This PR fixes false positiveis for `Style/RedundantParentheses` when parentheses in control flow keyword with multiline style argument.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
You're missing a `#` in the commit message header.

File: spec/rubocop/cop/style/redundant_parentheses_spec.rb [hunk 1]
```diff
@@ -793,6 +793,51 @@ def foo
...
 
+  it 'accepts parentheses in `return` with multiline style argument' do
+    expect_no_offenses(<<~RUBY)
+      return (
+        42
+      )
+    RUBY
+  end
+
+  it 'registers an offense when parentheses in `return` with single style argument' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/redundant_parentheses_spec.rb:804]: Should we also have a test for `(return 42)`?

Comment (koic) [reply spec/rubocop/cop/style/redundant_parentheses_spec.rb:804]: It seems to be a false negative, and it seems like `(x 42)` is also worked in the same. I'd like to address these false negatives collectively in a separate PR.

Comment (bbatsov) [reply spec/rubocop/cop/style/redundant_parentheses_spec.rb:804]: Fine by me.
