### PR TITLE
[Fix #12168]: Fix bug in `Style/ArgumentsForwarding`

### LINKED ISSUE #12168: Bug in `Style/ArgumentsForwarding`: only last occurrence of repeated method call is autocorrected
Extracted from https://github.com/rubocop/rubocop/issues/12144#issuecomment-1695879179

With the following code, RuboCop only marks the second send as an offense, which leads to the auto-corrected code having an undefined lvar:
```ruby
def foo(bar, *args)
  baz(*args)

  if something?
    baz(*args)
  end
end
```

```
Inspecting 1 file
C

Offenses:

example.rb:1:14: C: [Corrected] Style/ArgumentsForwarding: Use anonymous positional arguments forwarding (*).
def foo(bar, *args)
             ^^^^^
example.rb:5:9: C: [Corrected] Style/ArgumentsForwarding: Use anonymous positional arguments forwarding (*).
    baz(*args)
        ^^^^^

1 file inspected, 2 offenses detected, 2 offenses corrected
```

Auto-corrected code:

```ruby
def foo(bar, *)
  baz(*args)

  if something?
    baz(*)
  end
end
```

--------

## Expected behavior

There should be an additional offense at the send on line 2 and the auto-corrected file should contain:
```ruby
def foo(bar, *)
  baz(*)

  if something?
    baz(*)
  end
end
```

## Actual behavior

The auto-corrected file contains:
```ruby
def foo(bar, *)
  baz(*args) # Bug here: `args` is no longer defined

  if something?
    baz(*)
  end
end
```

## Steps to reproduce the problem

Use the example given above.

## RuboCop version

```
$ bundle exec rubocop -V
1.56.2 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [arm64-darwin22]
  - rubocop-performance 1.19.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.23.0
```

### PR DESCRIPTION
**Pull request by owst**
We were using nodes as Hash keys, which is not supported - the metadata (source location) is not used to distinguish nodes. Thus the two occurrences of the same send (method name and args) were collapsed into one, causing only one of two offense sites to be reported.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/arguments_forwarding.rb [hunk 1]
```diff
@@ -116,7 +116,7 @@ def extract_forwardable_args(args)
         end
 
         def only_forwards_all?(send_classifications)
-          send_classifications.each_value.all? { |c, _, _| c == :all }
+          send_classifications.each.all? { |_, (c, _, _)| c == :all }
```
Comment (koic) [inline lib/rubocop/cop/style/arguments_forwarding.rb:119]: It seems possible to simplify the block arguments.

```suggestion
          send_classifications.to_h.each_values.all? { |c, _, _| c == :all }
```

Comment (owst) [reply lib/rubocop/cop/style/arguments_forwarding.rb]: I ended up with a slightly different simplification - I realised I don't need the nested array structure, so can remove the array destructuring in all of the `send_classifications` iteration block args

**Comment by koic** [comment]
Looks good to me. Can you squash your commits into one?

File: changelog/fix_fix_12168_fix_bug_in_style_arguments_forwarding.md [hunk 2]
```diff
@@ -0,0 +1 @@
+* [#12168](https://github.com/rubocop/rubocop/pull/12168): Fix bug in `Style/ArgumentsForwarding` when there are repeated send nodes. ([@owst][])
```
Comment (koic) [inline changelog/fix_fix_12168_fix_bug_in_style_arguments_forwarding.md:1]:
```suggestion
* [#12168](https://github.com/rubocop/rubocop/issues/12168): Fix bug in `Style/ArgumentsForwarding` when there are repeated send nodes. ([@owst][])
```

**Comment by koic** [comment]
Thanks!
