### PR TITLE
[Fix #13866] Tweak the offense message of `Style/RedundantFormat`

### LINKED ISSUE #13866: Style/RedundantFormat offense with width specifiers
Style/RedundantFormat considers a format string with width specifiers to be an offense.
--------

## Expected behavior

Don't mark as an offense

## Actual behavior

Is marked as an offense

## Steps to reproduce the problem

```ruby
format('%10s', 'beepboop')
```

causes "Style/RedundantFormat: Redundant format can be removed"

## RuboCop version

```
1.72.0 (using Parser 3.3.7.1, rubocop-ast 1.38.0, analyzing as Ruby 3.4, running on ruby 3.4.1) [arm64-darwin24]
  - rubocop-capybara 2.21.0
  - rubocop-factory_bot 2.26.1
  - rubocop-rails 2.29.1
  - rubocop-rspec 3.4.0
  - rubocop-rspec_rails 2.30.0
```

### PR DESCRIPTION
**Pull request by koic**
This PR tweaks the offense message of `Style/RedundantFormat`. Including the result of calls like `format('%10s', 'beepboop')` in the message helps users understand the cop's role in identifying cases where a string literal can be used instead.

Fixes #13866.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Review by dvandersluis — APPROVED** [review]
Nice 👍

File: lib/rubocop/cop/style/redundant_format.rb [hunk 1]
```diff
@@ -47,7 +47,7 @@ module Style
       class RedundantFormat < Base
         extend AutoCorrector
 
-        MSG = 'Redundant `%<method_name>s` can be removed.'
+        MSG = 'Use `%<prefer>s` directly instead of redundant `%<method_name>s`.'
```
Comment (bbatsov) [inline lib/rubocop/cop/style/redundant_format.rb:50]: I'd say the word "redundant" is redundant here. ;-)
