### PR TITLE
[Fix #14737] Fix crash in `Layout/RedundantLineBreak` when `Layout/LineLength` is disabled

### LINKED ISSUE #14737: ArgumentError in check_single_line_suitability
## Steps to reproduce the problem

```yaml
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.8
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Layout/RedundantLineBreak:
  Enabled: false
#
Layout/RedundantLineBreak:
  Enabled: true
Layout/LineLength:
  Enabled: false


```

```bash
$ printf "_=[\n]" | rubocop -d -c ~/rubocop.yml -ss
```

## Expected behavior

No crash.

## Actual behavior

```bash
./rubocop/lib/rubocop/cop/mixin/check_single_line_suitability.rb:18:in 'Integer#>': comparison of Integer with nil failed (ArgumentError)
        to_single_line(lines.join("\n")).length > max_line_length
                                                  ^^^^^^^^^^^^^^^
```

## RuboCop version

```cfg
System Version: macOS 26.1 (25B78)
Model Identifier: MacBookAir10,1
ruby 3.4.8 (2025-12-17 revision 995b59f666) +PRISM [arm64-darwin25]
rubocop     2025-12-22 edca36ebb

```

### PR DESCRIPTION
**Pull request by ydakuka**
Fixes #14737

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/redundant_line_break_spec.rb [hunk 1]
```diff
@@ -774,4 +775,22 @@ def assignment?
       end
     end
   end
+
+  context 'when `Layout/LineLength` is disabled' do
+    let(:line_length_config) { { 'Enabled' => false } }
+    let(:inspect_blocks) { [false, true].sample }
```
Comment (koic) [inline spec/rubocop/cop/layout/redundant_line_break_spec.rb]: Please don't introduce randomness into test code. Can you update `let`s as shown below?

```diff
diff --git a/spec/rubocop/cop/layout/redundant_line_break_spec.rb b/spec/rubocop/cop/layout/redundant_line_break_spec.rb
index d00d130df..49ed6ebce 100644
--- a/spec/rubocop/cop/layout/redundant_line_break_spec.rb
+++ b/spec/rubocop/cop/layout/redundant_line_break_spec.rb
@@ -2,14 +2,17 @@

 RSpec.describe RuboCop::Cop::Layout::RedundantLineBreak, :config do
   let(:config) do
-    RuboCop::Config.new('Layout/LineLength' => line_length_config,
+    RuboCop::Config.new('Layout/LineLength' => {
+                          'Enabled' => line_length_enabled, 'Max' => max_line_length
+                        },
                         'Layout/RedundantLineBreak' => { 'InspectBlocks' => inspect_blocks },
                         'Layout/SingleLineBlockChain' => {
                           'Enabled' => single_line_block_chain_enabled
                         })
   end
-  let(:line_length_config) { { 'Max' => max_line_length } }
+  let(:line_length_enabled) { true }
   let(:max_line_length) { 31 }
+  let(:inspect_blocks) { false }
   let(:single_line_block_chain_enabled) { true }

   shared_examples 'common behavior' do
@@ -777,8 +780,7 @@ RSpec.describe RuboCop::Cop::Layout::RedundantLineBreak, :config do
   end

   context 'when `Layout/LineLength` is disabled' do
-    let(:line_length_config) { { 'Enabled' => false } }
-    let(:inspect_blocks) { [false, true].sample }
+    let(:line_length_enabled) { false }

     it 'registers an offense for a method call on multiple lines' do
       expect_offense(<<~RUBY)
```

Comment (ydakuka) [reply spec/rubocop/cop/layout/redundant_line_break_spec.rb]: Sure, changed.

**Comment by koic** [comment]
Thanks!
