### PR TITLE
[Fix #12527] Fix `Offense#highlighted_area` to return a valid `Parser::Source::Range`

### LINKED ISSUE #12527: undefined method `name` while accessing to `RuboCop::Cop::Offense::highlighted_area`
Hello 👋  I'm trying to access to the `highlighted_area` method of an offense, which is on the public api, but it's raising an error.

--------

## Expected behavior

Should return a `Parser::Source::Range` as documented here: 

https://github.com/rubocop/rubocop/blob/b1bcb3134d49a60061d08ef168ae996d70d8ce5c/lib/rubocop/cop/offense.rb#L138-L144

## Actual behavior

If I'm adding a debug in the `clang_formatter`:
https://github.com/rubocop/rubocop/blob/b1bcb3134d49a60061d08ef168ae996d70d8ce5c/lib/rubocop/formatter/clang_style_formatter.rb#L51-L56

Accessing to `highlighted_area` raise a `NoMethodError`

```ruby
(ruby) highlighted_area
#<NoMethodError: undefined method `name' for "  def dummy(node)":String> rescued during inspection
(ruby) highlighted_area.source_buffer
"  def dummy(node)"
(ruby) highlighted_area.begin_pos
2
(ruby) highlighted_area.source
"def dummy(node)"
``` 

## Steps to reproduce the problem

- Create a file `foo.rb`

```ruby
class Foo
  def dummy(node)
    puts "foo"
    puts "foo"
    puts "foo"
  end
end
``` 

- Enable the rule `Metrics/MethodLength` with `Max: 2`
- Add a breakpoint into `lib/rubocop/formatter/clang_style_formatter.rb`
- Run `bin/rubocop -d --only Metrics/MethodLength foo.rb`

## RuboCop version

```
bundle exec rubocop -V
1.58.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.2) [arm64-darwin23]
  - rubocop-minitest 0.33.0
  - rubocop-rake 0.6.0
  - rubocop-sorbet 0.7.5
```

### PR DESCRIPTION
**Pull request by ydakuka**
Fixes #12527 

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/offense.rb [hunk 1]
```diff
@@ -139,7 +139,8 @@ def disabled?
       # @return [Parser::Source::Range]
       #   the range of the code that is highlighted
       def highlighted_area
-        Parser::Source::Range.new(source_line, column, column + column_length)
+        source_buffer = Parser::Source::Buffer.new(location.source_buffer.name, source: source_line)
```
Comment (rafaelfranca) [inline lib/rubocop/cop/offense.rb:142]: Sometimes `location` is a `PseudoSourceRange` that doesn't have a `source_buffer` method.
