### PR TITLE
[Fix #10958] Fix an infinite loop for `Layout/SpaceInsideBlockBraces` when multiline block

### LINKED ISSUE #10958: `Layout/SpaceInsideBlockBraces` infinite loop, but corrected everything?
Using the following configuration:

```
AllCops:
  DisabledByDefault: true

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: no_space
```

On this project: https://github.com/socketry/async-http-cache

results in an infinite loop for what looks like relatively benign code:

```
11 files inspected, 8 offenses detected, 8 offenses corrected
Infinite loop detected in /home/samuel/Projects/socketry/async-http-cache/spec/async/http/cache/general_spec.rb and caused by Layout/SpaceInsideBlockBraces -> Layout/SpaceInsideBlockBraces
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:300:in `check_for_infinite_loop'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:283:in `block in iterate_until_no_changes'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:282:in `loop'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:282:in `iterate_until_no_changes'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:251:in `do_inspection_loop'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:134:in `block in file_offenses'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:159:in `file_offense_cache'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:133:in `file_offenses'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:124:in `process_file'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:105:in `block in each_inspected_file'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:104:in `each'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:104:in `reduce'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:104:in `each_inspected_file'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:90:in `inspect_files'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/runner.rb:47:in `run'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/cli/command.rb:11:in `run'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/cli.rb:72:in `run_command'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/cli.rb:79:in `execute_runners'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/lib/rubocop/cli.rb:48:in `run'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/exe/rubocop:19:in `block in <top (required)>'
/home/samuel/.rubies/ruby-3.1.2/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/home/samuel/.gem/ruby/3.1.2/gems/rubocop-1.35.0/exe/rubocop:19:in `<top (required)>'
/home/samuel/.gem/ruby/3.1.2/bin/rubocop:25:in `load'
/home/samuel/.gem/ruby/3.1.2/bin/rubocop:25:in `<main>'
```

Branch for repro: https://github.com/socketry/async-http-cache/tree/rubocop

Let me know if I can help further.

### PR DESCRIPTION
**Pull request by ydah**
Fix: #10958

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/space_inside_block_braces.rb [hunk 1]
```diff
@@ -157,8 +162,17 @@ def multiline_block?(left_brace, right_brace)
           left_brace.first_line != right_brace.first_line
         end
 
-        def aligned_braces?(left_brace, right_brace)
-          left_brace.first_line == right_brace.last_column
+        def aligned_braces?(node, inner, right_brace)
+          column = expression_column(node)
```
Comment (koic) [inline lib/rubocop/cop/layout/space_inside_block_braces.rb:166]: Can you update to the following and remove the new `expression_column` method and `child_send_node` matcher?

```suggestion
          column = column = node.loc.expression.column

```

File: changelog/fix_fix_an_infinite_loop_for_layout_space_inside_block_braces.md [hunk 2]
```diff
@@ -0,0 +1 @@
+* [#10958](https://github.com/rubocop/rubocop/issues/10958): Fix an infinite loop for `Layout/SpaceInsideBlockBraces`. ([@ydah][])
```
Comment (koic) [inline changelog/fix_fix_an_infinite_loop_for_layout_space_inside_block_braces.md:1]: Can you add a more bit explanation about the context of this error?

File: changelog/fix_fix_an_infinite_loop_for_layout_space_inside_block_braces.md [hunk 3]
```diff
@@ -0,0 +1 @@
+* [#10958](https://github.com/rubocop/rubocop/issues/10958): Fix an infinite loop for `Layout/SpaceInsideBlockBraces` when multiline block. ([@ydah][])
```
Comment (koic) [inline changelog/fix_fix_an_infinite_loop_for_layout_space_inside_block_braces.md:1]:
```suggestion
* [#10958](https://github.com/rubocop/rubocop/issues/10958): Fix an infinite loop for `Layout/SpaceInsideBlockBraces` when `EnforcedStyle` is `no_space` and using multiline block. ([@ydah][])
```

File: spec/rubocop/cop/layout/space_inside_block_braces_spec.rb [hunk 4]
```diff
@@ -391,6 +391,23 @@
...
+          RUBY
+        end
+
+        it 'registers an offense when braces are not aligned in multiline block with bracket' do
+          expect_offense(<<~RUBY)
+            foo {[
+              bar
+              ]}
+               ^{} Space inside } detected.
+          RUBY
```
Comment (koic) [inline spec/rubocop/cop/layout/space_inside_block_braces_spec.rb:409]: Can you add `expect_correction` code? It looks like `InfiniteCorrectionLoop` error is not resolved.

Comment (ydah) [reply spec/rubocop/cop/layout/space_inside_block_braces_spec.rb:421]: Ops, I added it. Thank you.
