### PR TITLE
[Fix #10605] Fix autocorrect for `Style/RedundantCondition`

### LINKED ISSUE #10605: Style/RedundantCondition making invalid corrections
## Expected behavior

Running `rubocop --auto-correct` should not result in broken code.

## Actual behavior

Running rubocop 1.29.0 triggers a correction from `Style/RedundantCondition` on this code:

```
if referer
  redirect_to referer
else
  redirect_to :action => :inbox
end
```

changing it to this:

```
redirect_to referer || :action => :inbox
```

which is incorrect and is rejected by ruby requiring it to be changed to:

```
redirect_to referer || { :action => :inbox }
```

in order to work.

## Steps to reproduce the problem

See above.

## RuboCop version

```
1.29.0 (using Parser 3.1.2.0, rubocop-ast 1.17.0, running on ruby 3.1.2 x86_64-linux)
  - rubocop-minitest 0.19.1
  - rubocop-performance 1.13.3
  - rubocop-rails 2.14.2
  - rubocop-rake 0.6.0
```

### PR DESCRIPTION
**Pull request by nobuyo**
...if argument for method in else branch is hash without braces.

Fixes #10605.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/redundant_condition.rb [hunk 1]
```diff
@@ -196,6 +200,10 @@ def require_parentheses?(node)
             (node.respond_to?(:semantic_operator?) && node.semantic_operator?)
         end
 
+        def require_braces?(node)
+          node.hash_type?
```
Comment (koic) [inline lib/rubocop/cop/style/redundant_condition.rb:204]: It will get a syntax error in the following already braced case:

```ruby
           if foo
           ^^^^^^ Use double pipes `||` instead.
             bar foo
           else
             bar({ baz => quux })
           end
```

Auto-corrected code is `bar foo || { { baz => quux } }`.

```ruby
% ruby -ce "bar foo || { { baz => quux } }"
-e:1: syntax error, unexpected '}', expecting =>
bar foo || { { baz => quux } }
```

Can you add the above test case and fix it?

Comment (nobuyo) [reply lib/rubocop/cop/style/redundant_condition.rb]: Thank you, fixed in 97c6273.

File: spec/rubocop/cop/style/redundant_condition_spec.rb [hunk 2]
```diff
@@ -292,6 +292,36 @@ def test
         RUBY
       end
 
+      it 'registers an offense and corrects when the branches contains method call with hash' do
```
Comment (koic) [inline spec/rubocop/cop/style/redundant_condition_spec.rb:295]: That's just my two cents. It will be symmetric with the `non-braced` of L310 :-)

```suggestion
      it 'registers an offense and corrects when the branches contains method call with braced hash' do
```

**Comment by koic** [comment]
Thanks!
