### PR TITLE
[Fix #13909] Fix false positive with `Layout/ClosingParenthesisIndentation` when first parameter is a hash

### LINKED ISSUE #13909: ClosingParenthesisIndentation reports false positive if first parameter is a hash
# Issue: Incorrect autocorrection by Layout/ClosingParenthesisIndentation cop

## Expected behavior

The `Layout/ClosingParenthesisIndentation` cop should not report an error with the indentation and autocorrect

```ruby
external_service.build_resource({},
  custom_merge: {
    "inventory_level_resources" => [inventory_level_resource],
  },
  version: "inventory_levels",
)
```

## Actual behavior

The `Layout/ClosingParenthesisIndentation` cop reports an error with the indentation of the closing parenthesis in the following Ruby code:

```ruby
external_service.build_resource({},
  custom_merge: {
    "inventory_level_resources" => [inventory_level_resource],
  },
  version: "inventory_levels",
)
```

When attempting to autocorrect, RuboCop produces the following incorrect output:

```ruby
external_service.build_resource({},
  custom_merge: {
    "inventory_level_resources" => [inventory_level_resource],
  },
  version: "inventory_levels",
                               )
```

The closing parenthesis is incorrectly aligned far to the right, which does not match the expected style.

## Steps to reproduce the problem

1. Create a Ruby file with the following content:

   ```ruby
   external_service.build_resource({},
     custom_merge: {
       "inventory_level_resources" => [inventory_level_resource],
     },
     version: "inventory_levels",
   )
   ```

2. Run RuboCop on this file with the command:

   ```bash
   rubocop --auto-correct
   ```

3. Observe the incorrect autocorrection of the closing parenthesis indentation.

## RuboCop version

```
$ rubocop -V
1.71.0
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes https://github.com/rubocop/rubocop/issues/13909

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/closing_parenthesis_indentation.rb [hunk 1]
```diff
@@ -155,15 +155,19 @@ def expected_column(left_paren, elements)
...
+            elements.first.each_child_node.map { |child| child.loc.column }
+          else
+            elements.flat_map do |e|
               e.loc.column
             end
           end.uniq.count == 1
         end
 
+        def all_kwargs?(elements)
+          elements.count == 1 && elements.first.hash_type?
```
Comment (koic) [inline lib/rubocop/cop/layout/closing_parenthesis_indentation.rb:168]: Is `elements.count == 1 &&` necessary? If so, can you add a corresponding test for it?

**Comment by koic** [comment]
Thanks!
