### PR TITLE
[Fix #14232] Add `AllowedPatterns` and `AllowBangMethods` configuration to `Naming/PredicateMethod`

### LINKED ISSUE #14232: `Naming/PredicateMethod` false positive when an "operation" returns `true`
The new `Naming/PredicateMethod` is returning a false positive for a method which is, maybe, not the best method ever but it is definitely not a predicate method

```rb
def set_admin!
  raise 'Nope' unless some_checks?

  admin_arel.first_or_create
  true
end
```

Actually, the `true` is just used to return a simpler object here. I'm not incline to remove it and return the internal admin object, but if you think it should work that way I would do the change

--------

## Expected behavior

No offenses, because the method returns a boolean, but is not a predicate. The boolean is the "result of the operation"

## Actual behavior

```
test.rb:1:5: C: Naming/PredicateMethod: Predicate method names should end with ?.
def set_admin!
```

## Steps to reproduce the problem

1. Create a file `test.rb`

```rb
def set_admin!
  raise 'Nope' unless some_checks?

  admin_arel.first_or_create
  true
end
```

2. `bundle exec rubocop --only Naming/PredicateMethod test.rb` 

## RuboCop version

```
$ be rubocop -V
1.76.0 (using Parser 3.3.8.0, rubocop-ast 1.45.0, analyzing as Ruby 2.7, running on ruby 3.4.3) [arm64-darwin24]
```

From main branch

### PR DESCRIPTION
**Pull request by dvandersluis**
* `AllowedPatterns` allows regular expressions to be set for allowing method names.
* `AllowBangMethods` allows method names ending with a bang (`!`) to always be accepted by the cop.

Fixes #14232.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Review by bbatsov — APPROVED** [review]
Looks good to me!

File: lib/rubocop/cop/naming/predicate_method.rb [hunk 1]
```diff
@@ -210,6 +229,16 @@ def extract_conditional_branches(node)
...
+
+        def allow_bang_methods?
+          cop_config.fetch('AllowBangMethods', false)
+        end
+
+        def allowed_bang_method?(node)
+          return false unless allow_bang_methods?
+
+          node.bang_method?
+        end
```
Comment (koic) [inline lib/rubocop/cop/naming/predicate_method.rb:237]: Can you reverse the order of `allow_bang_methods?` and `allowed_bang_method?` in the definition?

Comment (dvandersluis) [reply lib/rubocop/cop/naming/predicate_method.rb:237]: OK, done.
