### PR TITLE
[Fix #11202] Fix `--only` flag usage with `--auto-gen-config` and `Layout/LineLength`

### LINKED ISSUE #11202: Using `--auto-gen-config` and `--only` not working properly when `Layout/LineLength` COP is enabled
Currently, if we run `bundle exec rubocop --auto-gen-config --only Style/Documentation`, the config will contain all the enabled COPs from our `.rubocop.yml` config file.

--------

## Expected behavior

Using `--only` we can specify only the COPs we want to be verified.

## Actual behavior

When `Layout/LineLength` is enabled, all other COPs are verified even if we specify only a single COP.
Example:
```
$ master ⨯ bundle exec rubocop --auto-gen-config --only Style/Documentation                                                                                                                                                           
Added inheritance from `.rubocop_todo.yml` in `.rubocop.yml`.
Phase 1 of 2: run Layout/LineLength cop
Inspecting 71 files
......................................C............C...................

71 files inspected, 4 offenses detected
Created .rubocop_todo.yml.
Phase 2 of 2: run all cops
Inspecting 71 files
CCCC...........C...CCCCC.....C...C.W..CCCCC.CCCCCCCCC.C.C...CCCCC.CCCCC

71 files inspected, 178 offenses detected, 166 offenses autocorrectable
Created .rubocop_todo.yml.
```
```
$ master ⨯ cat .rubocop_todo.yml                                                                                                                                                                                                     
# This configuration was generated by
# `rubocop --auto-gen-config`
# on 2022-11-25 14:30:31 UTC using RuboCop version 1.39.0.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 6
# This cop supports safe autocorrection (--autocorrect).
Layout/EmptyLineAfterGuardClause:
  Exclude:
    - 'bin/bundle'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Layout/EmptyLines:
  Exclude:
    - 'config/environments/development.rb'
    - 'db/migrate/20221105195927_add_devise_to_users.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, no_empty_lines
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'
# ....
```

In case we disable `Layout/LineLength` COP in out config file, it will take into account the `--only` flag.
```
$ master ⨯ bundle exec rubocop --auto-gen-config --only Style/Documentation                                                                                                                                                           16:30:39
Phase 1 of 2: run Layout/LineLength cop (skipped because Layout/LineLength is disabled)
Phase 2 of 2: run all cops
Inspecting 71 files
.............................................................CCC.......

71 files inspected, 3 offenses detected
Created .rubocop_todo.yml.
```

```
$ master ⨯ cat .rubocop_todo.yml                                                                                                                                                                                                      16:35:23
# This configuration was generated by
# `rubocop --auto-gen-config`
# on 2022-11-25 14:35:23 UTC using RuboCop version 1.39.0.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 3
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'db/migrate/20221106143009_alter_field_nullability.rb'
    - 'db/migrate/20221106160757_confirmable_user.rb'
    - 'db/migrate/20221118145303_alter_user.rb'
```

Describe here what actually happened.
Please use `rubocop --debug` when pasting rubocop output as it contains additional information.

## Steps to reproduce the problem

- Create a new ruby project
- Add `rubocop` gem
- Enable 3-4 COPs (including `Layout/LineLength`)
- run `bundle exec rubocop --auto-gen-config --only Style/Documenttion` (or any other COP)
- see that the generated _todo_ config file contains all the COPs, not only the one specified in the `--only` flag

- then disable the `Layout/LineLength` COP in the config file
- run `bundle exec rubocop --auto-gen-config --only Style/Documenttion` (or any other COP)
- see that the generated _todo_ config file only contains the specified COP

## RuboCop version

```
$ master ⨯ bundle exec rubocop -v                                                                                                                                                                                                     16:38:34
1.39.0
```

## Fix proposal:
In the [run_line_length_cop](https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cli/command/auto_generate_config.rb#L63-L72) method, before assigning `Layout/Linelength` to `@options[:only]` ([here](https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cli/command/auto_generate_config.rb#L65)), save the `@options[:config]` to a variable.
Where we are currently deleting the `@options[:config]` ([here](https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cli/command/auto_generate_config.rb#L67)), make sure that we re-assign the original `@options[:only]` values

### PR DESCRIPTION
**Pull request by istvanfazakas**
**Fixes https://github.com/rubocop/rubocop/issues/11202
This PR fixes the usage of the `--only` flag with the `--auto-gen-config` when the `Layout/LineLength` COP is enabled.
It will only generate the config for the given COPs if we use use the `--only` flag.**

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cli/command/auto_generate_config.rb [hunk 1]
```diff
@@ -57,6 +60,10 @@ def line_length_cop(config)
           config.for_cop('Layout/LineLength')
         end
 
+        def options_has_only_flag?
+          @options[:only] # && !@options[:only].include?('Layout/LineLength')
```
Comment (bbatsov) [inline lib/rubocop/cli/command/auto_generate_config.rb:64]: Why is there some commented out code here?

File: lib/rubocop/cli/command/auto_generate_config.rb [hunk 2]
```diff
@@ -16,6 +16,7 @@ class AutoGenerateConfig < Base
 
         PHASE_1_OVERRIDDEN = '(skipped because the default Layout/LineLength:Max is overridden)'
         PHASE_1_DISABLED = '(skipped because Layout/LineLength is disabled)'
+        PHASE_1_SKIPPED = '(skipped because the COPs from the --only flag are parsed only)'
```
Comment (bbatsov) [inline lib/rubocop/cli/command/auto_generate_config.rb:19]: I'm struggling to understand this sentence, so it should probably be reworded - e.g. what is "the cops from the --only flag are parsed only"?

File: spec/rubocop/cli/auto_gen_config_spec.rb [hunk 3]
```diff
@@ -394,6 +394,97 @@ def f
...
+              return y
+            end
+
+            z
+          end
+        RUBY
+      end
+
+      context 'when --only does not contain Layout/Linelength' do
+        it 'generates TODO only for the mentioned COP and Layout/LineLength' do
```
Comment (bbatsov) [inline spec/rubocop/cli/auto_gen_config_spec.rb:420]: There's not need to capitalize COP like you've done. I also don't get what's the special significance of `LineLength` here if it's wasn't passed an argument.

**Comment by bbatsov** [comment]
Probably this change should also be reflected somewhere in the user docs.

File: lib/rubocop/cli/command/auto_generate_config.rb (hunk 1 above)
Comment (istvanfazakas) [reply lib/rubocop/cli/command/auto_generate_config.rb:64]: just forgot to remove it - addressing this now 👍

File: lib/rubocop/cli/command/auto_generate_config.rb (hunk 2 above)
Comment (istvanfazakas) [reply lib/rubocop/cli/command/auto_generate_config.rb:19]: in case the `Layout/LineLength` COP is enabled, and we use the `--only` flag with auto-generate, it will only generate the config for the given COPs passed with the `--only` flag

File: spec/rubocop/cli/auto_gen_config_spec.rb (hunk 3 above)
Comment (istvanfazakas) [reply spec/rubocop/cli/auto_gen_config_spec.rb:420]: I will update the wording used here to be more straight forward - sorry for this

**Comment by istvanfazakas** [comment]
> Probably this change should also be reflected somewhere in the user docs.

@bbatsov as per the docs, this should work as it is in this PR since the `--auto-gen-config` and `--only` flags are not mutually exclusive: https://docs.rubocop.org/rubocop/usage/basic_usage.html#command-line-flags

File: lib/rubocop/cli/command/auto_generate_config.rb (hunk 1 above)
Comment (istvanfazakas) [reply lib/rubocop/cli/command/auto_generate_config.rb]: removed commented code

File: spec/rubocop/cli/auto_gen_config_spec.rb (hunk 3 above)
Comment (istvanfazakas) [reply spec/rubocop/cli/auto_gen_config_spec.rb]: updated descriptions

File: lib/rubocop/cli/command/auto_generate_config.rb (hunk 2 above)
Comment (bbatsov) [reply lib/rubocop/cli/command/auto_generate_config.rb:19]: @istvanfazakas But I still don't get what is being "parsed" here. Is this some typo and you meant to write "passed"?

Comment (istvanfazakas) [reply lib/rubocop/cli/command/auto_generate_config.rb:19]: sorry, yes, it seems to be a typo. I will fix it

Comment (istvanfazakas) [reply lib/rubocop/cli/command/auto_generate_config.rb]: @bbatsov I just updated the sentence. Please take a look if it makes more sense now 🙏
