### PR TITLE
[Fix #9731] Fix two autocorrection issues for `Style/NegatedIfElseCondition`

### LINKED ISSUE #9731: Style/NegatedIfElseCondition bugs with specific conditions
The Style/NegatedIfElseCondition cop bugs with very specific conditions with error `Parser::Source::TreeRewriter detected clobbering`.

```
1 error occurred:
An error occurred while Style/NegatedIfElseCondition cop was inspecting ...
```
--------

## Steps to reproduce the problem

Create a file with the code below and run rubocop on it:

```ruby
if !a_condition
  # comment
  flag = false
  do_a
end

if !another_condition
  # comment
  flag = false
  do_b
else
  do_c
end
```

This seems very specific since it works if you remove the else block, if you remove the comments...

## RuboCop version

```
$ bundle exec rubocop -V
1.12.1 (using Parser 3.0.1.0, rubocop-ast 1.4.1, running on ruby 2.6.7 x86_64-darwin20)
  - rubocop-performance 1.9.2
  - rubocop-rails 2.9.1
  - rubocop-rspec 2.2.0
```

### PR DESCRIPTION
**Pull request by dvandersluis**
Previously, when swapping the `if` and `else` branches, if one of the branches only had a single statement, the branch would end up not being spaced out properly.

Additionally, when there is a node with a comment inside the `if` that has an identical node with a comment *before* the `if` statement, `CommentsHelp.begin_pos_with_comment` returns an incorrect range, which was causing a clobbering error. I fixed this by creating ranges of the entire body of the if and else branches, so that they can just be swapped without relying on `ProcessedSource#ast_with_comments`. See rubocop/rubocop-ast#179.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/negated_if_else_condition_spec.rb [hunk 1]
```diff
@@ -50,6 +50,21 @@
...
+        do_something :
+        do_something_else # comment
+    RUBY
+
+    expect_correction(<<~RUBY)
+      x ?
+        do_something_else :
+        do_something # comment
+    RUBY
+  end
```
Comment (dvandersluis) [inline spec/rubocop/cop/style/negated_if_else_condition_spec.rb:66]: This doesn't actually correct the comment properly but I wanted to add a test for this case just to document behaviour. Really no one should be writing multiline ternaries like this. 😏

File: lib/rubocop/cop/style/negated_if_else_condition.rb [hunk 2]
```diff
@@ -98,21 +97,38 @@ def swap_branches(corrector, node)
...
+        # Collect the entire if branch, including whitespace and comments
+        def if_range(node)
+          if node.ternary?
+            node.if_branch
+          else
+            Parser::Source::Range.new(
+              processed_source.buffer,
+              node.condition.loc.expression.end_pos,
+              node.loc.else.begin_pos
+            )
```
Comment (koic) [inline lib/rubocop/cop/style/negated_if_else_condition.rb:117]: That's just my two cents :-)

```suggestion
            range_between(node.condition.loc.expression.end_pos, node.loc.else.begin_pos)
```

File: lib/rubocop/cop/style/negated_if_else_condition.rb [hunk 3]
```diff
@@ -98,21 +97,38 @@ def swap_branches(corrector, node)
...
+        # Collect the entire else branch, including whitespace and comments
+        def else_range(node)
+          if node.ternary?
+            node.else_branch
+          else
+            Parser::Source::Range.new(
+              processed_source.buffer,
+              node.loc.else.end_pos,
+              node.loc.end.begin_pos
+            )
```
Comment (koic) [inline lib/rubocop/cop/style/negated_if_else_condition.rb:130]:
```suggestion
            range_between(node.loc.else.end_pos, node.loc.end.begin_pos)
```

**Comment by dvandersluis** [comment]
Thanks for the review @koic!
