### PR TITLE
[Fix #12172] Fix a false positive for `Style/EmptyCaseCondition`

### LINKED ISSUE #12172: Style/EmptyCaseCondition creates syntax error on autocorrect when following a return
## Expected behavior

I don't know. Certainly rubocop corrections should not lead to syntax errors.

## Actual behavior

```ruby
def foo(bar)
  return case
         when bar == 1
           2
         when bar != 12
           3
         else
           4
         end
end
```

is corrected to

```ruby
def foo(bar)
  return if bar == 1
           2
         elsif bar != 12
           3
         else
           4
         end
end
```

which is a syntax error, as the "return if bar == 1" is parsed as a postfix if.

## Steps to reproduce the problem

see above

## RuboCop version

```
$ [bundle exec] rubocop -V
1.42.0 (using Parser 3.1.3.0, rubocop-ast 1.24.1, running on ruby 3.1.3) +server [x86_64-linux] 
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12172.

This PR fixes a false positive for `Style/EmptyCaseCondition` when using `return`, `break`, `next` or method call before empty case condition.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/empty_case_condition_spec.rb [hunk 1]
```diff
@@ -266,67 +266,23 @@ def example
...
-                 else object
-                 end
-        RUBY
-      end
-      let(:corrected_source) do
-        <<~RUBY
-          return if object.nil?
-           Object.new
-                 else object
-                 end
```
Comment (koic) [inline spec/rubocop/cop/style/empty_case_condition_spec.rb:307]: This test case is removed because this autocorrected syntax is invalid. In other words, it's a bug.

File: spec/rubocop/cop/style/empty_case_condition_spec.rb [hunk 2]
```diff
@@ -266,67 +266,23 @@ def example
...
-                       else object
-                       end
-        RUBY
-      end
-      let(:corrected_source) do
-        <<~RUBY
-          do_some_work if object.nil?
-           Object.new
-                       else object
-                       end
```
Comment (koic) [inline spec/rubocop/cop/style/empty_case_condition_spec.rb:329]: Ditto.

File: spec/rubocop/cop/style/empty_case_condition_spec.rb [hunk 3]
```diff
@@ -240,22 +240,22 @@ def example
...
-                       else
-                         object
-                       end
+          case
+          ^^^^ Do not use empty `case` condition, instead use an `if` expression.
+          when object.nil?
+            Object.new
+          else
+            object
+          end
```
Comment (koic) [inline spec/rubocop/cop/style/empty_case_condition_spec.rb:249]: NOTE: These tests have been updated to use valid syntax.
