### PR TITLE
[Fix #14847] Fix false positive for `Layout/MultilineMethodCallIndentation` when a method is chained after a single-line block

### LINKED ISSUE #14847: Regression with `Layout/MultilineMethodCallIndentation` in `1.84.1`
Rubocop is reporting an error with previously passing code.

--------

## Steps to reproduce the problem

```
          rows.each_with_index.with_object([]) do |(row, row_index), galaxies|
            (0...row.length).select { row[it] == "#" }
                            .each { galaxies << [row_index, it] }
          end
```

## Expected behavior

No offenses to be raised.

## Actual behavior

```
test.rb:43:29: C: [Correctable] Layout/MultilineMethodCallIndentation: Use 2 (not 16) spaces for indenting an expression spanning multiple lines.
                            .each { galaxies << [row_index, it] }
                            ^^^^^
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
1.84.1 (using Parser 3.3.10.1, Prism 1.9.0, rubocop-ast 1.49.0, analyzing as Ruby 4.0, running on ruby 4.0.0) +server [x86_64-linux]
  - rubocop-performance 1.26.1
  - rubocop-rake 0.7.1
  - rubocop-rspec 3.9.0
```

### PR DESCRIPTION
**Pull request by ydakuka**
Fixes #14847

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/multiline_method_call_indentation.rb [hunk 1]
```diff
@@ -344,12 +344,17 @@ def find_multiline_block_chain_node(node)
 
         def find_continuation_receiver(node)
           receiver = node.receiver
+          return receiver.send_node if single_line_block_receiver?(receiver)
```
Comment (koic) [inline lib/rubocop/cop/layout/multiline_method_call_indentation.rb]: By combining this with the `single_line?` method, it could be expressed inline without introducing `single_line_block_receiver?`.

```suggestion
          return receiver.send_node if receiver.single_line? && receiver.any_block_type?
```

Comment (ydakuka) [reply lib/rubocop/cop/layout/multiline_method_call_indentation.rb]: Changed.

File: lib/rubocop/cop/layout/multiline_method_call_indentation.rb [hunk 2]
```diff
@@ -344,6 +344,7 @@ def find_multiline_block_chain_node(node)
 
         def find_continuation_receiver(node)
```
Comment (koic) [inline lib/rubocop/cop/layout/multiline_method_call_indentation.rb]: Since this method can now return `receiver.send_node`, which was not a possible return value before, the name `find_continuation_receiver` no longer seems to match its behavior.
For example, a name like `find_continuation_node` might be more appropriate. Of course, an even better name would be welcome if there is one.

Comment (ydakuka) [reply lib/rubocop/cop/layout/multiline_method_call_indentation.rb]: Agreed, I renamed it.

File: spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb [hunk 3]
```diff
@@ -943,6 +943,35 @@ def a
       RUBY
     end
 
+    it 'accepts aligned method chained after single-line block' do
+      expect_no_offenses(<<~RUBY)
+        rows.each_with_index.with_object([]) do |(row, row_index), galaxies|
+          (0...row.length).select { row[it] == "#" }
+                          .each { galaxies << [row_index, it] }
+        end
```
Comment (koic) [inline spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb]: Although this is the actual code from the issue report, can you simplify it into a smaller test case, similar to the other existing test cases? With the code in its current complex form, it’s difficult to see the core of the problem. A minimal reproduction case would be preferable.

Comment (ydakuka) [reply spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb]: Agreed. I’ve simplified the code to a minimal reproduction case.

Comment (koic) [reply spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb]: It looks like the tests still pass even without the product code change added to　`lib/rubocop/cop/layout/multiline_method_call_indentation.rb`.

```ruby
return receiver.send_node if receiver.single_line? && receiver.any_block_type?
```

Can you update reproducible test cases that fails without the change?

Comment (ydakuka) [reply spec/rubocop/cop/layout/multiline_method_call_indentation_spec.rb]: Sorry, my bad. I've fixed the tests and also addressed other detected false positives.
