### PR TITLE
[Fix #12087] Fix false positives for Style/ArgumentsForwarding

### LINKED ISSUE #12087: Style/ArgumentsForwarding mis-corrects when the called method has additional arguments.
Style/ArgumentsForwarding will replace all arguments to the called method with `...`, even if there are arguments besides the `*args, **kwargs, &`.

Given the following code:

```ruby
def self.get(*args, **kwargs, &)
  CanvasHttp.request(Net::HTTP::Get, *args, **kwargs, &)
end
```

## Expected behavior

```ruby
def self.get(...)
  CanvasHttp.request(Net::HTTP::Get, ...)
end
```

## Actual behavior

```ruby
def self.get(...)
  CanvasHttp.request(...)
end
```

Note the additional Net::HTTP::Get inline argument has been removed.

## Steps to reproduce the problem

Auto-correct the above code with the Style/ArgumentsForwarding cop.

## RuboCop version

```
1.55.1 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.1.3) [arm64-darwin21]
  - rubocop-factory_bot 2.23.1
  - rubocop-graphql 1.3.0
  - rubocop-performance 1.18.0
  - rubocop-rails 2.20.2
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.23.0
```

Note that I'm not sure if adding leading arguments is supported by all Ruby versions. I seem to remember when this syntax was introduced it was very limited. If that's the case, I would expect this cop to not even find an offense if the target Ruby version doesn't support leading arguments.

### PR DESCRIPTION
**Pull request by owst**
Additionally fixes:
* #12089
* #12096
* #12100

In Ruby < 3.2 this cop was overzealous and not considering various additional args/kwargs and other reasons to not allow forward-all (`...`), and was additionally assuming that forward-all meant all arguments were replaced, which was not always the case.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/arguments_forwarding.rb [hunk 1]
```diff
@@ -186,46 +187,36 @@ def classification_and_forwards(def_node, send_node, referenced_lvars, forwardab
...
-            if add_parens && !parentheses?(def_arguments_or_send)
-              add_parentheses(def_arguments_or_send, corrector)
-            end
+            add_parens_if_missing(def_arguments_or_send, corrector) if add_parens
 
             corrector.replace(kwrest_arg_or_splat, '**')
           end
         end
 
-        def register_forward_all_offense_on_forwarding_method(forwarding_method)
```
Comment (owst) [inline lib/rubocop/cop/style/arguments_forwarding.rb:207]: `register_forward_all_offense_on_forwarding_method` and `register_forward_all_offense_on_method_def` were essentially doing the same thing, and could be made to call the same method.

File: lib/rubocop/cop/style/arguments_forwarding.rb [hunk 2]
```diff
@@ -186,46 +187,36 @@ def classification_and_forwards(def_node, send_node, referenced_lvars, forwardab
 
         def register_forward_args_offense(def_arguments_or_send, rest_arg_or_splat)
           add_offense(rest_arg_or_splat, message: ARGS_MSG) do |corrector|
-            unless parentheses?(def_arguments_or_send)
-              add_parentheses(def_arguments_or_send, corrector)
-            end
```
Comment (owst) [inline lib/rubocop/cop/style/arguments_forwarding.rb:191]: I realised I could reuse this functionality across `register_forward_args_offense`, `register_forward_kwargs_offense` and the new method `register_forward_all_offense` (which replaces the two separate `register_forward_all_offense_on_forwarding_method` and `register_forward_all_offense_on_method_def`)

File: lib/rubocop/cop/style/arguments_forwarding.rb [hunk 3]
```diff
@@ -118,12 +118,13 @@ def only_forwards_all?(send_classifications)
           send_classifications.each_value.all? { |c, _, _| c == :all }
         end
 
-        def add_forward_all_offenses(node, send_classifications)
-          send_classifications.each_key do |send_node|
-            register_forward_all_offense_on_forwarding_method(send_node)
+        def add_forward_all_offenses(node, send_classifications, forwardable_args)
+          send_classifications.each do |send_node, (_c, forward_rest, _forward_kwrest)|
```
Comment (owst) [inline lib/rubocop/cop/style/arguments_forwarding.rb:122]: We need to capture the `forward_rest` value so that we can replace only after the splat if leading arguments are allowed e.g. in 
```ruby
def foo(x, *args, **kwargs, &block)
```
vs
```ruby
def foo(x, ...)
```

File: lib/rubocop/cop/style/arguments_forwarding.rb [hunk 4]
```diff
@@ -186,46 +187,36 @@ def classification_and_forwards(def_node, send_node, referenced_lvars, forwardab
...
-            arguments_range = range_with_surrounding_space(
-              method_definition.arguments.source_range, side: :left
-            )
-            corrector.replace(arguments_range, '(...)')
+            corrector.replace(arg_range, '...')
           end
         end
 
-        def arguments_range(node)
+        def arguments_range(node, first_node)
```
Comment (owst) [inline lib/rubocop/cop/style/arguments_forwarding.rb:214]: This change enables forward-all-with-leading-args e.g. `foo(x, ...)`

File: lib/rubocop/cop/style/arguments_forwarding.rb [hunk 5]
```diff
@@ -289,6 +286,27 @@ def classification
...
           private
 
+          def can_forward_all?
+            return false if any_arg_referenced?
+            return false if ruby_32_missing_rest_or_kwest?
+            return false unless offensive_block_forwarding?
+            return false if forward_additional_kwargs?
+
+            no_additional_args? || (target_ruby_version >= 3.0 && no_post_splat_args?)
+          end
```
Comment (owst) [inline lib/rubocop/cop/style/arguments_forwarding.rb:296]: This is the meat of the change of the PR - with various additional conditions as to when a forward-all is or is not allowed

**Comment by owst** [comment]
//cc @koic @bbatsov - please let me know what you think. I think there's a few points of simplification in the implementation that I've tried to highlight, and of course the bug fixes

File: changelog/fix_false_positives_for_style_arguments_forwarding_one.md [hunk 6]
```diff
@@ -0,0 +1 @@
+* [#12087](https://github.com/rubocop/rubocop/issues/12087): Fix false positive for `Style/ArgumentsForwarding` with additional arg passed in send node. ([@owst][])
```
Comment (koic) [inline changelog/fix_false_positives_for_style_arguments_forwarding_one.md:1]: I think changelog entries can be merged into this representative issue number entry.

File: lib/rubocop/cop/style/arguments_forwarding.rb [hunk 7]
```diff
@@ -305,25 +323,36 @@ def referenced_block_arg?
...
+            splat_index = arguments.index(forwarded_rest_arg)
+            arg_after_splat = arguments[splat_index + 1]
+
+            [nil, :hash, :block_pass].include?(arg_after_splat&.type)
+          end
+
+          def forward_additional_kwargs?
+            return false unless forwarded_kwrest_arg
+
+            forwarded_kwrest_arg.parent.children.size != 1
```
Comment (koic) [inline lib/rubocop/cop/style/arguments_forwarding.rb:344]: Nits :-)

```suggestion
            !forwarded_kwrest_arg.parent.children.one?
```

**Comment by koic** [comment]
@owst This looks good to me. Can you squash your commits into one?

**Comment by owst** [comment]
> @owst This looks good to me. Can you squash your commits into one?

Thanks @koic - done!

**Comment by koic** [comment]
Thanks!
