### PR TITLE
[Fix #9588] Fix causing a variable to be shadowed from outside the rescue block

### LINKED ISSUE #9588: `Naming/RescuedExceptionsVariableName` can cause a variable to be shadowed from outside the rescue block
Follows #9587. This test fails:

```ruby
context 'shadowing an external variable' do
  it 'does not register an offense' do
    expect_no_offenses(<<~RUBY)
      e = 'error message'
      begin
        something
      rescue StandardError => e1
        log(e, e1)
      end
    RUBY
  end
end
```

### PR DESCRIPTION
**Pull request by lilisako**
Fixes #9588
Fix causing a variable to be shadowed from outside the rescue block. 

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb [hunk 1]
```diff
@@ -150,6 +153,13 @@ def message(node)
           preferred_name = preferred_name(offending_name)
           format(MSG, preferred: preferred_name, bad: offending_name)
         end
+
+        def check_shadowed_variable_name(node)
```
Comment (koic) [inline lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb:157]: Can you rename to predicate method?

```suggestion
        def shadowed_variable_name?(node)
```

File: lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb [hunk 2]
```diff
@@ -150,6 +153,13 @@ def message(node)
...
+          node.each_descendant do |n|
```
Comment (koic) [inline lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb:158]: It seems that descendant nodes can be limited.

```suggestion
          node.each_descendant(:lvar) do |n|
```

File: lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb [hunk 3]
```diff
@@ -150,6 +153,13 @@ def message(node)
...
+            return true if n.children.first.to_s == cop_config.fetch('PreferredName', 'e')
```
Comment (koic) [inline lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb:159]: Is there a problem if it replaces `preferred_name`?

```suggestion
            return true if n.children.first.to_s == preferred_name(n)
```

File: lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb [hunk 4]
```diff
@@ -75,6 +75,9 @@ def on_resbody(node)
           preferred_name = preferred_name(offending_name)
           return if preferred_name.to_sym == offending_name
 
+          # check variable shadowing for exception variable
+          return if check_shadowed_variable_name(node)
```
Comment (koic) [inline lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb:79]: Can you update the caller name as well?

```suggestion
          return if shadowed_variable_name?(node)
```

File: lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb [hunk 5]
```diff
@@ -150,6 +153,13 @@ def message(node)
           preferred_name = preferred_name(offending_name)
           format(MSG, preferred: preferred_name, bad: offending_name)
         end
+
+        def shadowed_variable_name?(node)
+          node.each_descendant(:lvar) do |n|
+            return true if n.children.first.to_s == preferred_name(n)
+          end
+          false
```
Comment (koic) [inline lib/rubocop/cop/naming/rescued_exceptions_variable_name.rb:161]: It seems that it can be simplified by using `any?`.

```diff
         def shadowed_variable_name?(node)
-          node.each_descendant(:lvar) do |n|
-            return true if n.children.first.to_s == preferred_name(n)
-          end
-          false
+          node.each_descendant(:lvar).any? { |n| n.children.first.to_s == preferred_name(n) }
         end
```

**Comment by dvandersluis** [comment]
@lilisako ping!

**Comment by koic** [comment]
@lilisako Can you make this CI successful?

**Comment by lilisako** [comment]
Sorry for getting back to you late. I'll do it within 5-6 hours! When it's done I'm doing to mention you. Thanks!

**Comment by lilisako** [comment]
@koic @dvandersluis 
Just passed all CI tests. Could you re-review them? Thanks!

**Comment by koic** [comment]
Thanks!
