### PR TITLE
[Fix #13950] Obsoletion cache can be broken

### LINKED ISSUE #13950: Random failures with "Performance cops have been extracted to the rubocop-performance gem"
Every so often, rubocop fails for me, reporting 

```
Error: `Performance` cops have been extracted to the `rubocop-performance` gem.
(obsolete configuration found in .rubocop.yml, please update it)
```

(I've also seen the error with `Rails cops have been extracted to the rubocop-rails gem.`)

I am using the rubocop-performance gem, and my .rubocop.yml loads it as a plugin. This only occurs on a tiny percentage of runs, apparently at random.

--------

## Expected behavior

No random failures

## Actual behavior

```shellsession
$ while bundle exec rubocop --debug bin ; end

#...  many successful runs ...

For /Users/jon/Developer/haml-lint: configuration from /Users/jon/Developer/haml-lint/.rubocop.yml
Default configuration from /Users/jon/Developer/haml-lint/.devenv/state/.bundle/ruby/3.3.0/gems/rubocop-1.73.2/config/default.yml
Plugin configuration from /Users/jon/Developer/haml-lint/.devenv/state/.bundle/ruby/3.3.0/gems/rubocop-rails-2.30.3/config/default.yml
Plugin configuration from /Users/jon/Developer/haml-lint/.devenv/state/.bundle/ruby/3.3.0/gems/rubocop-rake-0.7.1/config/default.yml
Plugin configuration from /Users/jon/Developer/haml-lint/.devenv/state/.bundle/ruby/3.3.0/gems/rubocop-rspec-3.5.0/config/default.yml
Plugin configuration from /Users/jon/Developer/haml-lint/.devenv/state/.bundle/ruby/3.3.0/gems/rubocop-performance-1.24.0/config/default.yml
configuration from /Users/jon/Developer/haml-lint/.devenv/state/.bundle/ruby/3.3.0/gems/rubocop-factory_bot-2.26.1/config/default.yml
configuration from /Users/jon/Developer/haml-lint/.devenv/state/.bundle/ruby/3.3.0/gems/rubocop-capybara-2.21.0/config/default.yml
configuration from /Users/jon/Developer/haml-lint/.devenv/state/.bundle/ruby/3.3.0/gems/rubocop-rspec_rails-2.30.0/config/default.yml
Error: `Performance` cops have been extracted to the `rubocop-performance` gem.
(obsolete configuration found in .rubocop.yml, please update it)
Finished in 0.28030199999921024 seconds
```

## Steps to reproduce the problem

* Check out https://github.com/jdelStrother/haml-lint-extracted-cops
* (ignore the repo name - I originally thought this was an issue in haml-lint, but have since narrowed it down to just rubocop)
* `bundle install`
* Run in a loop with something like `while bundle exec rubocop bin ; do true; done`
* be patient, this can take hundreds of runs before the issue appears

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ bundle exec rubocop -V
1.73.2 (using Parser 3.3.7.1, rubocop-ast 1.38.1, analyzing as Ruby 3.4, running on ruby 3.3.5) [arm64-darwin24]
  - rubocop-rails 2.30.3
  - rubocop-rake 0.7.1
  - rubocop-rspec 3.5.0
  - rubocop-performance 1.24.0
  - rubocop-capybara 2.21.0
  - rubocop-factory_bot 2.26.1
  - rubocop-rspec_rails 2.30.0
```

I've also seen the problem occur on ruby 3.3, and on a linux VM inside of Github Actions.

### PR DESCRIPTION
**Pull request by Earlopain**
Fix #13950

The `LOAD_RULES_CACHE` uses a _shared_ array, which can cause the index to become damaged. So, although the array has been modified, stale data is returned, causing the extension to ignore that is was loaded from a gem.

No tests for this one because I have no idea how and it would be incredibly specific anyways.

rehashing seems to be occasionally be performed by ruby, this demonstrates the problem:

```rb
array = []
hash = {}

hash[array] = "ok"

pp hash[array] # => "ok"

array << "added"

pp hash[array] # => nil

# Ruby does this sometimes
hash.rehash

pp hash[array] # => "ok"

```

Also see https://docs.ruby-lang.org/en/master/Hash.html#class-Hash-label-Modifying+an+Active+Hash+Key

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/config_obsoletion.rb [hunk 1]
```diff
@@ -50,7 +50,7 @@ def reject_obsolete!
     # Default rules for obsoletions are in config/obsoletion.yml
     # Additional rules files can be added with `RuboCop::ConfigObsoletion.files << filename`
     def load_rules # rubocop:disable Metrics/AbcSize
-      rules = LOAD_RULES_CACHE[self.class.files] ||=
+      rules = LOAD_RULES_CACHE[self.class.files.hash] ||=
```
Comment (Earlopain) [inline lib/rubocop/config_obsoletion.rb:53]: I did `self.class.files.count` as the key first since I expect this to only ever be added to but this seems safer.

**Comment by jdelStrother** [comment]
Nice work, I was staring at this for ages and couldn't figure out why it might break.
I can confirm this seems to fix things for me.

**Comment by dvandersluis** [comment]
Thanks for figuring this out, @Earlopain!

**Comment by Earlopain** [comment]
Thanks for confirming @jdelStrother! Not the kind of bug I often run into

**Comment by bquorning** [comment]
I wonder, is there any valid use case for using a mutable object as a hash key? (of course besides strings, pre-Ruby 3.5/3.6 etc). Maybe Ruby should emit a warning when doing so.

**Comment by Earlopain** [comment]
There's nothing inherently wrong with doing such a thing. It can work just fine and many people are probably doing it without being aware the possible downside. As long as you don't modify it, all is good.

An issue on the ruby side would probably be received similar to https://bugs.ruby-lang.org/issues/19063, which is about a mutable default value
