### PR TITLE
[Fix #10004] Fix a false positive for `Style/RedundantBegin`

### LINKED ISSUE #10004: Style/RedundantBegin syntax error after auto-correction
## Expected behavior

Given this code:

```ruby
begin puts 'Test'; exit(0); end unless defined?(IORTable)
```

I'm expecting it to work after auto-correction (if it's needed).

## Actual behavior

The code is changed to:

```ruby
 puts 'Test'; exit(0);  unless defined?(IORTable)
```

Which shows this error when trying to run with `ruby` command: `test.rb:1: syntax error, unexpected end-of-input`

## RuboCop version

```
1.18.4 (using Parser 3.0.1.1, rubocop-ast 1.9.1, running on ruby 3.0.1 x64-mingw32)
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #10004.

This PR fixes a false positive for `Style/RedundantBegin` when using one-liner with semicolon.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/redundant_begin.rb [hunk 1]
```diff
@@ -131,6 +132,12 @@ def empty_begin?(node)
           node.children.empty?
         end
 
+        def oneliner_with_semicolon?(node)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/redundant_begin.rb:135]: I think it's better to count the number of child nodes in the begin - it's one-line and has 1+ children they must be separated by semicolons, right?

Comment (koic) [reply lib/rubocop/cop/style/redundant_begin.rb]: Right! And it should have been accepted if `begin` block has multiple statements, whether one-liner or multiple-lines. I also added several test cases and modified this implementation based on it.

**Comment by bbatsov** [comment]
Looks good!
