### PR TITLE
[Fix #14350] Fix `Naming/MethodName` cop false positives with `define_method` and operator name

### LINKED ISSUE #14350: Fix Naming/MethodName define method issue with equality
## Expected behavior

I would expect the following to not cause an error:

``` ruby
def define_equality
  define_method(:==) { |other| other.is_a?(self.class) && hash == other.hash }
end
```

## Actual behavior

Here's the output I see:

``` 
demo:16:17: C: Naming/MethodName: Use snake_case for method names. (https://rubystyle.guide#snake-case-symbols-methods-vars)
  define_method(:==) { |other| other.is_a?(self.class) && hash == other.hash }
                ^^^^
```

The problem is that RuboCop doesn't like the symbolized version equality (`:==`). ...but I'm guessing this to be an issue with any method using special characters as an argument to `define_method`.

## Steps to reproduce the problem

Use the following code snippet with the latest release of RuboCop to recreate:

``` ruby
def define_equality
  define_method(:==) { |other| other.is_a?(self.class) && hash == other.hash }
end
 ```

## RuboCop version

```
1.78.0 (using Parser 3.3.8.0, Prism 1.4.0, rubocop-ast 1.45.1, analyzing as Ruby 3.4, running on ruby 3.4.4) [arm64-darwin24.5.0]
  - rubocop-capybara 2.22.1
  - rubocop-disable_syntax 0.2.0
  - rubocop-packaging 0.6.0
  - rubocop-performance 1.25.0
  - rubocop-thread_safety 0.7.3
  - rubocop-rake 0.7.1
  - rubocop-rspec 3.6.0
```

### PR DESCRIPTION
**Pull request by viralpraxis**
Resolves https://github.com/rubocop/rubocop/issues/14350

-----------------

Before submitting the PR make sure the following are checked:

* [X] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [X] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/naming/method_name.rb [hunk 1]
```diff
@@ -159,7 +159,7 @@ def handle_method_name(node, name)
 
           if forbidden_name?(name.to_s)
             register_forbidden_name(node)
-          else
+          elsif /\A[[[:alpha:]]_\d]+[!?=]?\z/.match?(name.to_s)
```
Comment (Earlopain) [inline lib/rubocop/cop/naming/method_name.rb]: This seems to work as intended, but ideally this would be using `operator_method?` like it does in `on_def`. Unfortunatly, there's no way to check that with a string/symbol, only a def node (or similar). And the constant that contains all the operator methods is private in `rubocop-ast` :cry: (maybe that can be changed?)

Either way, it should be consistent with how normal method definitions are handled, I don't think should be a difference between the two.

**Comment by viralpraxis** [comment]
I've copy-pasted [that constant](https://github.com/rubocop/rubocop-ast/blob/8c26dbb0433c2731b5ab81e06a8e214d2fe5f2ec/lib/rubocop/ast/node/mixin/method_identifier_predicates.rb#L20) for now. Let me know if there's a better solution.

Also, emojies (e.g. `def 👽; end`) didn't work before https://github.com/rubocop/rubocop/pull/14331, so it seems to be a separate issue

**Review by bbatsov — APPROVED** [review]
