### PR TITLE
Fix false negative in `Layout/MultilineAssignmentLayout` for block variants

### LINKED ISSUE #14880: Layout/MultilineAssignmentLayout causes a false negative when using block on different line from left side of multi-line assignment
`Layout/MultilineAssignmentLayout` unrecognize block on different line from left side of multi-line assignment.

## Steps to reproduce the problem

```yaml
Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line
  SupportedTypes: ['block']
```

or

```yaml
Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line
  SupportedTypes: ['block']
```

## Expected behavior

The following code should be recognized:

### when new_line style

```ruby
bars = foo
^^^^^^^^^^ Right hand side of multi-line assignment is on the same line as the assignment operator `=`.
  .map { it.bar }
```

### when same_line style

```ruby
bars =
^^^^^^ Right hand side of multi-line assignment is not on the same line as the assignment operator `=`.
  foo.map { it.bar }
```

## Actual behavior

The above codes pass.

## RuboCop version

```
$ [bundle exec] rubocop -V
1.84.2 (using Parser 3.3.10.1, rubocop-ast 1.49.0, analyzing as Ruby 2.7, running on ruby 4.0.0) [arm64-darwin24]
  - rubocop-performance 1.26.1
  - rubocop-rake 0.7.1
  - rubocop-rspec 3.9.0
```

### PR DESCRIPTION
**Pull request by bbatsov**
When `SupportedTypes` includes `'block'`, the cop only matched the `:block` AST node type but not `:numblock` (Ruby 2.7 numbered parameters) or `:itblock` (Ruby 3.4 `it` parameter). This expands the `supported_types` method to automatically include all three block node types when `'block'` is configured.

Fixes #14880

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/multiline_assignment_layout.rb [hunk 1]
```diff
@@ -109,7 +109,10 @@ def check_same_line_offense(node, rhs)
         private
 
         def supported_types
-          @supported_types ||= cop_config['SupportedTypes'].map(&:to_sym)
+          @supported_types ||= cop_config['SupportedTypes'].flat_map do |type|
+            sym = type.to_sym
+            sym == :block ? %i[block numblock itblock] : sym
```
Comment (koic) [inline lib/rubocop/cop/layout/multiline_assignment_layout.rb]: It seems possible to extract `%i[block numblock itblock]` into a constant, such as `BLOCK_TYPES`.

**Comment by koic** [comment]
Can you rebase onto the latest master to resolve the conflicts?

**Comment by bbatsov** [comment]
@koic Rebased onto master and conflicts resolved. The `BLOCK_TYPES` constant was already extracted in this PR — it's what `supported_types` uses to expand `:block` into `%i[block numblock itblock]`.

**Comment by koic** [comment]
Thanks!
