### PR TITLE
[Fix #11704] Fix a false positive for `Lint/UselessMethodDefinition`

### LINKED ISSUE #11704: Lint/UselessMethodDefinition false positive on methods transformed by class method
## Expected behavior

The following code should not get picked up / auto-corrected by the `UselessMethodDefinition` cop:
```ruby
memoize def my_method
  super
end
```
(illustrated here in conjunction with [Memery](https://github.com/tycooon/memery), but this applies more generally)

## Actual behavior

The code gets auto-corrected to the following invalid code:

```ruby
memoize
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #11704.

This PR fixes a false positive for `Lint/UselessMethodDefinition` when method definition with non access modifier containing only `super` call.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/useless_method_definition.rb [hunk 1]
```diff
@@ -41,15 +41,23 @@ class UselessMethodDefinition < Base
...
+            range = node.parent&.send_type? ? node.parent : node
+
+            corrector.remove(range)
+          end
         end
         alias on_defs on_def
 
         private
 
+        def modifiered_method_definition?(node)
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/useless_method_definition.rb:57]: I'd go with "method_definition_with_modifier?" here.

File: spec/rubocop/cop/lint/useless_method_definition_spec.rb [hunk 2]
```diff
@@ -170,6 +214,14 @@ def method(x: 1)
     RUBY
   end
 
+  it 'does not register an offense when method definition with non access modifier containing only `super` call' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/useless_method_definition_spec.rb:217]: Technically speaking if it's not an access modifier we should probably call it should else - e.g. "generic method macro" or whatever. I'm not sure what's the best terminology here.

Comment (koic) [reply spec/rubocop/cop/lint/useless_method_definition_spec.rb]: I'm not sure the best terminology, but I think "generic method macro" is definitely a better name. Thank you for the suggestion! I've updated this PR.
