### PR TITLE
[Fix #12758] Fix false positives for `Layout/RedundantLineBreak`

### LINKED ISSUE #12758: Invalid offense/autocorrect for `Style/RedundantLineContinuation`
## Expected behavior

Not to flag the `Style/RedundantLineContinuation` offense.

## Actual behavior

Offense is flagged and incorrectly autocorrected.

### Input:
```
return unless params[:filter].present? && params[:show_inactive].present? \
  && params[:show_inactive] == 'true'
```

### Is flagged as:
```
app/controllers/api/v1/organizations_controller.rb:401:83: C: [Correctable] Style/RedundantLineContinuation: Redundant line continuation.
        return unless params[:filter].present? && params[:show_inactive].present? \ ...
```

### Autocorrects to:
```
return unless params[:filter].present? && params[:show_inactive].present?
  && params[:show_inactive] == 'true'
```

### Then produces:
```
app/controllers/api/v1/organizations_controller.rb:402:11: F: Lint/Syntax: unexpected token tAMPER
(Using Ruby 3.3 parser; configure using TargetRubyVersion parameter, under AllCops)
          && params[:show_inactive] == 'true'
          ^
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.62.0 (using Parser 3.3.0.5, rubocop-ast 1.31.1, running on ruby 3.3.0) [arm64-darwin23]
  - rubocop-rails 2.24.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12758.

This PR fixes false positives for `Layout/RedundantLineBreak` when using `&&` or `||` after a backslash newline.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/redundant_line_break_spec.rb [hunk 1]
```diff
@@ -172,6 +172,37 @@
...
+      end
+
+      it 'does not register an offense when using `&&` after a backslash newline' do
+        expect_no_offenses(<<~RUBY)
+          foo \\
+            && bar
+        RUBY
+      end
+
+      it 'registers an offense when using `||` before a backslash newline' do
```
Comment (bbatsov) [inline spec/rubocop/cop/layout/redundant_line_break_spec.rb:194]: Seems to me you're missing the "after" test case here. (you have 2 for `&&` and just 1 for `||`)

Comment (koic) [reply spec/rubocop/cop/layout/redundant_line_break_spec.rb:194]: Oops! I've added the missing test.

**Comment by bbatsov** [comment]
Thanks!
