### PR TITLE
[Fix #13453] Update `Style/AccessModifierDeclarations` to handle `attr_*` methods with multiple parameters

### LINKED ISSUE #13453: Style/AccessModifierDeclarations does not recognize AllowModifiersOnAttrs/Symbols
The Style/AccessModifierDeclarations cop seems to be borked.

This issue seem to exist for longer than the last half dozen or so releases. I have checked against RuboCop 1.68.0,  1.67.0, 1.65.0, and 1.0.0.

Given Ruby 3.2, RuboCop 1.68.0 and these files:

<details><summary><code>Gemfile</code></summary>

```rb
source "https://rubygems.org"

gem "rubocop"
```

</details>
<details><summary><code>Gemfile.lock</code></summary>

```
GEM
  remote: https://rubygems.org/
  specs:
    ast (2.4.2)
    json (2.8.1)
    language_server-protocol (3.17.0.3)
    parallel (1.26.3)
    parser (3.3.6.0)
      ast (~> 2.4.1)
      racc
    racc (1.8.1)
    rainbow (3.1.1)
    regexp_parser (2.9.2)
    rubocop (1.68.0)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.3.0.2)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 2.4, < 3.0)
      rubocop-ast (>= 1.32.2, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.35.0)
      parser (>= 3.3.1.0)
    ruby-progressbar (1.13.0)
    unicode-display_width (2.6.0)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  rubocop

BUNDLED WITH
   2.5.23
```

</details>
<details open><summary><code>test.rb</code></summary>

```rb
class TestAttr
  private attr_reader :foo, :bar
end

class TestSymbol
  private :x, :y
end

class TestBoth
  private attr_reader :foo, :bar
  private :x, :y
end
```

</details>

--------

## Expected behavior

Using the default configuration (i.e. `AllowModifiersOnAttrs: true` and `AllowModifiersOnSymbols: true`), the `test.rb` should not have any `Style/AccessModifierDeclarations` violations.

## Actual behavior

<details open><summary>Output</summary>

```console
$ bundle exec rubocop --debug --only Style/AccessModifierDeclarations test.rb
For /tmp/tmp.zjwOJJC1eK: Default configuration from /tmp/tmp.zjwOJJC1eK/.gems/3.2/gems/rubocop-1.68.0/config/default.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /tmp/tmp.zjwOJJC1eK/test.rb
C

Offenses:

test.rb:2:3: C: [Correctable] Style/AccessModifierDeclarations: private should not be inlined in method definitions.
  private attr_reader :foo, :bar
  ^^^^^^^
test.rb:6:3: C: [Correctable] Style/AccessModifierDeclarations: private should not be inlined in method definitions.
  private :x, :y
  ^^^^^^^
test.rb:11:3: C: [Correctable] Style/AccessModifierDeclarations: private should not be inlined in method definitions.
  private :x, :y
  ^^^^^^^

1 file inspected, 3 offenses detected, 3 offenses autocorrectable
Finished in 0.04921097400074359 seconds
```

Interestingly, in `TestBoth`, the `private attr_reader ...` line is fine.

## Steps to reproduce the problem

- Install RuboCop 1.68.0
- Copy the `test.rb` from above to disk
- Run `rubocop --only Style/AccessModifierDeclarations test.rb`

## RuboCop version

```
$ bundle exec rubocop -V
1.68.0 (using Parser 3.3.6.0, rubocop-ast 1.35.0, analyzing as Ruby 3.2, running on ruby 3.2.5) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by dvandersluis**
Similarly to #13404, update `Style/AccessModifierDeclarations` to handle attr methods with multiple parameters.

The autocorrect fix in #13443 does not affect attrs, so this PR handles autocorrect as well.  

Fixes #13453.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cli/autocorrect_spec.rb [hunk 1]
```diff
@@ -3320,6 +3320,40 @@ def foo; end
       RUBY
     end
 
+    it 'corrects when the first is a attr list' do
```
Comment (bbatsov) [inline spec/rubocop/cli/autocorrect_spec.rb:3323]: an attr list

File: spec/rubocop/cli/autocorrect_spec.rb [hunk 2]
```diff
@@ -3354,6 +3388,40 @@ def foo; end
       RUBY
     end
 
+    it 'corrects when the second is a attr list' do
```
Comment (bbatsov) [inline spec/rubocop/cli/autocorrect_spec.rb:3391]: ditto

File: spec/rubocop/cli/autocorrect_spec.rb (hunk 1 above)
Comment (dvandersluis) [reply spec/rubocop/cli/autocorrect_spec.rb]: Thanks! I've updated both of these now.
