### PR TITLE
[Fix #9939] Fix/hash as last array item

### LINKED ISSUE #9939: `Style/TrailingCommaInArrayLiteral` vs `Style/HashAsLastArrayItem`
Code:
```ruby
x = [
  1,
  {
    a: 1,
    b: 2,
  },
]
```
`.rubocop.yml`:
```yml
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces
```

Run `rubocop -a`

## Expected behavior

```ruby
x = [
  1,
  a: 1,
  b: 2,
]
```

## Actual behavior

```ruby
x = [
  1,
  
    a: 1,
    b: 2,
  ,
]
```
(Note the two commas at the end. The rest of the formatting is **not** what I am reporting)

## RuboCop version

```
$ rubocop -V
1.18.3 (using Parser 3.0.1.1, rubocop-ast 1.7.0, running on ruby 2.7.3 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by martinjaimem**
**Fix autocorrect bug with HashAsLastArrayItem**

Fixes #9939 

When running autocorrect with:
```
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces
```

there was an edge case where it created incorrect code:

before autocorrect
```
x = [
  1,
  {
    a: 1,
    b: 2,
  },
]
```

after autocorrect:
```
x = [
  1,
  
    a: 1,
    b: 2,
  ,
]
```

With this PR, the result of applying autocorrect makes executable code =>
```
x = [
  1,
  
    a: 1,
    b: 2,

]
```

## Notes:
 - The PR contains commits that are not squashed, that's because I specifically wanted to receive feedback before and ***then I can squash the two commits*** (this way I can show the two approaches)
  - The first commit represents the original approach that only corrected the code within the node, it worked fine with a one-line array but generated the wrong code with multi-line arrays. Maybe it was okay to leave it that way but It was better to mark it as unsafe, some feedback would be awesome.
  - The second commit corrects the code within the node and its parent (I don't know if that's a good practice, I'm really open to some feedback)
 

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [ ] Wrote [good commit messages][1].
* [ ] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed-related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/hash_as_last_array_item_spec.rb [hunk 1]
```diff
@@ -54,6 +54,42 @@
...
+      expect_offense(<<~RUBY)
+        [
+          1,
+          2,
+          {
+          ^ Omit the braces around the hash.
+            one: 1,
+            two: 2,
+          },
+        ]
```
Comment (thearjunmdas) [inline spec/rubocop/cop/style/hash_as_last_array_item_spec.rb:78]: Should there be a testcase for this scenario as well?
```ruby 
 [
    1,
    2,
    {
      one: 1,
      two: 2,
    },
    3,
    4
]
```
p.s I am not an official maintainer. Randomly came across your PR so I thought I could take a look to understand the codebase better..

Comment (martinjaimem) [reply spec/rubocop/cop/style/hash_as_last_array_item_spec.rb:78]: I added that scenario 👍 good call

**Comment by bbatsov** [comment]
The proposed fix looks good to me. Thanks!
