### PR TITLE
[Fix #13839] Fix false positives for `Lint/RedundantTypeConversion`

### LINKED ISSUE #13839: Lint/RedundantTypeConversion: false positives on Hash#to_h when a block is given
## Expected behavior

```ruby
{a: 1, b: 2}.to_h { |k, v| [k.to_s, v.to_s] }
```
```
$ bundler exec rubocop rubocop/to-h.rb
Inspecting 1 file
E

Offenses:

rubocop/to-h.rb:1:1: C: Naming/FileName: The name of this source file (to-h.rb) should use snake_case.
rubocop/to-h.rb:1:1: C: [Correctable] Style/FrozenStringLiteralComment: Missing frozen string literal comment.
{a: 1, b: 2}.to_h { |k, v| [k.to_s, v.to_s] }
^
rubocop/to-h.rb:1:14: E: [Correctable] Lint/RedundantTypeConversion: Redundant to_h detected.
{a: 1, b: 2}.to_h { |k, v| [k.to_s, v.to_s] }
             ^^^^

1 file inspected, 3 offenses detected, 2 offenses autocorrectable
```

This call to `to_h` is not redundant, it should not complain.

## Actual behavior

It does complain.

## Steps to reproduce the problem

See above.

## RuboCop version

```
$ bundler exec rubocop -V
1.72.0 (using Parser 3.3.7.1, rubocop-ast 1.38.0, analyzing as Ruby 3.3, running on ruby 3.3.7) [arm64-darwin24]
  - rubocop-minitest 0.36.0
  - rubocop-performance 1.23.1
```

Cheers!

### PR DESCRIPTION
**Pull request by koic**
This PR fixes false positives for `Lint/RedundantTypeConversion` when passing block arguments when generating a Hash or a Set.

Fixes #13839.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/redundant_type_conversion_spec.rb [hunk 1]
```diff
@@ -285,6 +285,10 @@
     it_behaves_like 'offense', :to_h, '::Kernel::Hash({ foo: bar })'
     it_behaves_like 'offense', :to_h, 'Hash[foo: bar]'
     it_behaves_like 'offense', :to_h, '::Hash[foo: bar]'
+
+    it_behaves_like 'accepted', 'Hash.new(hash).to_h { |k, v| [foo(k), bar(v)] }'
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/redundant_type_conversion_spec.rb:289]: Passing a hash to `Hash.new` doesn't seem like a very realistic example. I'd probably just use a literal instead.

File: spec/rubocop/cop/lint/redundant_type_conversion_spec.rb [hunk 2]
```diff
@@ -294,5 +298,9 @@
     it_behaves_like 'offense', :to_set, '::Set.new([1, 2, 3])'
     it_behaves_like 'offense', :to_set, 'Set[1, 2, 3]'
     it_behaves_like 'offense', :to_set, '::Set[1, 2, 3]'
+
+    it_behaves_like 'accepted', 'Set.new(set).to_set { |item| foo(item) }'
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/redundant_type_conversion_spec.rb:302]: Same here.

File: spec/rubocop/cop/lint/redundant_type_conversion_spec.rb (hunk 1 above)
Comment (koic) [reply spec/rubocop/cop/lint/redundant_type_conversion_spec.rb]: I've updated this example to use hash literal.

File: spec/rubocop/cop/lint/redundant_type_conversion_spec.rb (hunk 2 above)
Comment (koic) [reply spec/rubocop/cop/lint/redundant_type_conversion_spec.rb]: Since `Set` doesn't have a literal syntax, it has been replaced with `Set[...]`, which is the closest in meaning, to match the existing example.
