### PR TITLE
[Fix #10297] Fix a false positive for `Lint/DeprecatedOpenSSLConstant`

### LINKED ISSUE #10297: Autocorrect of Lint/DeprecatedOpenSSLConstant breaks code
(thanks again for a great tool!)

These variants are wrong but equivalent...
```ruby
OpenSSL::Digest.new('SHA1') # reasonable
OpenSSL::Digest::Digest.new('SHA1') # <-- this line is going to break
OpenSSL::Digest::Digest::Digest.new('SHA1') # WAT
```

## Expected behavior

Describe here how you expected RuboCop to behave in this particular situation.

```ruby
OpenSSL::Digest.new('SHA1') # reasonable
OpenSSL::Digest.new('SHA1') # <-- this line is going to break
OpenSSL::Digest.new('SHA1') # WAT
```

## Actual behavior

```ruby
OpenSSL::Digest.new('SHA1') # reasonable
OpenSSL::Digest.new('Digest', 'SHA1') # <-- this line is going to break
OpenSSL::Digest::Digest::Digest.new('SHA1') # WAT
```

note the second line is now invalid

## Steps to reproduce the problem
rubocop -a

## RuboCop version

```sh
1.23.0 (using Parser 3.0.3.2, rubocop-ast 1.14.0, running on ruby 2.7.5 x86_64-darwin21)
  - rubocop-performance 1.12.0
  - rubocop-rails 2.12.4
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.6.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #10297.

This PR fixes a false positive for `Lint/DeprecatedOpenSSLConstant` when building digest using an algorithm string and nested digest constants.

It aims to prevent the false positive. I may open a separated PR for another cop about detection of redundant constants.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb [hunk 1]
```diff
@@ -161,6 +161,12 @@
     RUBY
   end
 
+  it 'does not register an offense when building digest using an algorithm string and nested digest constants' do
+    expect_no_offenses(<<~RUBY)
+      OpenSSL::Digest::Digest.new('SHA256')
```
Comment (michaelglass) [inline spec/rubocop/cop/lint/deprecated_open_ssl_constant_spec.rb:166]: 🤘
