### PR TITLE
[Fix #13849] Fix an error for `Lint/UselessConstantScoping`

### LINKED ISSUE #13849: Lint/UselessConstantScoping raises undefined method 'send_type?' for Symbol in RuboCop 1.72.1
Rubocop is raising an error after the release of 1.72.1 for my application

## Expected behavior

RuboCop should analyze `config/application.rb` without raising an error. The `Lint/UselessConstantScoping` cop should correctly process all constants in the file without encountering an undefined method error.

## Actual behavior

Running RuboCop on `config/application.rb` produces the following error:

```
undefined method `send_type?' for an instance of Symbol
/Users/kyle/.rbenv/versions/3.3.7/lib/ruby/gems/3.3.0/gems/rubocop-1.72.1/lib/rubocop/cop/lint/useless_constant_scoping.rb:59:in `select'
```

The error is triggered by `Lint/UselessConstantScoping` when inspecting a constant assignment in `config/application.rb:33:19`. This suggests that RuboCop is incorrectly assuming that the node responds to `send_type?`, which is not the case for a `Symbol`.

## Steps to reproduce the problem

1. Ensure RuboCop 1.72.1 is installed.
2. Run the following command in a Ruby 3.3.7 environment:

   ```sh
   bundle exec rubocop -d ./config/application.rb
   ```

The offending section is `ENV['RAILS_ENV'] = RAILS_ENV = Rails.env.to_s`

3. Observe the error message related to `Lint/UselessConstantScoping`.

## RuboCop version
```
❯ bundle exec rubocop -V
1.72.1 (using Parser 3.3.7.1, rubocop-ast 1.38.0, analyzing as Ruby 3.3, running on ruby 3.3.7) +server [x86_64-darwin24]
  - rubocop-capybara 2.21.0
  - rubocop-performance 1.24.0
  - rubocop-rails 2.30.0
  - rubocop-rspec 3.5.0
```

### PR DESCRIPTION
**Pull request by koic**
This PR fixes an error for `Lint/UselessConstantScoping` hen multiple assigning to constants after `private` access modifier.

Fixes #13849.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/useless_constant_scoping.rb [hunk 1]
```diff
@@ -56,7 +56,11 @@ def on_casgn(node)
         private
 
         def after_private_modifier?(left_siblings)
-          left_siblings.compact.select(&:send_type?).any? { |node| node.command?(:private) }
+          access_modifier_candidates = left_siblings.compact.select do |left_sibling|
+            left_sibling.respond_to?(:send_type?) && left_sibling.send_type?
```
Comment (vlad-pisanov) [inline lib/rubocop/cop/lint/useless_constant_scoping.rb:60]: This fixes the exception, but it still ends up with a false negative for case reported in the issue:

```ruby
class Foo
  private
  ENV['RAILS_ENV'] = RAILS_ENV = Rails.env.to_s
end
```
(this won't flag an offense since the left siblings of the `RAILS_ENV` assignment node don't contain the `private` modifier). I think to detect the `private` modifier, you'd have to walk up the tree while the parent is an `assignment?` node and then check _its_ left siblings.

**Comment by bbatsov** [comment]
@koic You'll to rebase this PR. Looks good to me overall.

File: lib/rubocop/cop/lint/useless_constant_scoping.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/cop/lint/useless_constant_scoping.rb:60]: I see. Whether this corner use case should be registered as an offense is a bit debatable. For now, this PR focuses on resolving the error, and I will handle this issue separately. Thank you for the feedback.

**Comment by koic** [comment]
@bbatsov Yeah, I rebased this PR.
