### PR TITLE
[Fix #12852] Correctly deserialize a global offense

### LINKED ISSUE #12852: Crash with some formatters in v1.63.2
After upgrading to v1.63.2 from 1.62.1 I found that the default formatter resulted in a crash:

```
...
142 files inspected, 135 offenses detected, 105 offenses autocorrectable
index 0 outside of array bounds: 0...0
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/parser-3.3.0.5/lib/parser/source/buffer.rb:274:in `fetch'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/parser-3.3.0.5/lib/parser/source/buffer.rb:274:in `source_line'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/parser-3.3.0.5/lib/parser/source/range.rb:126:in `source_line'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/formatter/clang_style_formatter.rb:34:in `valid_line?'
...
```

I went through all the [documented formatters](https://docs.rubocop.org/rubocop/1.63/formatters.html) and found the following results:

```
| formatter   | crash? |
|-------------+--------|
| autogenconf | no     |
| clang       | yes    |
| emacs       | no     |
| files       | no     |
| fuubar      | yes    |
| github      | no     |
| html        | yes    |
| json        | no     |
| junit       | no     |
| markdown    | yes    |
| offenses    | no     |
| pacman      | yes    |
| progress    | yes    |
| quiet       | no     |
| simple      | no     |
| tap         | yes    |
| worst       | no     |
```

I then spot checked `clang` and `markdown` in previous versions. I found that `clang` started failing in 1.63.1 while `markdown` was failing since at least 1.62.1

## Expected behavior

I expect rubocop not to crash when using some formatters.

## Actual behavior

(not including `--debug` output here as the file is 2.1Mb... but I can provide that data if needed)

Rubocop will run and report errors for a while and then crash with an error:  `index 0 outside of array bounds: 0...0` and a stack trace:

```
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/parser-3.3.0.5/lib/parser/source/buffer.rb:274:in `fetch'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/parser-3.3.0.5/lib/parser/source/buffer.rb:274:in `source_line'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/parser-3.3.0.5/lib/parser/source/range.rb:126:in `source_line'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/formatter/clang_style_formatter.rb:34:in `valid_line?'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/formatter/clang_style_formatter.rb:27:in `report_offense'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/formatter/clang_style_formatter.rb:12:in `block in report_file'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/formatter/clang_style_formatter.rb:12:in `each'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/formatter/clang_style_formatter.rb:12:in `report_file'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/formatter/simple_text_formatter.rb:33:in `file_finished'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/formatter/formatter_set.rb:51:in `block in file_finished'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/formatter/formatter_set.rb:51:in `each'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/formatter/formatter_set.rb:51:in `file_finished'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/runner.rb:250:in `file_finished'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/runner.rb:162:in `process_file'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/runner.rb:138:in `block in each_inspected_file'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/runner.rb:137:in `each'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/runner.rb:137:in `reduce'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/runner.rb:137:in `each_inspected_file'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/runner.rb:123:in `inspect_files'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/runner.rb:76:in `run'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli/command.rb:11:in `run'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli/environment.rb:18:in `run'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli.rb:118:in `run_command'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli.rb:125:in `execute_runners'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli.rb:51:in `block in run'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli.rb:77:in `profile_if_needed'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/lib/rubocop/cli.rb:43:in `run'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/exe/rubocop:19:in `block in <top (required)>'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/rubocop-1.63.2/exe/rubocop:19:in `<top (required)>'
/Users/mark/.rbenv/versions/3.1.3/bin/rubocop:25:in `load'
/Users/mark/.rbenv/versions/3.1.3/bin/rubocop:25:in `<top (required)>'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/cli.rb:486:in `exec'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:48:in `block in <top (required)>'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/3.1.0/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/Users/mark/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/bundler-2.3.26/libexec/bundle:36:in `<top (required)>'
/Users/mark/.rbenv/versions/3.1.3/bin/bundle:25:in `load'
/Users/mark/.rbenv/versions/3.1.3/bin/bundle:25:in `<main>'
```

Most of the tested formatters that failed did have this failure coming from `clang_style_formatter` but markdown and html have failures starting in their formatters.

## Steps to reproduce the problem

I am unsure which rule is triggering the failure but it seems that most commonly the error seen just before the crash is: `Lint/EmptyFile: Empty file detected.`

## RuboCop version

```
> bundle exec rubocop -V
1.63.2 (using Parser 3.3.0.5, rubocop-ast 1.31.2, running on ruby 3.1.3) [arm64-darwin22]
  - rubocop-capybara 2.20.0
  - rubocop-factory_bot 2.25.1
  - rubocop-rails 2.24.1
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.29.1
```

### PR DESCRIPTION
**Pull request by Earlopain**
Closes #12852.

A global offense goes into the cache but a range comes out. This results in errors when trying to display this range because begin/end at 0 is not valid. The global offense structure handles this, which is why only the second run will fail.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by verdammelt** [comment]
I have tested this change in the scenario reported in #12852 and it appears to correct that issue.

File: lib/rubocop/cached_data.rb [hunk 1]
```diff
@@ -48,10 +48,18 @@ def deserialize_offenses(offenses)
       source_buffer = Parser::Source::Buffer.new(@filename)
       source_buffer.source = File.read(@filename, encoding: Encoding::UTF_8)
       offenses.map! do |o|
-        location = Parser::Source::Range.new(source_buffer,
-                                             o['location']['begin_pos'],
-                                             o['location']['end_pos'])
-        Cop::Offense.new(o['severity'], location, o['message'], o['cop_name'], o['status'].to_sym)
+        range = offense_from_cache(o, source_buffer)
+        Cop::Offense.new(o['severity'], range, o['message'], o['cop_name'], o['status'].to_sym)
```
Comment (koic) [inline lib/rubocop/cached_data.rb:52]: Can you rename to the following?

```suggestion
        location = location_from_source_buffer(o, source_buffer)
        Cop::Offense.new(o['severity'], location, o['message'], o['cop_name'], o['status'].to_sym)
```

File: lib/rubocop/cached_data.rb [hunk 2]
```diff
@@ -48,10 +48,18 @@ def deserialize_offenses(offenses)
...
+      end
+    end
+
+    def offense_from_cache(entry, source_buffer)
+      begin_pos = entry['location']['begin_pos']
+      end_pos = entry['location']['end_pos']
```
Comment (koic) [inline lib/rubocop/cached_data.rb:58]:
```suggestion
    def location_from_source_buffer(offense, source_buffer)
      begin_pos = offense['location']['begin_pos']
      end_pos = offense['location']['end_pos']
```

File: spec/rubocop/result_cache_spec.rb [hunk 3]
```diff
@@ -113,6 +113,19 @@ def abs(path)
...
+        let(:location) { RuboCop::Cop::Offense::NO_LOCATION }
+        let(:offense) do
+          RuboCop::Cop::Offense.new(:warning, location, 'empty file', 'Lint/EmptyFile',
+                                    :unsupported)
+        end
+
+        it 'serializes the range correctly' do
+          cache.save([offense])
+          expect(cache.load[0].location).to eq(location)
+        end
```
Comment (koic) [inline spec/rubocop/result_cache_spec.rb:127]: It seems that the following names could further clarify the intention:

```suggestion
        let(:no_location) { RuboCop::Cop::Offense::NO_LOCATION }
        let(:global_offense) do
          RuboCop::Cop::Offense.new(:warning, no_location, 'empty file', 'Lint/EmptyFile',
                                    :unsupported)
        end

        it 'serializes the range correctly' do
          cache.save([global_offense])
          expect(cache.load[0].location).to eq(no_location)
        end
```

**Comment by Earlopain** [comment]
Thanks for the review. Looks like CodeClimate is having some issues at the moment:
> '/tmp/cc-test-reporter: line 2: `<head><title>504 Gateway Time-out</title></head>

**Comment by koic** [comment]
I'm not sure of the cause, but something might have happened on the server side of cc-test-reporter. I've opened https://github.com/codeclimate/test-reporter/issues/520. I will merge this PR. Thank you.
