### PR TITLE
[Fix #13320] Fix incorrect autocorrect when `Layout/LineContinuationLeadingSpace` and `Style/StringLiterals` autocorrects in the same pass

### LINKED ISSUE #13320: `Layout/LineContinuationLeadingSpace` has a autofix logic error
## Expected behavior

Describe here how you expected RuboCop to behave in this particular situation.

_Nothing_ - string-splitting is "well defined" at the `\n`, or

```ruby
eq(
  "    0:    1    2    3    4         5    6    7    8      \n    " \
  "8:    9   10   11   12        13   14   15   16      \n   " \
  '16:   17   18   19   20',
)
```

I would also **not force** changing the quotes here. "It doesn't look as pretty here".

## Actual behavior

Describe here what actually happened.
Please use `rubocop --debug` when pasting rubocop output as it contains additional information.

```ruby
eq(
  "    0:    1    2    3    4         5    6    7    8      \n    " \
  "8:    9   10   11   12        13   14   15   16      \n      " \
  '16:   17   18   19   20',
)
```

## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

```ruby
eq(
  "    0:    1    2    3    4         5    6    7    8      \n"\
  "    8:    9   10   11   12        13   14   15   16      \n"\
  "   16:   17   18   19   20"
)
```

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ [bundle exec] rubocop -V
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, analyzing as Ruby 3.3, running on ruby 3.3.5) [x86_64-linux]
  - rubocop-performance 1.22.1
  - rubocop-rspec 3.1.0
```

### PR DESCRIPTION
**Pull request by dvandersluis**
When both cops are activated and run in the same iteration of the correction loop, `Style/StringLiterals` undoes the moving of spaces that `Layout/LineContinuationLeadingSpace` performs. This is because `StringLiterals` takes the original string content and transforms it, rather than just modifying the delimiters, in order to handle escaping for quotes within the string.

By marking `Style/StringLiterals` as incompatible with `Layout/LineContinuationLeadingSpace`, it allows the correction to be deferred to the next inspection loop, thereby avoiding the problem.

Fixes #13320.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by dvandersluis** [comment]
Trying to figure out why this is failing on Windows. For some reason it doesn't detect any `Layout/LineContinuationLeadingSpace` offenses in the test. 🤔

**Comment by dvandersluis** [comment]
The Windows failure are due to `create_file` writing files with `'w'` mode, which automatically converts line terminators to the native style. On windows, that's `CRLF`. `Layout/LineContinuationLeadingSpace` is not set up properly to detect continuations when there's a `\r\n` instead of an `n`.

I updated `create_file` to allow it to force line endings to be retained by using `'wb'` mode instead. We cannot do this across the board because it will cause a lot of `Layout/EndOfLine` failures in other tests, so I made it opt-in.

As a separate PR I am going to look at fixing `Layout/LineContinuationLeadingSpace` for CRLF line terminators.

**Comment by koic** [comment]
There is an issue with the committed code https://github.com/rubocop/rubocop/pull/13539/commits/892612b9f85035578a9eb4ddf22422ef0b355c47, which should pass local tests independently, does not. There might be a problem with the procedure for fixing the offense message.

**Comment by dvandersluis** [comment]
@koic thanks. I had updated the messages in the wrong commit, it's fixed now.

**Review by bbatsov — APPROVED** [review]

File: lib/rubocop/cop/layout/line_continuation_leading_space.rb [hunk 1]
```diff
@@ -51,6 +51,10 @@ class LineContinuationLeadingSpace < Base
         private_constant :LINE_1_ENDING, :LINE_2_BEGINNING,
                          :LEADING_STYLE_OFFENSE, :TRAILING_STYLE_OFFENSE
 
+        def self.autocorrect_incompatible_with
```
Comment (bbatsov) [inline lib/rubocop/cop/layout/line_continuation_leading_space.rb:54]: You might want to add this as a comment here:

> When both cops are activated and run in the same iteration of the correction loop, Style/StringLiterals undoes the moving of spaces that Layout/LineContinuationLeadingSpace performs. This is because StringLiterals takes the original string content and transforms it, rather than just modifying the delimiters, in order to handle escaping for quotes within the string.

Comment (dvandersluis) [reply lib/rubocop/cop/layout/line_continuation_leading_space.rb:59]: @bbatsov added the comment, thanks!
