### PR TITLE
[Fix #11237] Fix `Layout/CommentIndentation` comment aligned with acc…

### LINKED ISSUE #11237: `AccessModifierIndentation` and `CommentIndentation` does not work well together
`# rubocop: enable` and `# rubocop:disable` may wrap whole method definition.
In such case, indentation should be based on wrapped method.

--------

## Expected behavior

No offenses.

## Actual behavior

Having one offense.
We cannot suppress offense as long as comment is followed by access modifier.

```
rubocop -c test.rubocop.yml foo.rb
Inspecting 1 file
C

Offenses:

foo.rb:5:3: C: [Correctable] Layout/CommentIndentation: Incorrect indentation detected (column 2 instead of 0).
  # rubocop:enable
  ^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense autocorrectable
```

## Steps to reproduce the problem

Lint following file with the setting below:

foo.rb
```ruby
class A
  # rubocop:disable
  def foo
  end
  # rubocop:enable

private

  def bar
  end
end
```

test.rubocop.yml
```yml
AllCops:
  DisabledByDefault: true

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: outdent

Layout/CommentIndentation:
  Enabled: true
```

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
1.39.0 (using Parser 3.1.3.0, rubocop-ast 1.24.0, running on ruby 2.7.6) [x86_64-darwin21]
  - rubocop-rails 2.15.1
  - rubocop-rspec 2.11.1
```

### PR DESCRIPTION
**Pull request by soroktree**
[Fixed #11237] 

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/comment_indentation.rb [hunk 1]
```diff
@@ -154,7 +154,9 @@ def correct_indentation(next_line)
         end
 
         def less_indented?(line)
-          /^\s*(end\b|[)}\]])/.match?(line)
+          rule = config.for_cop('Layout/AccessModifierIndentation')['EnforcedStyle'] == 'outdent'
+          access_modifier = 'private|protected|public'
+          /^\s*(end\b|[)}\]])/.match?(line) || (rule && /^\s*(#{access_modifier})\b/.match?(line))
```
Comment (koic) [inline lib/rubocop/cop/layout/comment_indentation.rb:159]: Can you tweak it?

```suggestion
          /\A\s*(end\b|[)}\]])/.match?(line) || (rule && /\A\s*(#{access_modifier})\b/.match?(line))
```

**Comment by koic** [comment]
Can you add a changelog entry?

> Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named {change_type}_{change_description}.md if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

**Comment by koic** [comment]
This looks good to me. Can you squash your commits into one?

**Comment by soroktree** [comment]
done. thanks for quick review

File: lib/rubocop/cop/layout/comment_indentation.rb [hunk 2]
```diff
@@ -154,7 +154,9 @@ def correct_indentation(next_line)
         end
 
         def less_indented?(line)
-          /^\s*(end\b|[)}\]])/.match?(line)
+          rule = config.for_cop('Layout/AccessModifierIndentation')['EnforcedStyle'] == 'outdent'
+          access_modifier = 'private|protected|public'
+          /\A\s*(end\b|[)}\]])/.match?(line) || (rule && /\A\s*(#{access_modifier})\b/.match?(line))
```
Comment (fatkodima) [inline lib/rubocop/cop/layout/comment_indentation.rb:159]: I would suggest to extract `/\A\s*(#{access_modifier})\b/` into a constant or inline `access_modifier` into it, because this method call will always generate unnecessary allocations (needs measuring to know the impact).

File: spec/rubocop/cop/layout/comment_indentation_spec.rb [hunk 3]
```diff
@@ -292,4 +292,55 @@ def compile_sequence(seq, seq_var)
       RUBY
     end
   end
+
+  context 'when `Layout/AccessModifierIndentation EnforcedStyle: outdent`' do
+    let(:allow_for_alignment) { true }
+    let(:indentation_width) { 2 }
```
Comment (fatkodima) [inline spec/rubocop/cop/layout/comment_indentation_spec.rb:298]: I would suggest removing this line (and from the top of the file) and inlining its value into the call, because it is never changed in the test file.

File: spec/rubocop/cop/layout/comment_indentation_spec.rb [hunk 4]
```diff
@@ -292,4 +292,55 @@ def compile_sequence(seq, seq_var)
       RUBY
     end
   end
+
+  context 'when `Layout/AccessModifierIndentation EnforcedStyle: outdent`' do
+    let(:allow_for_alignment) { true }
```
Comment (fatkodima) [inline spec/rubocop/cop/layout/comment_indentation_spec.rb:297]: Looks like this is not needed, because you redefine `config` in this block (the single place where it was used).
