### PR TITLE
[Fix #11758] Fix a false positive for `Style/RedundantLineContinuation`

### LINKED ISSUE #11758: Style/RedundantLineContinuation should not look inside strings
When the trailing backslash is inside a string literal, I think it needs to be disregarded by the Style/RedundantLineContinuation cop.

--------

## Expected behavior

I expect these two spec examples to pass in spec/rubocop/cop/style/redundant_line_continuation_spec.rb:

```rb
expect_no_offenses(<<~'RUBY')
  "foo \
    bar"
RUBY

expect_no_offenses(<<~'RUBY')
  'foo \
    bar'
RUBY
```

## Actual behavior

The spec examples fail, suggesting to remove the trailing backslash.

## Steps to reproduce the problem

See above.

## RuboCop version

7c35167233e567cd0bad3879974de787b3c372bd

### PR DESCRIPTION
**Pull request by koic**
Fixes #11758.

This PR fixes a false positive for `Style/RedundantLineContinuation` when line continuations for string.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/redundant_line_continuation_spec.rb [hunk 1]
```diff
@@ -134,6 +134,20 @@ def self.foo(bar,#{trailing_whitespace}
     RUBY
   end
 
+  it 'does not register an offense when line continuations for double quoted string' do
+    expect_no_offenses(<<~'RUBY')
+      "foo \
+        bar"
```
Comment (bquorning) [inline spec/rubocop/cop/style/redundant_line_continuation_spec.rb:140]: The following code causes the spec to fail.
```suggestion
      a = "foo \
            bar"
```

Comment (koic) [reply spec/rubocop/cop/style/redundant_line_continuation_spec.rb]: Oops, I overlooked this case. I've fixed it and updated this PR.

File: lib/rubocop/cop/style/redundant_line_continuation.rb [hunk 2]
```diff
@@ -87,16 +88,20 @@ def on_new_investigation
...
         def ends_with_backslash_without_comment?(source_line)
           source_line.gsub(/#.+/, '').end_with?('\\')
         end
 
-        def string_concatenation?(source_line)
-          /["']\s*\\\z/.match?(source_line)
+        def string_concatenation?(range)
+          return true if /.*["']\s*\\\z/.match?(range.source_line)
+
+          processed_source.each_token.any? do |token|
```
Comment (bquorning) [inline lib/rubocop/cop/style/redundant_line_continuation.rb:102]: `#each_token` is deprecated: https://github.com/rubocop/rubocop-ast/blob/14844626f0c6f87aef0e74198769537b40b21b7b/lib/rubocop/ast/processed_source.rb#L88-L91
```suggestion
          processed_source.tokens.each.any? do |token|
```

File: lib/rubocop/cop/style/redundant_line_continuation.rb [hunk 3]
```diff
@@ -87,16 +88,20 @@ def on_new_investigation
...
+            ALLOWED_STRING_TOKENS.include?(token.type) && token.pos.overlaps?(range)
+          end
```
Comment (bquorning) [inline lib/rubocop/cop/style/redundant_line_continuation.rb:104]: This loop looks _a bit_ slow (but I have not measured), and it doesn’t really belong inside `#string_concatenation?`. Should it perhaps be a separate method (e.g. `#inside_string_literal?`?) and called _last_ inside `#require_line_continuation?`?
```rb
          !ends_with_backslash_without_comment?(range.source_line) ||
            string_concatenation?(range.source_line) ||
            start_with_arithmetic_operator?(processed_source[range.line]) ||
            inside_string_literal?(range)
```

Comment (koic) [reply lib/rubocop/cop/style/redundant_line_continuation.rb:107]: This looks like good logic ❤️ Thank you for the suggestion!

**Comment by koic** [comment]
Hm, especially `#ends_with_backslash_without_comment?` may have some problem. Any other method would be preferable to the regexp. I think the issue can be clarified and dealt with separately.
