### PR TITLE
[Fix #14622] Fix an error for `Naming/MethodName` when the first argument to `alias` contains interpolation

### LINKED ISSUE #14622: `Naming/MethodName` crashes with `NoMethodError` on `alias` with string interpolation
## Steps to reproduce the problem

  Create a file with the following content:

```ruby
  class Example
    attr_reader :foo_value
    attr_reader :bar_value

    def initialize(foo_name: 'foo', bar_name: 'bar')
      @foo_name = foo_name
      @bar_name = bar_name
    end

    def example_method
      alias :"get_#{@foo_name}" :foo_value
      alias :"get_#{@bar_name}" :bar_value
    end
  end
```
  Run RuboCop

  bundle exec rubocop test.rb

#  Expected behavior

  RuboCop should either check the naming convention for alias
  declarations with interpolated symbols or skip them without
  crashing.

#  Actual behavior

  RuboCop crashes with a NoMethodError. Running with --debug shows:

  An error occurred while Naming/MethodName cop was inspecting
  test.rb:13:4.
  An error occurred while Naming/MethodName cop was inspecting
  test.rb:14:4.

  /path/to/rubocop-1.81.6/lib/rubocop/cop/naming/method_name.rb:150
  :in 'RuboCop::Cop::Naming::MethodName#on_alias':
  undefined method 'value' for an instance of RuboCop::AST::Node
  (NoMethodError)

  The on_alias method in lib/rubocop/cop/naming/method_name.rb:150
  attempts to call .value on node.new_identifier, but when the
  alias uses string interpolation (e.g., alias :"method_#{var}" 
  :original), the node is of type :dstr (dynamic string), which
  does not have a .value method. The .value method only exists on
  :str and :sym node types.

  RuboCop version

  $ bundle exec rubocop -V
  1.81.6 (using Parser 3.3.9.0, Prism 1.6.0, rubocop-ast 1.47.1,
  analyzing as Ruby 3.4, running on ruby 3.4.7) [x86_64-linux]
    - rubocop-minitest 0.38.2
    - rubocop-performance 1.26.1

### PR DESCRIPTION
**Pull request by Earlopain**
This is valid syntax. `alias_method` already handles this by explicitly only accepting sym/str arguments but there was no test

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/naming/method_name_spec.rb [hunk 1]
```diff
@@ -621,13 +621,25 @@ def self.fooBar
       RUBY
     end
 
+    it 'accepts `alias` with interpolated argument' do
```
Comment (koic) [inline spec/rubocop/cop/naming/method_name_spec.rb]: Nits:

```suggestion
    it 'accepts `alias` with interpolated symbol argument' do
```

File: spec/rubocop/cop/naming/method_name_spec.rb [hunk 2]
```diff
@@ -621,13 +621,25 @@ def self.fooBar
...
+    end
+
     it 'registers an offense for `alias_method` snake_case string argument' do
       expect_offense(<<~RUBY)
         alias_method "fooBar", "foo"
                      ^^^^^^^^ Use snake_case for method names.
       RUBY
     end
 
+    it 'accepts `alias_method` with interpolated argument' do
```
Comment (koic) [inline spec/rubocop/cop/naming/method_name_spec.rb]:
```suggestion
    it 'accepts `alias_method` with interpolated string argument' do
```

**Comment by koic** [comment]
Thanks!
