### PR TITLE
[Fix #11419] Fix a false positive for `Style/RedundantRequireStatement`

### LINKED ISSUE #11419: Removing 'require pp' is unsafe when using pretty_inspect (Lint/RedundantRequireStatement)
Lint/RedundantRequireStatement autocorrects `require "pp"` by removing it. As noted in [11099](https://github.com/rubocop/rubocop/issues/11099), `pp` is included in ruby, but using `pretty_inspect` still requires requiring `pp`, as [noted in a comment](https://github.com/ruby/ruby/blob/aeddc19340c7116d48fac3080553fbb823857d16/lib/pp.rb#L630-L639).

--------

## Expected behavior

RuboCop leaves `require "pp"` in place, at least in cases where pretty_inspect is used, or the cop is marked as unsafe overall.

## Actual behavior

RuboCop removes the require statement (and the autocorrect is treated as safe).

## Steps to reproduce the problem

* with a file `test_cop.rb`
```
require 'pp'
'string'.pretty_inspect
p "Success!"
```
* code runs before:
```
ruby test_cop.rb
"Success!"
```
* run rubocop autocorrect
```
rubocop -a test_cop.rb --only Lint/RedundantRequireStatement
Inspecting 1 file
W

Offenses:

test_cop.rb:1:1: W: [Corrected] Lint/RedundantRequireStatement: Remove unnecessary require statement.
require 'pp'
^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```
* resulting code produces a bug
```
ruby test_cop.rb                                            
test_cop.rb:2:in `<main>': undefined method `pretty_inspect' for "string":String (NoMethodError)

'string'.pretty_inspect
        ^^^^^^^^^^^^^^^
```

## RuboCop version

```
rubocop -V
1.43.0 (using Parser 3.2.0.0, rubocop-ast 1.24.1, running on ruby 3.1.2) [x86_64-darwin20]
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #11419.

This PR fixes a false positive for `Style/RedundantRequireStatement` when using `pretty_inspect`.
It also fixes false positives for similar method usage.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/redundant_require_statement_spec.rb [hunk 1]
```diff
@@ -124,6 +126,46 @@
         require 'uri'
       RUBY
     end
+
+    it 'does not register an offense and corrects when using requiring `pp` and using `pretty_inspect`' do
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/redundant_require_statement_spec.rb:130]: I'd remove some of the duplication in the message by adding some `context` for "when requiring pp".

Comment (koic) [reply spec/rubocop/cop/lint/redundant_require_statement_spec.rb]: Sure! This should have been DRY 💦 I've updated it.
