### PR TITLE
[Fix #11067] Fix a false positive for `Lint/DuplicateRegexpCharacterClassElement`

### LINKED ISSUE #11067: Lint/DuplicateRegexpCharacterClassElement can misinterpret octal escapes as nulls
The parser might read a sequence like `\032` inside a character class, stop at the `\0`, and mistakenly call that a duplicate element. Likewise, the autocorrect might remove just those two characters.

--------

## Expected behavior

Do not tokenize the leading `\0` in the above example.

## Actual behavior

```
% rubocop --debug --only Lint/DuplicateRegexpCharacterClassElement -- app/controllers/application_controller.rb
[ ... ]
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /Users/knutsen/src/cap/app/controllers/application_controller.rb
Loading cache from /Users/knutsen/.cache/rubocop_cache/b97726938b2e65a342a5ff855c7ee681d9a527dc/7950ca6bb1872c499a0d4972f78f4fa237a9cb5a/6b4b7e968bce07d4cbd3e58fe70b7126206a5c29
W

Offenses:

app/controllers/application_controller.rb:88:23: W: [Correctable] Lint/DuplicateRegexpCharacterClassElement: Duplicate element inside regexp character class
    str.gsub(/([\0\n\r\032'"\\])/) do
                      ^^

1 file inspected, 1 offense detected, 1 offense autocorrectable
```

## Steps to reproduce the problem

See above for a one-liner.

## RuboCop version

```
% rubocop -V                                                                                                   
1.36.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.0.4) [x86_64-darwin21]
```

(I'm running x86 Ruby on an M1 MacBook for reasons that are too depressing to go into right now)

### PR DESCRIPTION
**Pull request by koic**
Fixes #11067.

This PR fixes a false positive for `Lint/DuplicateRegexpCharacterClassElement` when using regexp character starts with escaped zero number.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb [hunk 1]
```diff
@@ -32,26 +32,40 @@ def on_regexp(node)
           end
         end
 
+        # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
         def each_repeated_character_class_element_loc(node)
           node.parsed_tree&.each_expression do |expr|
-            next if expr.type != :set || expr.token == :intersection
+            next if skip_expression?(expr)
```
Comment (knutsenm) [inline lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb:38]: Why factor this out if it's only called once?

File: lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb [hunk 2]
```diff
@@ -32,26 +32,40 @@ def on_regexp(node)
...
 
-            expr.expressions.each do |child|
-              next if within_interpolation?(node, child)
+            expression_count.times do |current_number|
+              current_child = enum.next
+              next if within_interpolation?(node, current_child)
 
-              child_source = child.to_s
+              current_child_source = current_child.to_s
+              next_child = enum.peek if current_number + 1 < expression_count
```
Comment (knutsenm) [inline lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb:49]: Cool! Thanks, I learned something new today.

File: lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/cop/lint/duplicate_regexp_character_class_element.rb:38]: This seems to be called multiple times.

**Comment by bbatsov** [comment]
Looks good to me. Thanks!
