### PR TITLE
[Fix #14307] Fix `Style/MethodCallWithArgsParentheses` false positives

### LINKED ISSUE #14307: Fix Style/MethodCallWithArgsParentheses with guarded return and anonymous forwards
I'm seeing an issue where you'll get a RuboCop issue when using a guard to return early with bare double splats. I'm guessing this will happen with bare/named single splats, double splats, and block arguments too.

## Expected behavior

I would expect the following to be valid and require parenthesis in this case because, without them, you'll get a syntax error:

``` ruby
def demo(value, **)
  record = find_by_name value

  return create(name: value, **) unless record

  record
end
```

The reason is that `create(name: value, **)` requires parentheses in this case. Otherwise, it's a syntax error.

## Actual behavior

Here's what actually happens:

```
demo.rb:20:24: C: [Correctable] Style/MethodCallWithArgsParentheses: Omit parentheses for method calls with arguments. (https://rubystyle.guide#method-invocation-parens)
          return create(name: value, **) unless record
                       ^^^^^^^^^^^^^^^^^
```

## Steps to reproduce the problem

You can recreate the above using the following configuration:

``` yaml
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInChaining: true
  AllowParenthesesInMultilineCall: true
  IgnoreMacros: false
```

## RuboCop version

```
1.76.2 (using Parser 3.3.8.0, Prism 1.4.0, rubocop-ast 1.45.1, analyzing as Ruby 3.4, running on ruby 3.4.4) [arm64-darwin24.5.0]
  - rubocop-sequel 0.3.8
  - rubocop-capybara 2.22.1
  - rubocop-disable_syntax 0.2.0
  - rubocop-packaging 0.6.0
  - rubocop-performance 1.25.0
  - rubocop-thread_safety 0.7.2
  - rubocop-rake 0.7.1
  - rubocop-rspec 3.6.0
```

### PR DESCRIPTION
**Pull request by viralpraxis**
Resolves https://github.com/rubocop/rubocop/issues/14307

**Replace this text with a summary of the changes in your PR.
The more detailed you are, the better.**

-----------------

Before submitting the PR make sure the following are checked:

* [X] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [X] Wrote [good commit messages][1].
* [X] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [X] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [X] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [X] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb [hunk 1]
```diff
@@ -529,6 +529,14 @@ def foo(**)
           end
         RUBY
       end
+
+      it 'does not register an offense when arguments hash has additional nodes' do
```
Comment (koic) [inline spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb]: Isn't "forwarded keyword argument" more accurate than "hash"?

```suggestion
      it 'does not register an offense when forwarded keyword argument has additional nodes' do
```

Comment (viralpraxis) [reply spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb]: Changed the description.

**Comment by koic** [comment]
Thanks!
