### PR TITLE
[Fix #10203] Fix `Style/FormatStringToken` to respect `IgnoredMethods` with nested structures

### LINKED ISSUE #10203: `Style/FormatStringToken` does not respect `IgnoredMethods` for values in nested structures
The `Style/FormatStringToken` cop does not respect `IgnoredMethods` for values which are nested, e.g. into an options hash.

### Suggested solution

I've investigated why that is, and the culprit seems to be `FormatStringToken#use_ignored_method?` where we we only check if the found node (the offending string) has a method parent (`send` type). In case of a value inside a hash, the parent is not the method itself.

Maybe it makes sense to allow climbing up the node tree as long as parents are `pair` or `hash` nodes (maybe others?), and only then check if the surrounding node is of type `send`.

Please let me know if that approach sounds reasonable and I can try implementing a fix.

--------

## Expected behavior

Given the following config,
```yaml
Style/FormatStringToken:
  EnforcedStyle: annotated
  IgnoredMethods:
    - example
```

and the following Ruby code,
```ruby
example("Hello %{name}")
example("Hello %{name}", bye: "Bye %{name}")
```

both calls to `example` should be ignored.

## Actual behavior

`example("Hello %{name}")` is ignored, but `example("Hello %{name}", bye: "Bye %{name}")` raises an offense.

```
Offenses:

test.rb:2:36: C: Style/FormatStringToken: Prefer annotated tokens (like %<foo>s) over template tokens (like %{foo}).
example("Hello %{name}", bye: "Bye %{name}")
                                   ^^^^^^^
```

## Steps to reproduce the problem

Run Rubocop with example config from above against a file with example Ruby code from above.

## RuboCop version

```
$ bundle exec rubocop -V
1.22.1 (using Parser 3.0.2.0, rubocop-ast 1.12.0, running on ruby 2.7.3 x86_64-linux)
  - rubocop-performance 1.11.5
  - rubocop-rails 2.12.4
  - rubocop-rspec 2.5.0
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #10203

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/format_string_token.rb [hunk 1]
```diff
@@ -102,7 +102,8 @@ def format_string_token?(node)
         end
 
         def use_ignored_method?(node)
-          (parent = node.parent) && parent.send_type? && ignored_method?(parent.method_name)
+          send_parent = node.ancestors.find(&:send_type?)
```
Comment (dvandersluis) [inline lib/rubocop/cop/style/format_string_token.rb:105]:
```suggestion
          send_parent = node.each_ancestor(:send).first
```

Comment (tejasbubane) [reply lib/rubocop/cop/style/format_string_token.rb]: @dvandersluis Thanks. Changed.

**Review by dvandersluis — APPROVED** [review]

**Comment by dvandersluis** [comment]
Thanks @tejasbubane!
