### PR TITLE
[Fix #12377] Fix false positives for `Lint/Void`

### LINKED ISSUE #12377: Lint/Void and Lint/UselessAssignment removed my code with side effect
In spec we had the following code 

```rb
invoices = [FactoryBot.create(:invoice, customer_unit_id: @user.current_unit.id),
            FactoryBot.create(:invoice, supplier_unit_id: @user.current_unit.id),]
user = FactoryBot.create(:user)
```

During work to enable Lint/UselessAssignment. Rubocop found that invoices was an unused variable. I ran `be rubocop path.rb  --only Lint/UselessAssignment -A` and it replaced the code with the following code. which is fine. Lint/UselessAssignment is unsafe autocorrect so I ran it with -A.

```rb
[FactoryBot.create(:invoice, customer_unit_id: @user.current_unit.id),
 FactoryBot.create(:invoice, supplier_unit_id: @user.current_unit.id),]
user = FactoryBot.create(:user)
```
When I lint this code I get errors from Lint/Void. Running autofix safe version (-a) rubocop removed the array definition, so my two invoices are not created any more. 

```rb
user = FactoryBot.create(:user)
```
## Expected behavior

My suggestion is to don't modify the array if it has anything which could have side effect

## Actual behavior

Removes by factory bot calls

## Steps to reproduce the problem

Explained above 

## RuboCop version

```
⋊> ~/d/w/d/f/repo on st-bugsnag-w40 ⨯ bundle exec rubocop -V                                                                                                                              12:57:13
1.57.2 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.2.1) [arm64-darwin22]
  - rubocop-capybara 2.19.0
  - rubocop-factory_bot 2.24.0
  - rubocop-performance 1.19.1
  - rubocop-rails 2.22.1
  - rubocop-rspec 2.25.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12377.

This PR fixes false positives for `Lint/Void` when a collection literal that includes non-literal elements in a method definition.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/void.rb [hunk 1]
```diff
@@ -217,6 +217,17 @@ def autocorrect_nonmutating_send(corrector, node, suggestion)
                       end
           corrector.replace(send_node.loc.selector, suggestion)
         end
+
+        def entirely_literal?(node)
+          case node.type
+          when :array
+            node.each_value.all?(&:literal?)
+          when :hash
+            node.each_value.all?(&:literal?) && node.each_key.all?(&:literal?)
```
Comment (vlad-pisanov) [inline lib/rubocop/cop/lint/void.rb:226]: should this be recursive to handle nested literals like `[1, [2, 3]]`?

Comment (koic) [reply lib/rubocop/cop/lint/void.rb:226]: Considering the possibility, it should have been addressed. I've updated this PR. Thank you!

File: lib/rubocop/cop/lint/void.rb [hunk 2]
```diff
@@ -217,6 +217,19 @@ def autocorrect_nonmutating_send(corrector, node, suggestion)
                       end
           corrector.replace(send_node.loc.selector, suggestion)
         end
+
+        def entirely_literal?(node)
+          case node.type
+          when :array
+            node.each_value.all? { |value| entirely_literal?(value) }
+          when :hash
+            return false unless node.each_key.all?(&:literal?)
```
Comment (vlad-pisanov) [inline lib/rubocop/cop/lint/void.rb:226]: technically, keys can be complex literals themselves, but I don't know if it's worth handling since it's not super common 😅  

```ruby
{
  [1, 2] => :foo
}
```

Comment (koic) [reply lib/rubocop/cop/lint/void.rb]: You are right! I've updated this PR. Thanks!
