### PR TITLE
[Fix #10842] Make server mode aware of `CacheRootDirectory` and two env vars

### LINKED ISSUE #10842: Server Does not Appear to Work
After reading an article about the new Rubocop server I eagerly attempted it on a project that uses Nix to manage the dev environment. I believe something is awry, possibly related to #10771 (wild guess).

--------

## Expected behavior

Initializing a Rubocop server works, and continues to work upon subsequent calls to Rubocop.

## Actual behavior

Sample shell commands from a session:

```shell
$ bin/rubocop --start-server
RuboCop server starting on 127.0.0.1:61108.

$ bin/rubocop --server-status
RuboCop server (16113) is running.

$ time bin/rubocop
2607 files inspected, no offenses detected

real	0m23.144s
user	0m0.400s
sys	0m0.107s

$ bin/rubocop --server-status
RuboCop server is not running.
```

### `rubocop --debug`

```
For /Users/james/Projects/PN/eternal-sledgehammer: configuration from /Users/james/Projects/PN/eternal-sledgehammer/.rubocop.yml
configuration from /Users/james/Projects/PN/eternal-sledgehammer/vendor/cache/ruby/2.7.0/gems/rubocop-performance-1.14.3/config/default.yml
configuration from /Users/james/Projects/PN/eternal-sledgehammer/vendor/cache/ruby/2.7.0/gems/rubocop-performance-1.14.3/config/default.yml
Default configuration from /Users/james/Projects/PN/eternal-sledgehammer/vendor/cache/ruby/2.7.0/gems/rubocop-1.32.0/config/default.yml
configuration from /Users/james/Projects/PN/eternal-sledgehammer/vendor/cache/ruby/2.7.0/gems/rubocop-rails-2.15.2/config/default.yml
configuration from /Users/james/Projects/PN/eternal-sledgehammer/vendor/cache/ruby/2.7.0/gems/rubocop-rails-2.15.2/config/default.yml
configuration from /Users/james/Projects/PN/eternal-sledgehammer/vendor/cache/ruby/2.7.0/gems/rubocop-rspec-2.12.1/config/default.yml
configuration from /Users/james/Projects/PN/eternal-sledgehammer/vendor/cache/ruby/2.7.0/gems/rubocop-rspec-2.12.1/config/default.yml
Inheriting configuration from /Users/james/Projects/PN/eternal-sledgehammer/.rubocop_todo.yml
.rubocop.yml: Metrics/MethodLength:Exclude overrides the same parameter in .rubocop_todo.yml
Use parallel by default.
Running parallel inspection

# elide indications of cache scanning
```

Please use `rubocop --debug` when pasting rubocop output as it contains additional information.

## Steps to reproduce the problem

See above

## RuboCop version

Include the output of `rubocop -V` or `bundle exec rubocop -V` if using Bundler.
If you see extension cop versions (e.g. `rubocop-performance`, `rubocop-rspec`, and others)
output by `rubocop -V`, include them as well. Here's an example:

```
$ [bundle exec] rubocop -V
1.32.0 (using Parser 3.1.2.0, rubocop-ast 1.19.1, running on ruby 2.7.6 arm64-darwin21)
  - rubocop-performance 1.14.3
  - rubocop-rails 2.15.2
  - rubocop-rspec 2.12.1
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #10842 and follow up #10849.

This PR makes server mode aware of `CacheRootDirectory` config option value, `RUBOCOP_CACHE_ROOT`, and `XDG_CACHE_HOME` environment variables.

`RuboCop::ConfigLoader` and `RuboCop::ResultCache` classes to get these values has many dependencies. So, it is not suitable for use in server mode where speed is required.

This solution is to extract `ConfigPathFinder` class from `ConfigLoader` class and `CacheRoot` class from `ResultCache` class. This allows server mode to depend on lightweight `ConfigPathFinder` and `CacheRoot` classes.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/config_path_finder.rb [hunk 1]
```diff
@@ -0,0 +1,68 @@
+# frozen_string_literal: true
+
+require_relative 'file_finder'
+
+module RuboCop
+  # This class has methods related to finding configuration path.
+  # @api private
+  class ConfigPathFinder
```
Comment (bbatsov) [inline lib/rubocop/config_path_finder.rb:8]: Perhaps just `ConfigFinder`?

File: lib/rubocop/cache_root.rb [hunk 2]
```diff
@@ -0,0 +1,29 @@
+# frozen_string_literal: true
+
+module RuboCop
+  # This class represents the cache root of the caching RuboCop runs.
+  # @api private
+  class CacheRoot
```
Comment (bbatsov) [inline lib/rubocop/cache_root.rb:6]: `CacheRoot` seems a bit too specific to me to warrant a class - maybe this should be `CacheConfig` or something like this?

File: lib/rubocop/config_path_finder.rb (hunk 1 above)
Comment (koic) [reply lib/rubocop/config_path_finder.rb]: Thanks for the suggestion! I've update this class name.

File: lib/rubocop/cache_root.rb (hunk 2 above)
Comment (koic) [reply lib/rubocop/cache_root.rb]: `CacheConfig` looks good! Also changed the class method name from `CacheRoot.dir` to `CacheConfig.root_dir`.

**Comment by bbatsov** [comment]
Thanks!
