### PR TITLE
[Fix #12557] Make server mode aware of auto-restart for `bundle update`

### LINKED ISSUE #12557: Wrong version of extensions loaded with 1.59.0?
## Expected behavior

With same exact Gemfile and Gemfile.lock, with updated rubocop extensions, rubocop is loading the wrong version dependencies. (see version info below)

This is true even if the other versions are fully uninstalled (gem uninstall rubocop-performance and bundle exec gem uninstall rubocop-performance before bundle install again)

## Actual behavior

Gemfile has this in it:

```
  gem "rubocop", "~> 1.59.0"
  gem "rubocop-capybara", "~> 2.19.0"
  gem "rubocop-graphql", "~> 1.4.0"
  gem "rubocop-minitest", "~> 0.34.1"
  gem "rubocop-performance", "~> 1.20.0"
  gem "rubocop-rails", "~> 2.23.0"
  gem "rubocop-rake", "~> 0.6.0"
 ```

and this in .rubocop.yml:

```
require:
  - rubocop-rails
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-graphql
  - rubocop-capybara
```

## Steps to reproduce the problem

with above gemfile, have multiple people run:

```
bundle install
bundle exec rubocop -V
```

## RuboCop version

This is what it should be per Gemfile.lock and there on a number of our machines:

```
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.0.6) [arm64-darwin22]
  - rubocop-capybara 2.19.0
  - rubocop-graphql 1.4.0
  - rubocop-minitest 0.34.1
  - rubocop-performance 1.20.0
  - rubocop-rails 2.23.0
  - rubocop-rake 0.6.0
 ```

But others are seeing:

```
1.59.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 3.0.6) +server [arm64-darwin22]
  - rubocop-capybara 2.19.0
  - rubocop-graphql 1.4.0
  - rubocop-minitest 0.33.0
  - rubocop-performance 1.19.1
  - rubocop-rails 2.22.2
  - rubocop-rake 0.6.0
```

You can further see this in debug mode:

When working, it states:

```
For /Users/REDACTED/REDACTED/app: configuration from /Users/REDACTED/REDACTED/app/.rubocop.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-rails-2.23.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-rails-2.23.0/config/default.yml
Default configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-1.59.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-minitest-0.34.1/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-minitest-0.34.1/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-performance-1.20.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-performance-1.20.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-rake-0.6.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-graphql-1.4.0/config/default.yml
configuration from #{path}
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-capybara-2.19.0/config/default.yml
configuration from /Users/REDACTED/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/rubocop-capybara-2.19.0/lib/../config/default.yml
```

But when not, it only has:

```
For /Users/REDACTED/REDACTED/app: configuration from /Users/REDACTED/REDACTED/app/.rubocop.yml
```

### PR DESCRIPTION
**Pull request by koic**
Resolves #12557.

Currently, the server mode only auto-restarts due to incompatible versions of RuboCop core. This PR will enable auto-restart when the SHA1 value of Gemfile.lock becomes incompatible. If Gemfile.lock is missing, it will continue to refer to the RuboCop core version as before.

The advantage is that it can cover cases of version incompatibility caused by `bundle update`, which will likely cover many scenarios like those in #12557.

The disadvantage is that the server mode may become slightly slower. However, it is unlikely to be slow enough for users to notice. The trade-off is considered acceptable.

In the future, it might be possible to detect changes in rubocop configuration as well, but for now, I'd like to see how things go with this change.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by Earlopain** [comment]
Does this actually consider `Gemfile.lock`? From looking at the code I'd say that file is not used in that check.

**Comment by koic** [comment]
Ah, indeed. I've updated this PR.

File: lib/rubocop/server/cache.rb [hunk 1]
```diff
@@ -41,6 +43,14 @@ def project_dir_cache_key
           @project_dir_cache_key ||= project_dir[1..].tr('/', '+')
         end
 
+        def restart_key
+          lockfile_path = LOCKFILE_NAMES.map do |lockfile_name|
+            Pathname(project_dir).join(lockfile_name)
+          end.find(&:exist?)
+
+          Digest::SHA1.hexdigest(lockfile_path&.read || RuboCop::Version::STRING)
```
Comment (pirj) [inline lib/rubocop/server/cache.rb:51]: Does it make sense to `read.grep(/rubocop/)` to avoid restarting on unrelated updates?

**Review by pirj — APPROVED** [review]
Fantastic, thank you! 🙏

File: lib/rubocop/server/cache.rb (hunk 1 above)
Comment (Earlopain) [reply lib/rubocop/server/cache.rb:51]: Unrelated is a bit fuzzy here. For example, if I conservatively update the `parser` gem because a new ruby version released I'd still want it to restart rubocop.

Personally I think its safer to keep it like that, having it run more closely to how it would do without server mode.

Comment (koic) [reply lib/rubocop/server/cache.rb:51]: Yes. It is prioritize that the environment can be aligned even when updating dependent gems that don't match `/rubocop/`, to prevent user confusion. Especially since it is not possible to know in advance which gems 3rd party gem depends on. Also, since `bundle update` occurs less frequently than `rubocop` is run, it has been decided that updating the entire Gemfile.lock to SHA1 is a trade-off that makes sense.
