### PR TITLE
[Fix #14193] Fix `Lint/UselessAssignment` cop error when using nested assignment with splat

### LINKED ISSUE #14193: Lint/UselessAssignment: crash on splatted nested parallel assignment
Splatted, nested parallel assignment `(left, right), *rest = [[:foo, 1], [:bar, 2]]` makes the `Lint/UselessAssignment` cop crash.

(Possibly a variant of https://github.com/rubocop/rubocop/issues/11905)

## Expected behavior

RuboCop should finish without crashing.

## Actual behavior

<details>
<summary>BackTrace</summary>

```bash
RUBOCOP_TARGET_RUBY_VERSION=3.3 rubocop example.rb --debug
For /tmp/rubocop-variableforce-error: Default configuration from /home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/config/default.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /tmp/rubocop-variableforce-error/example.rb
An error occurred while Lint/UselessAssignment cop was inspecting /tmp/rubocop-variableforce-error/example.rb.
undefined method `source' for nil
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/lint/useless_assignment.rb:209:in `remove_local_variable_assignment_part'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/lint/useless_assignment.rb:179:in `autocorrect'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/lint/useless_assignment.rb:74:in `block (2 levels) in check_for_unused_assignments'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/base.rb:426:in `correct'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/base.rb:210:in `add_offense'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/lint/useless_assignment.rb:66:in `block in check_for_unused_assignments'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/lint/useless_assignment.rb:59:in `reverse_each'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/lint/useless_assignment.rb:59:in `check_for_unused_assignments'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/lint/useless_assignment.rb:52:in `block in after_leaving_scope'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/lint/useless_assignment.rb:52:in `each_value'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/lint/useless_assignment.rb:52:in `after_leaving_scope'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/force.rb:44:in `public_send'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/force.rb:44:in `block in run_hook'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/force.rb:41:in `each'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/force.rb:41:in `run_hook'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/variable_force.rb:376:in `block (2 levels) in <class:VariableForce>'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/variable_force/variable_table.rb:17:in `invoke_hook'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/variable_force/variable_table.rb:36:in `pop_scope'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/variable_force.rb:85:in `investigate'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/commissioner.rb:164:in `block (2 levels) in invoke_with_argument'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/commissioner.rb:171:in `with_cop_error_handling'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/commissioner.rb:164:in `block in invoke_with_argument'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/commissioner.rb:164:in `each'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/commissioner.rb:164:in `invoke_with_argument'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/commissioner.rb:85:in `investigate'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/team.rb:174:in `investigate_partial'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cop/team.rb:108:in `investigate'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:348:in `block in inspect_file'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:347:in `each'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:347:in `flat_map'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:347:in `inspect_file'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:290:in `block in do_inspection_loop'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:324:in `block in iterate_until_no_changes'
<internal:kernel>:187:in `loop'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:317:in `iterate_until_no_changes'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:286:in `do_inspection_loop'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:167:in `block in file_offenses'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:192:in `file_offense_cache'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:166:in `file_offenses'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:154:in `process_file'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:135:in `block in each_inspected_file'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:134:in `each'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:134:in `reduce'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:134:in `each_inspected_file'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:120:in `inspect_files'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/runner.rb:73:in `run'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli/command.rb:11:in `run'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli/environment.rb:18:in `run'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli.rb:122:in `run_command'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli.rb:129:in `execute_runners'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli.rb:51:in `block in run'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli.rb:81:in `profile_if_needed'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/lib/rubocop/cli.rb:43:in `run'
/home/s/.asdf/installs/ruby/3.3.6/lib/ruby/gems/3.3.0/gems/rubocop-1.75.6/exe/rubocop:19:in `<top (required)>'
/home/s/.asdf/installs/ruby/3.3.6/bin/rubocop:25:in `load'
/home/s/.asdf/installs/ruby/3.3.6/bin/rubocop:25:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Lint/UselessAssignment cop was inspecting /tmp/rubocop-variableforce-error/example.rb.
```

</details>

## Steps to reproduce the problem

Create a file named example.rb containing:

```ruby
# frozen_string_literal: true

(left, right), *rest = [[:foo, 1], [:bar, 2]]
```

Run RuboCop:

```bash
RUBOCOP_TARGET_RUBY_VERSION=3.3 rubocop example.rb --debug
```

## RuboCop version

```bash
rubocop -V                                                
1.75.6 (using Parser 3.3.8.0, rubocop-ast 1.44.1, analyzing as Ruby 2.7, running on ruby 3.3.6) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by Earlopain**
Fix #14193

The ast for `(left, right), *rest = foo` looks like this:
```
(masgn
  (mlhs
    (mlhs
      (lvasgn :left)
      (lvasgn :right))
    (splat
      (lvasgn :rest)))
  (send nil :foo))
```

Because of the splat node, it must reach up one furhter to land at the conclusion that this is indeed multiple assignment. Otherwise, it gets treated as normal assignment, where the type of autocorrect is not appropriate.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/variable_force/assignment_spec.rb [hunk 1]
```diff
@@ -125,8 +125,8 @@ def some_method
         RUBY
       end
 
-      it 'returns splat node' do
-        expect(assignment.meta_assignment_node.type).to eq(:splat)
+      it 'returns masgn node' do
+        expect(assignment.meta_assignment_node.type).to eq(:masgn)
```
Comment (Earlopain) [inline spec/rubocop/cop/variable_force/assignment_spec.rb:129]: `splat` is not a type of assignment, so it makes sense to me that this returns `masgn` instead now. I think the test was just wrong previously.

File: lib/rubocop/cop/variable_force/assignment.rb [hunk 2]
```diff
@@ -109,8 +109,13 @@ def operator_assignment_node
...
 
+        # rubocop:disable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
         def multiple_assignment_node
-          return nil unless node.parent&.mlhs_type?
+          candidate_mlhs_node = node&.parent
+          # In `(foo, bar), *baz`, the splat node must be traversed as well.
+          candidate_mlhs_node = candidate_mlhs_node&.parent if candidate_mlhs_node&.splat_type?
+
+          return nil unless candidate_mlhs_node&.mlhs_type?
           return nil unless (grandparent_node = node.parent&.parent)
```
Comment (koic) [inline lib/rubocop/cop/variable_force/assignment.rb:119]: By suppressing safe navigation, the new `rubocop:disable` annotation will likely no longer be necessary.

```suggestion
          return unless (candidate_mlhs_node = node.parent)

          # In `(foo, bar), *baz`, the splat node must be traversed as well.
          candidate_mlhs_node = candidate_mlhs_node.parent if candidate_mlhs_node.splat_type?

          return nil unless candidate_mlhs_node.mlhs_type?
          return nil unless (grandparent_node = node.parent.parent)
```

Comment (Earlopain) [reply lib/rubocop/cop/variable_force/assignment.rb]: Nice, thanks. It makes it a bit better, but one is still there.

File: lib/rubocop/cop/variable_force/assignment.rb [hunk 3]
```diff
@@ -109,8 +109,14 @@ def operator_assignment_node
...
+        # rubocop:disable Metrics/CyclomaticComplexity
         def multiple_assignment_node
-          return nil unless node.parent&.mlhs_type?
+          return nil unless (candidate_mlhs_node = node.parent)
+
+          # In `(foo, bar), *baz`, the splat node must be traversed as well.
+          candidate_mlhs_node = candidate_mlhs_node.parent if candidate_mlhs_node.splat_type?
+
+          return nil unless candidate_mlhs_node.mlhs_type?
           return nil unless (grandparent_node = node.parent&.parent)
```
Comment (koic) [inline lib/rubocop/cop/variable_force/assignment.rb:120]: Removing this safe navigation will allow the `rubocop:disable` annotation to be removed :-)

```suggestion
          return nil unless (grandparent_node = node.parent.parent)
```

Comment (Earlopain) [reply lib/rubocop/cop/variable_force/assignment.rb]: Oops, I missed this one. Indeed they are both gone with that, I believe this is safe to do.

File: changelog/fix_useless_assign_splat_mlhs.md [hunk 4]
```diff
@@ -0,0 +1 @@
+* [#14193](https://github.com/rubocop/rubocop/pull/14193): Fix `Lint/UselessAssignment` cop error when using nested assignment with splat. ([@earlopain][])
```
Comment (koic) [inline changelog/fix_useless_assign_splat_mlhs.md:1]:
```suggestion
* [#14193](https://github.com/rubocop/rubocop/issues/14193): Fix `Lint/UselessAssignment` cop error when using nested assignment with splat. ([@earlopain][])
```
