### PR TITLE
[Fix #13509] Update `Layout/ExtraSpacing` and `Layout/SpaceAroundOperators` to handle preceding operators inside strings

### LINKED ISSUE #13509: Layout/ExtraSpacing with ForceEqualSignAlignment aligns on string containing '='
Given the following setup:

```yaml
# .rubocop.yml
Layout/ExtraSpacing:
  ForceEqualSignAlignment: true
```

```ruby
# extra_space.rb

# ✅ good
a, b              = val.split('=')
opt.ssh_config[a] = b

# ✅ bad
c, d = val.split(':')
opt.ssh_config[c] = d

# ❌ good, but should be bad
e, f = val.split('=')
opt.ssh_config[e] = f
```

## Expected behavior

Running RuboCop on the `extra_space.rb` should yield two offenses:

- No offense in case (1), as both lines are aligned.
- Case (2) should be an offense as the assignments are not aligned.
- Case (3) should also be an offense, as it is identical to case (2), but with different string contents.

## Actual behavior

Case (3) is incorrectly identified as good:

```console
$ bundle exec rubocop --debug --only Layout/ExtraSpacing extra_space.rb
For /tmp/rubocop: configuration from /tmp/rubocop/.rubocop.yml
Default configuration from /tmp/rubocop/.gems/gems/rubocop-1.69.0/config/default.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /tmp/rubocop/extra_space.rb
C

Offenses:

extra_space.rb:9:19: C: [Correctable] Layout/ExtraSpacing: = is not aligned with the preceding assignment.
opt.ssh_config[c] = d
                  ^

1 file inspected, 1 offense detected, 1 offense autocorrectable
Finished in 0.056411404999380466 seconds
```

## Steps to reproduce the problem

```console
$ cd $(mktemp -d)
$ $EDITOR extra_space.rb      # paste contents from above
$ $EDITOR .rubocop.yml        # paste contents from above
$ echo >Gemfile "source 'https://rubygems.org'\n\ngem 'rubocop', require: false"
$ echo >.ruby-version 3.3     # optional, if using rbenv
$ echo >.ruby-gemset  ./.gems # optional, if using rbenv with gemset plugin
$ gem install bundler && bundle install
$ bundle exec rubocop --debug --only Layout/ExtraSpacing extra_space.rb
```

## RuboCop version

```
$ bundle exec rubocop -V
1.69.0 (using Parser 3.3.6.0, rubocop-ast 1.36.2, analyzing as Ruby 3.3, running on ruby 3.3.5) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by dvandersluis**
The `PrecedingFollowingAlignment` mixin is used to determine if lines are aligned properly based on certain criteria. For alignment involving assignment or `<<`, it was previously just matching the text content at a given column, but this could cause a false result if a string containing the operator was perfectly aligned with the column.

This update fixes that by ensuring that the position is within the correct token type.

Fixes #13509.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/space_around_operators_spec.rb [hunk 1]
```diff
@@ -958,6 +958,22 @@ class ShowSourceTestClass < ShowSourceTestSuperClass
       RUBY
     end
 
+    it 'registers an offense when operator is followed by aligned << inside a string' do
+      expect_offense(<<~RUBY)
+        x   += foo
+            ^^ Operator `+=` should be surrounded by a single space.
+        'yz << bar'
+      RUBY
```
Comment (koic) [inline spec/rubocop/cop/layout/space_around_operators_spec.rb:966]: Can you add `expect_correction`?

File: spec/rubocop/cop/layout/space_around_operators_spec.rb [hunk 2]
```diff
@@ -958,6 +958,22 @@ class ShowSourceTestClass < ShowSourceTestSuperClass
...
+    end
+
+    it 'registers an offense when operator is preceded by aligned << inside a string' do
+      expect_offense(<<~RUBY)
+        'yz << bar'
+        x   += foo
+            ^^ Operator `+=` should be surrounded by a single space.
+      RUBY
```
Comment (koic) [inline spec/rubocop/cop/layout/space_around_operators_spec.rb:974]: Ditto.

File: spec/rubocop/cop/layout/space_around_operators_spec.rb (hunk 1 above)
Comment (dvandersluis) [reply spec/rubocop/cop/layout/space_around_operators_spec.rb:966]: Yes of course. Both tests are updated now.
