### PR TITLE
[Fix #10636] Fix false positive in `Style/RedundantCondition` when the branches call the same method on different receivers

### LINKED ISSUE #10636: Style/RedundantCondition autofixes incorrectly (rubocop 1.29.1)
This code

```ruby
class Pippo
  def foo
    result =
      if x
        X.find(x)
      else
        Y.find(y)
      end

    result.to_s
  end
end
```

generates this warning:

```bash
app/pippo.rb:4:7: C: [Correctable] Style/RedundantCondition: Use double pipes || instead.
      if x ...
```

If I run `rubocop -a` it gets autofixed with:

```ruby
class Pippo
  def foo
    result =
      X.find(x || y)

    result.to_s
  end
end
```

but the behavior now it's changed.

## Expected behavior

I think the cop should not raise a warning, because it's not a redundant condition 🤔 

## RuboCop version

```
$ bundle exec rubocop -V
 ↳ $ bundle exec rubocop -V
1.29.1 (using Parser 3.1.2.0, rubocop-ast 1.17.0, running on ruby 2.7.6 x86_64-darwin21)
  - rubocop-performance 1.13.3
  - rubocop-rails 2.14.2
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.10.0
```

### PR DESCRIPTION
**Pull request by dvandersluis**
Fixes #10636.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/redundant_condition_spec.rb [hunk 1]
```diff
@@ -376,6 +376,34 @@ def test
           end
         RUBY
       end
+
+      it 'registers an offense and correct when the branches are the same with the same receivers' do
+        expect_offense(<<~RUBY)
+          result =
```
Comment (koic) [inline spec/rubocop/cop/style/redundant_condition_spec.rb:382]: That's just my two cents. Can you remove it? Because this assignment doesn't seem to matter.

```suggestion
```

File: spec/rubocop/cop/style/redundant_condition_spec.rb [hunk 2]
```diff
@@ -376,6 +376,34 @@ def test
...
+
+        expect_correction(<<~RUBY)
+          result =
+            X.find(x || y)
+        RUBY
+      end
+
+      it 'does not register an offense when the branches are the same with different receivers' do
+        expect_no_offenses(<<~RUBY)
+        result =
```
Comment (koic) [inline spec/rubocop/cop/style/redundant_condition_spec.rb:399]: Ditto.

```suggestion
```

**Comment by dvandersluis** [comment]
@koic thanks for the suggestion, updated.

**Comment by koic** [comment]
Perfect 👍 Thanks!
