### PR TITLE
[Fix #9683] Fix an incorrect auto-correct for `Style/HashConversion`

### LINKED ISSUE #9683: Style/HashConversion auto-correct generates invalid code
The `Style/HashConversion` cop may generate invalid code under some specific scenarios, see example below.

--------

## Expected behavior

Given the following code:

```ruby
Hash[[1,2,3].zip]
# => {1=>nil, 2=>nil, 3=>nil} 
```

RuboCop is expected to not register an offense or to auto-correct it with an equivalent code.

## Actual behavior

RuboCop auto-corrects it as follows:

```ruby
[1,2,3].zip.to_h
# ArgumentError (wrong array length at 0 (expected 2, was 1))
```

## RuboCop version

1.12.1 (using Parser 3.0.1.0, rubocop-ast 1.4.1, running on ruby 2.6.6 x86_64-linux)

### PR DESCRIPTION
**Pull request by koic**
Fixes #9683.

This PR fixes an incorrect auto-correct for `Style/HashConversion` when using `zip` method in `Hash[]`.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/hash_conversion.rb [hunk 1]
```diff
@@ -45,6 +45,7 @@ class HashConversion < Base
 
         def on_send(node)
           return unless hash_from_array?(node)
+          return if node.arguments.any? { |argument| argument.send_type? && argument.method?(:zip) }
```
Comment (bbatsov) [inline lib/rubocop/cop/style/hash_conversion.rb:48]: I don't like very much hardcoding such special cases. At the very least this should be mentioned in the docs.

Comment (bbatsov) [reply lib/rubocop/cop/style/hash_conversion.rb:48]: Also are there other methods that might produce some output similar to that of `zip`?

**Comment by bbatsov** [comment]
One more thing - if this `zip` actually had params everything would work just fine, which makes the use case extra weird. 

```ruby
[1, 3, 4, 5, 5,6].zip([1,2,3,4,5,6]).to_h
# => {1=>1, 3=>2, 4=>3, 5=>5, 6=>6}
```

**Comment by koic** [comment]
> One more thing - if this `zip` actually had params everything would work just fine, which makes the use case extra weird.

I overlooked the case of passing argument to `zip`.

> Also are there other methods that might produce some output similar to that of `zip`?

Similar cases were considered, such as `combination`, `permutation`, `repeated_combination`, and `repeated_permutation`.
But I think they no need to be considered as they will also occur in `ArgumentError` with `Hash[]`.

The following is an example. These behave differently depending on whether the argument are odd or even, but they occur the same error in bad case (`Hash[]`).

## `combination` with odd number argument

```ruby
% irb
irb(main):001:0> Hash[[1, 2, 3, 4].combination(2)]
(irb):1:in `[]': odd number of arguments for Hash (ArgumentError)
        from (irb):1:in `<main>'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:13:in `<top (required)>'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `load'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `<main>'
irb(main):002:0> [1, 2, 3, 4].combination(2).to_h
=> {1=>4, 2=>4, 3=>4}
```

## `combination` with even number argument

```ruby
irb(main):003:0> Hash[[1, 2, 3, 4].combination(3)]
(irb):3:in `[]': odd number of arguments for Hash (ArgumentError)
        from (irb):3:in `<main>'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:13:in `<top (required)>'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `load'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `<main>'
irb(main):004:0> [1, 2, 3, 4].combination(3).to_h
(irb):4:in `combination': element has wrong array length (expected 2, was 3) (ArgumentError)
        from (irb):4:in `each'
        from (irb):4:in `to_h'
        from (irb):4:in `<main>'
        from /Users/koic/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/irb-1.3.5/exe/irb:13:in `<top (required)>'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `load'
        from /Users/koic/.rbenv/versions/3.0.1/bin/irb:23:in `<main>'
irb(main):005:0> [1, 2, 3, 4].combination(1).to_h
```

As far as I searched, only `zip` with no arguments seems to be a special case. So, I would like to update this PR with an implementation and documentation specific to this `zip` special case.

**Comment by bbatsov** [comment]
Fair enough.

**Comment by koic** [comment]
I updated this PR. Thank you!

**Comment by gPrado** [comment]
Maybe a simpler alternative is to update the auto-correction code to handle this special case:

```ruby
Hash[[1,2,3].zip]
#  => {1=>nil, 2=>nil, 3=>nil} 
```

may be auto-corrected to:

```ruby
[1,2,3].zip([]).to_h
# => {1=>nil, 2=>nil, 3=>nil} 
```

**Comment by bbatsov** [comment]
I like this idea!

**Comment by bbatsov** [comment]
Thanks!
