### PR TITLE
[Fix #11098] Fix false positive for Style/RedundantStringEscape

### LINKED ISSUE #11098: Bad autocorrect for Style/RedundantStringEscape
The following string is auto-corrected incorrectly by Style/RedundantStringEscape:

```
"#\{foo\}"
```

## Expected behavior

The second escape is not necessary, but the first one is. So one good correction is:

```
"#\{foo}"
```

It seems to be more common to escape the `#` instead, so an alternative good correction is:

```
"\#{foo}"
```

## Actual behavior

The string is corrected to the following, which is definitely not correct:

```
"#{foo}"
```

## Steps to reproduce the problem

- Create a file `foo.rb` containing

```
"#\{foo\}"
```

- Run `rubocop -a foo.rb --only Style/RedundantStringEscape`.

## RuboCop version

```
$ [bundle exec] rubocop -V
1.37.0 (using Parser 3.1.2.1, rubocop-ast 1.22.0, running on ruby 3.1.2) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by tdeo**
Fix incorrect false-positives for escaped interpolation when escaping the character following the `#` instead of the `#` itself.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/redundant_string_escape_spec.rb [hunk 1]
```diff
@@ -21,22 +21,42 @@ def wrap(contents)
...
+    it 'does not register an offense for a @-escaped ivar interpolation' do
+      expect_no_offenses(wrap('#\@foo'))
+    end
+
     it 'does not register an offense for an escaped cvar interpolation' do
       expect_no_offenses(wrap('\#@@foo'))
     end
 
+    it 'does not register an offense for a @-escaped cvar interpolation' do
+      expect_no_offenses(wrap('\#@@foo'))
```
Comment (koic) [inline spec/rubocop/cop/style/redundant_string_escape_spec.rb:41]: It looks the same as the L37.

**Comment by koic** [comment]
It would be better if `expect_offense` and `expect_correction` is written about the following autocorrection.

```diff
-"#\{foo\}"
+"#\{foo}
```

**Comment by bbatsov** [comment]
Looks good. Thanks!
