### PR TITLE
[Fix #11244] Fix a false negative for `Style/RedundantReturn` when dynamic define methods

### LINKED ISSUE #11244: Make Style/RedundantReturn aware of dynamic methods
Potential enhancement to `Style/RedundantReturn`.

Currently, `Style/RedundantReturn` only examines statically-defined methods, and skips those defined via `define_method()`:

```ruby
def foo
  return 42   # Style/RedundantReturn flags redundant return ✔️
end

define_method(:bar) do
  return 42   # Style/RedundantReturn ignores 😔
end
```

It _seems_ like it could support both (but maybe I'm missing something)

### PR DESCRIPTION
**Pull request by ydah**
Fix: #11244

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/redundant_return_spec.rb [hunk 1]
```diff
@@ -54,6 +54,40 @@ def func
...
+      end
+    RUBY
+
+    expect_correction(<<~RUBY)
+      define_method(:foo) do
+        some_preceding_statements
+        something
+      end
+    RUBY
+  end
```
Comment (koic) [inline spec/rubocop/cop/style/redundant_return_spec.rb:72]: The following false negative and autocorrection should be resolved.

```ruby
    expect_offense(<<~RUBY)
      define_method(:foo) do
        return something
        ^^^^^^ Redundant `return` detected.
      end
    RUBY
```

Comment (ydah) [reply spec/rubocop/cop/style/redundant_return_spec.rb:102]: Thank you very much. I updated this PR.

File: lib/rubocop/cop/style/redundant_return.rb [hunk 2]
```diff
@@ -53,6 +53,19 @@ class RedundantReturn < Base
...
+        # @!method method_definition(node)
+        def_node_matcher :method_definition, <<~PATTERN
+          (block (send _ %DYNAMIC_DEFINE_METHODS _) _ $(begin ...))
+        PATTERN
+
+        def on_send(node)
+          method_definition(node.parent) do |def_node|
+            check_branch(def_node)
+          end
+        end
```
[the remark this answers is not in the document]
Comment (ydah) [reply lib/rubocop/cop/style/redundant_return.rb:62]: It certainly looks better that way. Thank you very much. I updated this PR.
