### PR TITLE
[Fix #10771] Make server mode aware of `--cache-root` command line option

### LINKED ISSUE #10771: Server cache does not respect `--cache-root` configuration
We run rubocop with a custom cache folder controlled by `--cache-root` option. Recently, after upgrading to rubocop 1.31, it writes to `~/.cache/rubocop_cache/server` which is not allowed by our CI; and breaks our build as we rely on rubocop as linter. 

Is it possible to make server cache folder customizable?

--------

## Expected behavior

 `Rubocop::Server::Cache` follows the same config in `--cache-root`

## Actual behavior

`Rubocop::Server::Cache` always uses `~/.cache/rubocop_cache/server`

## Steps to reproduce the problem

- Remove all data in cache: `rm -rf ~/.cache/rubocop_cache/`
- Change permission of cache folder: `chmod -w ~/.cache`
- Run rubocop: `bundle exec rubocop --cache=true --cache-root=~/othercache`

## RuboCop version

1.31.0

### PR DESCRIPTION
**Pull request by koic**
Fix #10771.

This PR makes server mode aware of `--cache-root` command line option.

The logic for getting `--cache-root` from command line option is original to make the implementation lighter. Because the client of server mode should be lightweight.
#10842 needs a different solution than `--cache-root` option. I'm working on it separately from solving this issue.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/server/cli_spec.rb [hunk 1]
```diff
@@ -145,6 +145,24 @@
...
+    end
+
+    context 'when using server option with `--server-root=path` option' do
+      it 'returns exit status 0 and display an information message' do
+        expect(cli.run(['--server-status', '--server-root=/tmp'])).to eq(0)
+        expect(cli.exit?).to be(true)
+        expect($stdout.string).to eq "RuboCop server is not running.\n"
+        expect($stderr.string).not_to eq "--server-status cannot be combined with other options.\n"
+      end
+    end
```
Comment (dvandersluis) [inline spec/rubocop/server/cli_spec.rb:165]: Everywhere you have `server-root` here, should it be `cache-root`? Or is this on purpose?

Comment (koic) [reply spec/rubocop/server/cli_spec.rb]: Oops! I've updated to `--cache-root` and adjusted the test code a little.

**Comment by bbatsov** [comment]
Looks good to me. Thanks!
