### PR TITLE
[Fix #11066] -- Update Docs for `Style/CollectionCompact`

### LINKED ISSUE #11066: Collection/Compact on ActionController::Parameters 6.0
I'm seeing this false positive. 
```
lib/blacklight/parameters.rb:14:14: C: [Correctable] Style/CollectionCompact: Use compact instead of reject { |_k, v| v.nil? }.
      params.reject { |_k, v| v.nil? }
             ^^^^^^^^^^^^^^^^^^^^^^^^^
```
When I make this change it fails because ActionController::Parameters 6.0 does not have a compact method.  It doesn't seem like one can infer that a `compact` method exists on an object just because a `.reject` method exists.

### PR DESCRIPTION
**Pull request by PolyCole**
- This PR fixes #11066. 
- Essentially, there's a situation that can happen where Rubocop says that `params.reject { |n| ... }` should be replaced with `params.compact`. However, the params object doesn't have an implementation of `compact`. 
- Since `Style/CollectionCompact` is already marked unsafe, the solution here was to update the associated documentation.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
    * Didn't actually add tests seeing as this is a documentation change, but if y'all have some way to run unit tests against docs lemme know and I'm happy to get that added 😁 
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
   * `"If the new code introduces user-observable changes"` -- I don't believe these changes are user-observable, but am more than happy to add this if it's necessary.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/collection_compact.rb [hunk 1]
```diff
@@ -8,7 +8,8 @@ module Style
       #
       # @safety
       #   It is unsafe by default because false positives may occur in the
-      #   `nil` check of block arguments to the receiver object.
+      #   `nil` check of block arguments to the receiver object. Additionally,
+      #    .compact may not exist for the highlighted object.
```
Comment (bbatsov) [inline lib/rubocop/cop/style/collection_compact.rb:12]: I'd say something like "we can't know for certain the type of the receiver object, which may result in false positives as well".

Comment (PolyCole) [reply lib/rubocop/cop/style/collection_compact.rb]: Will do! Thanks for the quick response @bbatsov, I appreciate it :)
