### PR TITLE
[Fix #14443] Fix false positive in `Layout/EmptyLinesAfterModuleInclusion`

### LINKED ISSUE #14443: Infinite loop caused by Layout/EmptyLinesAfterModuleInclusion -> Layout/EmptyLinesAroundBlockBody
## Expected behavior

RuboCop corrects only true module inclusions with Layout/EmptyLinesAfterModuleInclusion.

## Actual behavior

We are seeing an infinite loop caused by the introduction of Layout/EmptyLinesAfterModuleInclusion. As you can see below, this is not actually a module inclusion, it just seems to be finding instances of `include`.

```
includes = [include, sdk_include].compact.map do |inc|
  "'#{inc}',"
end.join(" ")
```

https://github.com/Homebrew/homebrew-core/blob/6459e6e64fcb1296eaf2bac13cda045fc409b4a4/Formula/lib/libxml2.rb#L109-L111

The below is from our wrapper around RuboCop
```
╰─ brew style --fix libxml2
Infinite loop detected in /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/lib/libxml2.rb and caused by Layout/EmptyLinesAfterModuleInclusion -> Layout/EmptyLinesAroundBlockBody
Taps/homebrew/homebrew-core/Formula/lib/libxml2.rb:109:17: C: [Corrected] Layout/EmptyLinesAfterModuleInclusion: Add an empty line after module inclusion.
    includes = [include, sdk_include].compact.map do |inc|
                ^^^^^^^
Taps/homebrew/homebrew-core/Formula/lib/libxml2.rb:110:1: C: [Corrected] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body beginning.

1 file inspected, 2 offenses detected, 2 offenses corrected

1 error occurred:
Infinite loop detected in /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula/lib/libxml2.rb and caused by Layout/EmptyLinesAfterModuleInclusion -> Layout/EmptyLinesAroundBlockBody
Errors are usually caused by RuboCop bugs.
Please, update to the latest RuboCop version if not already in use, and report a bug if the issue still occurs on this version.

Mention the following information in the issue report:

```

## Steps to reproduce the problem

The code provided above triggers the infinite loop. False positives can also be found in our LLVM formulae:
```
(xctoolchain/"usr").install_symlink [bin, include, lib, libexec, share]
```

## RuboCop version

```
1.79.2 (using Parser 3.3.9.0, rubocop-ast 1.46.0, analyzing as Ruby 2.7, running on ruby 3.4.5) [arm64-darwin20]
```

### PR DESCRIPTION
**Pull request by issyl0**
- Fixes #14443.
- Don't register an offense (and hence don't infinite loop when autocorrecting `Layout/EmptyLinesAfterModuleInclusion` and `Layout/EmptyLinesAroundBlockBody`) when the `include` (or others affected by this cop) send node is/are not followed by a single argument (usually a constant).

Example:

```ruby
includes = [include, sdk_include].compact
```

vs.

```ruby
include SdkIncludeModule
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/empty_lines_after_module_inclusion.rb [hunk 1]
```diff
@@ -92,6 +92,7 @@ def allowed_method?(node)
 
         def next_line_node(node)
           return if node.parent.if_type?
+          return unless node.first_argument&.const_type?
```
Comment (koic) [inline lib/rubocop/cop/layout/empty_lines_after_module_inclusion.rb]: It should be possible to return at an earlier stage and to check based on the arity of the arguments.

```diff
diff --git a/lib/rubocop/cop/layout/empty_lines_after_module_inclusion.rb b/lib/rubocop/cop/layout/empty_lines_after_module_inclusion.rb
index 8340bffa2..16f184c2b 100644
--- a/lib/rubocop/cop/layout/empty_lines_after_module_inclusion.rb
+++ b/lib/rubocop/cop/layout/empty_lines_after_module_inclusion.rb
@@ -38,7 +38,7 @@ module RuboCop
         RESTRICT_ON_SEND = MODULE_INCLUSION_METHODS
 
         def on_send(node)
-          return if node.receiver
+          return if node.receiver || !node.arguments.one?
           return if node.parent&.type?(:send, :any_block)
 
           return if next_line_empty_or_enable_directive_comment?(node.last_line)
@@ -92,7 +92,6 @@ module RuboCop
 
         def next_line_node(node)
           return if node.parent.if_type?
-          return unless node.first_argument&.const_type?
 
           node.right_sibling
         end
```

File: spec/rubocop/cop/layout/empty_lines_after_module_inclusion_spec.rb [hunk 2]
```diff
@@ -242,6 +242,16 @@ module Bar
     RUBY
   end
 
+  it 'does not register an offense when `include` is not followed by a constant' do
```
Comment (koic) [inline spec/rubocop/cop/layout/empty_lines_after_module_inclusion_spec.rb]:
```suggestion
  it 'does not register an offense when `include` does not have exactly one argument'
```

File: changelog/fix_fix_false_positive_in_20250814000019.md [hunk 3]
```diff
@@ -0,0 +1 @@
+* [#14443](https://github.com/rubocop/rubocop/issues/14443): Fix false positive in `Layout/EmptyLinesAfterModuleInclusion`. ([@issyl0][])
```
Comment (koic) [inline changelog/fix_fix_false_positive_in_20250814000019.md]:
```suggestion
* [#14443](https://github.com/rubocop/rubocop/issues/14443): Fix false positive in `Layout/EmptyLinesAfterModuleInclusion` when `include` does not have exactly one argument. ([@issyl0][])
```

**Comment by issyl0** [comment]
Thanks @koic - I made those changes.

File: lib/rubocop/cop/layout/empty_lines_after_module_inclusion.rb [hunk 4]
```diff
@@ -38,7 +38,7 @@ class EmptyLinesAfterModuleInclusion < Base
         RESTRICT_ON_SEND = MODULE_INCLUSION_METHODS
 
         def on_send(node)
-          return if node.receiver
+          return if node.receiver || !node.arguments.one?
```
Comment (lovro-bikic) [inline lib/rubocop/cop/layout/empty_lines_after_module_inclusion.rb:41]: [`include`](https://rubyapi.org/3.4/o/module#method-i-include) and other module inclusion methods can take more than one argument, so this change introduces false negatives.

Comment (issyl0) [reply lib/rubocop/cop/layout/empty_lines_after_module_inclusion.rb:41]: Thanks! Hopefully https://github.com/rubocop/rubocop/pull/14455 is better?

Comment (lovro-bikic) [reply lib/rubocop/cop/layout/empty_lines_after_module_inclusion.rb:41]: Looks good to me, thanks!
