### PR TITLE
[Fix #11123 ] Fix auto correction bug for Style/StringLiterals

### LINKED ISSUE #11123: Incorrect auto-correction for `Style/StringLiterals` cop
Hi there, thanks to all the people working on Rubocop. 

I noticed a weird behaviour when applying an autocorrection to the following code.

```ruby
a = {
  b: "{\"[\\\"*\\\"]\""
}
```

This gets correctly marked as violating `Style/StringLiterals` but when I run rubocop with `-a` (which I assume means it will correct all the cops as long as it is safe to do so) I get this as the output:

```ruby
a = {
  b: '{"["*"]"'
}

```

It seems to me that the autocorrection is too greedy and swollows too many escape characters?

--------

## Expected behavior

I would expect rubocop to either correctly escape the code to:
```ruby
a = {
  b: {"[\"*\"]"
}
```
or it should say that the cop is unsafe and can be used with `-A`, instead of `-a`.

## Actual behavior

Autocorrecting:

```ruby
a = {
  b: "{\"[\\\"*\\\"]\""
}
```

produces:

```ruby
a = {
  b: '{"["*"]"'
}

```

## Steps to reproduce the problem

Create an empty ruby file, add the following piece of code to it:
```ruby
a = {
  b: "{\"[\\\"*\\\"]\""
}
```

run:
```bash
rubocop -a [name-of-the-file]
```

check the file again.

## RuboCop version

```bash
$ rubocop -V
1.37.1 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 2.7.6) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by si-lens**
Fix: https://github.com/rubocop/rubocop/issues/11123

Before:
```
a = {
  b: "{\"[\\\"*\\\"]\""
}
```
was corrected to:
```
a = {
  b: '{"["*"]"'
}
```
These two strings are not the same.
After my changes it should result in correct string:
```
a = {
  b: '{"[\"*\"]"'
}
```
-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [ ] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/quoted_symbols.rb [hunk 1]
```diff
@@ -93,7 +93,7 @@ def correct_quotes(str)
                        end
 
           # The conversion process doubles escaped slashes, so they have to be reverted
-          correction.gsub('\\\\', '\\')
+          correction.gsub('\\\\', '\\').gsub('\"', '"')
```
Comment (koic) [inline lib/rubocop/cop/style/quoted_symbols.rb:96]: Can you add a test for the change?

Comment (si-lens) [reply lib/rubocop/cop/style/quoted_symbols.rb:96]: That change was made to keep [this](https://github.com/rubocop/rubocop/blob/master/spec/rubocop/cop/style/quoted_symbols_spec.rb#L116) test passing. It was the only one to fail after the change was made in `lib/rubocop/cop/util.rb`

**Comment by koic** [comment]
This looks good to me. Can you add a changelog entry? Please see the end of the PR check items for details.

**Comment by bbatsov** [comment]
@si-lens ping :-)

**Comment by si-lens** [comment]
> This looks good to me. Can you add a changelog entry? Please see the end of the PR check items for details.

Oh right, forgot about it! 
There you go 😄

File: changelog/fix_auto_correction_bug_for_string_literals.md [hunk 2]
```diff
@@ -0,0 +1 @@
+* [#11123](https://github.com/rubocop/rubocop/issues/11123): Fix autocorrection bug for `Style/StringLiterals` when using multiple escape characters. ([@si-lens][])
```
Comment (koic) [inline changelog/fix_auto_correction_bug_for_string_literals.md:1]: CI is failing. Can you insert the newline to make the test below pass?

```console
% bundle exec rspec spec/project_spec.rb
(snip)

Failures:

  1) RuboCop Project Changelog future entries For /home/circleci/project/spec/../changelog/fix_auto_correction_bug_for_string_literals.md has newline at end of file
     Failure/Error: expect(changelog.end_with?("\n")).to be true
```

**Comment by koic** [comment]
Thanks!
