### PR TITLE
[Fix #10474] Fix a false positive for `Style/DoubleNegation` with `EnforcedStyle: allowed_in_returns` when inside returned conditional clauses

### LINKED ISSUE #10474: DoubleNegation w/allowed_in_returns incorrectly reports offenses inside returned conditional clauses
Assuming the default configuration for `Style/DoubleNegation`, where `EnforcedStyle: allowed_in_returns`...

## Expected behavior

Double negation should be valid inside hash literals or array literals which are used as return values.

_(ideally, I'd also prefer a more lax `EnforcedStyle: disallow_in_conditionals`, but that needs a feature ticket...)_

## Actual behavior and steps to reproduce the problem

with example.rb:
```ruby
def bangbang_inside_a_hash
  { foo: etc, bar: !!baz } # => okay
end

def bangbang_inside_an_array
  [!!foo0, bar0, baz0]  # => okay
end

def bangbang_inside_an_array_inside_an_if_elsif_else
  if foo?
    [!!foo0, bar0, baz0]  # => incorrectly triggers Style/DoubleNegation
  elsif bar?
    [foo1, !!bar1, baz1]  # => incorrectly triggers Style/DoubleNegation
  elsif baz?
    [foo2, bar2, !!baz2]  # => incorrectly triggers Style/DoubleNegation
  else
    [foo3, !!bar3, baz3]  # => but this is okay
  end
end

def bangbang_inside_an_if_elsif_else_inside_a_hash
  if foo?
    { foo: !!foo0, bar: bar0, baz: baz0 }  # => incorrectly triggers Style/DoubleNegation
  elsif bar?
    { foo: !!foo1, bar: bar1, baz: baz1 }  # => incorrectly triggers Style/DoubleNegation
  elsif baz?
    { foo: !!foo2, bar: bar2, baz: baz2 }  # => incorrectly triggers Style/DoubleNegation
  else
    { foo: !!foo3, bar: bar3, baz: baz3 }  # => but this is okay
  end
end

def bangbang_inside_an_case_when_inside_a_hash
  case foobar
  when Foo
    { foo: !!foo0, bar: bar0, baz: baz0 }  # => incorrectly triggers Style/DoubleNegation
  when Boo
    { foo: !!foo1, bar: bar1, baz: baz1 }  # => incorrectly triggers Style/DoubleNegation
  when FooBar
    { foo: !!foo2, bar: bar2, baz: baz2 }  # => incorrectly triggers Style/DoubleNegation
  else
    { foo: !!foo3, bar: bar3, baz: baz3 }  # => but this is okay
  end
end

def bangbang_inside_an_case_when_inside_a_hash
  case foobar
  in Foo
    { foo: !!foo0, bar: bar0, baz: baz0 }  # => incorrectly triggers Style/DoubleNegation
  in Boo
    { foo: !!foo1, bar: bar1, baz: baz1 }  # => incorrectly triggers Style/DoubleNegation
  in FooBar
    { foo: !!foo2, bar: bar2, baz: baz2 }  # => incorrectly triggers Style/DoubleNegation
  else
    { foo: !!foo3, bar: bar3, baz: baz3 }  # => but this is okay
  end
end

```

The following command:
```sh
rubocop --only Style/DoubleNegation --force-default-config --cache false --debug example.rb
```

Returns the following offenses:

```
Default configuration from /home/nick/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/rubocop-1.26.1/config/default.yml
Inspecting 1 file
Scanning /home/nick/src/mailstrom/tmp/example.rb
C

Offenses:

example.rb:13:6: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    [!!foo0, bar0, baz0]  # => incorrectly triggers Style/DoubleNegation
     ^
example.rb:15:12: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    [foo1, !!bar1, baz1]  # => incorrectly triggers Style/DoubleNegation
           ^
example.rb:17:18: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    [foo2, bar2, !!baz2]  # => incorrectly triggers Style/DoubleNegation
                 ^
example.rb:25:12: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    { foo: !!foo0, bar: bar0, baz: baz0 }  # => incorrectly triggers Style/DoubleNegation
           ^
example.rb:27:12: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    { foo: !!foo1, bar: bar1, baz: baz1 }  # => incorrectly triggers Style/DoubleNegation
           ^
example.rb:29:12: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    { foo: !!foo2, bar: bar2, baz: baz2 }  # => incorrectly triggers Style/DoubleNegation
           ^
example.rb:38:12: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    { foo: !!foo0, bar: bar0, baz: baz0 }  # => incorrectly triggers Style/DoubleNegation
           ^
example.rb:40:12: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    { foo: !!foo1, bar: bar1, baz: baz1 }  # => incorrectly triggers Style/DoubleNegation
           ^
example.rb:42:12: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    { foo: !!foo2, bar: bar2, baz: baz2 }  # => incorrectly triggers Style/DoubleNegation
           ^
example.rb:51:12: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    { foo: !!foo0, bar: bar0, baz: baz0 }  # => incorrectly triggers Style/DoubleNegation
           ^
example.rb:53:12: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    { foo: !!foo1, bar: bar1, baz: baz1 }  # => incorrectly triggers Style/DoubleNegation
           ^
example.rb:55:12: C: [Correctable] Style/DoubleNegation: Avoid the use of double negation (!!).
    { foo: !!foo2, bar: bar2, baz: baz2 }  # => incorrectly triggers Style/DoubleNegation
           ^

1 file inspected, 12 offenses detected, 12 offenses auto-correctable
```

## RuboCop version
```
$ rubocop --force-default-config -V
1.26.1 (using Parser 3.1.1.0, rubocop-ast 1.16.0, running on ruby 2.7.4 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by ydah**
Fixes https://github.com/rubocop/rubocop/issues/10474

This PR fixes a false positive for `Style/DoubleNegation` when code like the following:

```ruby
def foo?
  if condition_foo?
    !!foo
  elsif condition_bar?
    do_something
    !!bar
  else
    !!baz
  end
end

def foo
  if condition_foo?
    { foo: !!foo0, bar: bar0, baz: baz0 }
  elsif condition_bar?
    do_something
    { foo: !!foo1, bar: bar1, baz: baz1 }
  else
    { foo: !!foo2, bar: bar2, baz: baz2 }
  end
end

def foo
  case condition
  when foo
    [ !!foo0, bar0, baz0 ]
  when bar
    do_something
    [ !!foo1, bar1, baz1 ]
  else
    [ !!foo2, bar2, baz2 ]
  end
end
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/double_negation_spec.rb [hunk 1]
```diff
@@ -116,6 +116,93 @@ def foo?
...
+      expect_no_offenses(<<~RUBY)
+        def foo?
+          if condition_foo?
+            !!foo
+          elsif condition_bar?
+            !!bar
+          else
+            !!baz
+          end
+        end
```
Comment (koic) [inline spec/rubocop/cop/style/double_negation_spec.rb:130]: It seems that false positives remain when the test will be updated as follows. The same is true for other tests.

```diff
          if condition_foo?
+           do_something
            !!foo
          elsif condition_bar?
+           do_something
            !!bar
          else
            !!baz
          end
        end
```

Comment (ydah) [reply spec/rubocop/cop/style/double_negation_spec.rb:390]: I had overlooked that case. I'll fix it.

**Comment by ydah** [comment]
I updated this PR. Thank you so much!

File: spec/rubocop/cop/style/double_negation_spec.rb [hunk 2]
```diff
@@ -48,6 +48,249 @@ def foo?
...
+            do_something
+          elsif condition_bar?
+            [ !!foo1, bar1, baz1 ]
+              ^ Avoid the use of double negation (`!!`).
+            do_something
+          else
+            [ !!foo2, bar2, baz2 ]
+              ^ Avoid the use of double negation (`!!`).
+            do_something
+          end
```
Comment (koic) [inline spec/rubocop/cop/style/double_negation_spec.rb:160]: Can you remove spaces inside the array literal brace?

```suggestion
          if condition_foo?
            [!!foo0, bar0, baz0]
              ^ Avoid the use of double negation (`!!`).
            do_something
          elsif condition_bar?
            [!!foo1, bar1, baz1]
              ^ Avoid the use of double negation (`!!`).
            do_something
          else
            [!!foo2, bar2, baz2]
              ^ Avoid the use of double negation (`!!`).
            do_something
          end
```

File: spec/rubocop/cop/style/double_negation_spec.rb [hunk 3]
```diff
@@ -48,6 +48,249 @@ def foo?
...
+            do_something
+            when bar
+            !!bar
+            ^ Avoid the use of double negation (`!!`).
+            do_something
+            else
+            !!baz
+            ^ Avoid the use of double negation (`!!`).
+            do_something
+          end
```
Comment (koic) [inline spec/rubocop/cop/style/double_negation_spec.rb:197]: Can you tweak the indentations for `when` and `else` keywords?

```suggestion
          case condition
          when foo
            !!foo
            ^ Avoid the use of double negation (`!!`).
            do_something
          when bar
            !!bar
            ^ Avoid the use of double negation (`!!`).
            do_something
          else
            !!baz
            ^ Avoid the use of double negation (`!!`).
            do_something
          end
```

**Comment by ydah** [comment]
Oops, sorry for the appearance.
I updated this PR.

File: spec/rubocop/cop/style/double_negation_spec.rb [hunk 4]
```diff
@@ -48,6 +48,249 @@ def foo?
...
+              do_something
+            when bar
+              !!bar
+              ^ Avoid the use of double negation (`!!`).
+              do_something
+            else
+              !!baz
+              ^ Avoid the use of double negation (`!!`).
+              do_something
+          end
```
Comment (koic) [inline spec/rubocop/cop/style/double_negation_spec.rb:197]: That's just my two cents. `case`, `when`, and `else` is better when aligned.

```suggestion
          case condition
          when foo
            !!foo
            ^ Avoid the use of double negation (`!!`).
            do_something
          when bar
            !!bar
            ^ Avoid the use of double negation (`!!`).
            do_something
          else
            !!baz
            ^ Avoid the use of double negation (`!!`).
            do_something
          end
```

**Comment by koic** [comment]
Thanks!

**Comment by nevans** [comment]
Thanks!
