### PR TITLE
[Fix #15048] Fix issue where the url_for is missing for Cops without instance methods

### LINKED ISSUE #15048: RuboCop::Cop::Documentation.url_for returns nil for builtin Cops with no instance methods defined
### Before submitting

- [x] I have searched the existing issues and this hasn't been reported yet.
- [x] I am running the latest stable version of RuboCop.

### Issue type

Other

### Cop name

Layout/AssignmentIndentation, Lint/UnusedBlockArgument, Metrics/CyclomaticComplexity, Metrics/AbcSize, Metrics/PerceivedComplexity, Style/HashExcept, Style/HashSlice

### Steps to reproduce the problem

These cops have no instance methods defined (cop.instance_methods(false).empty? == true), which causes RuboCop::Cop::Documentation.builtin?(cop) to return false on line 59 of lib/rubocop/cop/documentation.rb. As a result, url_for returns nil on line 21.

```ruby
RuboCop::Cop::Documentation.url_for(RuboCop::Cop::Layout::AssignmentIndentation)
# => nil
```

### Expected behavior

```ruby
RuboCop::Cop::Documentation.url_for(RuboCop::Cop::Layout::AssignmentIndentation)
# => "https://docs.rubocop.org/rubocop/cops_layout.html#layoutassignmentindentation"
```

### Actual behavior

```ruby
RuboCop::Cop::Documentation.url_for(RuboCop::Cop::Layout::AssignmentIndentation)
# => nil
```

### RuboCop configuration

```yaml

```

### RuboCop version

```shell
$ bundle exec rubocop -V
1.86.0 (using Parser 3.3.9.0, rubocop-ast 1.49.1, analyzing as Ruby 2.7, running on ruby 3.3.10) [arm64-darwin24]
  - rubocop-performance 1.26.1
  - rubocop-rake 0.7.1
  - rubocop-rspec 3.9.0
```

### PR DESCRIPTION
**Pull request by Fryguy**
Due to the way RuboCop::Cop::Documentation#builtin? checks for the source location by looking at non-inherited instance methods, some cops were not being detected properly as built-in. These cops are

Layout/AssignmentIndentation
Lint/UnusedBlockArgument
Metrics/CyclomaticComplexity
Metrics/AbcSize
Metrics/PerceivedComplexity
Style/HashExcept
Style/HashSlice

This PR changes the detection to look at the const_source_location instead.

Fixes #15048

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/documentation.rb [hunk 1]
```diff
@@ -55,11 +55,9 @@ def default_extension
...
       # @api private
       def builtin?(cop_class)
-        # any custom method will do
-        return false unless (m = cop_class.instance_methods(false).first)
-
-        path, _line = cop_class.instance_method(m).source_location
-        path.start_with?(__dir__)
+        # Get the source location where the class constant was defined
+        path, _line = Module.const_source_location(cop_class.to_s)
+        path&.start_with?(__dir__) || false
```
Comment (koic) [inline lib/rubocop/cop/documentation.rb]: Remove the unnecessary safe navigation and `|| false`, and update it as follows to make the added test case pass.

```suggestion
        return false unless (name = cop_class.name)

        path, _line = Module.const_source_location(name)

        path.start_with?(__dir__)
```

File: spec/rubocop/cop/cop_spec.rb [hunk 2]
```diff
@@ -32,6 +32,15 @@
...
       end
+
+      describe 'for a builtin cop class with only private methods' do
+        let(:cop_class) { RuboCop::Cop::Layout::AssignmentIndentation }
+
+        it 'returns the documentation URL' do
+          expect(cop_class.instance_methods(false)).to be_empty
+          expect(url).to eq 'https://docs.rubocop.org/rubocop/cops_layout.html#layoutassignmentindentation'
+        end
+      end
```
Comment (koic) [inline spec/rubocop/cop/cop_spec.rb:43]: Can you add the following test case?

```suggestion
      end

      describe 'for an anonymous class' do
        it 'is not considered builtin' do
          expect(RuboCop::Cop::Documentation).not_to be_builtin(Class.new)
        end
      end
```

**Comment by Fryguy** [comment]
@koic Done.
