### PR TITLE
[Fix #10592] Fix infinite loop on `Style/MultilineTernaryOperator`

### LINKED ISSUE #10592: Style/MultilineTernaryOperator may create infinite loop
Style/MultilineTernaryOperator created infinite loop in specific code below.

## Expected behavior

No error.

## Actual behavior

```
For E:/tmp: configuration from E:/tmp/.rubocop.yml                                                                          
Default configuration from C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/config/default.yml                     
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in
...(omit)...                                                                                                       
For more information: https://docs.rubocop.org/rubocop/versioning.html                                                      
Inspecting 1 file
Scanning E:/tmp/test.rb
C

Offenses:

test.rb:4:3: C: [Corrected] Style/MultilineTernaryOperator: Avoid multi-line ternary operators, use single-line instead.    
  b == ...
  ^^^^

0 files inspected, 1 offense detected, 1 offense corrected
Infinite loop detected in E:/tmp/test.rb and caused by Style/MultilineTernaryOperator
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:296:in `check_for_infinite_loop'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:279:in `block in iterate_until_no_changes'  
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:278:in `loop'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:278:in `iterate_until_no_changes'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:247:in `do_inspection_loop'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:130:in `block in file_offenses'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:155:in `file_offense_cache'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:129:in `file_offenses'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:120:in `process_file'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:101:in `block in each_inspected_file'       
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:100:in `each'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:100:in `reduce'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:100:in `each_inspected_file'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:86:in `inspect_files'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/runner.rb:47:in `run'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'   
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'  
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/cli/command.rb:11:in `run'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/cli/environment.rb:18:in `run'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/cli.rb:71:in `run_command'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/cli.rb:78:in `execute_runners'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/lib/rubocop/cli.rb:47:in `run'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/exe/rubocop:12:in `block in <top (required)>'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/benchmark-0.2.0/lib/benchmark.rb:311:in `realtime'
C:/develop/Ruby30/lib/ruby/gems/3.0.0/gems/rubocop-1.28.2/exe/rubocop:12:in `<top (required)>'
C:/develop/Ruby30/bin/rubocop:25:in `load'
C:/develop/Ruby30/bin/rubocop:25:in `<main>'
Finished in 0.8523308001458645 seconds                                                                                     
```

## Steps to reproduce the problem

Format this with `-A` option. No config required.
```ruby
a[:a] =
  b ==
    c ? d : e
```

## RuboCop version

```
1.28.2 (using Parser 3.1.2.0, rubocop-ast 1.17.0, running on ruby 3.0.3 i386-mingw32)
```

### PR DESCRIPTION
**Pull request by nobuyo**
…if using assignment method and condition/branch is multiline.

Fixes #10592.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by nobuyo** [comment]
This doesn't solve the case of other assignment-based methods...

```rb
class Test
  def value=(value)
    @value = value
  end
end

test = Test.new
test.value = a ==
  b ? c : d
```

**Comment by nobuyo** [comment]
All assignment methods are now supported by d5f4105be2298805eb204beb08ae9155abc8ce19.

File: lib/rubocop/cop/style/multiline_ternary_operator.rb [hunk 1]
```diff
@@ -73,7 +73,11 @@ def replacement(node)
         end
 
         def enforce_single_line_ternary_operator?(node)
-          SINGLE_LINE_TYPES.include?(node.parent.type)
+          SINGLE_LINE_TYPES.include?(node.parent.type) && !use_assignment_method?(node.parent)
+        end
+
+        def use_assignment_method?(node)
+          node.send_type? && node.method_name.end_with?('=')
```
Comment (koic) [inline lib/rubocop/cop/style/multiline_ternary_operator.rb:80]:
```suggestion
          node.send_type? && node.assignment_method?
```

**Comment by koic** [comment]
Thanks! Incidentally, for some reason your PRs don't trigger CircleCI. If you like, please contact CircleCI :-)

**Comment by nobuyo** [comment]
Thank you, I will give it a try. I was actually just wondering why CircleCI wouldn't start only my PR 😅
