### PR TITLE
[Fix #12138] Fix a false positive for `Layout/LineContinuationLeadingSpace`

### LINKED ISSUE #12138: `Layout/LineContinuationLeadingSpace` false positive
While examining the code for this rule, I noticed that the logic for detecting line continuations might mistakenly identify certain cases as such. 

In the `dstr` node type, lines ending with a backslash are flagged. However, multiline single-quoted strings, also parsed as this node type, are mistakenly flagged if they end with a backslash.

Here's a code example:

```ruby
puts '"this text is too" \
" long"'
```

---
## Expected behavior

No offences for `Layout/LineContinuationLeadingSpace` should arise.

## Actual behavior

An incorrect offence is reported as follows:

```
example.rb:2:2: C: [Correctable] Layout/LineContinuationLeadingSpace: Move leading spaces to the end of the previous line.
" long"'
 ^
```

When applying auto-correction with the `-a` option, it incorrectly alters the code's meaning as shown below:

```ruby
puts '"this text is too " \
"long"'
```

## Steps to reproduce the problem

1. Save the following code in a file named example.rb

```ruby
puts '"this text is too" \
" long"'
```

2. Run `bundle exec rubocop --only=Layout/LineContinuationLeadingSpace example.rb`

## RuboCop version

```
$ bundle exec rubocop -V
1.56.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.0.2) [x86_64-linux]
  - rubocop-performance 1.19.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.23.2
```

### PR DESCRIPTION
**Pull request by ymap**
Fixes rubocop#12138.

This PR fixes a false positive for `Layout/LineContinuationLeadingSpace` when a backslash is part of a multiline string literal.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/line_continuation_leading_space.rb [hunk 1]
```diff
@@ -57,17 +57,15 @@ def on_dstr(node)
...
-            next unless continuation?(raw_line_one)
+              next unless continuation?(raw_line_one, line_num, node)
 
-            if enforced_style_leading?
-              investigate_leading_style(raw_line_one, raw_line_two, end_of_first_line)
-            else
-              investigate_trailing_style(raw_line_one, raw_line_two, end_of_first_line)
+              investigate(raw_line_one, raw_line_two, end_of_first_line)
             end
-          end
```
Comment (koic) [inline lib/rubocop/cop/layout/line_continuation_leading_space.rb:70]: Can you refactor to the below?

```ruby
lines = raw_lines(node)
lines.each_cons(2).with_index(node.first_line) do |(raw_line_one, raw_line_two), line_num|
  end_of_first_line += raw_line_one.length

  next unless continuation?(raw_line_one, line_num, node)

  investigate(raw_line_one, raw_line_two, end_of_first_line)
end
```

**Comment by ymap** [comment]
@koic Thanks for the review! I've amended the commit.

**Comment by koic** [comment]
Thanks!
