### PR TITLE
[Fix #14756] Detect void expressions in `case`/`when` branches

### LINKED ISSUE #14756: Lint/Void should treat "case" and "if" the same way
## Steps to reproduce the problem

```ruby
foo = 1

case foo when 1 then 2 end
puts 3

2 if foo == 1
puts 3
```

## Expected behavior

Both should get `Literal 2 used in void context. [Lint/Void]`

## Actual behavior

The second does. The first doesn't. 

## RuboCop version

```
System Version: macOS 26.1 (25B78)
Model Identifier: MacBookAir10,1
ruby 3.4.8 (2025-12-17 revision 995b59f666) +PRISM [arm64-darwin25]
rubocop     2025-12-22 edca36ebb

```

### PR DESCRIPTION
**Pull request by bbatsov**
`Lint/Void` already detects void expressions inside `if` branches (e.g. `2 if foo == 1`), but missed the equivalent `case`/`when` pattern. This extends the check to recurse into each `when` body and the `else` branch.

### Before

```ruby
# Detected
2 if foo == 1
puts 3

# NOT detected (now fixed)
case foo when 1 then 2 end
puts 3
```

### Changes

- Extended `check_expression` to recurse into `case` nodes, checking each `when` body and `else` branch
- Added autocorrect guard for `when`/`case` parents (same rationale as the existing `if` guard — can't safely delete a branch body)
- Used `node.parent.type?(:if, :when, :case)` per `InternalAffairs/NodeTypeMultiplePredicates`

### Checklist

- [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
- [x] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/).
- [x] Commit message starts with `[Fix #issue-number]`.
- [x] Feature branch is up-to-date with `master`.
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Ran `bundle exec rubocop` on changed files — no offenses.
- [x] Added an entry to the changelog folder.

### CODE REVIEW

File: spec/rubocop/cop/lint/void_spec.rb [hunk 1]
```diff
@@ -1137,6 +1137,73 @@ def foo
...
+  end
+
+  it 'does not register an offense for `case` without when body' do
+    expect_no_offenses(<<~RUBY)
+      case foo
+      when 1
+      end
+      puts :ok
+    RUBY
+  end
```
Comment (koic) [inline spec/rubocop/cop/lint/void_spec.rb:1205]: Similarly to these cases, tests for `case...in...else` would also be necessary.

File: lib/rubocop/cop/lint/void.rb [hunk 2]
```diff
@@ -120,8 +120,13 @@ def check_begin(node)
...
 
         def check_expression(expr)
-          expr = expr.body if expr.if_type?
-          return unless expr
+          if expr.if_type?
+            expr = expr.body
+            return unless expr
+          elsif expr.case_type?
+            check_case_expression(expr)
+            return
```
Comment (koic) [inline lib/rubocop/cop/lint/void.rb]: It looks like logic is also needed for `case_match_type?`.

```suggestion
          elsif expr.case_type?
            check_case_expression(expr)
            return
          elsif expr.case_match_type?
            check_case_match_expression(expr)
            return
```

File: lib/rubocop/cop/lint/void.rb [hunk 3]
```diff
@@ -132,6 +137,11 @@ def check_expression(expr)
           check_nonmutating(expr)
         end
 
+        def check_case_expression(case_node)
+          case_node.each_when { |when_node| check_expression(when_node.body) if when_node.body }
+          check_expression(case_node.else_branch) if case_node.else_branch
+        end
```
Comment (koic) [inline lib/rubocop/cop/lint/void.rb:147]: A similar process using `each_in_pattern` also seems necessary.

```suggestion
        end

        def check_case_match_expression(case_node)
          case_node.each_in_pattern do |when_node|
            check_expression(when_node.body) if when_node.body
          end
          check_expression(case_node.else_branch) if case_node.else_branch
        end
```

File: lib/rubocop/cop/lint/void.rb [hunk 4]
```diff
@@ -238,7 +248,7 @@ def autocorrect_void_op(corrector, node)
         end
 
         def autocorrect_void_expression(corrector, node)
-          return if node.parent.if_type?
+          return if node.parent.type?(:if, :when, :case)
```
Comment (koic) [inline lib/rubocop/cop/lint/void.rb]: Logic like the following would be needed.

```suggestion
          return if node.parent.type?(:if, :case, :when, :case_match, :in_pattern)
```

**Comment by bbatsov** [comment]
@koic All feedback addressed — thanks for the review! Added `case...in` pattern matching support and fixed the `Metrics/MethodLength` CI failure by extracting the dispatch logic in `check_expression`.

**Comment by koic** [comment]
Thank you!
