### PR TITLE
[Fix #10528] Fix an infinite loop at autocorrect for `Layout/CaseIndentation`

### LINKED ISSUE #10528: Infinite loop on autocorrect due to Layout/BeginEndAlignment and Layout/CaseIndentation
Autocorrecting a small bit of code can add a ton of spaces to a file before giving up with an infinite loop.

I think I've tracked it down to a confluence of these two rules. I found the problem by a recent stanardrb update, but I've reproduced it with a minimal rubocop.yml alone

--------

## Expected behavior

I had hoped that it would autocorrect the code.

## Actual behavior

It added a ton of spaces to each case statement, then raised an exception and stopped.

## Steps to reproduce the problem

rubocop.yml
```yml
AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/BeginEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
  AutoCorrect: true
  Severity: warning

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end
```

a.rb
```ruby
# frozen_string_literal: true

case thing
when 3 then 1
when 2 then 2
else 3 end
```

It detects the problem fine

```
$ rubocop --debug a.rb
For /private/tmp/a: configuration from /private/tmp/a/.rubocop.yml
Default configuration from /Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/config/default.yml
Use parallel by default.
Running parallel inspection
Loading cache from /Users/will/.cache/rubocop_cache/825c5a2911314cb7c60896dcbcc0661f3f0753f0/6d7a3b621ca1730e04accd938619e4bdab66cfb1/1ac18ecaa1b4d525f467c225566c3b347384be48
Inspecting 1 file
Scanning /private/tmp/a/a.rb
Loading cache from /Users/will/.cache/rubocop_cache/825c5a2911314cb7c60896dcbcc0661f3f0753f0/6d7a3b621ca1730e04accd938619e4bdab66cfb1/1ac18ecaa1b4d525f467c225566c3b347384be48
C

Offenses:

a.rb:4:1: C: [Correctable] Layout/CaseIndentation: Indent when as deep as end.
when 3 then 1
^^^^
a.rb:5:1: C: [Correctable] Layout/CaseIndentation: Indent when as deep as end.
when 2 then 2
^^^^

1 file inspected, 2 offenses detected, 2 offenses auto-correctable
Finished in 0.1309340000152588 seconds
^^^^

1 file inspected, 2 offenses detected, 2 offenses auto-correctable
```

but when using `-x` 


```
For /private/tmp/a: configuration from /private/tmp/a/.rubocop.yml
Default configuration from /Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/config/default.yml
Inspecting 1 file
Scanning /private/tmp/a/a.rb
C

Offenses:

a.rb:4:1: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
when 3 then 1
^^^^
a.rb:4:8: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
       when 3 then 1
       ^^^^
a.rb:4:15: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
              when 3 then 1
              ^^^^
a.rb:4:22: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                     when 3 then 1
                     ^^^^
a.rb:4:29: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                            when 3 then 1
                            ^^^^
a.rb:4:36: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                   when 3 then 1
                                   ^^^^
a.rb:4:43: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                          when 3 then 1
                                          ^^^^
a.rb:4:50: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                                 when 3 then 1
                                                 ^^^^
a.rb:4:57: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                                        when 3 then 1
                                                        ^^^^
a.rb:4:64: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                                               when 3 then 1
                                                               ^^^^
a.rb:4:71: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                                                      when 3 then 1
                                                                      ^^^^
a.rb:4:78: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                                                             when 3 then 1
                                                                             ^^^^
a.rb:4:85: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                                                                    when 3 then 1
                                                                                    ^^^^
a.rb:4:92: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                                                                           when 3 then 1
                                                                                           ^^^^
a.rb:4:99: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                                                                                  when 3 then 1
                                                                                                  ^^^^
a.rb:4:106: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                                                                                         when 3 then 1
                                                                                                         ^^^^
a.rb:4:113: C: [Corrected] Layout/CaseIndentation: Indent when as deep as end.
                                                                                                                when 3 then 1
                                                                                                                ^^^^

<<this just keeps going, I've cut it out>>

a.rb:6:694: C: [Corrected] Layout/ElseAlignment: Align else with when.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     else 3 end
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ^^^^

0 files inspected, 303 offenses detected, 300 offenses corrected
Infinite loop detected in /private/tmp/a/a.rb and caused by Layout/ElseAlignment, Layout/LineLength
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:284:in `block in iterate_until_no_changes'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:280:in `loop'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:280:in `iterate_until_no_changes'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:249:in `do_inspection_loop'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:130:in `block in file_offenses'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:155:in `file_offense_cache'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:129:in `file_offenses'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:120:in `process_file'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:100:in `each'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:100:in `reduce'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:86:in `inspect_files'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:47:in `run'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/cli.rb:71:in `run_command'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/cli.rb:78:in `execute_runners'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/lib/rubocop/cli.rb:47:in `run'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/exe/rubocop:12:in `block in <top (required)>'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/Users/will/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/rubocop-1.27.0/exe/rubocop:12:in `<top (required)>'
/Users/will/.asdf/installs/ruby/3.1.1/bin/rubocop:25:in `load'
/Users/will/.asdf/installs/ruby/3.1.1/bin/rubocop:25:in `<main>'
Finished in 1.3684570000041276 seconds
```




## RuboCop version

```
/t/a> rubocop -V
1.27.0 (using Parser 3.1.1.0, rubocop-ast 1.17.0, running on ruby 3.1.1 x86_64-darwin20)
```

### PR DESCRIPTION
**Pull request by ydah**
Fixes https://github.com/rubocop/rubocop/issues/10528

The following rubocop.yml and run rubocop, resulted in an infinite loop.

```
Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: start_of_line
  AutoCorrect: true

Layout/CaseIndentation:
  EnforcedStyle: end
```

This doesn’t always occur, but only in edge cases.
This occurs when `when` and `end` are on the same line, as in the following code:

```
# frozen_string_literal: true

case thing
when 3 then 1
when 2 then 2
else 3 end
```
This means that if `Layout/CaseIndentation` is `EnforcedStyle: end` and `when` or `else` is on the same line as `end`, it will try to adjust the indentation of `else` or `end` to match that of `end`, but will not Because they are on the same line, the indentation adjustment will run many times.
So, if `when` or `else` is on the same line as `end` and `Layout/CaseIndentation` is `EnforcedStyle: end`, do not make auto-correction.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by will** [comment]
Thanks @ydah :)

File: lib/rubocop/cop/layout/case_indentation.rb [hunk 1]
```diff
@@ -109,6 +109,19 @@ module Layout
...
+      #   when 0
+      #   else end
+      #
+      #   case n
+      #   when 0
+      #   when 1 then end
+      #
+      #   case n
+      #   in pattern1 then 0
+      #   in pattern2 then 1 end
```
Comment (koic) [inline lib/rubocop/cop/layout/case_indentation.rb:124]: Hm, I'm worried whether it's preferable to show these as "good" style examples. These may not be needed as examples.

Comment (ydah) [reply lib/rubocop/cop/layout/case_indentation.rb]: I thought that was certainly true. I think it was quite excessive.
I've removed the relevant "good examples".

**Comment by ydah** [comment]
I updated this PR. Thank you so much!

**Comment by koic** [comment]
Thanks!
