### PR TITLE
[Fix #13299] Fix `Style/BlockDelimiters` to always accept braces when an operator method argument is chained

### LINKED ISSUE #13299: Autocorrect from `Layout/LineLength` can rewrite blocks into incompatible variants
Reported in https://github.com/rubocop/rubocop/discussions/13294

## Expected behavior

```yml
AllCops:
  NewCops: enable

Style/FormatString:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/LineLength:
  Max: 55
```

```rb
# frozen_string_literal: true

def foo(*, help:, **)
  pp help
end

foo :bar, :baaaaaaaaaaz, baaaaat: 'aaaaa',
                         help: 'Some text: %s' %
                               %w[foo bar].map { |v| v.upcase }.join(', ')
```

I expect the autocorrect to be safe.

## Actual behavior

`Layout/LineLength` triggers, rewriting the block to be multiline which somehow breaks things:

```rb
# frozen_string_literal: true

def foo(*, help:, **)
  pp help
end

foo :bar, :baaaaaaaaaaz, baaaaat: 'aaaaa',
                         help: 'Some text: %s' %
                               %w[foo bar].map do |v|
                                 v.upcase
                               end.join(', ')
# $ ruby test.rb
# "Some text: #<Enumerator:0x00007edb3df00518>"
# test.rb:11:in `<main>': undefined method `join' for an instance of String (NoMethodError)
#
#                                end.join(', ')
#                                   ^^^^^
```

Probably the ast has some different nesting levels. I am not quite sure.

## RuboCop version

```
$ [bundle exec] rubocop -V
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, running on ruby 3.3.5) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by dvandersluis**
Update `Style/BlockDelimiters` to not register an offense when braces are necessary to avoid changing precedence. Previously when an operator method was encountered, it was automatically evaluated (ie. not marked as ignored), but this can result in block delimiters being changed that affects block binding.

Now operator methods are evaluated for nodes to ignore, other than if it only has a single argument which is of block type.

As well, I added the missing `expect_corrections` tests for offenses without it.

Fixes #13299.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/block_delimiters_spec.rb [hunk 1]
```diff
@@ -338,21 +408,6 @@
...
-          x
-        end
-      RUBY
-
-      expect_correction(<<~RUBY)
-        foo = map { |x|
-          x
-        }
-      RUBY
-    end
```
Comment (dvandersluis) [inline spec/rubocop/cop/style/block_delimiters_spec.rb:354]: The tests that were starting on lines 341 and 371 were duplicates and have been removed now that the tests higher up have `expect_correction` checks.
