### PR TITLE
[Fix #12373] Fix a false negative for Lint/SymbolConversion

### LINKED ISSUE #12373: False negative with `Lint/SymbolConversion` in combination with string interpolation
With code like this I expect `Lint/SymbolConversion` to trigger an offence. Interpolation isn't currently considered.

```rb
foo = "bar"
"#{foo}_baz".to_sym
=> :bar_baz
```

Autocorrect would be the following which is equivalent:

```rb
:"#{foo}_baz"
```

## RuboCop version

```
1.55.1 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.2.2) [x86_64-linux-musl]
  - rubocop-erb 0.3.0
  - rubocop-rails 2.20.2
```

### PR DESCRIPTION
**Pull request by Earlopain**
Issue #12373: This PR fixes a false negative for `Lint/SymbolConversion` when using string interpolation

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [ x Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/symbol_conversion_spec.rb [hunk 1]
```diff
@@ -154,6 +158,19 @@
...
+        # rubocop:disable Lint/LiteralInInterpolation
+        expect_offense(<<~RUBY)
+          { foo: "bar-#{'baz'}".to_sym }
+                 ^^^^^^^^^^^^^^^^ Unnecessary symbol conversion; use `:"bar-#{'baz'}"` instead.
+        RUBY
+
+        expect_correction(<<~RUBY)
+          { foo: :"bar-#{'baz'}" }
+        RUBY
+        # rubocop:enable Lint/LiteralInInterpolation
```
Comment (koic) [inline spec/rubocop/cop/lint/symbol_conversion_spec.rb:172]: > The 5 characters from the literal interpolation are discarded and as such the range is off by that many characters. I have no idea where to start with that. I believe that issue may be unrelated to this PR.

The heredoc needs to be equivalent to single quotes. The following should resolve it:

```suggestion
        expect_offense(<<~'RUBY')
          { foo: "bar-#{'baz'}".to_sym }
                 ^^^^^^^^^^^^^^^^^^^^^ Unnecessary symbol conversion; use `:"bar-#{'baz'}"` instead.
        RUBY

        expect_correction(<<~'RUBY')
          { foo: :"bar-#{'baz'}" }
        RUBY
```

File: spec/rubocop/cop/lint/symbol_conversion_spec.rb [hunk 2]
```diff
@@ -124,6 +120,14 @@
           { '==': 'bar' }
         RUBY
       end
+
+      it 'does not register an offense for dstr' do
+        # rubocop:disable Lint/LiteralInInterpolation
+        expect_no_offenses(<<~RUBY)
+          { "foo-#{'bar'}": 'baz' }
+        RUBY
+        # rubocop:enable Lint/LiteralInInterpolation
```
Comment (koic) [inline spec/rubocop/cop/lint/symbol_conversion_spec.rb:129]:
```suggestion
        expect_no_offenses(<<~'RUBY')
          { "foo-#{'bar'}": 'baz' }
        RUBY
```

File: lib/rubocop/cop/lint/symbol_conversion.rb [hunk 3]
```diff
@@ -19,13 +19,15 @@ module Lint
       #   'underscored_string'.to_sym
       #   :'underscored_symbol'
       #   'hyphenated-string'.to_sym
+      #   "foo_#{bar}".to_sym
```
Comment (koic) [inline lib/rubocop/cop/lint/symbol_conversion.rb:22]: Nits:

```suggestion
      #   "interpolated_#{string}".to_sym
```

File: lib/rubocop/cop/lint/symbol_conversion.rb [hunk 4]
```diff
@@ -19,13 +19,15 @@ module Lint
...
       #
       #   # good
       #   :string
       #   :symbol
       #   :underscored_string
       #   :underscored_symbol
       #   :'hyphenated-string'
+      #   :"foo_#{bar}"
```
Comment (koic) [inline lib/rubocop/cop/lint/symbol_conversion.rb:30]:
```suggestion
      #   :"interpolated_#{string}"
```

**Review by koic — APPROVED** [review]
Looks good to me!

**Comment by bbatsov** [comment]
Agreed. Thanks for tackling this!

**Comment by Earlopain** [comment]
> Hello, a similar feature could be implemented in rubocop-performance for `Performance/StringIdentifierArgument`

Good suggestion, I have created https://github.com/rubocop/rubocop-performance/pull/387
