### PR TITLE
[Fix #11139] Fix a false negative for `Style/HashEachMethods` when using each with a symbol proc argument

### LINKED ISSUE #11139: Style/HashEachMethods doesn't detect &blocks
Currently, `Style/HashEachMethods` detects regular blocks and numblocks, but ignores &blocks:

```ruby
h.keys.each { ... }
# Style/HashEachMethods suggests: h.each_key { ... } ✔️

h.keys.each(&:foo)
# Style/HashEachMethods ignores ❌
```

Ideally, it should recommend:
```ruby
h.each_key(&:foo)
```

### PR DESCRIPTION
**Pull request by ydah**
Fix: #11139

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/hash_each_methods.rb [hunk 1]
```diff
@@ -38,28 +38,55 @@ class HashEachMethods < Base
           ({block numblock} $(send (send _ ${:keys :values}) :each) ...)
         PATTERN
 
+        # @!method block_pass_each(node)
+        def_node_matcher :block_pass_each, <<~PATTERN
```
Comment (koic) [inline lib/rubocop/cop/style/hash_each_methods.rb:42]:
```suggestion
        def_node_matcher :kv_each_with_block_pass, <<~PATTERN
```

File: lib/rubocop/cop/style/hash_each_methods.rb [hunk 2]
```diff
@@ -38,28 +38,55 @@ class HashEachMethods < Base
...
-            msg = format(message, prefer: "each_#{method[0..-2]}", current: "#{method}.each")
+          add_offense(kv_range(target), message: format_message(method)) do |corrector|
+            correct_key_value_each(target, corrector)
+          end
+        end
 
-            add_offense(kv_range(target), message: msg) do |corrector|
-              correct_key_value_each(target, corrector)
-            end
+        def register_block_pass_offense(node, target, method)
```
Comment (koic) [inline lib/rubocop/cop/style/hash_each_methods.rb:70]:
```suggestion
        def register_kv_with_block_pass_offense(node, target, method)
```

File: lib/rubocop/cop/style/hash_each_methods.rb [hunk 3]
```diff
@@ -38,28 +38,55 @@ class HashEachMethods < Base
...
+          return if ignored_receiver?(node.parent)
+
+          range = target.loc.selector.with(end_pos: node.parent.loc.selector.end_pos)
+          add_offense(range, message: format_message(method)) do |corrector|
+            corrector.replace(range, "each_#{method[0..-2]}")
           end
         end
 
+        def ignored_receiver?(node)
```
Comment (koic) [inline lib/rubocop/cop/style/hash_each_methods.rb:79]: Can you inline this method into `allowed_receiver?(receiver)? Because the terminologies and roles are mixed.

File: lib/rubocop/cop/style/hash_each_methods.rb (hunk 1 above)
Comment (ydah) [reply lib/rubocop/cop/style/hash_each_methods.rb]: Thank you. I updated it.

File: lib/rubocop/cop/style/hash_each_methods.rb (hunk 2 above)
Comment (ydah) [reply lib/rubocop/cop/style/hash_each_methods.rb]: Thank you. I updated it.

File: lib/rubocop/cop/style/hash_each_methods.rb (hunk 3 above)
Comment (ydah) [reply lib/rubocop/cop/style/hash_each_methods.rb]: Indeed it is. I inlined it.

**Comment by ydah** [comment]
I updated this PR. Thank you so much.

File: spec/rubocop/cop/style/hash_each_methods_spec.rb [hunk 4]
```diff
@@ -25,6 +25,17 @@
...
+      it 'registers offense, autocorrects foo#key.each to foo#each_key with a symbol proc argument' do
+        expect_offense(<<~RUBY)
+          foo.keys.each(&:bar)
+              ^^^^^^^^^ Use `each_key` instead of `keys.each`.
+        RUBY
+
+        expect_correction(<<~RUBY)
+          foo.each_key(&:bar)
+        RUBY
+      end
```
Comment (koic) [inline spec/rubocop/cop/style/hash_each_methods_spec.rb:37]: Can you add a test for `values.each(&:bar)` like `keys.each(&:bar)`?

File: spec/rubocop/cop/style/hash_each_methods_spec.rb [hunk 5]
```diff
@@ -70,6 +81,17 @@
...
+      it 'registers offense, autocorrects {}#key.each to {}#each_key with a symbol proc argument' do
+        expect_offense(<<~RUBY)
+          {}.keys.each(&:bar)
+             ^^^^^^^^^ Use `each_key` instead of `keys.each`.
+        RUBY
+
+        expect_correction(<<~RUBY)
+          {}.each_key(&:bar)
+        RUBY
+      end
```
Comment (koic) [inline spec/rubocop/cop/style/hash_each_methods_spec.rb:93]: Ditto.

File: spec/rubocop/cop/style/hash_each_methods_spec.rb [hunk 6]
```diff
@@ -92,6 +114,12 @@
         RUBY
       end
 
+      it 'does not register an offense for `keys.each` with a symbol proc argument' do
+        expect_no_offenses(<<~RUBY)
+          keys.each(&:bar)
+        RUBY
+      end
```
Comment (koic) [inline spec/rubocop/cop/style/hash_each_methods_spec.rb:121]: The same may be said here.

**Comment by ydah** [comment]
I updated this PR. Thank you so much.

File: spec/rubocop/cop/style/hash_each_methods_spec.rb [hunk 7]
```diff
@@ -25,6 +25,28 @@
         RUBY
       end
 
+      it 'registers offense, autocorrects foo#key.each to foo#each_key with a symbol proc argument' do
```
Comment (koic) [inline spec/rubocop/cop/style/hash_each_methods_spec.rb:28]:
```suggestion
      it 'registers offense, autocorrects foo#keys.each to foo#each_key with a symbol proc argument' do
```

File: spec/rubocop/cop/style/hash_each_methods_spec.rb [hunk 8]
```diff
@@ -25,6 +25,28 @@
...
+          foo.keys.each(&:bar)
+              ^^^^^^^^^ Use `each_key` instead of `keys.each`.
+        RUBY
+
+        expect_correction(<<~RUBY)
+          foo.each_key(&:bar)
+        RUBY
+      end
+
+      it 'registers offense, autocorrects foo#key.each to foo#each_value with a symbol proc argument' do
```
Comment (koic) [inline spec/rubocop/cop/style/hash_each_methods_spec.rb:39]:
```suggestion
      it 'registers offense, autocorrects foo#values.each to foo#each_value with a symbol proc argument' do
```

File: spec/rubocop/cop/style/hash_each_methods_spec.rb [hunk 9]
```diff
@@ -70,6 +92,28 @@
         RUBY
       end
 
+      it 'registers offense, autocorrects {}#key.each to {}#each_key with a symbol proc argument' do
```
Comment (koic) [inline spec/rubocop/cop/style/hash_each_methods_spec.rb:95]:
```suggestion
      it 'registers offense, autocorrects {}#keys.each to {}#each_key with a symbol proc argument' do
```

File: spec/rubocop/cop/style/hash_each_methods_spec.rb [hunk 10]
```diff
@@ -70,6 +92,28 @@
...
+          {}.keys.each(&:bar)
+             ^^^^^^^^^ Use `each_key` instead of `keys.each`.
+        RUBY
+
+        expect_correction(<<~RUBY)
+          {}.each_key(&:bar)
+        RUBY
+      end
+
+      it 'registers offense, autocorrects {}#key.each to {}#each_value with a symbol proc argument' do
```
Comment (koic) [inline spec/rubocop/cop/style/hash_each_methods_spec.rb:106]:
```suggestion
      it 'registers offense, autocorrects {}#values.each to {}#each_value with a symbol proc argument' do
```

**Comment by ydah** [comment]
Thank you so much!
