### PR TITLE
[Fix #13836] Fix an error for `Style/RedundantParentheses`

### LINKED ISSUE #13836: "Expected a Parser::Source::Range, Comment or RuboCop::AST::Node, got NilClass" in Style/RedundantParentheses
## Expected behavior

Complete `rubocop .` successfully

## Actual behavior

```
An error occurred while Style/RedundantParentheses cop was inspecting /Users/pcothenet/Projects/patch/app/presenters/inventory_management/sale/project_form_presenter.rb:184:4.
Expected a Parser::Source::Range, Comment or RuboCop::AST::Node, got NilClass
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/corrector.rb:111:in 'RuboCop::Cop::Corrector#to_range'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/corrector.rb:120:in 'RuboCop::Cop::Corrector#check_range_validity'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/parser-3.3.7.1/lib/parser/source/tree_rewriter.rb:398:in 'Parser::Source::TreeRewriter#combine'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/parser-3.3.7.1/lib/parser/source/tree_rewriter.rb:194:in 'Parser::Source::TreeRewriter#replace'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/parser-3.3.7.1/lib/parser/source/tree_rewriter.rb:218:in 'Parser::Source::TreeRewriter#remove'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/correctors/parentheses_corrector.rb:13:in 'RuboCop::Cop::ParenthesesCorrector.correct'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/style/redundant_parentheses.rb:206:in 'block in RuboCop::Cop::Style::RedundantParentheses#offense'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/base.rb:426:in 'RuboCop::Cop::Base#correct'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/base.rb:210:in 'RuboCop::Cop::Base#add_offense'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-rails-2.29.1/lib/rubocop/rails/migration_file_skippable.rb:29:in 'RuboCop::Rails::MigrationFileSkippable#add_offense'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/style/redundant_parentheses.rb:205:in 'RuboCop::Cop::Style::RedundantParentheses#offense'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/style/redundant_parentheses.rb:140:in 'RuboCop::Cop::Style::RedundantParentheses#check'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/style/redundant_parentheses.rb:40:in 'RuboCop::Cop::Style::RedundantParentheses#on_begin'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:107:in 'Kernel#public_send'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:107:in 'block (2 levels) in RuboCop::Cop::Commissioner#trigger_responding_cops'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:171:in 'RuboCop::Cop::Commissioner#with_cop_error_handling'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:106:in 'block in RuboCop::Cop::Commissioner#trigger_responding_cops'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:105:in 'Array#each'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:105:in 'RuboCop::Cop::Commissioner#trigger_responding_cops'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:69:in 'RuboCop::Cop::Commissioner#on_begin'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.38.0/lib/rubocop/ast/traversal.rb:137:in 'block in RuboCop::AST::Traversal#on_dstr'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.38.0/lib/rubocop/ast/traversal.rb:137:in 'Array#each'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.38.0/lib/rubocop/ast/traversal.rb:137:in 'RuboCop::AST::Traversal#on_dstr'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_begin'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.38.0/lib/rubocop/ast/traversal.rb:154:in 'RuboCop::AST::Traversal#on_def'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_def'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.38.0/lib/rubocop/ast/traversal.rb:137:in 'block in RuboCop::AST::Traversal#on_dstr'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.38.0/lib/rubocop/ast/traversal.rb:137:in 'Array#each'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.38.0/lib/rubocop/ast/traversal.rb:137:in 'RuboCop::AST::Traversal#on_dstr'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_begin'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.38.0/lib/rubocop/ast/traversal.rb:154:in 'RuboCop::AST::Traversal#on_class'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:71:in 'RuboCop::Cop::Commissioner#on_class'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-ast-1.38.0/lib/rubocop/ast/traversal.rb:20:in 'RuboCop::AST::Traversal#walk'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/commissioner.rb:87:in 'RuboCop::Cop::Commissioner#investigate'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/team.rb:174:in 'RuboCop::Cop::Team#investigate_partial'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cop/team.rb:108:in 'RuboCop::Cop::Team#investigate'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:348:in 'block in RuboCop::Runner#inspect_file'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:347:in 'Array#each'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:347:in 'Enumerable#flat_map'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:347:in 'RuboCop::Runner#inspect_file'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:290:in 'block in RuboCop::Runner#do_inspection_loop'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:324:in 'block in RuboCop::Runner#iterate_until_no_changes'
<internal:kernel>:168:in 'Kernel#loop'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:317:in 'RuboCop::Runner#iterate_until_no_changes'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:286:in 'RuboCop::Runner#do_inspection_loop'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:167:in 'block in RuboCop::Runner#file_offenses'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:192:in 'RuboCop::Runner#file_offense_cache'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:166:in 'RuboCop::Runner#file_offenses'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:154:in 'RuboCop::Runner#process_file'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:135:in 'block in RuboCop::Runner#each_inspected_file'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:134:in 'Array#each'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:134:in 'Enumerable#reduce'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:134:in 'RuboCop::Runner#each_inspected_file'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:120:in 'RuboCop::Runner#inspect_files'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/runner.rb:73:in 'RuboCop::Runner#run'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli/command/execute_runner.rb:26:in 'block in RuboCop::CLI::Command::ExecuteRunner#execute_runner'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli/command/execute_runner.rb:52:in 'RuboCop::CLI::Command::ExecuteRunner#with_redirect'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli/command/execute_runner.rb:25:in 'RuboCop::CLI::Command::ExecuteRunner#execute_runner'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli/command/execute_runner.rb:17:in 'RuboCop::CLI::Command::ExecuteRunner#run'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli/command.rb:11:in 'RuboCop::CLI::Command.run'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli/environment.rb:18:in 'RuboCop::CLI::Environment#run'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli.rb:122:in 'RuboCop::CLI#run_command'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli.rb:129:in 'RuboCop::CLI#execute_runners'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli.rb:51:in 'block in RuboCop::CLI#run'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli.rb:81:in 'RuboCop::CLI#profile_if_needed'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/lib/rubocop/cli.rb:43:in 'RuboCop::CLI#run'
/Users/pcothenet/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/rubocop-1.72.0/exe/rubocop:19:in '<top (required)>'
./bin/rubocop:8:in 'Kernel#load'
./bin/rubocop:8:in '<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Style/RedundantParentheses cop was inspecting /Users/pcothenet/Projects/patch/app/presenters/inventory_management/sale/project_form_presenter.rb:184:4.
configuration from /Users/pcothenet/Projects/patch/.rubocop.yml
```

## Steps to reproduce the problem

Run Rubocop on a file with a method returning a range defined with parentheses:

```
  def method
    bla
    (min_value..max_value)
  end
```

Note that I can fix by removing the parentheses, but the parser chokes otherwise.

## RuboCop version

```
$ [bundle exec] rubocop -V
1.72.0 (using Parser 3.3.7.1, rubocop-ast 1.38.0, analyzing as Ruby 3.4, running on ruby 3.4.1) [arm64-darwin24]
  - rubocop-capybara 2.21.0
  - rubocop-factory_bot 2.26.1
  - rubocop-performance 1.23.1
  - rubocop-rails 2.29.1
  - rubocop-rake 0.6.0
  - rubocop-rspec 3.4.0
```

### PR DESCRIPTION
**Pull request by koic**
This PR fixes an error for `Style/RedundantParentheses` when a different expression appears before a range literal.

Fixes #13836.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/redundant_parentheses_spec.rb [hunk 1]
```diff
@@ -697,6 +697,20 @@ def x
     expect_no_offenses('(a...b)')
   end
 
+  it 'accepts parentheses around an irange when a different expression precedes it' do
+    expect_no_offenses(<<~RUBY)
+      do_something
+      (a..b)
```
Comment (bbatsov) [inline spec/rubocop/cop/style/redundant_parentheses_spec.rb:703]: Hmm, why are the parens needed here?

Comment (koic) [reply spec/rubocop/cop/style/redundant_parentheses_spec.rb:703]: Yeah, the parentheses are not required for grammatical correctness. However, even in the current behavior, parentheses are preserved to respect cases where range literals are explicitly enclosed for clarity.

Comment (bbatsov) [reply spec/rubocop/cop/style/redundant_parentheses_spec.rb:703]: I see. That's not documented anywhere, though, so at the very least it should be made explicit, and even better - configurable.

**Comment by bbatsov** [comment]
I'll merge this to address the error, but overall I'm not very happy that we're implicitly accepting parentheses in cases where they are technically speaking redundant.
