### PR TITLE
[Fix #10766] Use the path given by `--cache-root` to be the parent for  `rubocop_cache` dir like other ways to specify it

### LINKED ISSUE #10766: Odd inconsistency with `--cache-root`
## Expected behavior

Configuring `--cache-root` would behave exactly like setting `RUBOCOP_CACHE_ROOT` or `AllCops: CacheRootDirectory`, modulo precedence.

## Actual behavior

The `--cache-root` flag specifies the exact cache folder. The other two options end up creating a nested `rubocop_cache` directory. I think I see from the code why this is happening but it is perplexing as an end user (and messed up my CI cache at first).

## Steps to reproduce the problem

Specify a directory to `--cache-root` and separately either of the other options and observe that the directory structure it creates is different.

## RuboCop version

```
1.31.0 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 2.7.6 x86_64-linux)
  - rubocop-performance 1.14.2
  - rubocop-rspec 2.11.1
```

I'm not sure if this should be changed to match or if the difference should just be documented but it is very surprising as-is. I actually prefer the `--cache-root` behavior (so i don't have an extra nesting of directories) but the main issue here is that it is confusing.

### PR DESCRIPTION
**Pull request by nobuyo**
Fixes #10766. 

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/result_cache.rb [hunk 1]
```diff
@@ -91,6 +91,7 @@ def initialize(file, team, options, config_store, cache_root = nil)
       @allow_symlinks_in_cache_location =
         ResultCache.allow_symlinks_in_cache_location?(config_store)
       @path = File.join(cache_root,
+                        'rubocop_cache',
```
Comment (koic) [inline lib/rubocop/result_cache.rb:94]: When `ResultCache.cache_root(config_store)` (L90) is assigned instead of `options[:cache_root]` (L89) seems to create an unexpected nested `rubocop_cache/rubocop_cache` directory. Can you add a test to prevent the unexpected behavior and fix the implementation?

Comment (nobuyo) [reply lib/rubocop/result_cache.rb]: Sorry, you're right. I've fixed the implementation.

**Comment by koic** [comment]
Thanks!
