### PR TITLE
[Fix #13378] When removing parens in `Style/TernaryParentheses` with a `send` node condition, ensure its arguments are parenthesized

### LINKED ISSUE #13378: Style/TernaryParentheses reported incorrectly
cop incorrectly reports when using `&.` and comparators.

[Before `rubocop -a`]

code:

```ruby
value = 100
puts (value&.> 10) ? 1000 : 2000

value = nil
puts (value&.> 10) ? 1000 : 2000
```

result:

```
1000
2000
```

[After `rubocop -a`]

code:

```ruby
value = 100
puts value&.> 10 ? 1000 : 2000

value = nil
puts value&.> 10 ? 1000 : 2000
```

result:

```
false

```

--------

## Expected behavior

cop should not report Style/TernaryParentheses. Additionally, do not auto-correct.

## Actual behavior

```
C: [Correctable] Style/TernaryParentheses: Omit parentheses for ternary conditions.
puts (value&.> 10) ? 1000 : 2000
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Steps to reproduce the problem

execute `rubocop -a`

## RuboCop version

```
1.67.0 (using Parser 3.3.5.0, rubocop-ast 1.32.3, analyzing as Ruby 3.3, running on ruby 3.3.5) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by dvandersluis**
When the condition to a ternary is a send node with arguments, and `Style/TernaryParentheses` removes parentheses around that condition, ensure the arguments are themselves parenthesized, because otherwise removing the surrounding parens will change the semantics of the ternary.

This also allows a number of test cases to be autocorrected which previously did not have autocorrect.

Fixes #13378.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/ternary_parentheses.rb [hunk 1]
```diff
@@ -203,16 +201,46 @@ def correct_parenthesized(corrector, condition)
...
+        end
+
+        def send_node_args_need_parens?(send_node)
+          return false unless send_node.call_type? || send_node.defined_type?
+
+          send_node.arguments.any? &&
+            !send_node.parenthesized? &&
+            (send_node.dot? ||
+              send_node.safe_navigation? ||
+              unparenthesized_method_call?(send_node))
```
Comment (koic) [inline lib/rubocop/cop/style/ternary_parentheses.rb:242]: Can you refactor to the following?

```suggestion
          return false unless send_node.call_type? || send_node.defined_type?
          return false if send_node.arguments.none? || send_node.parenthesized?

          send_node.dot? || send_node.safe_navigation? || unparenthesized_method_call?(send_node)
```

File: lib/rubocop/cop/style/ternary_parentheses.rb [hunk 2]
```diff
@@ -203,16 +201,46 @@ def correct_parenthesized(corrector, condition)
...
+        end
+
         def whitespace_after?(node)
           last_token = processed_source.last_token_of(node)
           last_token.space_after?
         end
+
+        def condition_send_node(condition)
+          return condition if condition.call_type? || condition.defined_type?
+          return nil unless condition.begin_type? && condition.child_nodes.length == 1
```
[the remark this answers is not in the document]
Comment (dvandersluis) [reply lib/rubocop/cop/style/ternary_parentheses.rb:229]: Not necessary, I'll simplify. Thank you!

**Comment by dvandersluis** [comment]
@koic thanks for the review! :heart: I've updated with your requested changes.

File: lib/rubocop/cop/style/ternary_parentheses.rb [hunk 3]
```diff
@@ -203,16 +201,47 @@ def correct_parenthesized(corrector, condition)
...
+        end
+
         def whitespace_after?(node)
           last_token = processed_source.last_token_of(node)
           last_token.space_after?
         end
+
+        def condition_send_node(condition)
+          return condition if node_with_args?(condition)
+          return nil unless condition.begin_type?
```
Comment (koic) [inline lib/rubocop/cop/style/ternary_parentheses.rb:229]: Is this condition (`return nil unless condition.begin_type?`) necessary as well?

File: lib/rubocop/cop/style/ternary_parentheses.rb [hunk 4]
```diff
@@ -203,16 +201,44 @@ def correct_parenthesized(corrector, condition)
...
+        end
+
         def whitespace_after?(node)
           last_token = processed_source.last_token_of(node)
           last_token.space_after?
         end
+
+        def condition_send_node(condition)
+          send_node = condition.child_nodes.last
+          send_node if node_with_args?(send_node)
```
Comment (koic) [inline lib/rubocop/cop/style/ternary_parentheses.rb:229]: Apologies for the repetition feedback, it seems the tests pass even without the `if node_with_args?` guard condition.

Comment (dvandersluis) [reply lib/rubocop/cop/style/ternary_parentheses.rb]: Yup true, because `send_node_args_need_parens?` calls `node_with_args?` too. I refactored away the `condition_send_node` method now.
