### PR TITLE
[Fix #14791] Fix autocorrect producing `SyntaxError` in `Lint/InterpolationCheck` when single quoted string contains double quotes with invalid interpolation

### LINKED ISSUE #14791: `Lint/InterpolationCheck` autocorrect causes a `SyntaxError`
## Description

```ruby
# before autocorrect
msg = 'Text `A("#{%<base>s}/%<path>s")` and `B` with C.'
puts format(msg, base: 'bar', path: 'baz')

# after
msg = %{Text `A("#{%<base>s}/%<path>s")` and `B` with C.}
puts format(msg, base: 'bar', path: 'baz')
```

--------

## RuboCop version

```console
$ rubocop -V
1.82.1 (using Parser 3.3.10.1, rubocop-ast 1.49.0, analyzing as Ruby 2.7, running on ruby 3.4.7) [x86_64-linux]
  - rubocop-performance 1.26.1
  - rubocop-rake 0.7.1
  - rubocop-rspec 3.9.0
```

### PR DESCRIPTION
**Pull request by ydakuka**
Fixes #14791

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/interpolation_check_spec.rb [hunk 1]
```diff
@@ -86,4 +86,27 @@
...
+  it 'registers an offense and corrects when containing a closing brace without double quotes' do
+    expect_offense(<<~'RUBY')
+      'foo #{bar} }'
+      ^^^^^^^^^^^^^^ Interpolation in single quoted string detected. Use double quoted strings if you need interpolation.
+    RUBY
+
+    expect_correction(<<~'RUBY')
+      "foo #{bar} }"
+    RUBY
+  end
```
Comment (koic) [inline spec/rubocop/cop/lint/interpolation_check_spec.rb]: Can you add the test at an appropriate location in the file, rather than appending it to the end of the file?

Comment (ydakuka) [reply spec/rubocop/cop/lint/interpolation_check_spec.rb]: Sure, I moved it.

File: lib/rubocop/cop/lint/interpolation_check.rb [hunk 2]
```diff
@@ -18,6 +18,7 @@ module Lint
       #
       #   # good
       #   foo = "something with #{interpolation} inside"
+      #
```
Comment (koic) [inline lib/rubocop/cop/lint/interpolation_check.rb]: It looks like an update unrelated to this change.

Comment (ydakuka) [reply lib/rubocop/cop/lint/interpolation_check.rb]: I've removed it.
