### PR TITLE
[Fix #14997] Fix false positives in `Style/FileOpen`

### LINKED ISSUE #14997: Is Style/FileOpen applicable for class/global variables?
### Before submitting

- [x] I have searched the existing issues and this hasn't been reported yet.
- [x] I am running the latest stable version of RuboCop.

### Issue type

False positive

### Cop name

Style/FileOpen

### Steps to reproduce the problem

1. How is ...

```ruby
def open
  File.open('foo')
end

def bar(str)
  $baz ||= open
  $baz.write(str)
end
```

... better than ...

```ruby
def bar(str)
  $baz ||= File.open('foo') # Style/FileOpen
  $baz.write(str)
end
```

2. And ....

```ruby
class Foo
  def initialize
    @file = open
  end

  def open
    File.open('foo')
  end

  def write(str)
    @file.write(str)
  end
end
```

... better than ...

```ruby
class Foo
  def initialize
    @file = File.open('foo') # Style/FileOpen
  end

  def write(str)
    @file.write(str)
  end
end
```

### Expected behavior

Does the cop actually serve its purpose (preventing fd leaks) in these cases, or just add verbosity?

### Actual behavior

Style/FileOpen

### RuboCop configuration

```yaml

```

### RuboCop version

```shell
System Version: macOS 26.3 (25D125)
Model Identifier: MacBookAir10,1
ruby 4.0.1 (2026-01-13 revision e04267a14b) +PRISM [arm64-darwin25]
rubocop     2026-03-06 b7d518bb6
```

### PR DESCRIPTION
**Pull request by koic**
This PR fixes false positives in `Style/FileOpen`
when assigning `File.open` to an instance variable, class variable, global variable, or constant.

Assignments to local variables may produce false positives because the file may be closed elsewhere.

Fixes #14997.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/file_open_spec.rb [hunk 1]
```diff
@@ -36,6 +36,30 @@
...
+    RUBY
+  end
+
+  it 'does not register an offense when assigning `File.open` to a global variable' do
+    expect_no_offenses(<<~RUBY)
+      $gvar = File.open('file')
+    RUBY
+  end
+
+  it 'does not register an offense when assigning `File.open` to a constant' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/file_open_spec.rb:57]: Perhaps you should also add a test showing the behaviour when you assign to a local?

Comment (koic) [reply spec/rubocop/cop/style/file_open_spec.rb:57]: It already existed, but I moved it closer to the related section.
