### PR TITLE
[Fix #10410] Improve help string for `--fail-level` CLI option

### LINKED ISSUE #10410: document --fail-level letter meaning
```
        --fail-level SEVERITY        Minimum severity (A/I/R/C/W/E/F) for exit
                                     with error code.
```

- say what the letters mean or only show long-form (autocorrect etc)
- ideally support `all` or `any` so it's obvious that I want to fail on anything
because someone reading `--fail-level A` needs to read up on what that means whereas `--fail-level any` would be obvious.

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #10410

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/options.rb [hunk 1]
```diff
@@ -467,8 +467,14 @@ module OptionsHelp
...
-      fail_level:                       ['Minimum severity (A/I/R/C/W/E/F) for exit',
-                                         'with error code.'],
+      fail_level:                       ['Minimum severity for exit with error code.',
+                                         '[A] autocorrect',
+                                         '[I] info',
+                                         '[R] refactor',
+                                         '[C] convention',
+                                         '[W] warning',
+                                         '[E] error',
+                                         '[F] fatal'],
```
Comment (tejasbubane) [inline lib/rubocop/options.rb:477]: We already allow both words and abbreviations:
https://github.com/rubocop/rubocop/blob/9f82e0fb2a581283e588a7161839a10c77a2509c/spec/rubocop/options_spec.rb#L298-L301

**Comment by bbatsov** [comment]
Thanks!
