### PR TITLE
[Fix #11706] Fix infinite loop when `--disable-uncorrectable` option and there is a multi-line percent array violates `Layout/LineLength`

### LINKED ISSUE #11706: `--disable-uncorrectable` option does not insert todo comment as expected for multiline case
thank you for the fix to https://github.com/rubocop/rubocop/pull/11701
but, another issue similar to https://github.com/rubocop/rubocop/issues/11685 is there.

## Expected behavior

Rubocop should process

```ruby
ARRAY = %w[
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
].freeze
```
 
as

```ruby
# rubocop:todo Layout/LineLength
ARRAY = %w[
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
].freeze
# rubocop:enable Layout/LineLength
```
for "--disable-uncorrectable" option

## Actual behavior

it become infinite loop and I got

```ruby
# rubocop:todo Metrics/CollectionLiteralLength
ARRAY = %w[
  # rubocop:todo Layout/LineLength
  # rubocop:enable Layout/LineLength
  # rubocop:enable Layout/LineLength
  ...
  # rubocop:todo Layout/LineLength
  # rubocop:todo Layout/LineLength
  # rubocop:enable Layout/LineLength
  # rubocop:todo Layout/LineLength
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# rubocop:enable Layout/LineLength
  # rubocop:todo Layout/LineLength
# rubocop:enable Layout/LineLength
  ...
# rubocop:enable Layout/LineLength
  # rubocop:todo Layout/LineLength
  # rubocop:todo Layout/LineLength
  # rubocop:enable Layout/LineLength
].freeze
# rubocop:enable Metrics/CollectionLiteralLength
```

## Steps to reproduce the problem

1. create `test_case.rb`
2. create`.rubocop.yml`
3. run `bundle exec rubocop -A --disable-uncorrectable test_case.rb`

test_case.rb
```ruby
ARRAY = %w[
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
].freeze
```

.rubocop.yml
```yml
Layout/LineLength:
  Max: 30
```

## RuboCop version

This happens with HEAD of master (4346f8ef4)

```
$ [bundle exec] rubocop -V
1.48.1 (using Parser 3.2.1.1, rubocop-ast 1.27.0, running on ruby 3.0.5) [x86_64-darwin22]
  - rubocop-performance 1.16.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.19.0
```

### PR DESCRIPTION
**Pull request by nobuyo**
Fixes #11706, follows up #11701.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cli/disable_uncorrectable_spec.rb [hunk 1]
```diff
@@ -282,6 +282,32 @@ def our_function
             # rubocop:enable Layout/LineLength
           RUBY
         end
+
+        it 'adds before-and-after disable statement around the multi-line percent array' do
+          create_file('.rubocop.yml', <<~YAML)
+            Layout/LineLength:
+              Max: 30
+          YAML
```
Comment (koic) [inline spec/rubocop/cli/disable_uncorrectable_spec.rb:290]: Can you move this `create_file('.rubocop.yml', <<~YAML)` under L263 and put it in `before` block?

```diff
diff --git a/spec/rubocop/cli/disable_uncorrectable_spec.rb b/spec/rubocop/cli/disable_uncorrectable_spec.rb
index b1d42a469..e2003225b 100644
--- a/spec/rubocop/cli/disable_uncorrectable_spec.rb
+++ b/spec/rubocop/cli/disable_uncorrectable_spec.rb
@@ -261,11 +261,14 @@ RSpec.describe 'RuboCop::CLI --disable-uncorrectable', :isolated_environment do
       end

       context 'and the offense is inside a percent array' do
-        it 'adds before-and-after disable statement around the percent array' do
+        before do
           create_file('.rubocop.yml', <<~YAML)
             Layout/LineLength:
               Max: 30
           YAML
+        end
+
+        it 'adds before-and-after disable statement around the percent array' do
           create_file('example.rb', <<~RUBY)
             # frozen_string_literal: true

@@ -284,10 +287,6 @@ RSpec.describe 'RuboCop::CLI --disable-uncorrectable', :isolated_environment do
         end

         it 'adds before-and-after disable statement around the multi-line percent array' do
-          create_file('.rubocop.yml', <<~YAML)
-            Layout/LineLength:
-              Max: 30
-          YAML
           create_file('example.rb', <<~RUBY)
             # frozen_string_literal: true
```
