### PR TITLE
[Fix #10881] Fix `Style/SoleNestedConditional` to properly wrap `block` and `csend` nodes when necessary

### LINKED ISSUE #10881: [Style/SoleNestedConditional] Syntax error when autocorrecting nested if conditions with a block
If there are nested `if` statesments, where the second `if` condition is a function with an arugment and a block, autocorrecting causes a syntax error. Given snippet `test.rb`

```ruby
def foo
  if cond
    if validate :strict do
        "hello"
      end
    end
  end
end
```

and running 

```
rubocop test.rb --force-default-config --only Style/SoleNestedConditional -a
```

there is a syntax error reported by `ruby` (see below). Prior to autocorrect, there was no syntax error.

--------

## Expected behavior

`ruby test.rb` do not report syntax error after autocorrect. Proposed solution is to add parenthesis around arguments.

```ruby
def foo
  if cond && validate(:strict) do
        "hello"
      end
    end
end
```

## Actual behavior

The source code is autocorrected to

```ruby
def foo
  if cond && validate :strict do
        puts "hello"
      end
    end
end
```

`ruby test.rb` reports syntax error:

```
/tmp/test.rb:2: syntax error, unexpected symbol literal, expecting `do' or '{' or '('
  if cond && validate :strict do
/tmp/test.rb:5: syntax error, unexpected `end', expecting end-of-input
    end
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.33.0 (using Parser 3.1.2.0, rubocop-ast 1.19.1, running on ruby 2.7.4 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by dvandersluis**
`Style/SoleNestedConditional` adds parentheses around `send` nodes that have unparenthesized arguments, but this wasn't being done for `csend` or `block` nodes, so this change fixes that.

Fixes #10881.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/sole_nested_conditional_spec.rb [hunk 1]
```diff
@@ -663,6 +663,46 @@ def foo
...
+            if foo
+              if bar&.baz quux
+              ^^ Consider merging nested conditions into outer `if` conditions.
+                do_something
+              end
+            end
+          RUBY
+
+          expect_correction(<<~RUBY)
+            if foo && (bar&.baz quux)
```
Comment (koic) [inline spec/rubocop/cop/style/sole_nested_conditional_spec.rb:679]: It would be more better to correct as follows.

```suggestion
            if foo && bar&.baz(quux)
```

File: spec/rubocop/cop/style/sole_nested_conditional_spec.rb [hunk 2]
```diff
@@ -663,6 +663,46 @@ def foo
...
+                end
+              end
+            end
+          RUBY
+
+          expect_correction(<<~RUBY)
+            if foo && (ok? bar do
+                  do_something
+                end)
+              end
```
Comment (koic) [inline spec/rubocop/cop/style/sole_nested_conditional_spec.rb:702]: Ditto :-)

```suggestion
            if foo && ok?(bar) do
                  do_something
                end
              end
```

File: spec/rubocop/cop/style/sole_nested_conditional_spec.rb (hunk 1 above)
Comment (dvandersluis) [reply spec/rubocop/cop/style/sole_nested_conditional_spec.rb:679]: I agree, but this is the existing autocorrection for `send` nodes I'm just extending it to `csend` and `block` nodes as well to prevent syntax errors from autocorrection.

Would you be good with accepting this as-is and improving autocorrection in a future PR?

Comment (koic) [reply spec/rubocop/cop/style/sole_nested_conditional_spec.rb:679]: OK, I think we can do it separately. It would be useful to leave a `FIXME` comment.

Comment (dvandersluis) [reply spec/rubocop/cop/style/sole_nested_conditional_spec.rb:679]: Added!

**Comment by koic** [comment]
Thanks!
