### PR TITLE
[Fix #13900] Fix infinite loop between `Layout/EmptyLinesAroundAccessModifier` and `Layout/EmptyLinesAroundBlockBody` with `EnforcedStyle: no_empty_lines`

### LINKED ISSUE #13900: Infinite loop detected between `Layout/EmptyLinesAroundBlockBody` and `Layout/EmptyLinesAroundAccessModifier`
RuboCop autocorrection results in an infinite loop when an access modifier is located at the bottom of a block with no following code.

```ruby
block do
  def foo
  end

  private
end
```

```
$ rubocop test.rb --except Lint/UselessAccessModifier -A
Inspecting 1 file
Infinite loop detected in /Users/daniel/RubymineProjects/rubocop/test.rb and caused by Layout/EmptyLinesAroundBlockBody -> Layout/EmptyLinesAroundAccessModifier
C

Offenses:

test.rb:4:3: C: [Corrected] Style/EmptyMethod: Put empty method definitions on a single line.
  def foo ...
  ^^^^^^^
test.rb:6:3: C: [Corrected] Layout/EmptyLinesAroundAccessModifier: Keep a blank line before and after private.
  private
  ^^^^^^^
test.rb:7:1: C: [Corrected] Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body end.
test.rb:7:3: C: [Corrected] Layout/EmptyLinesAroundAccessModifier: Keep a blank line before and after private.
  private
  ^^^^^^^

1 file inspected, 4 offenses detected, 4 offenses corrected

1 error occurred:
Infinite loop detected in /Users/daniel/RubymineProjects/rubocop/test.rb and caused by Layout/EmptyLinesAroundBlockBody -> Layout/EmptyLinesAroundAccessModifier
Errors are usually caused by RuboCop bugs.
Please, update to the latest RuboCop version if not already in use, and report a bug if the issue still occurs on this version.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.72.2 (using Parser 3.3.7.1, rubocop-ast 1.38.0, analyzing as Ruby 2.7, running on ruby 3.4.1) [arm64-darwin24]
```

### PR DESCRIPTION
**Pull request by dvandersluis**
Fixes infinite loop when  `Layout/EmptyLinesAroundAccessModifier` is configured with `EnforcedStyle: around` and `Layout/EmptyLinesAroundBlockBlody` with `EnforcedStyle: no_empty_lines`, and there is an access modifier with no following code at the beginning or end of a block.

eg.:
```ruby
block do
  def foo
  end

  private
end
```

Previously the two cops would repeatedly add and remove a line after `private`.

Fixes #13900.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/empty_lines_around_access_modifier.rb [hunk 1]
```diff
@@ -205,6 +207,29 @@ def message_for_only_before_style(node)
...
+        end
+
+        def should_insert_line_after?(node)
+          return true unless inside_block?(node) && no_empty_lines_around_block_body?
+
+          node.parent.children.last != node
+        end
+
+        def inside_block?(node)
+          node.parent.block_type? || (node.parent.begin_type? && node.parent&.parent&.block_type?)
```
Comment (koic) [inline lib/rubocop/cop/layout/empty_lines_around_access_modifier.rb:226]: Since `parent` is already confirmed to be `begin_type`, safe navigation does not seem necessary. 

```suggestion
          node.parent.block_type? || (node.parent.begin_type? && node.parent.parent&.block_type?)
```

Since `parent` is already confirmed to be `begin_type`, safe navigation does not seem necessary. If safe navigation is needed for its `node.parent.parent&.block_type?`, additional tests should be added.

Comment (dvandersluis) [reply lib/rubocop/cop/layout/empty_lines_around_access_modifier.rb]: Updated, thanks.
