### PR TITLE
[Fix #14833] Fix false positive for `Layout/MultilineMethodCallIndentation` when a multi-dot method chain is inside a hash pair value

### LINKED ISSUE #14833: Layout/MultilineMethodCallIndentation false positive in 1.84.1
In 1.84.1, correctly formatted code is flagged as an error by `Layout/MultilineMethodCallIndentation`

--------

## Steps to reproduce the problem

```ruby
# frozen_string_literal: true

method(key: value.chain1.chain2
                 .chain3)

```

## Expected behavior

I would expect no error.  This is using the default values for `Layout/MultilineMethodCallIndentation` of aligned.  Since `.chain3` is aligned with the dot of the first method in the chain, I would expect this to be acceptable.

## Actual behavior

```
$ rubocop --debug test.rb
For /app: configuration from /app/.rubocop.yml
Default configuration from /home/docker-user/bundle/ruby/3.3.0/gems/rubocop-1.84.1/config/default.yml
Plugin configuration from /home/docker-user/bundle/ruby/3.3.0/gems/rubocop-rails-2.34.3/config/default.yml
Use parallel by default.
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /app/test.rb
Loading cache from /home/docker-user/.cache/rubocop_cache/f949e70474bdfbf9be0eb032b218ce426938c3fb/8c3e361d53661224764d286241e06b0a70c26148/97d8e6c9212104493d0a3800574218ee21eefcff
C

Offenses:

test.rb:4:18: C: [Correctable] Layout/MultilineMethodCallIndentation: Align .chain3 with value.chain1.chain2 on line 3.
                 .chain3)
                 ^^^^^^^

1 file inspected, 1 offense detected, 1 offense autocorrectable
Finished in 0.20254784999997355 seconds
```

## RuboCop version

```
$ rubocop -V
1.84.1 (using Parser 3.3.10.1, Prism 1.9.0, rubocop-ast 1.49.0, analyzing as Ruby 3.3, running on ruby 3.3.10) [x86_64-linux]
  - rubocop-rails 2.34.3

```

### PR DESCRIPTION
**Pull request by ydakuka**
Fixes #14833

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/multiline_method_call_indentation.rb [hunk 1]
```diff
@@ -165,6 +166,16 @@ def find_hash_pair_alignment_base(node)
           first_call.loc.dot.join(first_call.loc.selector)
         end
 
+        def aligned_with_first_line_dot?(node, rhs)
+          return false unless rhs.source.start_with?('.', '&.')
+
+          first_call = first_call_has_a_dot(node)
+          return false if first_call.equal?(node.receiver)
```
Comment (koic) [inline lib/rubocop/cop/layout/multiline_method_call_indentation.rb]: Is there a reason for using `equal?` instead of `==`?

Comment (ydakuka) [reply lib/rubocop/cop/layout/multiline_method_call_indentation.rb]: No, I changed it.
