### PR TITLE
[Fix #14981] Add Safe and SafeAutoCorrect to COMMON_PARAMS

### LINKED ISSUE #14981: Spurious warning: "[Cop] does not support SafeAutoCorrect parameter" when SafeAutoCorrect is a valid parameter for all cops
## Steps to reproduce the problem

Create a `.rubocop.yml` with `SafeAutoCorrect: false` for any cop that does not already have `SafeAutoCorrect` listed in its default configuration:

```yaml
# .rubocop.yml
Lint/UselessAssignment:
  SafeAutoCorrect: false
```

Run RuboCop against any Ruby file:

```
$ bundle exec rubocop test.rb
```

The same warning is produced with `Safe: false` for cops that do not have `Safe` in their default config.

## Expected behavior

No warning should be emitted. `SafeAutoCorrect` (and `Safe`) are documented, recognized configuration parameters that are valid for all cops. They appear in `CONFIG_CHECK_KEYS` and are actively read at runtime via `cop_config.fetch('SafeAutoCorrect', true)` in `autocorrect_logic.rb`.

## Actual behavior

```
Warning: Lint/UselessAssignment does not support SafeAutoCorrect parameter.

Supported parameters are:

  - Enabled
  - AutoCorrect
```

The warning fires for any cop that does not have `SafeAutoCorrect` explicitly listed in its entry in `config/default.yml`. Only the ~53 cops that already have `SafeAutoCorrect:` in `default.yml` are unaffected.

The root cause is in `config_validator.rb`. `COMMON_PARAMS` does not include `Safe` or `SafeAutoCorrect`, so `each_invalid_parameter` treats them as unknown when they are absent from a cop's default config entry:

```ruby
COMMON_PARAMS = %w[Exclude Include Severity inherit_mode AutoCorrect StyleGuide Details
                   Enabled Reference References].freeze

def each_invalid_parameter(cop_name)
  default_config = ConfigLoader.default_configuration[cop_name]
  @config[cop_name].each_key do |param|
    next if COMMON_PARAMS.include?(param) || default_config.key?(param)
    # SafeAutoCorrect is neither in COMMON_PARAMS nor in most cops' default_config,
    # so it falls through and triggers the warning.
    yield param, supported_params
  end
end
```

The fix is to add `Safe` and `SafeAutoCorrect` to `COMMON_PARAMS`.

## RuboCop version

```
$ bundle exec rubocop -V
1.85.0 (using Parser 3.3.10.2, rubocop-ast 1.49.0, analyzing as Ruby 2.7, running on ruby 3.4.6) [arm64-darwin24]
```

### PR DESCRIPTION
**Pull request by dduugg**
## Summary

Fixes #14981.

`Safe` and `SafeAutoCorrect` are valid configuration parameters for all cops — they are listed in `CONFIG_CHECK_KEYS` and actively consumed at runtime in `autocorrect_logic.rb`. However, they were absent from `COMMON_PARAMS`, so `each_invalid_parameter` would emit a spurious warning for any cop that does not have them in its `config/default.yml` entry (the majority of cops).

**Root cause** in `config_validator.rb`:

```ruby
COMMON_PARAMS = %w[Exclude Include Severity inherit_mode AutoCorrect StyleGuide Details
                   Enabled Reference References].freeze   # Safe/SafeAutoCorrect missing

def each_invalid_parameter(cop_name)
  default_config = ConfigLoader.default_configuration[cop_name]
  @config[cop_name].each_key do |param|
    next if COMMON_PARAMS.include?(param) || default_config.key?(param)
    # SafeAutoCorrect falls through here for most cops → spurious warning
    yield param, supported_params
  end
end
```

**Fix:** add `Safe` and `SafeAutoCorrect` to `COMMON_PARAMS`.

## Test plan

- Added two new examples to `spec/rubocop/config_spec.rb` asserting that setting `Safe: false` or `SafeAutoCorrect: false` on a cop that has no default entry for those keys produces no warning.
- `bundle exec rspec spec/rubocop/config_spec.rb` — 81 examples, 0 failures.

### CODE REVIEW

File: spec/rubocop/config_spec.rb [hunk 1]
```diff
@@ -179,6 +179,38 @@
...
+          Lint/UselessAssignment:
+            SafeAutoCorrect: false
+        YAML
+      end
+
+      it 'does not print a warning' do
+        configuration
+        expect($stderr.string).not_to match(/does not support SafeAutoCorrect parameter/)
+      end
+    end
```
Comment (koic) [inline spec/rubocop/config_spec.rb:216]: Could the test be updated to ensure it actually reproduces the regression? As it stands, the original code appears to pass the test as well.

```diff
$ git diff .
diff --git a/lib/rubocop/config_validator.rb b/lib/rubocop/config_validator.rb
index 4bd8b02e6..c1ac3ca98 100644
--- a/lib/rubocop/config_validator.rb
+++ b/lib/rubocop/config_validator.rb
@@ -13,7 +13,7 @@ module RuboCop
     # @api private
     INTERNAL_PARAMS = %w[Description StyleGuide
                          VersionAdded VersionChanged VersionRemoved
-                         Reference References Safe SafeAutoCorrect].freeze
+                         Reference References].freeze
     # @api private
     NEW_COPS_VALUES = %w[pending disable enable].freeze
```

```console
$ bundle exec rspec spec/rubocop/config_spec.rb

Randomized with seed 22030
.................................................................................

Finished in 0.20048 seconds (files took 0.71795 seconds to load)
81 examples, 0 failures
```

Comment (dduugg) [reply spec/rubocop/config_spec.rb:216]: Thank you for the review! The tests do catch the regression — the diff you applied reverted `INTERNAL_PARAMS` rather than `COMMON_PARAMS` (the actual fix), so `COMMON_PARAMS` still contained `Safe`/`SafeAutoCorrect` in your test run.

To confirm: checking out master (where `COMMON_PARAMS` lacks `Safe`/`SafeAutoCorrect`), the two new examples fail with:

```
Warning: Lint/UselessAssignment does not support Safe parameter.
```

With the fix they pass. I've updated the spec with a comment and clearer context descriptions to make the intent more explicit.

Comment (koic) [reply spec/rubocop/config_spec.rb:216]: Oops! Understood. Thank you for the explanation. Can you squash your commits into one?

Comment (dduugg) [reply spec/rubocop/config_spec.rb:216]: Sure thing, done!

**Comment by koic** [comment]
Thanks!
