### PR TITLE
[Fix #14445] Fix false positives for `Lint/UselessAssignment` with `for` loops when the variable is referenced in the collection

### LINKED ISSUE #14445: `Lint/UselessAssignment` must be considered unsafe
## Expected behavior

I don't mind if this code has offenses, but this auto-correction is WRONG; must not happen.

It is super-duper difficult -- if not impossible -- to statically prove if a variable assignment is useless or not.  Rubocop does not have such feature.  That is a reasonable, practical design decision that I support.  You should just stop pretending that you do so.

## Actual behavior

Autocorrection breaks semantics of the code.

## Steps to reproduce the problem

```console
$ cat tmp.rb
def foo
  backtrack = []
  result = []
  node = self

  until node.nil?
    children = node.children
    result << children.first

    unless children.second
      node = backtrack.pop
      next
    end

    backtrack.push(children[2..]).flatten! if children.third
    node = children.second
  end

  result
end
$
$
$ bin/rubocop --safe-auto-correct tmp.rb
--safe-auto-correct is deprecated; use --autocorrect instead.
Inspecting 1 file
W

Offenses:

tmp.rb:11:7: W: [Corrected] Lint/UselessAssignment: Useless assignment to variable - node.
      node = backtrack.pop
      ^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

## RuboCop version

```
$ bin/rubocop -V
1.79.0 (using Parser 3.3.9.0, rubocop-ast 1.46.0, analyzing as Ruby 3.2, running on ruby 3.2.4) [x86_64-linux]
  - rubocop-faker 1.1.0
  - rubocop-performance 1.21.1
  - rubocop-rails 2.25.1
  - rubocop-rspec 3.0.4
```

### PR DESCRIPTION
**Pull request by Earlopain**
Fix #14445

In a for-style loop, the children don't appear in the order that they actually execute.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/variable_force.rb [hunk 1]
```diff
@@ -243,6 +243,11 @@ def process_loop(node)
           condition_node, body_node = *node
           process_node(body_node)
           process_node(condition_node)
+        elsif node.for_type?
+          # In `for foo in bar` the rightmost expression is evaluated first
```
Comment (koic) [inline lib/rubocop/cop/variable_force.rb]: That's just my two cents:

```suggestion
          # In `for item in items` the rightmost expression is evaluated first.
```

Comment (Earlopain) [reply lib/rubocop/cop/variable_force.rb]: Sure, I changed it
