### PR TITLE
[Fix #14420] Fix false positives for `Style/SafeNavigation`

### LINKED ISSUE #14420: Style/SafeNavigation reports on complex nil checks that should pass
## Expected behavior

The following code is flagged as a Style/SafeNavigation violation.

```ruby
end_time = end_date.nil? ? nil : end_date.in_time_zone(timezone) + 1.day
```

The shape of the code actually matches one of the exceptions listed in the [documentation](https://docs.rubocop.org/rubocop/cops_style.html#stylesafenavigation):

```
foo ? foo * 42 : nil      # Ignored `foo&.*(42)` due to unclear readability benefit.
```

I think the correct fix is to ignore any safe navigation where there is arithmetic or other ignored methods (like `[]`) anywhere in the non-nil side of the conditional.

## Actual behavior

Arithmetic calls are excepted in the docs due to readability, but because there is a method call before the arithmetic but inside the conditional, rubocop incorrectly fixes to non-functional code.

```ruby
end_time = end_date&.in_time_zone(timezone) + 1.day
```

This seems to have started around 1.79, since we're only getting these violations now, whereas they weren't triggering before, though I'm not certain this is the exact version where it changed.

## Steps to reproduce the problem

Save the following code:

```ruby
end_time = end_date.nil? ? nil : end_date.in_time_zone(timezone) + 1.day
```

See that it violates Style/SafeNavigation. It should not.

Try auto-correct, see that it produces code that will error when `nil` receives `+`.

## RuboCop version

```
$ bundle exec rubocop -V
1.79.1 (using Parser 3.3.8.0, Prism 1.4.0, rubocop-ast 1.46.0, analyzing as Ruby 3.4, running on ruby 3.4.5) +server [arm64-darwin24]
  - rubocop-rspec 3.6.0
  - rubocop-performance 1.25.0
  - rubocop-rake 0.7.1
  - rubocop-capybara 2.22.1
  - rubocop-factory_bot 2.27.1
  - rubocop-graphql 1.5.6
  - rubocop-performance 1.25.0
  - rubocop-rake 0.7.1
  - rubocop-rspec 3.6.0
  - rubocop-rspec_rails 2.31.0
  - rubocop-sorbet 0.10.5
  - rubocop-rails 2.32.0
```

### PR DESCRIPTION
**Pull request by koic**
This PR fixes false positives for `Style/SafeNavigation` when ternary expression with operator method call with method chain.

Fixes #14420.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/safe_navigation_spec.rb [hunk 1]
```diff
@@ -879,14 +879,15 @@ def foobar
           RUBY
         end
 
-        it 'registers an offense for ternary expression with operator method call with method chain' do
-          expect_offense(<<~RUBY, variable: variable)
+        it 'does not register an offense for ternary expression with operator method call with method chain' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/safe_navigation_spec.rb]: I think this should be move up in the allowed example, earlier in this context.

Comment (bbatsov) [reply spec/rubocop/cop/style/safe_navigation_spec.rb]: Also, how is this different from the behavior above in practical terms?

Comment (koic) [reply spec/rubocop/cop/style/safe_navigation_spec.rb]: This was a spec that described incorrect behavior. As noted in #14420, the previous behavior of this test was to auto-correct from `var.nil? ? nil : var.foo * 42` to `var&.foo * 42`, which is not safe. To make it safe, the correction would have to be `var&.foo&.*(42)`, but that would reduce readability.

This is a more complex version of examples already documented.

```ruby
#   foo ? foo[index] : nil    # Ignored `foo&.[](index)` due to unclear readability benefit.                                                                                           
#   foo ? foo[idx] = v : nil  # Ignored `foo&.[]=(idx, v)` due to unclear readability benefit.                                                                                         
#   foo ? foo * 42 : nil      # Ignored `foo&.*(42)` due to unclear readability benefit.  
```
https://docs.rubocop.org/rubocop/1.79/cops_style.html#examples-stylesafenavigation

So the documentation has not been updated.

Comment (bbatsov) [reply spec/rubocop/cop/style/safe_navigation_spec.rb]: I meant that https://github.com/rubocop/rubocop/pull/14421/files/da0e3e7a1fb6bf65a17f32fcfa3e5e44f9aec36d#diff-736e663e58ab853ebfddd666306d7bddb37502d4cde5c1b8703cac7f1b20dcc8R871 is essentially the same. 

And if you go up in the specs group you'll see that the allowed examples are earlier, so I think those should be grouped together.

Comment (koic) [reply spec/rubocop/cop/style/safe_navigation_spec.rb]: Ah, I see. In cases like `foo.*(42)` or `foo.[](42)`, where the method call already includes a dot, converting them to safe navigation like `foo&.*(42)` or `foo&.[42]` doesn't reduce readability, so an offense is registered.

On the other hand, for calls like `foo * 42` or `foo[42]`, which don't include a dot, no offense is registered in order to preserve readability.

So, there's a distinction based on whether operator method call and index access are written with a dot.
I structured the specs to reflect this symmetry.

Comment (koic) [reply spec/rubocop/cop/style/safe_navigation_spec.rb]: Oops, I misunderstood the intent. I've updated it to keep the diff simple.

**Review by bbatsov — APPROVED** [review]
