### PR TITLE
Fix `Style/RedundantFormat` false positive when a interpolated value is given to a specifier with a width or precision

### LINKED ISSUE #14604: Style/RedundantFormat gives doubly inconsistent advice
## Steps to reproduce the problem

```ruby
%w[you sunshine].each do
  puts  format '(%16s)',   "Hello #{it}" # Style/RedundantFormat
  print format "(%16s)\n", "Hello #{it}" # Style/RedundantFormat
  printf       "(%16s)\n", "Hello #{it}" # Identical, but no cop
  puts "(     Hello #{it})"              # Suggestion, different
  puts
end
```

## Expected behavior

Not being pulled over.

## Actual behavior

```
(       Hello you)
(       Hello you)
(       Hello you)
(     Hello you)

(  Hello sunshine)
(  Hello sunshine)
(  Hello sunshine)
(     Hello sunshine)

-:2:9: C: [Correctable] Style/RedundantFormat: Use "(     Hello #{it})" directly instead of format.
  puts  format '(%16s)',   "Hello #{it}" # Style/RedundantFormat
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-:3:9: C: [Correctable] Style/RedundantFormat: Use "(     Hello #{it})
" directly instead of format.
  print format "(%16s)\n", "Hello #{it}" # Style/RedundantFormat
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Side issue**: Control characters should appear as originally written (`\n` in this instance)

## RuboCop version

```
ruby      2025-08-01 30a20bc16
rubocop   2025-10-15 473598c90
System Version: macOS 15.6 (24G84)
Model Identifier: MacBookAir10,1
```

### PR DESCRIPTION
**Pull request by dvandersluis**
When `format` or `sprintf` has a specifier with a width or precision, and the related argument is an interpolated string, we cannot register that as a redundant format, as we cannot know ahead of time how wide the resulting string should be since it depends on the value of the interpolation.

Fixes #14604.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/redundant_format.rb [hunk 1]
```diff
@@ -134,7 +134,7 @@ def register_all_fields_literal(node, string, arguments)
           end
         end
 
-        # rubocop:disable Metrics/CyclomaticComplexity
+        # rubocop:disable Metrics/AbcSize,Metrics/CyclomaticComplexity,Metrics/PerceivedComplexity
```
Comment (koic) [inline lib/rubocop/cop/style/redundant_format.rb]: That's just my two cents.

```suggestion
        # rubocop:disable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
```

File: lib/rubocop/cop/style/redundant_format.rb [hunk 2]
```diff
@@ -147,13 +147,14 @@ def all_fields_literal?(string, arguments)
...
             next unless matching_argument?(sequence, argument)
+            next if (sequence.width || sequence.precision) && argument.dstr_type?
 
             count += 1
           end
 
           sequences.size == count
         end
-        # rubocop:enable Metrics/CyclomaticComplexity
+        # rubocop:enable Metrics/AbcSize,Metrics/CyclomaticComplexity,Metrics/PerceivedComplexity
```
Comment (koic) [inline lib/rubocop/cop/style/redundant_format.rb]:
```suggestion
        # rubocop:enable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
```

**Comment by koic** [comment]
Thanks!
