### PR TITLE
[Fix #13916] Stop Lint/LiteralAsCondition from acting on the rhs of && statements.

### LINKED ISSUE #13916: `Lint/LiteralAsCondition` makes invalid autocorrections
After upgrading to 1.73.0, Lint/LiteralAsCondition is causing the following autocorrections:

```ruby
- h.label_tag(name, class: errors[name.to_sym] && "error")
+ h.label_tag(name, class: errors[name.to_sym])
```

```ruby
 def message
   "Remote provider %s returned %s%s" % [
-    provider, result, desc && " (#{desc})",
+    provider, result, desc,
   ]
 end
```

In both cases, the value of the expression is used for more than just a boolean check. This would be safe for boolean expressions in conditionals (`if bool`, `elsif bool`, `unless bool`, `while bool`, `until bool`, `bool ? expr1 : expr2`).  But for anything else we may care about the distinction between `nil` vs `false` or `true` vs other truthy values.

Could this be related to #13117?

--------

## Expected behavior

These should not be reported as offenses, nor should they be autocorrected.

## Actual behavior

They are reported as offenses and incompatibly autocorrected.

## Steps to reproduce the problem

See examples above.

## RuboCop version

1.73.0

### PR DESCRIPTION
**Pull request by Zopolis4**
Fixes #13916.

~~This does mean some valid cases won't be caught, but for a Lint cop I presume its better to prioritize safety.~~

The right hand side of an && isn't a condition, its just executed conditionally. 

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by Zopolis4** [comment]
Note that this will mean `Lint/LiteralAsCondition` will not be able to be fully extended to satisfy #12840, although the safety issues there were already pointed out in https://github.com/rubocop/rubocop/issues/12840#issuecomment-2052132998.

**Comment by koic** [comment]
> Lint cop I presume its better to prioritize safety.

I think so too.

The following example also seems to need an update.

```ruby
      #   # bad
      #   if some_var && true
      #     do_something
      #   end
```

Additionally, it would be good to add a description to the documentation explaining the reason for allowing this case.

**Comment by Zopolis4** [comment]
> Additionally, it would be good to add a description to the documentation explaining the reason for allowing this case.

Unless I'm misunderstanding something, this case doesn't actually fall under the domain of this cop? The right hand side of an && isn't a condition, its just being conditionally executed.

**Comment by Zopolis4** [comment]
Converting to draft while I look at this issue in more depth.

**Comment by bbatsov** [comment]
> Unless I'm misunderstanding something, this case doesn't actually fall under the domain of this cop? The right hand side of an && isn't a condition, its just being conditionally executed.

Yeah, that's fair. I'm guessing we can have a separate cop checking for logical expressions when some of the operands is a literal, which is kind of weird IMO. 

I agree with the proposed fix, although it'd be good to also add some comment explaining that outcome is kind of fixed only if the literal is on the left side of `&&`.

**Comment by Zopolis4** [comment]
> although it'd be good to also add some comment explaining that outcome is kind of fixed only if the literal is on the left side of &&.

I'm not entirely sure what you mean by this?

File: lib/rubocop/cop/lint/literal_as_condition.rb [hunk 1]
```diff
@@ -18,12 +18,12 @@ module Lint
       #   end
       #
       #   # bad
-      #   if some_var && true
+      #   if true && some_var
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/literal_as_condition.rb:21]: I was referring to this snippet - I was thinking it'd be good to have some note explaining why care only for `true` as the first operand.

**Comment by bbatsov** [comment]
@Zopolis4 See my inline comment, I hope it makes more sense. In a nutshell - I think the cop examples would benefit from some inline comments explaining why the cop targets them, as I don't think all the examples are obvious.

File: lib/rubocop/cop/lint/literal_as_condition.rb (hunk 1 above)
Comment (Zopolis4) [reply lib/rubocop/cop/lint/literal_as_condition.rb:24]: I've added a note.

**Comment by bbatsov** [comment]
Thanks!

**Comment by Zopolis4** [comment]
> My apologies, because I haven't really worked with `rubocop`'s code much myself, so I don't know if what I'm going to suggest is simple or hard (or simply _wrong_).
> 
> But, what (naively) makes sense to me is for all of the control flow expression visitors (`on_if`, `on_while`, etc) to look at their `node.condition` recursively. Something like:
> 
> ```ruby
>         def on_while(node)
>           return if node.condition.source == 'true'
> 
>           if node.condition.falsey_literal?
>             add_offense(node.condition) do |corrector|
>               corrector.remove(node)
>             end
>           else
>             check_condition_expression(node.condition)
>             # ^^^^^ this should also be used by `on_if`, `on_while_post`, etc.
>           end
>         end
> 
>        def check_condition_expression(condition)
>           if condition.truthy_literal?
>             add_offense(condition) do |corrector|
>               corrector.replace(condition, 'true')
>             end
>           elsif condition.falsey_literal?
>             add_offense(condition) do |corrector|
>               corrector.replace(condition, 'false')
>             end
>           else
>             # TODO: recursively visit nodes, using something like the original logic
>           end
>         end
> ```
> 

Assuming I'm understanding your intent correctly, node recursion isn't necessary because rubocop revisits changed nodes, so all cops essentially act recursively without having to explicitly handle it.

This is why, for example, [this spec](https://github.com/rubocop/rubocop/blob/master/spec/rubocop/cop/lint/literal_as_condition_spec.rb#L195) ends up autocorrecting to `top`, despite the cop only checking the lhs: if the left hand side is a truthy literal, it is removed, leaving an if statement with the original right hand side as the condition, which is also a truthy literal, which is then revisited due to the node being changed, and then autocorrected.

```ruby
# Original statement
if 10084 && 'mobius'
  foo
end

# First round of autocorrect: 10084 is detected as a truthy literal and removed by on_and.
if 'mobius'
  foo
end

# Second round of autocorrect triggered by this node being changed: 'mobius' is detected as a truthy literal and the if statement is removed by on_if.
foo
```
