### PR TITLE
[Fix #13933] Fix wrong autocorrect for `Style/KeywordParametersOrder` with comments

### LINKED ISSUE #13933: Botches the code completely for keyword arguments with a comment
Given this file where a defaulted keyword argument is followed by a non-defaulted keyword argument with a comment:

```
class Foo
  def foo(a: 1,
    # comment about b
    b:)
  end
end
```

Running `rubocop -A` totally botches the syntax (besides making the comment no longer associated with the code that the comment is intended for):

```
# frozen_string_literal: true

class Foo
  def foo(b:, a: 1,
          # comment about b)
  end
end
```

Expected result: leave the code alone when there are comments involved

```
 rubocop -V
1.50.2 (using Parser 3.3.5.0, rubocop-ast 1.32.3, running on ruby 3.3.4) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by Earlopain**
Fix #13933

There is nothing sensible to do here, except to not offer autocorrect at all. I think.

The first commit extracts a method to get the arguments range into `RangeHelp` since it already exists a few times and I was about to add another one.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/mixin/range_help.rb [hunk 1]
```diff
@@ -34,6 +34,21 @@ def contents_range(node)
         range_between(node.loc.begin.end_pos, node.loc.end.begin_pos)
       end
 
+      # A range containing the first to the last argument
+      # of a method call or method definition.
+      # def foo(a, b:)
+      #         ^^^^^
+      # bar(1, 2, 3, &blk)
+      #     ^^^^^^^^^^^^^
+      # baz { |x, y:, z: }
```
Comment (dvandersluis) [inline lib/rubocop/cop/mixin/range_help.rb:43]: Looks like you're missing a pipe here.
```suggestion
      # baz { |x, y:, z:| }
```

File: lib/rubocop/cop/mixin/range_help.rb [hunk 2]
```diff
@@ -34,6 +34,21 @@ def contents_range(node)
...
+      #        ^^^^^^^^^
+      def arguments_range(node)
+        range_between(
+          node.first_argument.source_range.begin_pos,
+          node.last_argument.source_range.end_pos
+        )
```
Comment (dvandersluis) [inline lib/rubocop/cop/mixin/range_help.rb:49]: This could be simplified:

```suggestion
        node.first_argument.source_range.join(node.last_argument.source_range)
```

Comment (Earlopain) [reply lib/rubocop/cop/mixin/range_help.rb]: Neat, applied. Thanks

**Comment by bbatsov** [comment]
Looks good to me!
