### PR TITLE
[Fix #12117] Fix `Style/ArgumentsForwarding` when not always forwarding a block

### LINKED ISSUE #12117: Style/ArgumentsForwarding breaks code in Ruby 2.7
Example code:

```ruby
class Foo
  def bar(*args, &block)
    hello(*args, &block)
    world(*args)
  end
end
```

## Expected behavior

Output code should be working code after autofix.

## Actual behavior

```
$ bundle exec rubocop -a test.rb`
...

test.rb:3:13: C: [Corrected] Style/ArgumentsForwarding: Use shorthand syntax ... for arguments forwarding.
    def bar(*args, &block)
            ^^^^^^^^^^^^^
test.rb:4:12: C: [Corrected] Style/ArgumentsForwarding: Use shorthand syntax ... for arguments forwarding.
      puts(*args, &block)
           ^^^^^^^^^^^^^
```

Result

```ruby
class Foo
  class << self
    def bar(...)
      puts(...)
      puts(*args)
    end
  end
end
```

This is broken since `args` is not defined anymore.

Please note it happens when running on 3.2.0 with `TargetRubyVersion: 2.7`.

If I run it on 3.2.0 with `TargetRubyVersion: 3.2`, output is:

```
class Foo
  class << self
    def bar(*, &block)
      puts(*, &block)
      puts(*)
    end
  end
end
```

And this is not working on ruby 2.7

## Steps to reproduce the problem

`Gemfile`

```ruby
source 'https://rubygems.org'

gem 'rubocop', '1.56.0'
```

`Gemfile.lock`

```
GEM
  remote: https://rubygems.org/
  specs:
    ast (2.4.2)
    base64 (0.1.1)
    json (2.6.3)
    language_server-protocol (3.17.0.3)
    parallel (1.23.0)
    parser (3.2.2.3)
      ast (~> 2.4.1)
      racc
    racc (1.7.1)
    rainbow (3.1.1)
    regexp_parser (2.8.1)
    rexml (3.2.6)
    rubocop (1.56.0)
      base64 (~> 0.1.1)
      json (~> 2.3)
      language_server-protocol (>= 3.17.0)
      parallel (~> 1.10)
      parser (>= 3.2.2.3)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml (>= 3.2.5, < 4.0)
      rubocop-ast (>= 1.28.1, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 2.4.0, < 3.0)
    rubocop-ast (1.29.0)
      parser (>= 3.2.1.0)
    ruby-progressbar (1.13.0)
    unicode-display_width (2.4.2)

PLATFORMS
  arm64-darwin-22

DEPENDENCIES
  rubocop (= 1.56.0)

BUNDLED WITH
   2.4.12
```

`.rubocop.yml`

```yaml
AllCops:
  TargetRubyVersion: 2.7

Style/ArgumentsForwarding:
  Enabled: true
```

```
$ ruby --version
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [arm64-darwin22]

$ bundle exec rubocop -V
1.56.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 2.7.8) [arm64-darwin22]

$ cat .tool-versions
ruby 2.7.8
``````

### PR DESCRIPTION
**Pull request by owst**
With `TargetRubyVersion < 3.2`, if some call sites forwarded the block but others didn't then the cop didn't classify the without-block call site as a forwarding call, and thus didn't notice the discrepancy between those that did forward the block and those that didn't.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/arguments_forwarding.rb [hunk 1]
```diff
@@ -280,7 +280,7 @@ def classification
 
             if can_forward_all?
               :all
-            elsif target_ruby_version >= 3.2
```
Comment (owst) [inline lib/rubocop/cop/style/arguments_forwarding.rb:283]: We check this condition again on line 105 (but by then we would have already rejected the false-positive this PR fixes)

File: changelog/fix_an_error_for_style_arguments_forwarding_when_not_always_forwarding_block.md [hunk 2]
```diff
@@ -0,0 +1 @@
+* [#12117](https://github.com/rubocop/rubocop/issues/12117): Fix an error for `Style/ArgumentsForwarding` cop when not always forwarding block. ([@owst][])
```
Comment (koic) [inline changelog/fix_an_error_for_style_arguments_forwarding_when_not_always_forwarding_block.md:1]: Can you tweak to the following?

```suggestion
* [#12117](https://github.com/rubocop/rubocop/issues/12117): Fix a false positive for `Style/ArgumentsForwarding` cop when not always forwarding block. ([@owst][])
```

File: spec/rubocop/cop/style/arguments_forwarding_spec.rb [hunk 3]
```diff
@@ -240,6 +240,34 @@ def foo(*args, &block)
...
+    it 'does not register an offense when not always passing the block as well as restarg' do
+      expect_no_offenses(<<~RUBY)
+        def foo(*args, &block)
+          bar(*args, &block)
+          baz(*args)
+        end
+      RUBY
+    end
+
+    it 'does not register an offense when not always passing the block as well as krestarg' do
```
Comment (koic) [inline spec/rubocop/cop/style/arguments_forwarding_spec.rb:252]: Is this a typo?

```suggestion
    it 'does not register an offense when not always passing the block as well as kwrestarg' do
```

File: spec/rubocop/cop/style/arguments_forwarding_spec.rb [hunk 4]
```diff
@@ -956,6 +984,68 @@ def foo(*, **, &block)
...
+
+      expect_correction(<<~RUBY)
+        def foo(*, &block)
+          bar(*, &block)
+          baz(*)
+        end
+      RUBY
+    end
+
+    it 'registers an offense when not always passing the block as well as krestarg' do
```
Comment (koic) [inline spec/rubocop/cop/style/arguments_forwarding_spec.rb:1006]: Ditto :-)

```suggestion
    it 'registers an offense when not always passing the block as well as kwrestarg' do
```

**Comment by koic** [comment]
Looks good to me. Can you squash your commits into one?

**Comment by koic** [comment]
Thanks!
