### PR TITLE
[Fix #9713] Skip autocorrection for block_local_variables in `Lint/UnusedBlockArgument`

### LINKED ISSUE #9713: Lint/UnusedBlockArgument: mishandles block local variables
In the following example rubucop changed the meaning of the program.

```
$ ruby foo.rb
42
$ rubocop -A --only Lint/UnusedBlockArgument foo.rb
[...]
$ ruby foo.rb
666
```

--------

## Expected behavior

In the following program, I have explicitly stated that v2 in the block is scoped to the block, and different from the one around.

```
$ cat foo.rb
v2 = 42
[1, 2, 3].sum do |v; v2|
  v2 = 666
  v*v
end
puts v2
```

The inner v2 is absolutely useless, granted, so I should get something like

```
v2 = 42
[1, 2, 3].sum do |v; _v2|
  _v2 = 666
  v*v
end
puts v2
```

## Actual behavior

I get

```
v2 = 42
[1, 2, 3].sum do |v; _v2|
  v2 = 666
  v*v
end
puts v2
```
where the inner assignment to v2 was not renamed, so the meaning was changed.

> Please use `rubocop --debug` when pasting rubocop output as it contains additional information.

You asked for it.

```
$ rubocop  --only Lint/UnusedBlockArgument --debug foo.rb
For /private/tmp: configuration from /Users/akim/.rubocop.yml
Default configuration from /opt/local/lib/ruby3.0/gems/3.0.0/gems/rubocop-1.12.1/config/default.yml
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.

Please also note that can also opt-in to new cops by default by adding this to your config:
  AllCops:
    NewCops: enable

Gemspec/DateAssignment: # (new in 1.10)
  Enabled: true
Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true
Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true
Lint/EmptyBlock: # (new in 1.1)
  Enabled: true
Lint/EmptyClass: # (new in 1.3)
  Enabled: true
Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true
Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true
Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true
Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: true
Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true
Lint/SymbolConversion: # (new in 1.9)
  Enabled: true
Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true
Lint/TripleQuotes: # (new in 1.9)
  Enabled: true
Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true
Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true
Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true
Style/CollectionCompact: # (new in 1.2)
  Enabled: true
Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true
Style/EndlessMethod: # (new in 1.8)
  Enabled: true
Style/HashConversion: # (new in 1.10)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true
Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true
Style/NilLambda: # (new in 1.3)
  Enabled: true
Style/RedundantArgument: # (new in 1.4)
  Enabled: true
Style/StringChars: # (new in 1.12)
  Enabled: true
Style/SwapValues: # (new in 1.1)
  Enabled: true
For more information: https://docs.rubocop.org/rubocop/versioning.html
Inspecting 1 file
Scanning /private/tmp/foo.rb
W

Offenses:

foo.rb:2:22: W: [Correctable] Lint/UnusedBlockArgument: Unused block local variable - v2.
[1, 2, 3].sum do |v; v2|
                     ^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
Finished in 0.1177519999910146 seconds
```

## Steps to reproduce the problem

See above the self contained example.

## RuboCop version

```
$ rubocop -V
1.12.1 (using Parser 3.0.1.0, rubocop-ast 1.4.1, running on ruby 3.0.1 x86_64-darwin18)
```

Cheers!

### PR DESCRIPTION
**Pull request by tejasbubane**
Not sure if there is a better solution. But I think this cop should restrict itself to arguments and not make corrections within block body as suggested in the issue.

Closes #9713

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/unused_block_argument_spec.rb [hunk 1]
```diff
@@ -199,17 +199,31 @@
...
+
+        it 'registers an offense but does not correct' do
           expect_offense(<<~RUBY)
-            1.times do |index; block_local_variable|
-                               ^^^^^^^^^^^^^^^^^^^^ Unused block local variable - `block_local_variable`.
+            1.times do |index; x|
+                               ^ #{message}
+              x = 10
               puts index
             end
```
Comment (dvandersluis) [inline spec/rubocop/cop/lint/unused_block_argument_spec.rb:214]: Why is this an offense? The block variable is used?

**Comment by koic** [comment]
I agree with @dvandersluis's concern. The issue is a false positive when using a local variable defined outside the block as a block variable. It requires testing based on #9713 and fix to the false positive. Unfortunately, skipping auto-correction does not solve the issue 😢

**Comment by tejasbubane** [comment]
@koic @dvandersluis This was an [existing behaviour](https://github.com/rubocop/rubocop/blob/76bc0a0e026b13fccdc7b6bccfd6d082d24a7b52/spec/rubocop/cop/lint/unused_block_argument_spec.rb#L48-L65) which I assumed was intentional because the variable assigned inside block is not really used.

**Comment by tejasbubane** [comment]
I have changed code to not register offense in this case.

**Review by koic — APPROVED** [review]
This change looks good to me. Thank you!

**Comment by bbatsov** [comment]
Thanks!
