### PR TITLE
[Fix #13085] Fix a false positive for `Style/EmptyElse`

### LINKED ISSUE #13085: False positive for `Style/EmptyElse` when `AllowComments: true` with elsif-clause
## Expected behavior

We expect that the following codes are not offenses:
```ruby
if condition
  statement
elsif condition2
  statement2
else
  # some comment
end
```

## Actual behavior

Offenses occur:
```ruby
if condition
  statement
elsif condition2
  statement2
else
^^^^ Redundant `else`-clause.
  # some comment
end
```

## Steps to reproduce the problem

The following settings must be included in .rubocop.yml:

```yaml
Style/EmptyElse:
  AllowComments: true
```

## RuboCop version

```
❯ bundle exec rubocop -V                                     
1.65.0 (using Parser 3.3.4.0, rubocop-ast 1.31.3, running on ruby 3.3.0) [arm64-darwin23]
  - rubocop-performance 1.21.1
  - rubocop-rake 0.6.0
  - rubocop-rspec 3.0.3
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #13085.

This PR fixes a false positive for `Style/EmptyElse` when a comment-only `else` is used after `elsif` and `AllowComments: true` is set.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/empty_else_spec.rb [hunk 1]
```diff
@@ -589,6 +589,63 @@
           RUBY
         end
       end
+
+      context 'with not comment and empty else-clause after `elsif`' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/empty_else_spec.rb:593]: not -> no

File: spec/rubocop/cop/style/empty_else_spec.rb [hunk 2]
```diff
@@ -589,6 +589,63 @@
...
+            elsif condition2
+              bar
+            else
+            ^^^^ Redundant `else`-clause.
+            end
+          RUBY
+        end
+      end
+
+      context 'with not comment and nil else-clause after `elsif`' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/empty_else_spec.rb:607]: not -> no

File: changelog/fix_false_positive_for_style_empty_else.md [hunk 3]
```diff
@@ -0,0 +1 @@
+* [#13085](https://github.com/rubocop/rubocop/issues/13085): Fix a false positive for `Style/EmptyElse` when an empty `else` is used after `elsif` and `AllowComments: true` is set. ([@koic][])
```
Comment (Earlopain) [inline changelog/fix_false_positive_for_style_empty_else.md:1]:
```suggestion
* [#13085](https://github.com/rubocop/rubocop/issues/13085): Fix a false positive for `Style/EmptyElse` when comment-only `else` is used after `elsif` and `AllowComments: true` is set. ([@koic][])
```

File: lib/rubocop/cop/style/empty_else.rb [hunk 4]
```diff
@@ -171,16 +171,16 @@ def nil_check(node)
...
           corrector.remove(range_between(node.loc.else.begin_pos, end_pos))
         end
 
-        def comment_in_else?(loc)
-          return false if loc.else.nil? || loc.end.nil?
+        def comment_in_else?(node)
+          node = node.parent while node.if_type? && node.elsif?
 
-          processed_source.contains_comment?(loc.else.join(loc.end))
+          processed_source.contains_comment?(node.loc.else.join(node.source_range.end))
```
Comment (chaadow) [inline lib/rubocop/cop/style/empty_else.rb:183]: I believe the issue stems from here, the node does not have an else statement, hence `else` is nil and triggering the error
