### PR TITLE
[Fix #10951] Fix an autocorrection error for `Lint/EmptyConditionalBody` when some conditional branch is empty

### LINKED ISSUE #10951: Parser::Source::TreeRewriter detected clobbering during `Lint/EmptyConditionalBody`
<details>
  <summary>Complete error log</summary>
  
  ```text
An error occurred while Lint/EmptyConditionalBody cop was inspecting /home/earlopain/Documents/test.rb:2:2.
Parser::Source::TreeRewriter detected clobbering
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter.rb:427:in `trigger_policy'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter.rb:414:in `enforce_policy'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:233:in `call'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:233:in `swallow'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:97:in `with'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:124:in `place_in_hierarchy'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:106:in `do_combine'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:117:in `place_in_hierarchy'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:106:in `do_combine'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:30:in `combine'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter.rb:400:in `combine'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter.rb:194:in `replace'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/lint/empty_conditional_body.rb:103:in `correct_other_branches'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/lint/empty_conditional_body.rb:84:in `autocorrect'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/lint/empty_conditional_body.rb:75:in `block in on_if'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/base.rb:346:in `correct'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/base.rb:127:in `add_offense'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/lint/empty_conditional_body.rb:74:in `on_if'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:98:in `each'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:69:in `on_if'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:153:in `on_class'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:71:in `on_class'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/team.rb:155:in `investigate_partial'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/team.rb:83:in `investigate'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:311:in `inspect_file'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:255:in `block in do_inspection_loop'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:289:in `block in iterate_until_no_changes'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:282:in `loop'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:282:in `iterate_until_no_changes'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:251:in `do_inspection_loop'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:134:in `block in file_offenses'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:159:in `file_offense_cache'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:133:in `file_offenses'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:69:in `block in warm_cache'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:557:in `process_incoming_jobs'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
/home/earlopain/.gem/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:238:in `each'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:69:in `warm_cache'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:46:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/command.rb:11:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/environment.rb:18:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli.rb:72:in `run_command'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli.rb:79:in `execute_runners'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli.rb:48:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/exe/rubocop:19:in `block in <top (required)>'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/exe/rubocop:19:in `<top (required)>'
/home/earlopain/.rbenv/versions/3.1.2/bin/rubocop:25:in `load'
/home/earlopain/.rbenv/versions/3.1.2/bin/rubocop:25:in `<top (required)>'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
/home/earlopain/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/earlopain/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Inspecting 1 file
Scanning /home/earlopain/Documents/test.rb
An error occurred while Lint/EmptyConditionalBody cop was inspecting /home/earlopain/Documents/test.rb:2:2.
Parser::Source::TreeRewriter detected clobbering
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter.rb:427:in `trigger_policy'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter.rb:414:in `enforce_policy'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:233:in `call'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:233:in `swallow'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:97:in `with'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:124:in `place_in_hierarchy'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:106:in `do_combine'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:117:in `place_in_hierarchy'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:106:in `do_combine'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter/action.rb:30:in `combine'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter.rb:400:in `combine'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/parser-3.1.2.1/lib/parser/source/tree_rewriter.rb:194:in `replace'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/lint/empty_conditional_body.rb:103:in `correct_other_branches'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/lint/empty_conditional_body.rb:84:in `autocorrect'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/lint/empty_conditional_body.rb:75:in `block in on_if'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/base.rb:346:in `correct'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/base.rb:127:in `add_offense'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/lint/empty_conditional_body.rb:74:in `on_if'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:98:in `each'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:69:in `on_if'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:153:in `on_class'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:71:in `on_class'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-ast-1.21.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/team.rb:155:in `investigate_partial'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cop/team.rb:83:in `investigate'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:311:in `inspect_file'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:255:in `block in do_inspection_loop'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:289:in `block in iterate_until_no_changes'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:282:in `loop'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:282:in `iterate_until_no_changes'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:251:in `do_inspection_loop'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:134:in `block in file_offenses'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:159:in `file_offense_cache'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:133:in `file_offenses'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:124:in `process_file'
/home/earlopain/.rbeoutside of the class.nv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:105:in `block in each_inspected_file'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:104:in `each'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:104:in `reduce'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:104:in `each_inspected_file'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:90:in `inspect_files'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/runner.rb:47:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/command.rb:11:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli/environment.rb:18:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli.rb:72:in `run_command'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli.rb:79:in `execute_runners'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/lib/rubocop/cli.rb:48:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/exe/rubocop:19:in `block in <top (required)>'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rubocop-1.35.1/exe/rubocop:19:in `<top (required)>'
/home/earlopain/.rbenv/versions/3.1.2/bin/rubocop:25:in `load'
/home/earlopain/.rbenv/versions/3.1.2/bin/rubocop:25:in `<top (required)>'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `load'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli/exec.rb:23:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli.rb:483:in `exec'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli.rb:31:in `dispatch'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/cli.rb:25:in `start'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/exe/bundle:48:in `block in <top (required)>'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/home/earlopain/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.12/exe/bundle:36:in `<top (required)>'
/home/earlopain/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/earlopain/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
W

Offenses:

test.rb:3:3: W: [Correctable] Lint/EmptyConditionalBody: Avoid elsif branches without a body.
  elsif condition2
  ^^^^^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense autocorrectable

1 error occurred:
An error occurred while Lint/EmptyConditionalBody cop was inspecting /home/earlopain/Documents/test.rb:2:2.
  ```
</details>

## Steps to reproduce the problem
Here's a minimally reproducable piece of code. The class is required, it works normally when it's top-level code.
```rb
class Test
  if condition1
  elsif condition2
  end
end

  ```

## RuboCop version

```
1.35.1 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.1.2 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by ydah**
Fix: #10951

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/empty_conditional_body.rb [hunk 1]
```diff
@@ -96,7 +96,8 @@ def remove_empty_branch(corrector, node)
         end
 
         def correct_other_branches(corrector, node)
-          return unless (node.if? || node.unless?) && node.else_branch
+          return unless correctable_condition?(node) && node.else_branch
```
Comment (koic) [inline lib/rubocop/cop/lint/empty_conditional_body.rb:99]: Can you use `node.if_type?` instead of the new `correctable_condition?` method?

```suggestion
          return unless node.if_type? && node.else_branch
```

File: lib/rubocop/cop/lint/empty_conditional_body.rb [hunk 2]
```diff
@@ -107,14 +108,36 @@ def correct_other_branches(corrector, node)
...
+
+        def empty_else_branch?(node)
+          node.else_branch.if_type? && !node.else_branch.body
+        end
+
         def branch_range(node)
           if node.loc.else
             node.source_range.with(end_pos: node.loc.else.begin_pos - 1)
+          elsif all_branches_body_missing?(node)
+            node.source_range.with(end_pos: parent_if_node(node).loc.end.end_pos)
```
Comment (koic) [inline lib/rubocop/cop/lint/empty_conditional_body.rb:123]: Can you use `node.ancestors.detect(&:if?)` instead of the new `parent_if_node` method?

```suggestion
            if_node = node.ancestors.detect(&:if?)

            node.source_range.with(end_pos: if_node.loc.end.end_pos)
```

`Metrics/AbcSize`'s warning will probably be displayed, but I think that `branch_range` method can be enclosed with `# rubocop:disable Metrics/AbcSize` and `# rubocop:enable Metrics/AbcSize`.

File: lib/rubocop/cop/lint/empty_conditional_body.rb (hunk 1 above)
Comment (ydah) [reply lib/rubocop/cop/lint/empty_conditional_body.rb]: That looks better. Thank you!

File: lib/rubocop/cop/lint/empty_conditional_body.rb (hunk 2 above)
Comment (ydah) [reply lib/rubocop/cop/lint/empty_conditional_body.rb]: Indeed it is. Use `node.ancestors.detect(&:if?)`. Thank you!

**Comment by ydah** [comment]
I updated this PR. Thank you so much!

**Comment by koic** [comment]
Can you add the test below and it passes?

```ruby
   it 'registers an offense for missing `elsif` body' do
     expect_offense(<<~RUBY)
       if condition
         do_something1
       elsif other_condition1
       ^^^^^^^^^^^^^^^^^^^^^^ Avoid `elsif` branches without a body.
       elsif other_condition2
         do_something2
       end
     RUBY

     expect_correction(<<~RUBY)
       if condition
         do_something1
       elsif other_condition2
         do_something2
       end
     RUBY
   end
```

Would be a syntax error.

```console
% bundle exec rspec  spec/rubocop/cop/lint/empty_conditional_body_spec.rb

Randomized with seed 32341
....F.............

Failures:

  1) RuboCop::Cop::Lint::EmptyConditionalBody registers an offense for missing `if` and `elsif` body
     Failure/Error: expect(new_source).to eq(correction)

       expected: "if condition\n  do_something1\nelsif other_condition2\n  do_something2\nend\n"
            got: "if condition\n  do_something1\nif other_condition2\n  do_something2\nend\n"

       (compared using ==)

       Diff:
       @@ -1,6 +1,6 @@
        if condition
          do_something1
       -elsif other_condition2
       +if other_condition2
          do_something2
        end

     # ./lib/rubocop/rspec/expect_offense.rb:162:in `expect_correction'
     # ./spec/rubocop/cop/lint/empty_conditional_body_spec.rb:51:in `block (2 levels) in <top (required)>'

Finished in 0.17541 seconds (files took 1.09 seconds to load)
18 examples, 1 failure

Failed examples:
```

**Comment by ydah** [comment]
Thank you very much. I updated this PR.

File: lib/rubocop/cop/lint/empty_conditional_body.rb [hunk 3]
```diff
@@ -107,13 +107,41 @@ def correct_other_branches(corrector, node)
           end
         end
 
+        def correct_other_branches?(node)
```
Comment (koic) [inline lib/rubocop/cop/lint/empty_conditional_body.rb:110]: How about a method name like?

```suggestion
        def require_other_branches_correction?(node)
```

File: lib/rubocop/cop/lint/empty_conditional_body.rb [hunk 4]
```diff
@@ -107,13 +107,41 @@ def correct_other_branches(corrector, node)
...
+          return false unless node.if_type? && node.else_branch
+
+          !(!empty_if_branch?(node) && node.elsif?) && !empty_else_branch?(node)
```
Comment (koic) [inline lib/rubocop/cop/lint/empty_conditional_body.rb:113]: Can you refactor to the below? Because this condition is complicated.

```suggestion
          return false unless node.if_type? && node.else_branch
          return false if !empty_if_branch?(node) && node.elsif?

          !empty_else_branch?(node)
```

File: lib/rubocop/cop/lint/empty_conditional_body.rb [hunk 5]
```diff
@@ -107,13 +107,41 @@ def correct_other_branches(corrector, node)
...
+        end
+
+        def empty_if_branch?(node)
+          return false unless node.parent&.if_type?
+          return true unless node.parent.if_branch
+
+          node.parent.if_branch.if_type? && !node.parent.if_branch.body
```
Comment (koic) [inline lib/rubocop/cop/lint/empty_conditional_body.rb:120]: Can you reduce repeated method calls?

```suggestion
          return false unless (parent = node.parent)
          return true unless parent.if_type?
          return true unless (if_branch = parent.if_branch)

          parent.if_branch.if_type? && !parent.if_branch.body
```

File: changelog/fix_fix_an_autocorrection_error_for_lint_empty_conditional_body.md [hunk 6]
```diff
@@ -0,0 +1 @@
+* [#10951](https://github.com/rubocop/rubocop/issues/10951): Fix an autocorrection error for `Lint/EmptyConditionalBody`. ([@ydah][])
```
Comment (koic) [inline changelog/fix_fix_an_autocorrection_error_for_lint_empty_conditional_body.md:1]: Can you add a more bit explanation about the context of this incorrect autocorection?

File: spec/rubocop/cop/lint/empty_conditional_body_spec.rb [hunk 7]
```diff
@@ -24,19 +24,60 @@
...
+      elsif other_condition
+      ^^^^^^^^^^^^^^^^^^^^^ Avoid `elsif` branches without a body.
+      end
+      if condition
+      ^^^^^^^^^^^^ Avoid `if` branches without a body.
+      elsif other_condition1
+      ^^^^^^^^^^^^^^^^^^^^^^ Avoid `elsif` branches without a body.
+      elsif other_condition2
+      ^^^^^^^^^^^^^^^^^^^^^^ Avoid `elsif` branches without a body.
+      end
```
Comment (koic) [inline spec/rubocop/cop/lint/empty_conditional_body_spec.rb:75]: Wouldn't it be better to split L64-L68 and L69-L75 into different test cases?

Comment (koic) [reply spec/rubocop/cop/lint/empty_conditional_body_spec.rb:75]: That aside, I watch the repository so review request is unneeded after PR update.
