### PR TITLE
[Fix #12687] Fix a false positive for `Lint/Void`

### LINKED ISSUE #12687: Lint/Void false positive and unsafe autocorrect
Hi, I noticed a bug while using [Parallel)](https://github.com/grosser/parallel/tree/master) .

sample.rb
```ruby
# frozen_string_literal: true
require 'parallel'
items = [1, 2, 3]
Parallel.each(items,
              finish: lambda { |_item, _index, result|
                puts "puts result: #{result}"
              }) do |i|
  puts i * 10
  i * 10
end
```

## Expected behavior
```shell
bundle exec rubocop -a sample.rb
```
No changes should occur, and the following result should be obtained:

```
30
10
20
puts result: 10
puts result: 20
puts result: 30
```

## Actual behavior
The following error occurs:

```
Inspecting 1 file
W

Offenses:

sample.rb:11:3: W: [Corrected] Lint/Void: Variable i used in void context.
  i
  ^
sample.rb:11:5: W: [Corrected] Lint/Void: Operator * used in void context.
  i * 10
    ^
sample.rb:12:1: C: [Corrected] Layout/IndentationConsistency: Inconsistent indentation detected.
10
^^
sample.rb:12:1: W: [Corrected] Lint/Void: Literal 10 used in void context.
10
^^
sample.rb:12:3: W: [Corrected] Lint/Void: Literal 10 used in void context.
  10
  ^^

1 file inspected, 5 offenses detected, 5 offenses corrected
```

This code and results are changed.

```ruby
# frozen_string_literal: true
require 'parallel'
items = [1, 2, 3]
Parallel.each(items,
              finish: lambda { |_item, _index, result|
                puts "puts result: #{result}"
              }) do |i|
  puts i * 10
end
```

```
20
10
puts result:
puts result:
30
puts result:
```

I think `check_void_op` runs when 'each' is detected.
https://github.com/rubocop/rubocop/blob/master/lib/rubocop/cop/lint/void.rb#L86

Additionally, If you change the return value from `i * 10` to `(i * 10)`, nothing happens. which is storange.

## Steps to reproduce the problem
Test case above.
You can pull it from [this gist](https://gist.github.com/yayamochi/d9accbcf1c28e44274333d9725ce6273) and execute rubocop.

## RuboCop version

```
$ [bundle exec] rubocop -V
1.60.2 (using Parser 3.3.0.5, rubocop-ast 1.30.0, running on ruby 3.0.4) [arm64-darwin22]
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12687.

This PR fixes a false positive for `Lint/Void` when `each` block with conditional expressions that has multiple statements.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/void_spec.rb [hunk 1]
```diff
@@ -614,6 +614,18 @@ def foo=(rhs)
     RUBY
   end
 
+  it 'does not register `#each` block with conditional expressions that has multiple statements' do
+    expect_no_offenses(<<~RUBY)
+      enumerator_as_filter.each do |item|
```
Comment (bbatsov) [inline spec/rubocop/cop/lint/void_spec.rb:619]: Won't this be different for this different enumerators, though? Maybe some Allowed list would make more sense than just assuming that multiple expressions are OK all the time.

Comment (koic) [reply spec/rubocop/cop/lint/void_spec.rb:619]: Initially, I also considered Allowed list approach, but it appears that the issue was simply that the following logic for `on_block` was not accounted for in the implementation of `on_begin`.
https://github.com/rubocop/rubocop/blob/v1.60.2/lib/rubocop/cop/lint/void.rb#L86

So, I think this approach could provide a more generic solution instead of Allowed list.
