### PR TITLE
[Fix #12111] Fix an error for `Bundler/DuplicatedGroup`

### LINKED ISSUE #12111: Bundler/DuplicatedGroup undefined method
## Expected behavior

Preferably, to Rubocop not to return errors. 

```SH
$ bundle exec rubocop
Inspecting 15 files
...............

15 files inspected, no offenses detected
$ echo $?
0
```

## Actual behavior

```SH
$ bundle exec rubocop
An error occurred while Bundler/DuplicatedGroup cop was inspecting /home/user/Git/2factorauth/twofactorauth/Gemfile.
To see the complete backtrace run rubocop -d.
Inspecting 15 files
An error occurred while Bundler/DuplicatedGroup cop was inspecting /home/user/Git/2factorauth/twofactorauth/Gemfile.
To see the complete backtrace run rubocop -d.
$ echo $?
1
...............

15 files inspected, no offenses detected

1 error occurred:
An error occurred while Bundler/DuplicatedGroup cop was inspecting /home/user/Git/2factorauth/twofactorauth/Gemfile.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.56.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.1.2) [x86_64-linux-gnu]
```

```
Scanning /home/user/Git/2factorauth/twofactorauth/Gemfile
An error occurred while Bundler/DuplicatedGroup cop was inspecting /home/user/Git/2factorauth/twofactorauth/Gemfile.
undefined method `value' for s(:hash,
  s(:pair,
    s(:sym, :optional),
    s(:true))):RuboCop::AST::HashNode

            .group_by { |node| node.arguments.map(&:value).map(&:to_s).sort }
                                             ^^^^
Did you mean?  values
```
## Steps to reproduce the problem

Run Rubocop (using a version where #12074 is included) with the following Gemfile:
```
# frozen_string_literal: true

source 'https://rubygems.org'

group :tests, optional: true do
  gem 'activesupport'
  gem 'addressable'
  gem 'json_schemer'
  gem 'nokogiri'
  gem 'rubocop'
  gem 'twitter'
end

gem 'algolia', '~> 2.3'
gem 'dotenv', '~> 2.8'
gem 'parallel', '~> 1.22'
```

## RuboCop version

```SH
$ bundle exec rubocop -V
1.56.0 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.1.2) [x86_64-linux-gnu]
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12111.

This PR fixes an error for `Bundler/DuplicatedGroup` group declaration has keyword option.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/bundler/duplicated_group_spec.rb [hunk 1]
```diff
@@ -77,6 +77,16 @@
       end
     end
 
+    context 'and a group has a keyword option' do
+      it 'does not register any offenses' do
+        expect_no_offenses(<<~RUBY, 'Gemfile')
```
Comment (bbatsov) [inline spec/rubocop/cop/bundler/duplicated_group_spec.rb:82]: Might be better to have a test showing same groups with same options and same groups with different options.

**Comment by bbatsov** [comment]
I think it's important that the cop handles keywords in his logic for comparing groups - e.g. same group with the same options should be flagged as duplicate.

File: spec/rubocop/cop/bundler/duplicated_group_spec.rb (hunk 1 above)
Comment (koic) [reply spec/rubocop/cop/bundler/duplicated_group_spec.rb:94]: It makes sense! I updated this PR.

**Comment by bbatsov** [comment]
Looks great!
