### PR TITLE
[Fix #13324] Fix `--disable-uncorrectable` to not insert a comment inside a string continuation

### LINKED ISSUE #13324: --disable-uncorrectable creates syntax errors when violations occur within multi-line strings
`--disable-uncorrectable` should not attempt to inject a line-level `rubocop:todo` comment in the middle of a multi-line string.  This results in syntax errors.

This was filed in issue https://github.com/rubocop/rubocop/issues/7216 but root cause was not addressed in that issue.  The example cop was just modified to detect fewer violations to work around it.  The general issue of `--disable-uncorrectable` not working correctly with multi-line strings is reproducible with any non-autocorrectable cop that can detect a violation on a line that ends with a string.

Example:

```
# This code has a violation of Lint/DuplicateHashKey

          foo = {
            key1: "something",
            key1: "whatever"\
              "something else",
          }
```

--------

## Expected behavior

`--disable-uncorrectable` should wrap the multi-line string like this:

```
          foo = {
            key1: "something",
            # rubocop:todo Lint/DuplicateHashKey
            key1: "whatever"\
              "something else",
            # rubocop:enable Lint/DuplicateHashKey
          }
```

## Actual behavior

Instead it creates a syntax error

```
          foo = {
            key1: "something",
            key1: "whatever"\ # rubocop:todo Lint/DuplicateHashKey
              "something else",
          }
```

## Steps to reproduce the problem

Create any code sample that has a non-autocorrectable violation of any cop on a line that terminates part-way through a multi-line string.

Run rubocop with `-A --disable-uncorrectable`

## RuboCop version

```
bundle exec rubocop -V
1.66.1 (using Parser 3.3.5.0, rubocop-ast 1.32.3, running on ruby 3.1.3) +server [arm64-darwin21]
  - rubocop-rails 2.10.1
  - rubocop-rspec 2.12.1
  - rubocop-sorbet 0.7.4
  - rubocop-thread_safety 0.5.1

```

### PR DESCRIPTION
**Pull request by dvandersluis**
With the following code and `--disable-uncorrectable` specified:

```ruby
{
  key1: "something",
  key1: "whatever"\
    "something else",
}
```

Previously RuboCop corrected to a syntax error:

```ruby
{
  key1: "something",
  key1: "whatever"\ # rubocop:todo Lint/DuplicateHashKey
    "something else",
}
```

With this correction, RuboCop uses the block form of `todo` instead:

```ruby
{
  key1: 'something',
  # rubocop:todo Lint/DuplicateHashKey
  key1: 'whatever'\
    'something else'
  # rubocop:enable Lint/DuplicateHashKey
}
```

Fixes #13324.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/autocorrect_logic.rb [hunk 1]
```diff
@@ -88,10 +90,28 @@ def surrounding_percent_array(offense_range)
...
+
+        string_continuation_nodes = processed_source.ast.each_descendant.filter_map do |node|
+          range_by_lines(node.source_range) if string_continuation?(node)
+        end
+
+        string_continuation_nodes.find { |range| range_overlaps_offense?(offense_range, range) }
+      end
+
+      def range_overlaps_offense?(offense_range, range)
+        offense_range.begin_pos > range.begin_pos && range.overlaps?(offense_range)
```
Comment (koic) [inline lib/rubocop/cop/autocorrect_logic.rb:108]: It seems the test passes even without `range.overlaps?(offense_range)`. Can you review the logic or the test?

File: lib/rubocop/cop/autocorrect_logic.rb [hunk 2]
```diff
@@ -88,10 +90,28 @@ def surrounding_percent_array(offense_range)
...
+      end
+
+      def string_continuation?(node)
+        (node.str_type? || node.dstr_type? || node.xstr_type?) && node.source =~ /\\\s*$/
```
[the remark this answers is not in the document]
Comment (dvandersluis) [reply lib/rubocop/cop/autocorrect_logic.rb:112]: Updated, thanks.

File: lib/rubocop/cop/autocorrect_logic.rb (hunk 1 above)
Comment (dvandersluis) [reply lib/rubocop/cop/autocorrect_logic.rb:108]: It is necessary. I added a second test that would fail without it:

```ruby
context 'and the offense is on a different line than a string continuation' do
  it 'adds a single one-line disable statement' do
    create_file('.rubocop.yml', <<~YAML)
      AllCops:
        DisabledByDefault: true
      Lint/DuplicateHashKey:
        Enabled: true
    YAML
    create_file('example.rb', <<~'RUBY')
      x = 'something'\
        'something else'
      {
        key1: 'foo',
        key1: 'bar'
      }
    RUBY
    expect(exit_code).to eq(0)
    expect(File.read('example.rb')).to eq(<<~'RUBY')
      x = 'something'\
        'something else'
      {
        key1: 'foo',
        key1: 'bar' # rubocop:todo Lint/DuplicateHashKey
      }
    RUBY
  end
end
```
