### PR TITLE
[Fix #10651] Fix autocorrect for `Style/For` when using array with operator methods as collection

### LINKED ISSUE #10651: Style/For correction breaks when using array concatenation
```
a = [1]
b = [2]
c = [3]

for n in a + b + c
  puts n
end
```

Outputs:
```
1
2
3
```

Running `rubocop -A` on this method:

```
style_for_test.rb:5:1: C: [Corrected] Style/For: Prefer each over for.
for n in a + b + c ...
^^^^^^^^^^^^^^^^^^
```

File becomes:

```
a = [1]
b = [2]
c = [3]

a + b + c.each do |n|
  puts n
end
```

Outputs:

```
3
```

**Output has changed!**

Expected correction:

```
a = [1]
b = [2]
c = [3]

(a + b + c).each do |n|
  puts n
end
```

Which retains the original output.

`rubocop -V`:
```
1.29.1 (using Parser 3.1.2.0, rubocop-ast 1.18.0, running on ruby 2.7.6 x86_64-linux)
  - rubocop-minitest 0.17.2
  - rubocop-performance 1.13.2
  - rubocop-rails 2.13.2
```

### PR DESCRIPTION
**Pull request by nobuyo**
Fixes #10651.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/correctors/for_to_each_corrector.rb [hunk 1]
```diff
@@ -35,7 +35,15 @@ def collection_source
       end
 
       def requires_parentheses?
-        collection_node.range_type?
+        collection_node.range_type? || send_with_operator? || using_logical_operator?
```
Comment (koic) [inline lib/rubocop/cop/correctors/for_to_each_corrector.rb:38]: Maybe it won't lose information even if it's inline. The name `using_logical_operator?` may be a little confused with `logical_operator?`, but this solves it :-)

```suggestion
        return true if collection_node.send_type? && collection_node.operator_method?
        
        collection_node.range_type? || collection_node.or_type? || collection_node.and_type?
```

**Comment by nobuyo** [comment]
I've updated this PR. Thank you!

**Comment by koic** [comment]
Thanks!
