### PR TITLE
[Fix #11120] Fix an incorrect autocorrect for `Lint/RedundantRequireStatement`

### LINKED ISSUE #11120: `Lint/RedundantRequireStatement` breaks code with modifiers
```ruby
require 'pp' unless respond_to?(:pretty_inspect)
```

Autocorrect breaks code when `require` is followed by postfix `unless`.

--------

## Expected behavior

Autocorrects into valid Ruby code, possibly like below (considering the modifier condition may have side effects.)

```ruby
respond_to?(:pretty_inspect)
```

## Actual behavior

```
Offenses:

main.rb:1:1: W: [Correctable] Lint/RedundantRequireStatement: Remove unnecessary require statement.
require 'pp' unless respond_to?(:pretty_inspect)
^^^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense autocorrectable
```

effectively autocorrects code into

```ruby
unless respond_to?(:pretty_inspect)
```

, which is syntactically incorrect.

## Steps to reproduce the problem

```
$ cat main.rb
require 'pp' unless respond_to?(:pretty_inspect)
$ rubocop --only Lint/RedundantRequireStatement
```

## RuboCop version

```
$ rubocop -V
1.37.1 (using Parser 3.1.2.1, rubocop-ast 1.23.0, running on ruby 3.1.1) [x86_64-darwin20]
$ 
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #11120.

This PR fixes an incorrect autocorrect for `Lint/RedundantRequireStatement` when using redundant `require` with modifier form.

For example, in essential it is unknown how many times `do_something` will be executed when `require 'enumerator' while do_something`. So it does not autocorrects when modifier form is used to avoid side effects.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by bbatsov** [comment]
> For example, in essential it is unknown how many times do_something will be executed when require 'enumerator' while do_something. So it does not autocorrects when modifier form is used to avoid side effects.

I think that's not the right approach and we should just kill the conditionals directly if they are `if` or `unless`.  I can't imagine who'd be writing a conditional require with `while` and `until` but, for them I agree we should not attempt to auto-correct them.

File: lib/rubocop/cop/lint/redundant_require_statement.rb [hunk 1]
```diff
@@ -48,6 +48,8 @@ def on_send(node)
           return unless redundant_require_statement?(node)
 
           add_offense(node) do |corrector|
+            next if node.parent.respond_to?(:modifier_form?) && node.parent.modifier_form?
```
Comment (Drenmi) [inline lib/rubocop/cop/lint/redundant_require_statement.rb:51]: If we're confident no-one will do `require "foo" until x` maybe we can be more specific and check if `parent` is an `if_type?`. WDYT? 🙂

**Review by Drenmi — APPROVED** [review]

File: lib/rubocop/cop/lint/redundant_require_statement.rb (hunk 1 above)
Comment (bbatsov) [reply lib/rubocop/cop/lint/redundant_require_statement.rb:51]: We probably need a lint about `require... until` :D That's some wild code! :D

Comment (Drenmi) [reply lib/rubocop/cop/lint/redundant_require_statement.rb:51]: Needless to say I have never seen it in the wild. I was trying to dream up some use case for it, but can honestly say I failed to even imagine one. 😅

Comment (bbatsov) [reply lib/rubocop/cop/lint/redundant_require_statement.rb:51]: Same here! 😆

**Comment by tsugimoto** [comment]
Should this cop eagerly propose removing the conditionals along (works ~~almost~~ every real world case but theoretically:tm: turns this cop unsafe), or stay away from modifiers and be able to safely autocorrect `require`s without modifiers?

I see this PR is taking the safe side, which makes enough sense.

**Comment by koic** [comment]
Yeah, this PR is on the safe side. As has been discussed, `require` with modifier condition is a corner case. So, I think leaving it to user's decision without autocorrection does not reduce usability.

**Comment by bbatsov** [comment]
Btw, won't we have exactly the same problem if the parent note is some conditional or a loop? E.g.

```ruby
if foo
  require 'bar'
end
```

This won't result in broken code from a syntax perspective, but it's essentially the same as the modifier form, so I wonder if we should treat those differently.

**Comment by koic** [comment]
Sure. I've tried to focus only removing redundant `require` statement for autocorrection. So, I've updated this PR to add `end` keyword for prevent the syntax error:

```ruby
it 'registers an offense when using requiring `enumerator` with modifier form' do
  expect_offense(<<~RUBY)
    require 'enumerator' if condition
    ^^^^^^^^^^^^^^^^^^^^ Remove unnecessary `require` statement.
    require 'uri'
  RUBY

  expect_correction(<<~RUBY)
    if condition
    end
    require 'uri'
  RUBY
end
```

This would make modifier form and normal form compatible. How about it?

**Comment by bbatsov** [comment]
I like it more. Thanks!
