### PR TITLE
[Fix #10066] Fix how `MinDigits` is calculated for `Style/NumericLiterals` when generating a configuration file

### LINKED ISSUE #10066: Inline disabling of Style/NumericLiterals is ignored when generating MaxLength in the todo file
Using `# rubocop:disable Style/NumericLiterals` inline, works fine when running `rubocop`.

However, the length of the disabled literal is used by the logic that creates `.rubocop_todo.yml` file. This is a problem when the literal that has been excluded for the cop is longer than the existing value of `MinDigits` in the `todo` file. This means that the `MinDigits` parameter can get set to something larger than is desired, which eventually means it's impossible to use `# rubocop:disable Style/NumericLiterals` on numbers that are longer than `MinDigits` as I go on to describe.

--------

## Expected behavior

Running `rubocop --regenerate-todo` should not change the `MaxLength` value.

## Actual behavior

Running `rubocop --regenerate-todo` increases the value of `MinDigits` to be one more than the length of the literal that we have instructed the `Style/NumericLiterals` to ignore.

This then leads to follow-up problems - the next run of `rubocop` will not be green due to an un-necessary `disable` comment being detected, and removing the `disable` comment is undesirable as we intended to mark that specific literal is being OK.

## Steps to reproduce the problem

1. Create a 10 digit constant somewhere `FIRST_VIOLATION = 1234567890`
2. Run `rubocop --regenerate-todo` which should generate something like
```
# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 11
```
3. Create a 20 digit constant somewhere, but add an inline disable.
```ruby
SECOND_VIOLATION = 12345678901234567890`
```
4. Run `rubocop` and everything is green. It's all good and as desired up to this point.
5. Now run `rubocop --regenerate-todo` again. It will get updated to
```
# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 21
```
6. Run `rubocop` and it doesn't run succesfully - it tells you the `disable` is no longer required.
7. Remove the inline `disable` and `rubocop` will return green. However, now the special case which we want to allow, is no longer explicitly allowed and is now part of the `todo` file.

## RuboCop version

```
1.18.4 (using Parser 3.0.2.0, rubocop-ast 1.8.0, running on ruby 2.7.1 x86_64-darwin19)
  - rubocop-rails 2.11.3
```

### PR DESCRIPTION
**Pull request by dvandersluis**
Previously, `MinDigits` is incremented regardless of if the offense is disabled or not.

Fixes #10066.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/rspec/cop_helper.rb [hunk 1]
```diff
@@ -49,7 +49,7 @@ def _investigate(cop, processed_source)
     team = RuboCop::Cop::Team.new([cop], nil, raise_error: true)
     report = team.investigate(processed_source)
     @last_corrector = report.correctors.first || RuboCop::Cop::Corrector.new(processed_source)
-    report.offenses
+    report.offenses.reject(&:disabled?)
```
Comment (dvandersluis) [inline lib/rubocop/rspec/cop_helper.rb:52]: In order to test this, I needed to update `expect_offense` and `expect_no_offenses` to not consider disabled offenses. There was only one test (in `spec/rubocop/cop/layout/line_length_spec.rb`) that was affected by this change.

File: changelog/fix_fix_how_mindigits_is_calculated_for.md [hunk 2]
```diff
@@ -0,0 +1 @@
+* [#10066](https://github.com/rubocop/rubocop/pull/10066): Fix how `MinDigits` is calculated for `Style/NumericLiterals` when generating a configuration file. ([@dvandersluis][])
```
Comment (koic) [inline changelog/fix_fix_how_mindigits_is_calculated_for.md:1]: That's just my two cents :-)

```suggestion
* [#10066](https://github.com/rubocop/rubocop/issues/10066): Fix how `MinDigits` is calculated for `Style/NumericLiterals` when generating a configuration file. ([@dvandersluis][])
```

Comment (dvandersluis) [reply changelog/fix_fix_how_mindigits_is_calculated_for.md]: Good catch, thanks. Updated now!

**Comment by bbatsov** [comment]
Nice!
