### PR TITLE
[Fix #13645] Fix false positives for `Style/MethodCallWithArgsParentheses` and `omit_parentheses`

### LINKED ISSUE #13645: Fix Style/MethodCallWithArgsParentheses with endless range
## Expected behavior

Hello. :wave: I ran into an issue where, if using an endless range, RuboCop will attempt to auto-correct the code which leads to a Ruby 3.4.0 syntax error.

## Actual behavior

Here's the error I see:

``` 
demo.rb:26:38: C: [Correctable] Style/MethodCallWithArgsParentheses: Omit parentheses for method calls with arguments. (https://rubystyle.guide#method-invocation-parens)
        "demo".byteslice(2..)
         ^^^^^^^^^^^^^^^^
```

## Steps to reproduce the problem

Use the following configuration:

``` yaml
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
```

You can use the following code snippet to recreate the error:

``` ruby
# Save as `snippet.rb` and run as `rubocop snippet.rb`

module Demo
  def self.example
    "demo".byteslice(2..)
    slice + "end"
  end
end
```

If you were to remove the parenthesis from `byteslice`, then you'd get a syntax error:

``` 
demo:26:in 'Demo.example': undefined method '+' for nil (NoMethodError)

    slice + "end"
          ^
	from /Users/bkuhlmann/Engineering/Misc/demo:30:in '<main>'
```

This only occurs when the endless range is followed by another line of code.

## RuboCop version

```
1.69.2 (using Parser 3.3.6.0, rubocop-ast 1.37.0, analyzing as Ruby 3.4, running on ruby 3.4.1) [arm64-darwin24.2.0]
  - rubocop-capybara 2.21.0
  - rubocop-packaging 0.5.2
  - rubocop-performance 1.23.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 3.3.0
  - rubocop-thread_safety 0.6.0
```

### PR DESCRIPTION
**Pull request by Earlopain**
When the range is open towards either the begin or ending, removing the parens can change meaning.
After the parens have been removed, either `Lint/RequireRangeParentheses`  or `Layout/SpaceInsideRangeLiteral` will complain further.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb [hunk 1]
```diff
@@ -935,6 +935,44 @@ def seatle_style arg: default(42)
...
+
+        expect_correction(<<~RUBY)
+          foo 2.., 1
+        RUBY
+      end
+
+      it 'accepts parens when no begin node and first argument' do
+        expect_no_offenses(<<~RUBY)
+          foo(..2, 1)
+          foo(...2)
```
Comment (koic) [inline spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb:960]: Unlike parenthesis-less endless range with subsequent lines, beginless range retains its meaning even without parentheses.

Comment (koic) [reply spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb:960]: Ah, that was my mistake. When `foo(..end_of_range)` becomes `foo ..end_of_range`, the meaning changes.

Comment (Earlopain) [reply spec/rubocop/cop/style/method_call_with_args_parentheses_spec.rb:960]: Yup, that's right :+1: . I only noticed because of `Layout/SpaceInsideRangeLiteral` for this specific case.

File: lib/rubocop/cop/style/method_call_with_args_parentheses.rb [hunk 2]
```diff
@@ -61,6 +61,7 @@ module Style
       #   https://bugs.ruby-lang.org/issues/18396.
       # - Parentheses are required in anonymous arguments, keyword arguments
       #   and block passing in Ruby 3.2.
+      # - Parentheses are required when the first or last argument is an endless range.
```
Comment (koic) [inline lib/rubocop/cop/style/method_call_with_args_parentheses.rb:64]: Would the following be correct?

```suggestion
      # - Parentheses are required when the first argument is a beginless range or
      #   the last argument is an endless range.
```

Comment (Earlopain) [reply lib/rubocop/cop/style/method_call_with_args_parentheses.rb]: Yes, that sounds right. Thanks

File: lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb [hunk 3]
```diff
@@ -177,6 +180,18 @@ def hash_literal_in_arguments?(node)
...
           end
 
+          def ambiguous_range_argument?(node)
+            if (first_arg = node.first_argument)&.range_type? && first_arg.begin.nil?
+              return true
+            end
+
+            if (last_arg = node.last_argument)&.range_type? && last_arg.end.nil?
+              return true
+            end
```
Comment (koic) [inline lib/rubocop/cop/style/method_call_with_args_parentheses/omit_parentheses.rb:190]: That's just my two cents. Could you update it to a style that reflects guard conditions?

```suggestion
            return true if (first_arg = node.first_argument)&.range_type? && first_arg.begin.nil?
            return true if (last_arg = node.last_argument)&.range_type? && last_arg.end.nil?
```
