### PR TITLE
[#10265] Fix clobbering error when `Style/IfInsideElse` encounters a nested `if-then` structure.

### LINKED ISSUE #10265: An error occurred while Style/IfInsideElse cop was inspecting <file>
## Expected behavior

Rubocop shouldn't crash when parsing valid code.

## Actual behavior

The `Style/IfInsideElse` cop is errors when parsing code that uses a single line `if then` block inside and `else`. 

```
$ rubocop -d example.rb 
For /Users/alexl/code: Default configuration from /Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/config/default.yml
Use parallel by default.
Running parallel inspection
An error occurred while Style/IfInsideElse cop was inspecting /Users/alexl/code/example.rb:3:0.
Parser::Source::TreeRewriter detected clobbering
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter.rb:427:in `trigger_policy'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter.rb:414:in `enforce_policy'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:233:in `call'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:233:in `swallow'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:97:in `with'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:119:in `place_in_hierarchy'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:106:in `do_combine'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:30:in `combine'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter.rb:400:in `combine'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter.rb:194:in `replace'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter.rb:218:in `remove'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/style/if_inside_else.rb:88:in `autocorrect'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/style/if_inside_else.rb:76:in `block in on_if'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/base.rb:342:in `correct'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/base.rb:127:in `add_offense'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/style/if_inside_else.rb:75:in `on_if'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:98:in `each'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:69:in `on_if'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/team.rb:155:in `investigate_partial'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/team.rb:83:in `investigate'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:309:in `inspect_file'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:253:in `block in do_inspection_loop'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:287:in `block in iterate_until_no_changes'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:280:in `loop'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:280:in `iterate_until_no_changes'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:249:in `do_inspection_loop'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:130:in `block in file_offenses'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:155:in `file_offense_cache'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:129:in `file_offenses'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:67:in `block in warm_cache'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:485:in `process_incoming_jobs'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:465:in `block in worker'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:447:in `block in create_workers'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each_with_index'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `create_workers'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:386:in `work_in_processes'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:289:in `map'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parallel-1.21.0/lib/parallel.rb:238:in `each'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:67:in `warm_cache'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:46:in `run'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli.rb:71:in `run_command'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli.rb:78:in `execute_runners'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli.rb:47:in `run'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/exe/rubocop:12:in `block in <top (required)>'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/exe/rubocop:12:in `<top (required)>'
/Users/alexl/.rbenv/versions/2.6.6/bin/rubocop:23:in `load'
/Users/alexl/.rbenv/versions/2.6.6/bin/rubocop:23:in `<main>'
Inspecting 1 file
Scanning /Users/alexl/code/example.rb
An error occurred while Style/IfInsideElse cop was inspecting /Users/alexl/code/example.rb:3:0.
Parser::Source::TreeRewriter detected clobbering
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter.rb:427:in `trigger_policy'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter.rb:414:in `enforce_policy'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:233:in `call'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:233:in `swallow'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:97:in `with'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:119:in `place_in_hierarchy'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:106:in `do_combine'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter/action.rb:30:in `combine'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter.rb:400:in `combine'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter.rb:194:in `replace'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/parser-3.0.2.0/lib/parser/source/tree_rewriter.rb:218:in `remove'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/style/if_inside_else.rb:88:in `autocorrect'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/style/if_inside_else.rb:76:in `block in on_if'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/base.rb:342:in `correct'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/base.rb:127:in `add_offense'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/style/if_inside_else.rb:75:in `on_if'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:160:in `with_cop_error_handling'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:98:in `each'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:69:in `on_if'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-ast-1.13.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/team.rb:155:in `investigate_partial'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cop/team.rb:83:in `investigate'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:309:in `inspect_file'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:253:in `block in do_inspection_loop'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:287:in `block in iterate_until_no_changes'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:280:in `loop'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:280:in `iterate_until_no_changes'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:249:in `do_inspection_loop'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:130:in `block in file_offenses'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:155:in `file_offense_cache'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:129:in `file_offenses'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:120:in `process_file'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:100:in `each'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:100:in `reduce'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:86:in `inspect_files'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/runner.rb:47:in `run'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli.rb:71:in `run_command'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli.rb:78:in `execute_runners'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/lib/rubocop/cli.rb:47:in `run'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/exe/rubocop:12:in `block in <top (required)>'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/alexl/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubocop-1.23.0/exe/rubocop:12:in `<top (required)>'
/Users/alexl/.rbenv/versions/2.6.6/bin/rubocop:23:in `load'
/Users/alexl/.rbenv/versions/2.6.6/bin/rubocop:23:in `<main>'
C

Offenses:

example.rb:6:3: C: [Correctable] Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
  if y then 'y' end
  ^^

1 file inspected, 1 offense detected, 1 offense auto-correctable

1 error occurred:
An error occurred while Style/IfInsideElse cop was inspecting /Users/alexl/code/example.rb:3:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop/rubocop/issues

Mention the following information in the issue report:
1.23.0 (using Parser 3.0.2.0, rubocop-ast 1.13.0, running on ruby 2.6.6 x86_64-darwin20)
Finished in 0.30757199999061413 seconds
```

## Steps to reproduce the problem

```
# frozen_string_literal: true

if x
  'x'
else
  if y then 'y' end
end
```

## RuboCop version

```
 rubocop -V
1.23.0 (using Parser 3.0.2.0, rubocop-ast 1.13.0, running on ruby 2.6.6 x86_64-darwin20)
```

### PR DESCRIPTION
**Pull request by dvandersluis**
This PR does two things:
1. Extract the correction logic for converting `if-then` to a multiline if from `Style/OneLineConditional` to a new `IfThenCorrector`.
2. Uses that corrector in `Style/IfInsideElse` in order to convert `if-then` to multiline so that the existing correction code can correct it properly on the second pass.

By reusing the existing correction code, we don't need to replicate it for `IfInsideElse` (which currently is choking on `then`).

Fixes #10265.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/if_inside_else.rb [hunk 1]
```diff
@@ -102,15 +110,22 @@ def correct_to_elsif_from_modifier_form(corrector, node)
...
           else
             corrector.remove(range_by_whole_lines(if_condition_range, include_final_newline: true))
           end
+
           corrector.remove(condition)
         end
 
+        def then?(node)
+          node.loc.begin&.source == 'then'
+        end
```
Comment (dvandersluis) [inline lib/rubocop/cop/style/if_inside_else.rb:127]: This is probably something that should be extracted into `rubocop-ast`.

**Comment by bbatsov** [comment]
Great work!
