### PR TITLE
[Fix #14499] Fix wrong autocorrect for `Style/StringConcatenation` with escaped quotes and interpolation

### LINKED ISSUE #14499: `Style/StringConcatenation` autocorrect triggers `Lint/Syntax` error
`Style/StringConcatenation` incorrectly autocorrected the following excerpt of code, causing a syntax error:
```ruby
autocorrect(node, "File.open(\"#{path}\")" + '.each_line("\n").to_a.join.split(/\n{2,}/).reject { |e| e.empty? }.reverse.map_with_index {|e, i| i == 0 ? e : "#{e}\n\n" }.reverse')
```

I've isolated it down to what i'm fairly certain is the same issue:

--------

## Expected behavior

`Style/StringConcatenation` to work properly and not create syntax errors.

## Actual behavior

```
Inspecting 1 file
F

Offenses:

example2.rb:1:10: C: [Corrected] Style/StringConcatenation: Prefer string interpolation to string concatenation.
foo(bar, "\"#{quz}\"" + '')
         ^^^^^^^^^^^^^^^^^
example2.rb:2:1: F: Lint/Syntax: unexpected token $end
(Using Ruby 2.7 parser; configure using TargetRubyVersion parameter, under AllCops)

1 file inspected, 2 offenses detected, 1 offense corrected
```

```ruby
# the resulting autocorrected code 
foo(bar, ""#{quz}"")
```

## Steps to reproduce the problem

```ruby
# minimized example
foo(bar, "\"#{quz}\"" + '')
```

## RuboCop version

```
1.80.1 (using Parser 3.3.9.0, rubocop-ast 1.46.0, analyzing as Ruby 2.7, running on ruby 3.4.4) [x86_64-linux-gnu]
```

### PR DESCRIPTION
**Pull request by Earlopain**
Fixes #14499

The dstr parts also need to have their content adjusted since they may contains strings.

This slightly changes one autocorrect expectation, but the parens inside of the interpolation
are redundant so there is no problem removing them.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/string_concatenation.rb [hunk 1]
```diff
@@ -142,21 +142,23 @@ def corrected_ancestor?(node)
...
-            case part.type
-            when :str
-              adjust_str(part)
-            when :dstr
-              part.children.all?(&:str_type?) ? adjust_str(part) : part.value
-            else
-              "\#{#{part.source}}"
-            end
+            adjust_str(part)
           end
```
Comment (koic) [inline lib/rubocop/cop/style/string_concatenation.rb]: Nits: The following one-liner is simpler.

```ruby
interpolated_parts = parts.map { |part| adjust_str(part) }
```
