### PR TITLE
[Fix #14783] Fix incorrect autocorrect for `Style/HashSyntax` when shorthand syntax is used in condition of `if`/`unless`/`while`/`until`

### LINKED ISSUE #14783: Incorrect autocorrect for Style/HashSyntax with shorthand notation
When requiring shorthand notation either with `consistent` or `always`, the autocorrect for Style/HashSyntax creates semantically and sometimes syntactically incorrect Ruby in certain cases.

## Steps to reproduce the problem

1. Create a file `foo.rb` with:

   ```ruby
   # frozen_string_literal: true
 
   unless foo bar: bar
     baz qux: quuz
     baz zyxxy
   end
   ```
2. Create a file `.rubocop.yml` with:
   ```yaml
   AllCops:
     NewCops: enable
     TargetRubyVersion: 3.3
   
   Style/HashSyntax:
     Enabled: true
     EnforcedShorthandSyntax: always
   ```
3. run `rubocop -a`

## Expected behavior

The file `foo.rb` is corrected, and the `foo` method call has parentheses added, like so:
```ruby
# frozen_string_literal: true

unless foo(bar:)
  baz qux: quuz
  baz zyxxy
end
```

## Actual behavior

The file `foo.rb` is corrected, and the `foo` method call has shorthand syntax but no parentheses, leading to a syntax error:

```ruby
# frozen_string_literal: true

unless foo bar:
  baz qux: quuz
  baz zyxxy
end
```

## RuboCop version

```
$ rubocop -V
1.82.1 (using Parser 3.3.10.1, Prism 1.8.0, rubocop-ast 1.49.0, analyzing as Ruby 3.3, running on ruby 4.0.0) [x86_64-linux]
```

### PR DESCRIPTION
**Pull request by ydakuka**
Fixes #14783 

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/mixin/hash_shorthand_syntax.rb [hunk 1]
```diff
@@ -168,7 +168,7 @@ def method_dispatch_as_argument?(method_dispatch_node)
         parent = method_dispatch_node.parent
         return false unless parent
 
-        parent.type?(:call, :super, :yield)
+        parent.type?(:call, :super, :yield, :if, :while, :until)
```
Comment (koic) [inline lib/rubocop/cop/mixin/hash_shorthand_syntax.rb]: With the conditional added, the method name `method_dispatch_as_argument?` looks like it may need to be updated. As my two cents, the following adjustments could also be considered.

```suggestion
        parent.type?(:call, :if, :super, :until, :while, :yield)
```

Comment (ydakuka) [reply lib/rubocop/cop/mixin/hash_shorthand_syntax.rb]: Done. I renamed it to `#requires_parentheses_context?`.

**Comment by koic** [comment]
Adding test cases for `if`, `while`, and `until` in addition to `unless` would better align the tests with the intent of the change.

**Comment by ydakuka** [comment]
Added.
