### PR TITLE
[Fix #14880] Recognize block on different line from left side of multi-line assignment in `Layout/MultilineAssignmentLayout`

### LINKED ISSUE #14880: Layout/MultilineAssignmentLayout causes a false negative when using block on different line from left side of multi-line assignment
`Layout/MultilineAssignmentLayout` unrecognize block on different line from left side of multi-line assignment.

## Steps to reproduce the problem

```yaml
Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line
  SupportedTypes: ['block']
```

or

```yaml
Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line
  SupportedTypes: ['block']
```

## Expected behavior

The following code should be recognized:

### when new_line style

```ruby
bars = foo
^^^^^^^^^^ Right hand side of multi-line assignment is on the same line as the assignment operator `=`.
  .map { it.bar }
```

### when same_line style

```ruby
bars =
^^^^^^ Right hand side of multi-line assignment is not on the same line as the assignment operator `=`.
  foo.map { it.bar }
```

## Actual behavior

The above codes pass.

## RuboCop version

```
$ [bundle exec] rubocop -V
1.84.2 (using Parser 3.3.10.1, rubocop-ast 1.49.0, analyzing as Ruby 2.7, running on ruby 4.0.0) [arm64-darwin24]
  - rubocop-performance 1.26.1
  - rubocop-rake 0.7.1
  - rubocop-rspec 3.9.0
```

### PR DESCRIPTION
**Pull request by sanfrecce-osaka**
fixed #14880 

`RuboCop::AST::BlockNode#single_line?` determines whether block is a single line, so when block is on a different line from the left-hand side, `rhs.single_line?` returned true, resulting in a false negative.
So I fixed it.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/multiline_assignment_layout.rb [hunk 1]
```diff
@@ -69,11 +69,12 @@ class MultilineAssignmentLayout < Base
...
                             'on the same line as the assignment operator `=`.'
 
-        def check_assignment(node, rhs)
+        def check_assignment(node, rhs) # rubocop:disable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
           return if node.send_type? && node.loc.operator&.source != '='
           return unless rhs
           return unless supported_types.include?(rhs.type)
-          return if rhs.single_line?
+          return if !rhs.block_type? && rhs.single_line?
+          return if rhs.block_type? && rhs.single_line? && node.loc.line == rhs.loc.begin.line
```
Comment (koic) [inline lib/rubocop/cop/layout/multiline_assignment_layout.rb]: Can you refactor to the following?

```suggestion
          return if rhs.single_line? && (!rhs.block_type? || same_line?(node, rhs.loc.begin))
```

File: lib/rubocop/cop/layout/multiline_assignment_layout.rb [hunk 2]
```diff
@@ -69,11 +69,12 @@ class MultilineAssignmentLayout < Base
         SAME_LINE_OFFENSE = 'Right hand side of multi-line assignment is not ' \
                             'on the same line as the assignment operator `=`.'
 
-        def check_assignment(node, rhs)
+        def check_assignment(node, rhs) # rubocop:disable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
```
Comment (koic) [inline lib/rubocop/cop/layout/multiline_assignment_layout.rb]: Can you place the `rubocop:disable` directive outside the method?

```suggestion
        # rubocop:disable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
        def check_assignment(node, rhs)
```

Overall, it would look like the following.

```diff
-        def check_assignment(node, rhs) # rubocop:disable Metrics/AbcSize, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
+        # rubocop:disable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
+        def check_assignment(node, rhs)
           return if node.send_type? && node.loc.operator&.source != '='
           return unless rhs
           return unless supported_types.include?(rhs.type)
-
-          if rhs.block_type?
-            return if rhs.single_line? && same_line?(node, rhs.loc.begin)
-          elsif rhs.single_line?
-            return
-          end
+          return if rhs.single_line? && (!rhs.block_type? || same_line?(node, rhs.loc.begin))
 
           check_by_enforced_style(node, rhs)
         end
+        # rubocop:enable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
```

File: lib/rubocop/cop/layout/multiline_assignment_layout.rb (hunk 1 above)
Comment (sanfrecce-osaka) [reply lib/rubocop/cop/layout/multiline_assignment_layout.rb]: @koic 

Thank you for your feedback, I apply your suggestion!!

File: lib/rubocop/cop/layout/multiline_assignment_layout.rb (hunk 2 above)
Comment (sanfrecce-osaka) [reply lib/rubocop/cop/layout/multiline_assignment_layout.rb]: Thank you for your feedback, I apply it!!

File: spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb [hunk 3]
```diff
@@ -123,6 +123,40 @@
           end
         RUBY
       end
+
+      it 'registers an offense when multi-line assignments using single-line block is on different line' do
+        expect_offense(<<~RUBY)
+          bars = foo
+          ^^^^^^^^^^ Right hand side of multi-line assignment is on the same line as the assignment operator `=`.
+            .map { it.bar }
+        RUBY
```
Comment (koic) [inline spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb:132]: can you add `expect_correction`?

File: spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb [hunk 4]
```diff
@@ -246,6 +280,40 @@
...
+      end
+
+      it 'registers an offense multi-line assignments using single-line block is on different and separate line' do
+        expect_offense(<<~RUBY)
+          bars =
+          ^^^^^^ Right hand side of multi-line assignment is not on the same line as the assignment operator `=`.
+            foo.map { it.bar }
+        RUBY
```
Comment (koic) [inline spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb:310]: Ditto.

File: spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb [hunk 5]
```diff
@@ -246,6 +280,40 @@
...
+      end
+
+      it 'registers an offense multi-line assignments using multi-line block is on different and separate line' do
+        expect_offense(<<~RUBY)
+          bars =
+          ^^^^^^ Right hand side of multi-line assignment is not on the same line as the assignment operator `=`.
+            foo.map do
+              it.bar
+            end
+        RUBY
```
Comment (koic) [inline spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb:333]: Ditto.

File: spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb (hunk 3 above)
Comment (sanfrecce-osaka) [reply spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb:132]: Sure, I fixed it with https://github.com/rubocop/rubocop/pull/14881/commits/6bac232e9d5713025efa039ee42d7422f05ba43f

File: spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb (hunk 4 above)
Comment (sanfrecce-osaka) [reply spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb:310]: Ditto.

https://github.com/rubocop/rubocop/pull/14881#discussion_r2807490540

File: spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb (hunk 5 above)
Comment (sanfrecce-osaka) [reply spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb:333]: Ditto.

https://github.com/rubocop/rubocop/pull/14881#discussion_r2807490540

File: spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb [hunk 6]
```diff
@@ -123,6 +123,54 @@
           end
         RUBY
       end
+
+      it 'registers an offense when multi-line assignments using single-line block is on different line' do
+        expect_offense(<<~RUBY)
+          bars = foo
+          ^^^^^^^^^^ Right hand side of multi-line assignment is on the same line as the assignment operator `=`.
+            .map { it.bar }
```
Comment (koic) [inline spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb]: Unless there is a specific reason, can you use a regular block parameter instead of an `it` block parameter in this PR? Also, as a minor point, to align with the surrounding tests, it might be preferable to name it `foo = items.map do |item|`, or something similar.


```suggestion
          foo = items
          ^^^^^^^^^^^ Right hand side of multi-line assignment is on the same line as the assignment operator `=`.
            .map { |item| item.do_something }
```

**Comment by koic** [comment]
Since the intermediate work commits are not of particular interest here, please squash your commits into one.

File: spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb (hunk 6 above)
Comment (sanfrecce-osaka) [reply spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb]: Thank you for your feedback, I fixed. it.

https://github.com/rubocop/rubocop/compare/6bac232e9d5713025efa039ee42d7422f05ba43f..e9dc5a055c9f63ce8e7eaeb5897589e784dcdfbd

**Comment by sanfrecce-osaka** [comment]
> Since the intermediate work commits are not of particular interest here, please squash your commits into one.

Sorry, I was unsure when to squash them and ended up leaving them as is.
I squashed them.

File: spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb (hunk 3 above)
Comment (sanfrecce-osaka) [reply spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb:132]: The existing some test codes in `spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb` also lacks `expect_correction`. Is it okay to add it together within this Pull Request?

Comment (koic) [reply spec/rubocop/cop/layout/multiline_assignment_layout_spec.rb:132]: This is not related to this change, so there is no need to include it in the same pull request.

**Comment by koic** [comment]
Thanks!
