### PR TITLE
[Fix #5022] Fix false negative for `Lint/DuplicateMethods` inside `class << self`

### LINKED ISSUE #5022: Lint/DuplicateMethods for classes inside `class << self` of parent module
As in #4758, but with `class << self`.

Real-life case: https://github.com/panthomakos/timezone/blob/b70e1d8/lib/timezone/lookup.rb

--------

## Expected behavior

No warnings.

## Actual behavior

```
Inspecting 1 file
W

Offenses:

.test.rb:10:7: W: Method Foo.config is defined at both .test.rb:4 and .test.rb:10.
      attr_reader :config
      ^^^^^^^^^^^

1 file inspected, 1 offense detected
```

## Steps to reproduce the problem

```ruby
# Module with class-methods
module Foo
  class << self
    def config
      'Foo.config'
    end

    # Private class for module
    class Bar
      attr_reader :config
    end
  end
end
```

## RuboCop version

```
$ rubocop -V
0.51.0 (using Parser 2.4.0.0, running on ruby 2.4.2 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by dvandersluis**
Requires rubocop/rubocop-ast#197 in order to fix `Node#parent_module_name`.

Properly handles the updated format of `parent_module_name` and adds tests to ensure the case from #5022 works.

Also reverts the pending tests in #9995.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by dvandersluis** [comment]
There's a bit of a catch 22 between this PR and rubocop/rubocop-ast#197. Each PR needs the other to get the tests passing.

File: spec/rubocop/cop/lint/duplicate_methods_spec.rb [hunk 1]
```diff
@@ -233,16 +233,14 @@ def self.another
...
         #{opening_line}
           class << blah
             def some_method
               implement 1
             end
             def some_method
-            ^^^^^^^^^^^^^^^ Method `A#some_method` is defined at both test.rb:3 and test.rb:6.
               implement 2
             end
           end
```
Comment (dvandersluis) [inline spec/rubocop/cop/lint/duplicate_methods_spec.rb:246]: This test will not be able to ever pass, because `Node#parent_module_name` will return `nil` because it cannot evaluate `class << blah`, so I have removed the `pending` and marked it as `expect_no_offenses`.

Comment (marcandre) [reply spec/rubocop/cop/lint/duplicate_methods_spec.rb:246]: I would mark it as `pending`, as ideally the cop would detect it.

Comment (dvandersluis) [reply spec/rubocop/cop/lint/duplicate_methods_spec.rb:246]: Ok I'll drop that commit then.
