### PR TITLE
Fix a false positive for `Style/RedundantRegexpCharacterClass`

### LINKED ISSUE #11067: Lint/DuplicateRegexpCharacterClassElement can misinterpret octal escapes as nulls
The parser might read a sequence like `\032` inside a character class, stop at the `\0`, and mistakenly call that a duplicate element. Likewise, the autocorrect might remove just those two characters.

--------

## Expected behavior

Do not tokenize the leading `\0` in the above example.

## Actual behavior

```
% rubocop --debug --only Lint/DuplicateRegexpCharacterClassElement -- app/controllers/application_controller.rb
[ ... ]
Skipping parallel inspection: only a single file needs inspection
Inspecting 1 file
Scanning /Users/knutsen/src/cap/app/controllers/application_controller.rb
Loading cache from /Users/knutsen/.cache/rubocop_cache/b97726938b2e65a342a5ff855c7ee681d9a527dc/7950ca6bb1872c499a0d4972f78f4fa237a9cb5a/6b4b7e968bce07d4cbd3e58fe70b7126206a5c29
W

Offenses:

app/controllers/application_controller.rb:88:23: W: [Correctable] Lint/DuplicateRegexpCharacterClassElement: Duplicate element inside regexp character class
    str.gsub(/([\0\n\r\032'"\\])/) do
                      ^^

1 file inspected, 1 offense detected, 1 offense autocorrectable
```

## Steps to reproduce the problem

See above for a one-liner.

## RuboCop version

```
% rubocop -V                                                                                                   
1.36.0 (using Parser 3.1.2.1, rubocop-ast 1.21.0, running on ruby 3.0.4) [x86_64-darwin21]
```

(I'm running x86 Ruby on an M1 MacBook for reasons that are too depressing to go into right now)

### PR DESCRIPTION
**Pull request by koic**
This is a similar issue to https://github.com/rubocop/rubocop/issues/11067.

This PR fixes a false positive for `Style/RedundantRegexpCharacterClass` when using starting with "\0" number.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb [hunk 1]
```diff
@@ -307,6 +307,15 @@
     end
   end
 
+  context 'with a character class containing an escaped-0' do
+    # See https://github.com/rubocop/rubocop/issues/11067 for details - in short "\0" != "0" - the
+    # former means an Unicode code point `"\u0000"`, the latter a number character `"0"`.
+    # Similarly "\032" means "\u001A". Other numbers starting with "\0" can also be mentioned.
+    it 'does not register an offense' do
+      expect_no_offenses('foo = /[\032]/')
```
Comment (knutsenm) [inline spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb:315]: Will redundant codes, like `[\032\032]` or `[\b\b]`, register an offense? If not, shouldn't they?

Comment (knutsenm) [reply spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb:315]: The latter _does_ register an offense presently, so I suppose the former will as well?

```
% cat test3.rb                                                       
puts "one \010 two \010".gsub(/[\b]/, "potato")

puts "one \010 two \010".gsub(/[\b\b]/, "potato")

% ruby test3.rb
one potato two potato
one potato two potato

% rubocop --only Lint/DuplicateRegexpCharacterClassElement -- test3.rb
Inspecting 1 file
W

Offenses:

test3.rb:3:35: W: [Correctable] Lint/DuplicateRegexpCharacterClassElement: Duplicate element inside regexp character class
puts "one \010 two \010".gsub(/[\b\b]/, "potato")
                                  ^^

1 file inspected, 1 offense detected, 1 offense autocorrectable
```

File: changelog/fix_a_false_positive_for_lint_uuplicate_regexp_character_class_element.md [hunk 2]
```diff
@@ -0,0 +1 @@
+* [#11067](https://github.com/rubocop/rubocop/issues/11067): Fix a false positive for `Lint/DuplicateRegexpCharacterClassElement` when using starting with "\0" number. ([@koic][])
```
Comment (knutsenm) [inline changelog/fix_a_false_positive_for_lint_uuplicate_regexp_character_class_element.md:1]: Misspelled filename, "uuplicate" should be "duplicate"

File: spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb (hunk 1 above)
Comment (koic) [reply spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb:315]: Ah, what this PR fixes is `Style/RedundantRegexpCharacterClass`. So, it looks like I was looking at a different cop that was similar. I will see about `Lint/DuplicateRegexpCharacterClassElement` in a separate PR.

Comment (koic) [reply spec/rubocop/cop/style/redundant_regexp_character_class_spec.rb:315]: I've opened #11086.

**Comment by bbatsov** [comment]
Thanks!
