### PR TITLE
[Fix #8099] Fix infinite loop between `Layout/SpaceAroundOperators` and `Layout/HashAlignment` with `EnforcedHashRocketStyle` being an array containing `table`

### LINKED ISSUE #8099: Infinite loop between Layout/SpaceAroundOperators and Layout/HashAlignment with EnforcedHashRocketStyle table
## Expected behavior

`Layout/SpaceAroundOperators` with `AllowForAlignment: true` should not complain when a hash is aligned with hashes above it.

## Actual behavior

`Layout/SpaceAroundOperators` complains about extra space, and when autocorrected it is undone by `Layout/HashAlignment` autocorrection, and an infinite loop is reported.

It is also impossible to manually fix for the same reason: fixing for `Layout/SpaceAroundOperators` then makes `Layout/HashAlignment` complain, and fixing for that takes us back to the original `Layout/SpaceAroundOperators` complaint – an endless cycle 😢 

No problems with colon-style, only rocket-style.

## Steps to reproduce the problem

- Have the following rubocop config:
```yml
Layout/SpaceAroundOperators:
  Enabled: true
  AllowForAlignment: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle:
    - table
    - key
```
- Create the following file:
```rb
# bug.rb in the output above
hash = {
  "one"   => 1,
  "hash"  => {

  },
  "align" => {
    "hello" => "value"
  },
  "deep"  => {
    "hash" => {
      "this is" => "deep"
    }
  }
}
```
- Run `rubocop --only Layout --fix-layout` on that file.
- See the following output:
```
$ rubocop --only Layout --fix-layout bug.rb
Inspecting 1 file
C

Offenses:

bug.rb:9:3: C: [Corrected] Layout/HashAlignment: Align the keys and values of a hash literal if they span more than one line.
  "deep" => { ...
  ^^^^^^^^^^^
bug.rb:9:11: C: [Corrected] Layout/SpaceAroundOperators: Operator => should be surrounded by a single space.
  "deep"  => {
          ^^

0 files inspected, 2 offenses detected, 2 offenses corrected
Infinite loop detected in /Users/me/Code/my_gemset/bug.rb.
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:287:in `check_for_infinite_loop'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:271:in `block in iterate_until_no_changes'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:270:in `loop'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:270:in `iterate_until_no_changes'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:241:in `do_inspection_loop'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:122:in `block in file_offenses'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:146:in `file_offense_cache'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:120:in `file_offenses'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:111:in `process_file'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:90:in `block in each_inspected_file'
...etc...
```

This also happens on the `align` hash key if you rename it to `x`, so the preceeding hash doesn't have to contain anything, it just has to have `{` `}` on separate lines:
```rb
hash = {
  "one"  => 1,
  "hash" => {

  },
  "x" => {
    "hello" => "value"
  },
  "deep" => {
    "hash" => {
      "this is" => "deep"
    }
  }
}
```
```
$ rubocop --only Layout --fix-layout bug.rb
Inspecting 1 file
C

Offenses:

bug.rb:2:3: C: [Corrected] Layout/HashAlignment: Align the keys of a hash literal if they span more than one line.
  "one"   => 1,
  ^^^^^^^^^^^^
bug.rb:3:3: C: [Corrected] Layout/HashAlignment: Align the keys of a hash literal if they span more than one line.
  "hash"  => { ...
  ^^^^^^^^^^^^
bug.rb:6:3: C: [Corrected] Layout/HashAlignment: Align the keys and values of a hash literal if they span more than one line.
  "x" => { ...
  ^^^^^^^^
bug.rb:6:10: C: [Corrected] Layout/SpaceAroundOperators: Operator => should be surrounded by a single space.
  "x"    => {
         ^^
bug.rb:9:3: C: [Corrected] Layout/HashAlignment: Align the keys of a hash literal if they span more than one line.
  "deep"  => { ...
  ^^^^^^^^^^^^
bug.rb:9:11: C: [Corrected] Layout/SpaceAroundOperators: Operator => should be surrounded by a single space.
  "deep"  => {
          ^^

0 files inspected, 6 offenses detected, 6 offenses corrected
Infinite loop detected in /Users/me/Code/my_gemset/bug.rb.
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:287:in `check_for_infinite_loop'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:271:in `block in iterate_until_no_changes'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:270:in `loop'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:270:in `iterate_until_no_changes'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:241:in `do_inspection_loop'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:122:in `block in file_offenses'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:146:in `file_offense_cache'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:120:in `file_offenses'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:111:in `process_file'
/Users/me/.rbenv/versions/2.6.6/gemsets/my_gemset/gems/rubocop-0.84.0/lib/rubocop/runner.rb:90:in `block in each_inspected_file'
...etc...
```

But no problem with colon-style hashes:
```rb
hash = {
  one: 1,
  hash: {

  },
  align: {
    hello: "value"
  },
  deep: {
    hash: {
      "this is": "deep"
    }
  }
}
```
```yml
Layout/SpaceAroundOperators:
  Enabled: true
  AllowForAlignment: true

Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle:
    - table
    - key
  EnforcedHashRocketStyle:
    - table
    - key
```
```
$ rubocop --only Layout --fix-layout bug.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

## RuboCop version

0.84.0 (using Parser 2.7.1.3, rubocop-ast 0.0.3, running on ruby 2.6.6 x86_64-darwin19)

### PR DESCRIPTION
**Pull request by dvandersluis**
Although `Layout/SpaceAroundOperators` already had a carve-out for dealing with `table` hash style, `Layout/HashAlignment` allows multiple values for `EnforcedHashRocketStyle`, which was not handled, thus leading to an infinite loop.

Fixes #8099.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cli/autocorrect_spec.rb [hunk 1]
```diff
@@ -3888,4 +3888,35 @@ def foo
...
+
+    status = cli.run(%w[--autocorrect-all --only Layout/SpaceAroundOperators,Layout/HashAlignment])
+    expect(status).to eq(0)
+    expect($stdout.string).to eq(<<~RESULT)
+      Inspecting 1 file
+      .
+
+      1 file inspected, no offenses detected
+    RESULT
+    expect($stderr.string).to eq('')
```
Comment (koic) [inline spec/rubocop/cli/autocorrect_spec.rb:3920]: The product code before the change also appears to pass the test. Does this test case reproduce the issue?

Comment (dvandersluis) [reply spec/rubocop/cli/autocorrect_spec.rb:3921]: Thank you, I was trying to simplify that example from the issue for the purpose of the test, but didn't ensure it was failing on master. I've updated it now to a test that fails on master and passes on this branch.

Comment (koic) [reply spec/rubocop/cli/autocorrect_spec.rb:3921]: The test does fail, but it seems to detect only `Layout/SpaceAroundOperators` cop rather than an infinite loop error. The `autocorrect_spec.rb` is expected to test across multiple cops (in this case, an infinite loop error). Does this behavior align with the intended reproduction case?

Comment (dvandersluis) [reply spec/rubocop/cli/autocorrect_spec.rb:3925]: Updated again, sorry. Now the test fails on master with an infinite loop.

```
Inspecting 1 file
Infinite loop detected in /src/rubocop/example.rb and caused by Layout/SpaceAroundOperators -> Layout/HashAlignment
C

Offenses:

example.rb:4:11: C: [Corrected] Layout/SpaceAroundOperators: Operator => should be surrounded by a single space.
  "one"   => 1,
          ^^
example.rb:5:3: C: [Corrected] Layout/HashAlignment: Align the keys and values of a hash literal if they span more than one line.
  "two"  => { ...
  ^^^^^^^^^^^
example.rb:5:10: C: [Corrected] Layout/SpaceAroundOperators: Operator => should be surrounded by a single space.
  "two"  => {
         ^^
example.rb:9:3: C: [Corrected] Layout/HashAlignment: Align the keys and values of a hash literal if they span more than one line.
  "four" => { ...
  ^^^^^^^^^^^
example.rb:9:11: C: [Corrected] Layout/SpaceAroundOperators: Operator => should be surrounded by a single space.
  "four"  => {
          ^^

1 file inspected, 5 offenses detected, 5 offenses corrected

1 error occurred:
Infinite loop detected in /src/rubocop/example.rb and caused by Layout/SpaceAroundOperators -> Layout/HashAlignment
```

Comment (koic) [reply spec/rubocop/cli/autocorrect_spec.rb:3925]: Perfect! Thank you!
