### PR TITLE
[Fix #14621] Fix an error for `Naming/PredicateMethod`

### LINKED ISSUE #14621: Naming/PredicateName crashes when inspecting method with pattern   matching and negated predicate
## Steps to reproduce the problem

  Create a file with the following Ruby code using pattern
  matching:

  ```ruby
  class Example
    def update!
      case @value
      in String
        ()
      in Integer
        raise "error" if !@value.is_a?(String)
      end
    end
  end
```

  Run RuboCop on the file:

  bundle exec rubocop example.rb

  # Expected behavior

  RuboCop should inspect the file without errors. The
  Naming/PredicateMethod cop should skip the update! method since
  it ends with ! (bang), not ? (predicate).

  # Actual behavior

  RuboCop crashes with a NoMethodError:

  An error occurred while Naming/PredicateMethod cop was inspecting
   example.rb:9:4.

  Workaround: Replacing if ! with unless resolves the crash.

  RuboCop version

  $ bundle exec rubocop -V
  1.81.6 (using Parser 3.3.9.0, Prism 1.6.0, rubocop-ast 1.47.1,
  analyzing as Ruby 3.4, running on ruby 3.4.7) [x86_64-linux]
    - rubocop-minitest 0.38.2
    - rubocop-performance 1.26.1

### PR DESCRIPTION
**Pull request by koic**
This PR fixes an error for `Naming/PredicateMethod` when using an `in` pattern with empty parentheses body.

Fixes #14621.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/naming/predicate_method_spec.rb [hunk 1]
```diff
@@ -276,6 +276,17 @@ def self.foo
...
+    it 'does not register an offense for an `in` pattern with empty parentheses body' do
+      expect_no_offenses(<<~RUBY)
+        def foo
+          case expr
+          in pattern
+            ()
+          end
+        end
+      RUBY
+    end
```
Comment (dvandersluis) [inline spec/rubocop/cop/naming/predicate_method_spec.rb:288]: FYI This applies to all conditionals, not just case-match.

Comment (koic) [reply spec/rubocop/cop/naming/predicate_method_spec.rb:288]: Thank you. In any case, it addresses the underlying cause by handling `node.children.last` properly in the `last_value` method.

**Comment by dvandersluis** [comment]
Thank you!
