### PR TITLE
[Fix #14496] Fix false negatives for `Layout/EmptyLineBetweenDefs` …

### LINKED ISSUE #14496: Layout/EmptyLineBetweenDefs not working with DefLikeMacros option
When using the `Layout/EmptyLineBetweenDefs` cop with the `DefLikeMacros` option, errors are not reported nor autocorrected when two macros do not have an empty line between them.

Rubocop config:

```
# .rubobop.yml

plugins:
 - rubocop-factory_bot
 - rubocop-performance
 - rubocop-rails
 - rubocop-rake
 - rubocop-rspec
 - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.5

Layout/EmptyLineBetweenDefs:
  Enabled: true
  DefLikeMacros: [monetize]
```
--------

## Expected behavior

```ruby
class TestClass
  monetize :price

  monetize :other_price
end
```

Here is a test that seems to validate the expected behavior: https://github.com/rubocop/rubocop/blob/2271a78fb230a49cd44255ed31a2411d950d03f8/spec/rubocop/cop/layout/empty_line_between_defs_spec.rb#L662

## Actual behavior

```ruby
class TestClass
  monetize :price
  monetize :other_price
end
```

Output of `rubocop --debug`:

```
For /app: configuration from /app/.rubocop.yml
Default configuration from /usr/local/bundle/gems/rubocop-1.80.1/config/default.yml
Plugin configuration from /usr/local/bundle/gems/rubocop-factory_bot-2.27.1/config/default.yml
Plugin configuration from /usr/local/bundle/gems/rubocop-performance-1.25.0/config/default.yml
Plugin configuration from /usr/local/bundle/gems/rubocop-rails-2.33.3/config/default.yml
Plugin configuration from /usr/local/bundle/gems/rubocop-rake-0.7.1/config/default.yml
Plugin configuration from /usr/local/bundle/gems/rubocop-rspec-3.6.0/config/default.yml
Plugin configuration from /usr/local/bundle/gems/rubocop-rspec_rails-2.31.0/config/default.yml
Use parallel by default.
Running parallel inspection
Inspecting 4 files
Scanning /app/Gemfile
Loading cache from /root/.cache/rubocop_cache/9969a80ad293c4977dce6159aac2711461d93ca0/6d7a3b621ca1730e04accd938619e4bdab66cfb1/22a189253b26d6cde2ba5218571f8c485dc346e1
.Scanning /app/Rakefile
Loading cache from /root/.cache/rubocop_cache/9969a80ad293c4977dce6159aac2711461d93ca0/6d7a3b621ca1730e04accd938619e4bdab66cfb1/e33e15c9f3e5cfcc10f948c2fcce738379c2d3f0
.Scanning /app/lib/test_class.rb
Loading cache from /root/.cache/rubocop_cache/9969a80ad293c4977dce6159aac2711461d93ca0/6d7a3b621ca1730e04accd938619e4bdab66cfb1/8e4664d0607939b6428978aa32139a15aa6771ba
.Scanning /app/spec/spec_helper.rb
Loading cache from /root/.cache/rubocop_cache/9969a80ad293c4977dce6159aac2711461d93ca0/6d7a3b621ca1730e04accd938619e4bdab66cfb1/be18d96b9179563484e23ff379bc484bb355fecd
```

## Steps to reproduce the problem

Add the following to the rubocop config:

```
Layout/EmptyLineBetweenDefs:
  Enabled: true
  DefLikeMacros: [monetize]
```

Then add two `monetize` calls to a class without an empty line between them and run `rubocop`. For example:

```ruby
class TestClass
  monetize :price
  monetize :other_price
end
```

## RuboCop version

```
bundle exec rubocop -V

1.80.1 (using Parser 3.3.9.0, Prism 1.4.0, rubocop-ast 1.46.0, analyzing as Ruby 3.4, running on ruby 3.4.5) [aarch64-linux]
  - rubocop-factory_bot 2.27.1
  - rubocop-performance 1.25.0
  - rubocop-rails 2.33.3
  - rubocop-rake 0.7.1
  - rubocop-rspec 3.6.0
  - rubocop-rspec_rails 2.31.0
```

### PR DESCRIPTION
**Pull request by Earlopain**
Fix #14496

… with `AllowAdjacentOneLineDefs: false` for `DefLikeMacros` that take no block

`foo :bar` is just as much a macro as `foo :bar { baz }`

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/layout/empty_line_between_defs.rb [hunk 1]
```diff
@@ -175,8 +177,15 @@ def empty_line_between_macros
...
 
         def macro_candidate?(node)
-          node.any_block_type? && node.children.first.macro? &&
-            empty_line_between_macros.include?(node.children.first.method_name)
+          macro_candidate =
+            if node.any_block_type?
+              node.children.first
+            elsif node.send_type?
+              node
+            end
```
Comment (koic) [inline lib/rubocop/cop/layout/empty_line_between_defs.rb]:
```suggestion
          macro_candidate = if node.any_block_type?
                              node.send_node
                            elsif node.send_type?
                              node
                            end
```

**Comment by koic** [comment]
For example, block macros like the following would be expected to have a blank line. This is already implemented.

```ruby
has_many :authors do
  ...
end

has_many :comments do
  ...
end
```

On the other hand, it is questionable whether blank lines should be enforced for non-block macros like the following:

```ruby
has_many :authors
has_many :comments
```

In other words, it is unclear whether macro usage can be regarded the same as a class definition such as `class ErrorA < BaseError; end` shown in the `AllowAdjacentOneLineDefs` example.

This might be something that should be provided as a new option, such as `AllowAdjacentOneLineMacros`.

**Comment by Earlopain** [comment]
`AllowAdjacentOneLineDefs` applies to all types (method/class/module), not just classes like the code examples make it seem. The user asks some macros to be treated like methods, so if it already applies to method definitions it makes sense to me to also apply it to macros that the user wants to treat like methods.

I can update the examples instead?

**Comment by koic** [comment]
Yeah, I think it can move forward for now by updating the examples.

File: lib/rubocop/cop/layout/empty_line_between_defs.rb [hunk 2]
```diff
@@ -76,28 +76,40 @@ module Layout
       #   # good
       #   class ErrorA < BaseError; end
       #   class ErrorB < BaseError; end
-      #   class ErrorC < BaseError; end
```
Comment (Earlopain) [inline lib/rubocop/cop/layout/empty_line_between_defs.rb:79]: Made it more concise by only listing two after each other. The third is not needed for these examples.

File: lib/rubocop/cop/layout/empty_line_between_defs.rb [hunk 3]
```diff
@@ -76,28 +76,40 @@ module Layout
...
       #
-      #   class ErrorC < BaseError; end
+      #   # good
+      #   def foo = 123
+      #   def bar = 456
+      #
+      #   # good
+      #   def foo = 123
+      #
+      #   def foo = 456
```
Comment (koic) [inline lib/rubocop/cop/layout/empty_line_between_defs.rb]: Can you describe examples with macro instead of an endless method definition, in line with the intent of this PR?

**Comment by koic** [comment]
Thanks!
