### PR TITLE
[Fix #9839] Add `AllowedReceivers` option for `Style/HashEachMethods`

### LINKED ISSUE #9839: False positive in Style/HashEachMethods
I have code like this:

```ruby
        ::ApplicationRecord.connection.execute(sql).values.each do |field|
          p field
        end
```
--------

## Expected behavior

No error is raised by Style/HashEachMethods. There is no such method `each_value` as it's not a Hash.

## Actual behavior
```
dates.rb:56:59: C: [Correctable] Style/HashEachMethods: Use each_value instead of values.each.
        ::ApplicationRecord.connection.execute(build_sql).values.each do |field|
```

## Steps to reproduce the problem

Run RuboCop on the code snippet.

## RuboCop version

```
$ [bundle exec] rubocop -V
1.15.0 (using Parser 3.0.1.1, rubocop-ast 1.6.0, running on ruby 3.0.1 x86_64-linux)
  - rubocop-rails 2.9.1
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #9839.

This PR adds `AllowedReceivers` option for `Style/HashEachMethods`.

`Style/HashEachMethods` cop is already marked as unsafe. This PR can use allow list to rule out false positives.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/hash_each_methods_spec.rb [hunk 1]
```diff
@@ -87,5 +87,29 @@
...
+      end
+
+      it 'does not register an offense when receiver is `execute` variable' do
+        expect_no_offenses(<<~RUBY)
+          execute = do_something(argument)
+          execute.values.each { |v| p v }
+        RUBY
+      end
+
+      it 'does not register an offense when receiver is not allowed name' do
```
Comment (styx) [inline spec/rubocop/cop/style/hash_each_methods_spec.rb:107]: `does not` seems to be a copy-paste typo

Comment (koic) [reply spec/rubocop/cop/style/hash_each_methods_spec.rb:107]: Oops! Thanks!
