### PR TITLE
[Fix #10106] Fix `Style/RedundantSelf` for pattern matching

### LINKED ISSUE #10106: `Style/RedundantSelf` doesn't consider pattern matching variables
`Style/RedundantSelf` doesn't consider pattern matching variables. It treats the following code as offense, while removing `self` would change the behavior:

```ruby
case cdr
in Integer => bar
  self.bar + bar
end
```

Also I want to notice that this code will be **automatically corrected** by RuboCop, which is a serious issue.

--------

## Expected behavior

```
$ rubocop --debug main.rb
For /home/kotovalexarian: configuration from /home/kotovalexarian/.rubocop.yml
Default configuration from /home/kotovalexarian/.rvm/gems/ruby-3.0.2@arcamark/gems/rubocop-1.21.0/config/default.yml
Use parallel by default.
Running parallel inspection
Inspecting 1 file
Scanning /home/kotovalexarian/main.rb
Loading cache from /home/kotovalexarian/.cache/rubocop_cache/1659dbf77b85bb74d511f7d88e7efa9320f1354c/6d7a3b621ca1730e04accd938619e4bdab66cfb1/a12a29925874af02e20456d83e6d5b54d11f7cee
.

1 file inspected, no offenses detected
Finished in 0.15581881400066777 seconds
```

## Actual behavior

```
$ rubocop --debug main.rb
For /home/kotovalexarian: configuration from /home/kotovalexarian/.rubocop.yml
Default configuration from /home/kotovalexarian/.rvm/gems/ruby-3.0.2@arcamark/gems/rubocop-1.21.0/config/default.yml
Use parallel by default.
Running parallel inspection
Loading cache from /home/kotovalexarian/.cache/rubocop_cache/1659dbf77b85bb74d511f7d88e7efa9320f1354c/6d7a3b621ca1730e04accd938619e4bdab66cfb1/9a472dafb77012ac390f31cfdb34eb67a85f31ab
Inspecting 1 file
Scanning /home/kotovalexarian/main.rb
Loading cache from /home/kotovalexarian/.cache/rubocop_cache/1659dbf77b85bb74d511f7d88e7efa9320f1354c/6d7a3b621ca1730e04accd938619e4bdab66cfb1/9a472dafb77012ac390f31cfdb34eb67a85f31ab
C

Offenses:

main.rb:14:7: C: [Correctable] Style/RedundantSelf: Redundant self detected.
      self.bar + bar
      ^^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
Finished in 0.10107574600078806 seconds
```

## Steps to reproduce the problem

Install **Ruby 3.0.2** and **RuboCop 1.12.0**.

Create file `.rubocop.yml` with the following content:

```yaml
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
```

Create file `main.rb` with the following content:

```ruby
# frozen_string_literal: true

##
# Foo class.
#
class Foo
  def bar
    100
  end

  def car(cdr)
    case cdr
    in Integer => bar
      self.bar + bar
    end
  end
end

raise unless Foo.new.cdr(23) == 123
```

## RuboCop version

```
$ rubocop -V 
1.21.0 (using Parser 3.0.2.0, rubocop-ast 1.11.0, running on ruby 3.0.2 x86_64-linux)
```

### PR DESCRIPTION
**Pull request by dvandersluis**
A `match-as` node creates a local variable within an `in-pattern` node that wasn't being registered by `Style/RedundantSelf`. 

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/redundant_self_spec.rb [hunk 1]
```diff
@@ -292,4 +292,38 @@ def do_something((a, b)) # This method expects Array that has 2 elements as argu
       end
     RUBY
   end
+
+  context 'with ruby >= 2.7', :ruby27 do
+    context 'with pattern matching' do
+      it 'accepts a self receiver on an `match-var`' do
+        expect_no_offenses(<<~RUBY)
+          case foo
+            in Integer => bar
```
Comment (koic) [inline spec/rubocop/cop/style/redundant_self_spec.rb:301]: Patterns other than `:match_as` seem to have the same issue. e.g. `:hash_pattern`, `:array_pattern`, and so on:

```ruby
case pattern
in {foo: 42}
end

case pattern
in [1, 2, 3]
end
```

Comment (dvandersluis) [reply spec/rubocop/cop/style/redundant_self_spec.rb:301]: Got it, I'm not super familiar with pattern matching! I'll fix those as well, thank you :heart:

**Comment by dvandersluis** [comment]
@koic I have added quite a few more test cases for different types of pattern matching, which are all covered now. Thanks for the input!

**Comment by bbatsov** [comment]
Looks good to me!
