### PR TITLE
[Fix #9977] Update `Layout/EmptyLineAfterGuardClause` to not register an offense if there is another expression following the guard clause on the same line

### LINKED ISSUE #9977: Layout/EmptyLineAfterGuardClause inserts empty line outside of block, breaking method chaining
The Layout/EmptyLineAfterGuardClause cop misbehaves in a situation such as this (very contrived) example:

```ruby
# frozen_string_literal: true

def weird_sum(my_array)
  my_array
    .map { |item| next unless item.positive?; item * 2 }
    .compact
    .sum
end
```

## Expected behavior

No empty line inserted, **or** an empty line is inserted inside the block.

## Actual behavior

An empty line is inserted before the `.compact` line, resulting in a syntax error.

```
$ rubocop --debug --auto-correct test.rb
For /home/afn/work: Default configuration from /home/afn/.rvm/gems/ruby-3.0.1/gems/rubocop-1.18.4/config/default.yml
Inspecting 1 file
Scanning /home/afn/work/test.rb
E

Offenses:

test.rb:5:19: C: [Corrected] Layout/EmptyLineAfterGuardClause: Add empty line after guard clause.
    .map { |item| next unless item.positive?; item * 2 }
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
test.rb:7:5: E: Lint/Syntax: unexpected token tDOT
(Using Ruby 3.0 parser; configure using TargetRubyVersion parameter, under AllCops)
    .compact
    ^

1 file inspected, 2 offenses detected, 1 offense corrected
Finished in 0.11396609200164676 seconds
```

Resulting file:

```ruby
# frozen_string_literal: true

def weird_sum(my_array)
  my_array
    .map { |item| next unless item.positive?; item * 2 }

    .compact
    .sum
end
```

## Steps to reproduce the problem

See above.

## RuboCop version

1.18.4 (using Parser 3.0.2.0, rubocop-ast 1.8.0, running on ruby 3.0.1 x86_64-linux)

### PR DESCRIPTION
**Pull request by dvandersluis**
`Layout/EmptyLineAfterGuardClause` corrects by adding a blank line after the clause, assuming that it is on its own line (or followed by a comment). However, if there is another statement on the same line, it's not taken into account.

This change does not attempt to correct if the clause is not the last node on the line. It'll leave autocorrection to `Style/Semicolon` (which currently doesn't do this autocorrection either).

Fixes #9977.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb [hunk 1]
```diff
@@ -560,4 +560,15 @@ def foo
       end
     RUBY
   end
+
+  it 'registers an offense but does not correct when the clause is ended with a semicolon' do
+    expect_offense(<<~RUBY)
+      def foo(item)
+        return unless item.positive?; item * 2
+        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Add empty line after guard clause.
```
Comment (koic) [inline spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb:568]: I think this case is acceptable because it is a false positive. So the cop can respect the will of programmers who want to use semicolons.

Comment (dvandersluis) [reply spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb:568]: @koic I'm not sure I follow, that offense isn't new, this PR just doesn't try to autocorrect the offense.

Are you saying this should not be an offense?

Comment (koic) [reply spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb:568]: Yes. I think `expect_no_offences` should be used in this test and pass for cop role’s design.

Comment (dvandersluis) [reply spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb:582]: @koic updated, it'll now not consider guard clauses when there's another statement on the same line. I added some additional tests as well.

File: spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb [hunk 2]
```diff
@@ -28,7 +34,7 @@ def foo
       end
     RUBY
 
-    expect_correction(<<~RUBY)
+    expect_correction(<<~RUBY )
```
Comment (koic) [inline spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb:37]: That's just my two cents.

```suggestion
    expect_correction(<<~RUBY)
```

File: spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb (hunk 1 above)
Comment (koic) [reply spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb:582]: Great! Thanks!

File: spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb (hunk 2 above)
Comment (dvandersluis) [reply spec/rubocop/cop/layout/empty_line_after_guard_clause_spec.rb:37]: 🤦 thanks @koic!
