### PR TITLE
[Fix #13343] Prevent `Layout/LineLength` from breaking up a method with arguments chained onto a heredoc delimiter

### LINKED ISSUE #13343: `Layout/LineLength` can fold code inside a heredoc
```ruby
str = <<-HTML.strip_heredoc.strip_heredoc.strip_heredoc.encode!('utf-8', invalid: :replace, replace: '').strip.force_encoding('binary')
  <html>
  </html>
HTML
```

## Expected behavior

_idk_

## Actual behavior

Describe here what actually happened.
Please use `rubocop --debug` when pasting rubocop output as it contains additional information.

```ruby
str = <<-HTML.strip_heredoc.strip_heredoc.strip_heredoc.encode!('utf-8', invalid: :replace, 
replace: '').strip.force_encoding('binary')
  <html>
  </html>
HTML
```

## Steps to reproduce the problem

This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.

## RuboCop version

```
$ bin/bundle exec rubocop -V
1.67.0 (using Parser 3.3.5.0, rubocop-ast 1.32.3, analyzing as Ruby 2.7, running on jruby 3.1.4) [java]
  - rubocop-performance 1.22.1
```

### PR DESCRIPTION
**Pull request by dvandersluis**
If a method chain starting with a heredoc goes over the line length limit, breaking it onto multiple lines is a syntax error. This prevents the autocorrection that would do so.

```ruby
str = <<~HEREDOC.do_something.with_args(foo: '', bar: '', baz: '')
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ Line is too long. [66/40]
  text
HEREDOC
```

Fixes #13343.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/mixin/check_line_breakable.rb [hunk 1]
```diff
@@ -222,6 +224,22 @@ def already_on_multiple_lines?(node)
...
+        while receiver
+          if (receiver.str_type? || receiver.dstr_type? || receiver.xstr_type?) && receiver.heredoc?
+            return true
+          end
+
+          receiver = receiver.receiver
+        end
+
+        false
+      end
```
Comment (koic) [inline lib/rubocop/cop/mixin/check_line_breakable.rb:242]: Can you refactor to the following?

```suggestion
      def chained_to_heredoc?(node)
        while (node = node.receiver)
          if (node.str_type? || node.dstr_type? || node.xstr_type?) && node.heredoc?
            return true
          end
        end

        false
      end
```

Comment (dvandersluis) [reply lib/rubocop/cop/mixin/check_line_breakable.rb]: Sure, updated.

**Comment by koic** [comment]
Thanks!
