### PR TITLE
[Fix #11685] Fix incorrect directive comment insertion when percent array violates `Layout/LineLength` cop

### LINKED ISSUE #11685: `--disable-uncorrectable` option does not insert todo comment as expected
## Expected behavior

Rubocop should process

```ruby
ARRAY = %w[AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBB].freeze
```
 
as

```ruby
# rubocop:todo Layout/LineLength
ARRAY = %w[AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBB].freeze
# rubocop:enable Layout/LineLength
```
for "--disable-uncorrectable" option

## Actual behavior

it become infinite loop and I got

```ruby
ARRAY = %w[
  # rubocop:todo Layout/LineLength
  # rubocop:enable Layout/LineLength
  # rubocop:enable Layout/LineLength
  ...
  # rubocop:todo Layout/LineLength
  # rubocop:todo Layout/LineLength
  # rubocop:enable Layout/LineLength
  # rubocop:todo Layout/LineLength
AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBB
# rubocop:enable Layout/LineLength
  # rubocop:todo Layout/LineLength
# rubocop:enable Layout/LineLength
  ...
# rubocop:enable Layout/LineLength
  # rubocop:todo Layout/LineLength
  # rubocop:todo Layout/LineLength
  # rubocop:enable Layout/LineLength
].freeze
```

## Steps to reproduce the problem

1. create `test_case.rb`
2. create`.rubocop.yml`
3. run `bundle exec rubocop -A --disable-uncorrectable test_case.rb`

test_case.rb
```ruby
ARRAY = %w[AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBB].freeze
```

.rubocop.yml
```yml
Layout/LineLength:
  Max: 30
```

## RuboCop version

This happens with HEAD of master (e74bed3e8)

```
$ [bundle exec] rubocop -V
1.46.0 (using Parser 3.2.1.1, rubocop-ast 1.26.0, running on ruby 2.7.6) [x86_64-darwin19]
  - rubocop-performance 1.16.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.18.1
```

This happens with ruby `3.1.2` too.

### PR DESCRIPTION
**Pull request by nobuyo**
Fixes #11685.

The problem was that directive comments were inserted inside percent literals and thus had no effect.
So I've added a condition to detect percent array as well as heredoc.

```rb
ARRAY = %i[
# rubocop:todo Layout/LineLength <---- 💥 
AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBB].freeze
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/layout/line_length_spec.rb [hunk 1]
```diff
@@ -1235,5 +1235,28 @@ def baz(bar)
...
+
+          expect_correction(<<~RUBY)
+            # rubocop:todo Layout/LineLength
+            ARRAY = %i[
+            AAAAAAAAAAAAAAAAAAAA BBBBBBBBBBBBBBBBBBBB].freeze
+            # rubocop:enable Layout/LineLength
+          RUBY
+        end
+      end
+    end
```
Comment (koic) [inline spec/rubocop/cop/layout/line_length_spec.rb:1260]: IMHO, mock testing is naive and should be used as little as possible. Can you replace it with cli/autocorrect_spec.rb instead?

File: lib/rubocop/cop/autocorrect_logic.rb [hunk 2]
```diff
@@ -45,16 +45,25 @@ def autocorrect_enabled?
...
+        percent_array_range = surrounding_percent_array(range)
+
         if heredoc_range
           disable_offense_before_and_after(range_by_lines(heredoc_range))
+        elsif percent_array_range
+          disable_offense_before_and_after(range_by_lines(percent_array_range))
+        else
+          disable_offense_with_eol_or_surround_comment(range)
+        end
+      end
```
Comment (koic) [inline lib/rubocop/cop/autocorrect_logic.rb:57]: Can you tweak it?

```suggestion
      def disable_offense(offense_range)
        range = surrounding_heredoc(offense_range) || surrounding_percent_array(offense_range)

        if range
          disable_offense_before_and_after(range_by_lines(range))
        else
          disable_offense_with_eol_or_surround_comment(offense_range)
        end
      end
```

Comment (nobuyo) [reply lib/rubocop/cop/autocorrect_logic.rb]: Ah - smart. Thank you.

**Comment by koic** [comment]
Thanks!
