### PR TITLE
[Fix #12312] Fix an incorrect autocorrect for `Style/HashSyntax`

### LINKED ISSUE #12312: Invalid autocorrect for  Style/HashSyntax
This was a String format operator, but it gets transformed to be a String quotation.
```
Offenses:

app/helpers/application_helper.rb:36:37: C: [Corrected] Style/HashSyntax: Omit the hash value.
      Settings.embed.url % { druid: druid }
                                    ^^^^^

40 files inspected, 1 offense detected, 1 offense corrected

➜  git diff
diff --git a/app/helpers/application_helper.rb b/app/helpers/application_helper.rb
index 5809493..5468147 100644
--- a/app/helpers/application_helper.rb
+++ b/app/helpers/application_helper.rb
@@ -33,7 +33,7 @@ module ApplicationHelper

   def embeddable_url(druid)
     if Settings.embed.url
-      Settings.embed.url % { druid: druid }
+      Settings.embed.url %({ druid: })
     else
       purl_url(druid)


➜  bundle exec  rubocop -v
1.56.2
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12312.

This PR fixes an incorrect autocorrect for `Style/HashSyntax` when braced hash key and value are the same and it is used in `if`...`else`.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/hash_syntax_spec.rb [hunk 1]
```diff
@@ -938,6 +938,25 @@
         RUBY
       end
 
+      it 'registers and corrects an offense when braced hash key and value are the same and its used in `if`...`else`' do
```
Comment (bbatsov) [inline spec/rubocop/cop/style/hash_syntax_spec.rb:941]: its used -> it is used

File: changelog/fix_an_incorrect_autocorrect_style_hash_syntax.md [hunk 2]
```diff
@@ -0,0 +1 @@
+* [#12312](https://github.com/rubocop/rubocop/issues/12312): Fix an incorrect autocorrect for `Style/HashSyntax` when braced hash key and value are the same and its used in `if`...`else`. ([@koic][])
```
Comment (bbatsov) [inline changelog/fix_an_incorrect_autocorrect_style_hash_syntax.md:1]: its -> it is

**Comment by koic** [comment]
I've updated this PR. Thanks!
