### PR TITLE
[Fix #14985] Fix incorrect autocorrection in `Lint/SafeNavigationChain`

### LINKED ISSUE #14985: Unsafe autocorrection for Lint/SafeNavigationChain
Autocorrection for Lint/SafeNavigationChain can sometimes lead to syntax error.

--------

## Steps to reproduce the problem

I encounter this error when I run rubocop on some code which includes ternary operator on an ActiveModel object:

```rb
user = User.find_by(uuid: params[:uuid])

some_number = user&.age ? user&.age - 1 : 0
```

## Expected behavior

It should either ignore this, or detect but shouldn't autocorrect it

## Actual behavior

The autocorrection leads to syntax error.

Command output:

```sh
$ rubocop dummy.rb --autocorrect
Inspecting 1 file
F

Offenses:

dummy.rb:3:1: W: [Corrected] Lint/UselessAssignment: Useless assignment to variable - some_number.
some_number = user&.age ? user&.age - 1 : 0
^^^^^^^^^^^
dummy.rb:3:36: W: [Corrected] Lint/SafeNavigationChain: Do not chain ordinary method call after safe navigation operator.
some_number = user&.age ? user&.age - 1 : 0
                                   ^^^^
dummy.rb:3:40: F: Lint/Syntax: expected a : after the true expression of a ternary operator
(Using Ruby 3.4 parser; configure using TargetRubyVersion parameter, under AllCops)
some_number = user&.age ? user&.age&. - 1 : 0

dummy.rb:3:43: F: Lint/Syntax: unexpected ':', expecting end-of-input
(Using Ruby 3.4 parser; configure using TargetRubyVersion parameter, under AllCops)
some_number = user&.age ? user&.age&. - 1 : 0
                                          ^

1 file inspected, 4 offenses detected, 2 offenses corrected
```

Resulted file:

```rb
user = User.find_by(uuid: params[:uuid])

some_number = user&.age ? user&.age&. - 1 : 0
```

## RuboCop version

1.82.1 (using Parser 3.3.10.0, Prism 1.7.0, rubocop-ast 1.49.0, analyzing as Ruby 3.4, running on ruby 3.4.2) [x86_64-linux]
  - rubocop-rails 2.34.2
  - rubocop-rspec 3.8.0
  - rubocop-performance 1.26.1

### PR DESCRIPTION
**Pull request by koic**
This PR fixes incorrect autocorrection in `Lint/SafeNavigationChain` when chaining a method call after safe navigation in the if branch of a ternary.

`foo&.bar ? foo&.bar - 1 : baz` should be detected by `Lint/RedundantSafeNavigation` as
`foo&.bar ? foo.bar - 1 : baz`, which will be addressed separately.

For `foo&.bar ? baz : foo&.bar - 1`, the code in the else branch chains a method call on a receiver that may be nil. Autocorrection is not possible because the intended logic cannot be determined automatically.

Fixes #14985.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/lint/safe_navigation_chain_spec.rb [hunk 1]
```diff
@@ -398,6 +398,24 @@
       RUBY
     end
 
+    # NOTE: `foo&.bar` in the true branch is handled by `Lint/RedundantSafeNavigation`.
```
Comment (koic) [inline spec/rubocop/cop/lint/safe_navigation_chain_spec.rb:401]: This will be handled by #14989.
