### PR TITLE
[Fix #12274] Fix a false positive for `Lint/Void`

### LINKED ISSUE #12274: Lint/Void removing valid block content
Before:
```
    e.each do |_k, v|
      v == 'b'
    end
```
After autocorecction:
```
    e.each do |_k, v|
    end
```
In my case `e` is a enumerator that filters. Of course, that fails after autocorrection. But also, removing block contents and leaving a empty block is not so useful either.

### PR DESCRIPTION
**Pull request by koic**
Fixes #12274.

This PR fixes a false positive for `Lint/Void` when `each`'s receiver is an object of `Enumerator` to which `filter` has been applied.

`each` blocks are allowed to prevent false positives. The expression inside the following block is not void:

```ruby
enumerator = [1, 2, 3].filter
enumerator.each { |item| item >= 2 } #=> [2, 3]
```

This might introduce false negatives, but higher severity Lint cop should aim for as safe detections as possible, I think.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/void.rb [hunk 1]
```diff
@@ -6,6 +6,15 @@ module Lint
       # Checks for operators, variables, literals, lambda, proc and nonmutating
       # methods used in void context.
       #
+      # `each` blocks are allowed to prevent false positives.
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/void.rb:9]: You might expand on this a bit here - e.g. saying that the receiver might be an enumerator.

**Comment by bbatsov** [comment]
Perhaps we should still flag an offense if the receiver is clearly not an enumerator - e.g. it's some literal or a constant (yeah, it can technically be an enumerator but this seems quite unlikely).

**Comment by koic** [comment]
> it's some literal or a constant (yeah, it can technically be an enumerator but this seems quite unlikely).

Already supported by the implementation, but I added missing specs for these. And I've also tweaked the offense message I discovered with this additional spec. There was a message that should be a "Constant" rather than a "Variable". This intentionally separates the commits.

**Comment by bbatsov** [comment]
Thanks!
