### PR TITLE
[Fix #12052] Handle all glob special characters

### LINKED ISSUE #12052: Subfolders can't include glob special characters
Related to https://github.com/rubocop/rubocop/issues/9593

Rubocop is unable to detect files within folders that contain special characters used by Glob, such as `{}[]*?`. 

--------

## Expected behavior

```
rubocop . --list-target-files
[bar]/two.rb
{foo}/one.rb
```

## Actual behavior

```
rubocop . --list-target-files
(empty)
```

## Steps to reproduce the problem

```
mkdir sample
cd sample
mkdir \{foo\}
mkdir \[bar\]
touch \{foo\}/one.rb
touch \[bar\]/two.rb
rubocop . --list-target-files
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.52.1 (using Parser 3.2.2.3, rubocop-ast 1.29.0, running on ruby 3.1.3) [arm64-darwin21]
```

### PR DESCRIPTION
**Pull request by meric426**
Addresses #12052 

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/target_finder.rb [hunk 1]
```diff
@@ -94,8 +94,8 @@ def find_files(base_dir, flags)
     end
 
     def wanted_dir_patterns(base_dir, exclude_pattern, flags)
-      base_dir = base_dir.gsub('/{}/', '/\{}/')
-      dirs = Dir.glob(File.join(base_dir.gsub('/*/', '/\*/').gsub('/**/', '/\**/'), '*/'), flags)
+      base_dir = base_dir.gsub(/[\\\{\}\[\]\*\?]/) { |x| "\\#{x}" }
```
Comment (koic) [inline lib/rubocop/target_finder.rb:97]: Can you update a more descriptive name for the variable `x`?

Comment (meric426) [reply lib/rubocop/target_finder.rb]: Made a few changes. What do you think?

**Comment by koic** [comment]
Thanks!
