### PR TITLE
[Fix #10321] Make `Style/MethodDefParentheses` aware of anonymous block forwarding

### LINKED ISSUE #10321: Fix Style/MethodDefParentheses issue with annonymous block forwarding
## Expected behavior

I would expect `Style/MethodDefParentheses` to not throw errors when anonymous block forwarding is used because anonymous block forwarding appears to require the use of parenthesis while explicit `&block` usage does not.

## Actual behavior

When enabling the `Naming/BlockForwarding` cop and correcting the code accordingly, you'll start getting errors with `Style/MethodDefParentheses`.

## Steps to reproduce the problem

Start by configuring Rubocop to use the following configuration:

``` 
Naming/BlockForwarding:
  Enabled: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
```

Next, use the following code as an example:

``` ruby
def fetch_value key, *default_value, &block
  fetch(key, *default_value, &block) || default_value.first
end
```

Save the above and run as `rubocop snippet.rb`. Notice you get `Naming/BlockForwarding` errors, now change the above implementation to use anonymous block forwarding as shown below:

``` ruby
def fetch_value(key, *default_value, &)
  fetch(key, *default_value, &) || default_value.first
end
```

Notice you now have a single `Style/MethodDefParentheses` error now.

## Notes

I'd like to note that this behavior is similar to what was reported [in this earlier issue](https://github.com/rubocop/rubocop/issues/10317). Also, it's odd that Ruby 3.1.0 requires the use of parenthesis when using anonymous block forwarding. Is this a possible Ruby 3.1.0 bug? I tried searching Ruby Issues but didn't see anything that hinted at this new behavior.

## RuboCop version

```
1.24.0 (using Parser 3.0.3.2, rubocop-ast 1.15.0, running on ruby 3.1.0 arm64-darwin21.2.0)
  - rubocop-performance 1.13.0
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.7.0
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #10321.

This PR fixes a false positive for `Style/MethodDefParentheses` when using `EnforcedStyle: require_no_parentheses` and Ruby 3.1's anonymous block forwarding.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/style/method_def_parentheses.rb [hunk 1]
```diff
@@ -133,9 +133,9 @@ def forced_parentheses?(node)
           # Regardless of style, parentheses are necessary for:
           # 1. Endless methods
           # 2. Argument lists containing a `forward-arg` (`...`)
+          # 3. Argument lists containing an anonymous block forwarding (`&`)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/method_def_parentheses.rb:136]: Probably this whole section should be repeated in the cop's description.

**Comment by bbatsov** [comment]
Looks good, we just need to document this behavior.

**Comment by koic** [comment]
Sure! I updated the cop's doc!

**Comment by bbatsov** [comment]
Thanks!
