### PR TITLE
[Fix #13103] Make `Lint/UselessAssignment` autocorrection safe

### LINKED ISSUE #13103: Do not do unsafe autocorrection for `Lint/UselessAssignment`
The cop is already marked as unsafe with the example using `||=` provided and the problematic variable declaration. 
But, there is another example I just encountered.

```ruby
foo += bar ? 1 : 2 
```

Which is incorrectly gets autocorrected to `foo + bar ? 1 : 2` (which is equivalent to `(foo + bar) ? 1 : 2`, but should be autocorrected to something like `foo + (bar ? 1 : 2)` (note the operator precedences in both examples).

What if we stop autocorrecting for such cases (and for cases like mentioned in the "safety" doc-block)?

### PR DESCRIPTION
**Pull request by koic**
Fixes #13103.

This PR makes `Lint/UselessAssignment` autocorrection safe.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: lib/rubocop/cop/lint/useless_assignment.rb [hunk 1]
```diff
@@ -53,24 +52,27 @@ def after_leaving_scope(scope, _variable_table)
...
-            next if assignment.used? || part_of_ignored_node?(assignment.node)
+            assignment_node = assignment.node
+            next if assignment.used? || part_of_ignored_node?(assignment_node)
 
             message = message_for_useless_assignment(assignment)
             range = offense_range(assignment)
 
             add_offense(range, message: message) do |corrector|
-              autocorrect(corrector, assignment) unless sequential_assignment?(assignment.node)
+              if !sequential_assignment?(assignment_node) && !assignment_node.parent&.or_asgn_type?
```
Comment (bbatsov) [inline lib/rubocop/cop/lint/useless_assignment.rb:67]: Might be good to add some comment here explaining what we're skipping for the auto-correction.

Comment (koic) [reply lib/rubocop/cop/lint/useless_assignment.rb]: Sure! I've added code comment for the logic.
