### PR TITLE
[Fix #12444] Fix false positive for `Style/HashEachMethods`

### LINKED ISSUE #12444: False positive on the `Style/HashEachMethods` cop for array destructuring
## Actual behavior

Before autocorrection

```ruby
def my_method
  [[1, 2, 3], [4, 5, 6]].each { |a, _| puts(a) }
end
```
output:
```console
2.7.6 :002 > [[1, 2, 3], [4, 5, 6]].each { |a, _| puts(a) }
1
4
 => [[1, 2, 3], [4, 5, 6]] 
```

After autocorrection

```ruby
def my_method
  [[1, 2, 3], [4, 5, 6]].each_key { |a| puts(a) }
end
```

output:
```console
2.7.6 :003 > [[1, 2, 3], [4, 5, 6]].each_key { |a| puts(a) }
Traceback (most recent call last):
        4: from /home/ydakuka/.rvm/rubies/ruby-2.7.6/bin/irb:23:in `<main>'
        3: from /home/ydakuka/.rvm/rubies/ruby-2.7.6/bin/irb:23:in `load'
        2: from /home/ydakuka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        1: from (irb):3
NoMethodError (undefined method `each_key' for [[1, 2, 3], [4, 5, 6]]:Array)
Did you mean?  each_entry
```

## Rubocop

```console
ydakuka@yauhenid:~/Work/project$ bin/rails_docker rubocop -V
1.58.0 (using Parser 3.2.2.4, rubocop-ast 1.30.0, running on ruby 2.7.8) [x86_64-linux]
  - rubocop-capybara 2.19.0
  - rubocop-factory_bot 2.24.0
  - rubocop-performance 1.19.1
  - rubocop-rails 2.22.2
  - rubocop-rake 0.6.0
  - rubocop-rspec 2.25.0
  - rubocop-thread_safety 0.5.1
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #12444.

This PR fixes false positive for `Style/HashEachMethods` when receiver literal is not a hash literal.

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/rubocop/cop/style/hash_each_methods_spec.rb [hunk 1]
```diff
@@ -144,6 +144,23 @@
...
+        RUBY
+
+        expect_correction(<<~RUBY)
+          {hash: :literal}.each_key { |k| p k }
+        RUBY
+      end
+
+      it "does not register an offense when `['array', 'literal'].keys.each`" do
+        expect_no_offenses(<<~RUBY)
+          ['array', 'literal'].keys.each { |k| p k }
```
Comment (ydakuka) [inline spec/rubocop/cop/style/hash_each_methods_spec.rb:160]: This code is broken.

```ruby
2.7.6 :002 > ['array', 'literal'].keys.each { |k| p k }
Traceback (most recent call last):
        4: from /home/ydakuka/.rvm/rubies/ruby-2.7.6/bin/irb:23:in `<main>'
        3: from /home/ydakuka/.rvm/rubies/ruby-2.7.6/bin/irb:23:in `load'
        2: from /home/ydakuka/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        1: from (irb):1
NoMethodError (undefined method `keys' for ["array", "literal"]:Array)
```

Comment (ydakuka) [reply spec/rubocop/cop/style/hash_each_methods_spec.rb:160]: The issue describes another case: when two args are passed to the `#each` and second one is not used.
```ruby
[[1, 2, 3], [4, 5, 6]].each { |a, _| puts(a) }
```

File: lib/rubocop/cop/style/hash_each_methods.rb [hunk 2]
```diff
@@ -88,6 +90,12 @@ def on_block_pass(node)
 
         private
 
+        def handlable?(node)
```
Comment (bbatsov) [inline lib/rubocop/cop/style/hash_each_methods.rb:93]: Did you meant to write "handleable"?

Comment (koic) [reply lib/rubocop/cop/style/hash_each_methods.rb]: Oops, this is a typo. I've fixed it.
